# Son, sade metinler (başlık, açıklama) — build.py bunları TR'nin üstüne yazar.
# Terimler: merkez (dış güç değil), işgal (girmek değil), boşluk (aralık değil).
FINAL = {
'A-1-1': ("Başlangıç pozisyonu", "Siyah 1 ile keima doğru cevaptır. Beyaz için en iyi devam çoğunlukla A'daki yapışmadır. B ve C eskiden popülerdi ama biraz yavaştır. D, E ve F ancak uygun durumlarda oynanır. Beyaz tenuki de yapabilir."),
'A-1-1-1': ("Beyaz yapışır, çift hane", "Beyaz yapışıp iki kez hane yapar ve siyahı hemen karar vermeye zorlar. Siyahın normal cevabı A'dır. B ve C yapay zekânın yeni fikirleri, D ve E eski hamlelerdir. F genelde kötüdür."),
'A-1-1-1-1-1': ("Siyah sente merkez kurar", "Bugün en çok oynanan şekillerden biri. Siyah merkezi, beyaz köşeyi alır. Sonuç eşit."),
'A-1-1-1-1-2': ("Siyah aşağı uzanır, beyaz yapışır", "Siyah 1 alanını korur. Beyaz 2 ile siyahın az nefesinden yararlanır. Merdiven siyahın lehineyse siyah 3 güçlüdür. İki taraf için de oynanabilir."),
'A-1-1-1-1-3': ("Siyah 1 erken uzanır", "Siyah 1 için henüz erken. Beyaz 2'den sonra siyah A'yı oynayamaz; bu küçük bir kayıp."),
'A-1-1-1-1-4': ("Beyazın iki zıplaması (AlphaGo)", "Beyazın iki zıplaması çok serttir; AlphaGo'nun oynadığı bir yol. Beyaz 5 ve 7 şarttır. Sonuç yapay zekâ tarzı, eşit bir josekidir."),
'A-1-1-1-1-5': ("Siyah dört taşı alır – kötü", "Siyah 1 dört taşı alır ama sıra beyaza geçer. Açılışta bu çok yavaştır; beyaz sente merkez kurar."),
'A-1-1-1-1-6': ("Siyah 1 taşı alır – kötü", "Siyah 1 ile taşı almak kötüdür. Beyaz 2'den sonra rahat oynar, beyaz 16'dan sonra köşedeki siyah taşlar zora girer."),
'A-1-1-1-1-7': ("Beyaz sırayı karıştırır", "Beyaz 1 ile önce uzanmak yanlış sıradır. Kesme artık sente olmaz ve beyaz dışarıda çok kaybeder."),
'A-1-1-1-1-8': ("Beyaz keser ve hane yapar", "Beyaz keser ve hane yapar. Burada merdiven önemlidir: merdiven siyahın lehineyse siyah 6 ile çıkar. Sonuç aşağı yukarı eşit."),
'A-1-1-1-1-9': ("Siyah 10 yerine itip alır", "Siyah 10 yerine 1'de iterse taşlar takas edilir. Sonraki savaşta beyaz biraz daha iyidir."),
'A-1-1-1-1-10': ("Sol üst siyahsa siyah döner", "Sol üst siyahsa siyah 1 güçlüdür. Siyah birkaç taşını feda eder ve çok iyi bir merkez kurar."),
'A-1-1-1-1-11': ("Merdiven kötüyse siyah tenuki", "Merdiven siyahın aleyhineyse siyah tenuki yapmak zorunda kalır. Beyazın A'daki hamlesi çok büyük olur; siyah biraz geride kalır."),
'A-1-1-1-1-12': ("Merdiveni bozan taş varken – aşırı", "Sağ üstteki işaretli beyaz taş merdiveni bozar. Siyah 1 ile çıkmaya çalışırsa taşları dağılır."),
'A-1-1-1-1-13': ("Merdiven kötüyse hemen sıkıştır", "Merdiven siyahın aleyhineyse siyah 1 ile hemen sıkıştırmak doğrudur. Sonuç eşit."),
'A-1-1-1-1-14': ("Beyaz omuz vuruşu, sonra pincer", "Beyaz omuz vuruşu yapar, sonra 7 ile pincer yaparak karşılık verir. İki taraf için de oynanabilir."),
'A-1-1-1-1-15': ("Beyaz sakince açılır", "Beyaz 1 ile sakince açılır. Biraz kayıptır ama karışık savaşlardan kaçar."),
'A-1-1-1-1-16': ("Beyaz köşeyi alır – genelde kötü", "Beyaz 1 ile köşeyi almak genelde iyi değildir. Siyah 2 çok büyük bir hamledir; siyah biraz daha iyi."),
'A-1-1-1-1-17': ("Beyaz 1 – kaba hamle", "Beyaz 1 kaba bir hamledir. Siyah ileride A, B ve C'yi sente kullanır ve merkezde sağlam kalır."),
'A-1-1-1-1-18': ("Siyah 1-3-5 ile sıkı şekil", "Siyah 1, 3 ve 5 ile şeklini hemen belirler. Beyaz 14 ile keserek savaşır; siyah biraz daha rahattır."),
'A-1-1-1-1-19': ("Siyah kapatır – daha zayıf", "Siyah 1 önceki iki şekilden zayıftır. Siyah 5 ile tamamlamak zorundadır, yoksa beyazın A'daki kesmesi çok acıtır."),
'A-1-1-1-1-20': ("Eski yol: taş feda edip merkez almak", "Eskiden oynanan bir yol: siyah taş feda edip merkez alır. Yapay zekâya göre siyahın merkezi hâlâ zayıftır; siyah biraz kayıpta."),
'A-1-1-1-1-21': ("Siyah aşağı iter – eski joseki", "Siyah 1 ile aşağı itmek eski bir josekidir. Beyaz A'dan hemen çıkarsa zor bir savaş başlar."),
'A-1-1-1-1-22': ("Beyaz bağlanıp çıkar", "Beyaz 1 ile bağlanıp çıkar. Beyaz 7 bu şeklin anahtar hamlesidir. Beyaz 11'den sonra siyah bir seçim yapmalıdır."),
'A-1-1-1-1-23': ("Siyah keser ve feda eder", "Siyah 1 ile kesip taşları feda etmek iyidir. Beyaz üç taşı alır ama sıra siyaha geçer. İki taraf da kabul edebilir."),
'A-1-1-1-1-24': ("Siyah anahtar taşları alamaz", "Siyah 1 ve 3 ile beyazın taşlarını yakalamaya çalışmamalıdır. Beyaz yön değiştirir ve siyahın duvarına bir taş yerleştirir."),
'A-1-1-1-1-25': ("Siyah yumuşak kosumi", "Siyah yumuşak ama sağlam oynar. Beyaz rahatça çıkar, siyah hafif bir baskı kurar. İki taraf için de oynanabilir."),
'A-1-1-1-1-26': ("Siyah yukarıdan atari", "Siyah 1 ile yukarıdan atari de olur. Beyaz 2 ile hemen uzanmalıdır; sonra zor bir savaş başlar."),
'A-1-1-1-1-27': ("Beyaz hemen çıkmazsa", "Beyaz hemen çıkmazsa siyah 1 ile rahatça tamamlar. Beyaz biraz geride kalır."),
'A-1-1-1-1-28': ("Beyaz önce bağlanır", "Beyaz önce 1 ile bağlanabilir. Siyah 2 ile hane yaparsa A-1-1-1-1-22'deki şekle döner."),
'A-1-1-1-1-29': ("İşaretli taş varken itmek işe yaramaz", "İşaretli beyaz taş varken siyah 1 işe yaramaz. Nefes yarışını siyah bir nefesle kaybeder."),
'A-1-1-1-1-30': ("Beyaz köşeyi alır – zayıf", "Beyaz 1 ile köşeyi almak zayıftır. Siyah 2'den sonra A-1-1-1-1-16'daki şekle döner."),
'A-1-1-1-1-31': ("Siyah kaplan ağzı", "Siyah 1 ile kaplan ağzı da olur. Beyaz 2'den sonra A-1-1-1-1-1'deki şekle döner."),
'A-1-1-1-1-32': ("Beyaz köşeyi alıp saldırır – şüpheli", "Beyaz 1 ile köşeyi almak şüphelidir. Siyah 4 ile taşları sağlamca yakalar; ileride A'daki atari beyazı zorlar."),
'A-1-1-1-2-1': ("Ters kaplan ağzı (yapay zekâ)", "Ters kaplan ağzı yapay zekânın bulduğu bir hamledir. Siyah 3 ile başını çıkarır, beyaz 4 ile yükselir. İki taraf için de oynanabilir."),
'A-1-1-1-2-2': ("Beyaz tenuki yapabilir", "Beyaz tenuki yapabilir. Siyah 1 ile sıkıştırırsa beyaz köşede yaşar."),
'A-1-1-1-2-3': ("Beyaz yapışıp karşılık verir", "Beyaz 1 ile çıkarak karşılık verebilir. Siyah 2 önemli noktadır; beyaz 5'ten sonra siyah peşini bırakmak zorunda kalır."),
'A-1-1-1-2-4': ("Siyahın düz saldırısı işe yaramaz", "Siyahın doğrudan saldırısı işe yaramaz. Beyaz 6 ve 8 ile rahatça kurtulur, siyah bir şey kazanmaz."),
'A-1-1-1-2-5': ("Siyah tenuki – iyi değil", "Siyahın tenuki yapması iyi değildir. Beyaz 1 ile şeklini güçlendirir."),
'A-1-1-1-3-1': ("Siyah aşağı uzanır", "Siyah 1 ile aşağı uzanmak alana önem verir. Yapay zekâya göre sonuç eşit: siyah en çok alanı alır ama merkezde zayıf kalır."),
'A-1-1-1-3-2': ("Beyaz atari – şüpheli", "Beyaz 1 ile atari şüphelidir. Siyah 2 ile iyi bir yere çıkar. Köşe zaten yaşadığı için beyaz sadece taşlarını ağırlaştırır."),
'A-1-1-1-3-3': ("Siyah uzanır – kötü", "Siyah 1 ile uzanmak kötüdür. Beyaz 2'den sonra oyun beyaza döner; siyah 10 puandan fazla kaybeder."),
'A-1-1-1-3-4': ("Beyaz kaplan ağzı – kötü", "Beyaz 1 ile kaplan ağzı kötüdür. Siyahın taşları iyi yerdedir ve nefes sorunu da yoktur."),
'A-1-1-1-4-1': ("Siyah çift hane – eski yol", "Siyahın çift hanesi eski bir hamledir. Normalde siyah biraz kayıptadır; ancak A civarında siyah taş varsa oynanabilir."),
'A-1-1-1-4-2': ("Beyaz basitçe bağlanır", "Beyaz 1 ile basitçe bağlanır. Bu da beyaz için biraz daha iyidir."),
'A-1-1-1-4-3': ("Beyaz tenuki", "Beyaz tenuki yapabilir. Siyah köşeyi alır ama buraya fazladan hamle harcamıştır; beyaz da memnun olabilir."),
'A-1-1-1-4-4': ("Siyah atari verip iter – kötü", "Siyah 1 ve 3 kötüdür. Beyaz yön değiştirir; siyahın aldığı taşların değeri azdır."),
'A-1-1-1-4-5': ("Beyazın karşılığı aşırı", "Beyazın karşı saldırısı aşırıdır. Beyaz taşlarını feda etmek zorunda kalır ve zayıf düşer."),
'A-1-1-1-5-1': ("Siyah bağlanır – biraz yumuşak", "Siyah 1 ile bağlanmak biraz yumuşaktır. Beyaz 2 ile şeklini tamamlar; yapay zekâya göre siyah biraz kayıpta."),
'A-1-1-1-6-1': ("2. sırada atari – kayıp", "Siyah 1 ile 2. sıradan atari kayıptır. Bu takastan beyaz açıkça kazançlı çıkar."),
'A-1-1-1-6-2': ("Siyah kaçmakta ısrar ederse", "Siyah kaçmakta ısrar ederse beyaz 2 çok iyi bir hamledir. Siyah kaçtıkça durumu kötüleşir."),
'A-1-1-1-6-3': ("Siyah inatçı ama verimsiz", "Siyah kesme noktası yaratmaya çalışır ama beyaz 6 ile rahat oynar. Siyahın şekli verimsizdir."),
'A-1-1-1-6-4': ("Siyah döner – çok kötü", "Siyah 1 ile dönmek çok kötüdür. Beyaz 2 ile daha da güçlenir."),
'A-1-1-2-1-1': ("Siyah tenuki en iyisi", "Beyaz 1 eskiden standart hamleydi; yapay zekâ bunu biraz yavaş bulur. Siyahın tenuki yapması iyidir."),
'A-1-1-2-1-2': ("Beyaz saldırırsa siyah rahat çıkar", "Beyaz saldırırsa siyah 2 ile köşeyi korur ve 4 ile rahatça çıkar. Beyazın hamlesi siyahı pek zorlamaz."),
'A-1-1-2-2-1': ("Siyah 3-3 kosumi – duruma bağlı", "Siyah 1 ile 3-3'e kosumi yapmanın değeri azdır. Beyaz 2 ile açılınca bu takas genelde siyaha biraz kayıptır; duruma göre oynanır."),
'A-1-1-2-2-2': ("Sağ alt beyazsa beyaz tenuki", "Sağ alt beyazsa beyaz tenuki yapabilir. Siyah pincer yaparsa beyaz sakince çıkar. Sonuç eşit."),
'A-1-1-2-2-3': ("Sol üstte destek varsa bastırma", "Sol üstte siyah taş varsa siyah 1 ile yukarıdan bastırmak da olur. Beyaz 2 ile çıkar; sonuç eşit."),
'A-1-1-2-2-4': ("Siyah küçük zıplama – uygun değil", "Siyah 1 küçük bir hatadır. Beyaz 2 ve 4 ile sıkı oynar ve taşlar takas edilir."),
'A-1-1-2-2-5': ("Siyah topak şekil – kötü", "Siyah 1 kötü bir şekildir. Beyaz 2 ile sorunu çözer; siyahın tenuki yapması daha iyiydi."),
'A-1-1-2-2-6': ("Siyah köşeye hane – kötü", "Siyah 1 ile köşeye hane kötüdür. Beyaz 2 ve 4 ile kolayca üstün duruma geçer."),
'A-1-1-2-2-7': ("Beyaz hane – biraz zayıf", "Beyaz 1 ile hane biraz zayıftır. Siyah 2 ve 4 ile iyi karşılık verir."),
'A-1-1-2-3-1': ("Siyah karşı pincer", "Siyah 1 ile karşı pincer eskiden popülerdi. Beyaz 2 ile çıkar, 8 ile karşılık verir. Savaş dengeli."),
'A-1-1-2-3-2': ("Siyah araya girer – sol üst beyazsa", "Siyah 1 ile araya girmek serttir. Sol üst beyazsa beyaz rahatça çıkar ve zor bir savaş başlar."),
'A-1-1-2-3-3': ("Sol üst siyahsa beyaz sakince zıplar", "Sol üst siyahsa beyaz 1 ile sakince zıplar. Sonuç eşit."),
'A-1-1-2-3-4': ("Beyaz 3-3 kosumi – yavaş", "Beyaz 1 biraz yavaştır. Siyah basit oynar, sonra tenuki yapar."),
'A-1-1-2-3-5': ("Beyaz hane ile çıkar – aşırı", "Beyaz 1 ile çıkmak aşırıdır. Siyah iyi şekil kurar; savaş beyaz için kötü gider."),
'A-1-1-2-3-6': ("Merdiven iyiyse kosumi-tsuke", "Merdiven siyahın lehineyse siyah 1 de olur. Beyaz 4 ve 6 iyi hamlelerdir. Sonuç eşit."),
'A-1-1-2-3-7': ("Beyaz hane – eski joseki", "Beyaz 1 eski bir josekidir. Siyah bir taşı merdivenle yakalar; bu beyaz için büyük kayıptır."),
'A-1-1-2-3-8': ("Merdiven kötüyse siyah uzanır", "Merdiven siyahın aleyhineyse siyah 1 ile uzanmak zorundadır. Siyah biraz geride kalır."),
'A-1-1-2-3-9': ("Beyaz sıkıştırır – kötü", "Beyaz 1 kötüdür. Siyah bir taşı sararak yakalar ve biraz öne geçer."),
'A-1-1-2-3-10': ("Beyaz atari – çok kötü", "Beyaz 1 ile atari çok kötüdür. Siyah beyazın şeklini bozar."),
'A-1-1-2-3-11': ("Beyaz kosumi – zorlama", "Beyaz 1 zorlamadır. Siyah karşılık verir, köşeyi alarak çok kazanır."),
'A-1-1-2-4-1': ("Kore usulü yapışma josekisi", "Merdiven siyahın lehineyse siyah 1 ile yapışmak bir zamanlar moda olan bir josekidir. Beyaz 2 doğru cevaptır. Sonra beyaz A, B ve C arasından seçer."),
'A-1-1-2-4-2': ("Sağ alt beyazsa beyaz aşağı uzanır", "Sağ alt beyazsa beyaz 1 iyidir. Siyah köşeye yaklaşır ve taş feda eder; sonuç eşit."),
'A-1-1-2-4-3': ("Siyah 3-3 kosumi – uygun değil", "Siyah 1 uygun değildir. Beyaz rahatça bastırır ve öne geçer."),
'A-1-1-2-4-4': ("Sağ alt siyahsa siyah uzanır", "Sağ alt siyahsa siyah 1 ile uzanabilir. Beyaz sakince tamamlar; iki taraf için de oynanabilir."),
'A-1-1-2-4-5': ("Siyah hemen döner", "Siyah 1 ile hemen dönmek de olur. Önceki şekille hemen hemen aynıdır."),
'A-1-1-2-4-6': ("Siyah acele keser", "Siyah 1 ile kesmek acelecidir. Beyaz 2'den sonra siyah toparlanamaz."),
'A-1-1-2-4-7': ("Sağ alt siyahsa beyaz bağlanır", "Sağ alt siyahsa beyaz 1 iyi bir hamledir. Beyaz sonra büyük bir bastırma yapar, iki taşı alır ve memnun olur."),
'A-1-1-2-4-8': ("Siyah 12 yerine bağlanırsa", "Siyah 12 yerine 1 ile bağlanırsa beyaz taş feda eder ve iyi bir noktayı alır."),
'A-1-1-2-4-9': ("Beyaz sert hane", "Beyaz 1 serttir. Beyaz yine taş feda edip sente alır ama önceki şekilden biraz geridedir."),
'A-1-1-2-4-10': ("Siyah kaplan ağzı – uygun değil", "Siyah 2 yerine 1'i oynamak uygun değildir. Beyaz rahatça atari verir ve savaşı yönetir."),
'A-1-1-2-4-11': ("Sağ alt beyazsa beyaz önce uzanır", "Sağ alt beyazsa beyaz 1 ile önce uzanmak iyidir. Sonuç eşit."),
'A-1-1-2-4-12': ("Beyaz büyük bastırma", "Beyaz doğrudan büyük bir bastırma da yapabilir. Siyah sağlam oynar; iki taraf için de oynanabilir."),
'A-1-1-2-4-13': ("Merdiven iyiyse beyaz bastırır", "Merdiven beyazın lehineyse beyaz 1 güçlüdür. Sağ alt siyahsa beyaz çok iyi durumdadır."),
'A-1-1-2-4-14': ("Sağ alt beyazsa büyük bastırma", "Sağ alt beyazsa beyaz büyük bir bastırma ile saldırır; siyah zorlanır."),
'A-1-1-2-4-15': ("Siyah hane – aşırı", "Siyah 1 aşırıdır. Beyaz güçlü hamlelerle karşılık verir ve açıkça öne geçer."),
'A-1-1-2-4-16': ("Merdiven beyazın aleyhineyse", "Merdiven beyazın aleyhineyse siyah 1'i oynayabilir. Siyah açıkça kazançlıdır."),
'A-1-1-2-4-17': ("Beyaz kesemez", "Beyaz 1 ile kesemez. Siyah atari verip bastırır; beyaz A ve B'yi aynı anda koruyamaz."),
'A-1-1-2-4-18': ("Merdiven kötüyse beyaz geri çekilir", "Merdiven beyazın aleyhineyse beyaz geri çekilmek zorundadır. Beyaz biraz kayıpta."),
'A-1-1-2-4-19': ("Beyaz aşağı hane – yumuşak", "Beyaz 1 biraz yumuşaktır. Siyah taş feda edip beyazı kapatır ve memnun olur."),
'A-1-1-2-4-20': ("Beyazın karşı saldırısı kötü", "Beyazın karşı saldırısı iyi değildir. Siyah köşeyi alır ve biraz öne geçer."),
'A-1-1-2-4-21': ("Siyah çift hane – biraz zayıf", "Siyah 1 biraz zayıftır. Beyaz sente taşı alır. Sonuç eşit."),
'A-1-1-2-4-22': ("Beyaz tek başına uzanır – kötü", "Beyaz 1 kötüdür. Siyah kazançlı çıkar ve tenuki yapabilir."),
'A-1-1-2-5-1': ("Siyah omuz vuruşu", "Siyah 1 ile omuz vuruşu merkezi almayı hedefler. Sağ alt siyahsa sonuç eşit; sağ alt beyazsa siyah için kötüdür."),
'A-1-1-2-5-2': ("Sağ alt beyazsa siyah uzanır", "Sağ alt beyazsa siyah 1 ile uzanmak iyidir. Savaş dengeli."),
'A-1-1-2-5-3': ("Beyaz yapışıp çıkar", "Beyaz 1 ile çıkabilir. Sağ alt siyahsa beyaz yerinde yaşar; sonuç eşit."),
'A-1-1-2-5-4': ("Sağ alt beyazsa beyaz aşağı uzanır", "Sağ alt beyazsa beyaz 1 sakin bir hamledir; sonra 5 ve 7 ile sert oynar. Sonuç eşit."),
'A-1-1-2-5-5': ("Beyaz 3-3 kosumi – yumuşak", "Beyaz 1 biraz yumuşaktır. Siyah kalın bir şekil kurar."),
'A-1-1-3-1-1': ("Kenarda açılma – artık nadir", "Beyaz 1 ile kenarda açılmak eskiden çok oynanırdı. Yapay zekâ önce köşede şekil kurmayı daha verimli bulur; bu yüzden artık nadir görülür."),
'A-1-1-3-1-2': ("Beyazın köşeye yapışması hep büyük", "Beyazın 1 ile köşeye yapışması her zaman büyük bir hamledir."),
'A-1-1-3-2-1': ("Siyah işgal eder – ko", "Merdiven siyahın lehine ve sağ alt beyazsa siyah 1 ile işgal eder. Bir ko çıkar; iki taraf da bir şey kazanır."),
'A-1-1-3-2-2': ("Beyaz hemen ko açar – uygun değil", "Beyaz 10 yerine hemen ko açarsa uygun olmaz. Siyahın taşları daha rahattır."),
'A-1-1-3-2-3': ("Merdiven kötüyse beyaz bağlanır", "Merdiven siyahın aleyhineyse beyazın 1 ile bağlanması yeterlidir. Beyaz iyi durumdadır."),
'A-1-1-3-2-4': ("Beyaz yukarıdan atari – gevşek", "Beyaz 1 biraz gevşektir. Siyah beyazın alanında rahatça yaşar."),
'A-1-1-3-2-5': ("Beyaz kapatıp feda eder – kötü", "Beyaz 1 ile taş feda etmek kötüdür. Siyah büyük alan kazanır."),
'A-1-1-3-2-6': ("Sağ alt siyahsa beyaz geri çekilir", "Sağ alt siyahsa beyaz 1 ile geri çekilmek yeterlidir. Beyaz iyi bir noktayı alır."),
'A-1-1-3-3-1': ("İşaretli taş varken yüksek işgal", "İşaretli siyah taş varsa siyah 1 ile yüksekten işgal etmek iyidir. Zor bir savaş başlar."),
'A-1-1-3-3-2': ("Siyah acele ayırır", "Siyah 1 ve 3 acelecidir. Beyaz doğru sırayla oynar ve temposu hızlıdır."),
'A-1-1-3-3-3': ("Beyaz yapışıp keser – aşırı", "Beyaz 1 ve 3 aşırıdır. Siyah 8'den sonra savaşta siyah daha rahattır."),
'A-1-1-4': ("Beyaz 3-3 işgali", "Beyaz 3-3'ü işgal eder. Hemen oynanırsa genelde biraz kayıptır. Siyah A ya da B ile beyazı ayırmalıdır."),
'A-1-1-4-1-1': ("Siyah kapatır – sade", "Siyah 1 ile kapatmak sade ve iyidir. Beyazın köşesi tam yaşamadığı için savaşta siyah daha rahattır."),
'A-1-1-4-1-2': ("Siyah aşağı uzanır", "Siyah 1 ile aşağı uzanmak da olur. Siyah kalın oynar; bu da siyahın lehinedir."),
'A-1-1-4-1-3': ("Siyah sürünür", "Siyah 1 ile sürünmek de bir seçenektir. Siyah iyi bir şekil kurar."),
'A-1-1-4-1-4': ("Beyaz uzansa da siyah rahat", "Beyaz 1 ile uzansa bile siyahın endişelenmesine gerek yok. Beyazın savaşı zordur."),
'A-1-1-4-2-1': ("Siyah keima – yapay zekâ fikri", "Siyah 1 ile keima yapay zekânın yeni fikridir. Beyaz köşede yaşar ama siyah açıkça öndedir."),
'A-1-1-4-2-2': ("Beyaz yapışıp takas arar", "Beyaz 1 ile yapışıp takas arar. Siyah sağlam oynar, sente alarak memnun olur."),
'A-1-1-4-2-3': ("Siyah hane – şüpheli", "Siyah 1 şüphelidir. Beyaz itip keserek rahatça çıkar."),
'A-1-1-4-2-4': ("Beyaz itip keser – aşırı", "Beyaz 1 ve 3 ile doğrudan kesmek aşırıdır. Siyah 4 ile nefes yarışını başlatır."),
'A-1-1-4-2-5': ("Önceki şeklin devamı", "Önceki şeklin devamı. Siyah dışarıda kazanç sağlar, sonra köşeyi alır ve çok büyük alan kazanır."),
'A-1-1-5': ("Beyaz yandan yapışır (yapay zekâ)", "Beyaz yandan yapışır; bu yapay zekâdan gelen bir fikirdir. Çevre boşken beyaz için biraz kötüdür. Siyahın en iyi cevapları A ve B'dir."),
'A-1-1-5-1-1': ("Siyah dıştan hane", "Siyah 1 ile dıştan hane güçlüdür. Siyah doğru sırayla oynar ve öne geçer."),
'A-1-1-5-1-2': ("Beyaz kaplan ağzı – aşırı", "Beyaz 1 aşırıdır. Beyaz nefes yarışını kazansa da kazandığından fazlasını kaybeder."),
'A-1-1-5-1-3': ("Siyah köşeye hane – biraz zayıf", "Siyah 1 ile köşeye hane biraz zayıftır. Beyaz çıkar ve karışık bir savaş başlar."),
'A-1-1-5-1-4': ("Siyah geri çekilir – çok yumuşak", "Siyah 1 ile geri çekilmek çok yumuşaktır. Beyaz iyi bir şekil kurar."),
'A-1-1-5-1-5': ("Beyaz hemen keser – kötü", "Beyaz 1 ile hemen kesmek kötüdür. Siyah 2 güçlüdür ve beyazın taşları ağır kalır."),
'A-1-1-5-1-6': ("Beyaz itemez – nefesi yetmez", "Beyaz 1 işe yaramaz. Köşedeki nefes yarışını beyaz kaybeder."),
'A-1-1-5-2-1': ("Siyah kapatır – sade", "Siyah 1 ile kapatmak sadedir. Beyaz köşeyi işgal edip sente alır. İki taraf da kabul edebilir."),
'A-1-1-5-2-2': ("Beyaz dışarıda uzanır – kötü", "Beyaz 1 ile dışarıda uzanmak kötüdür. Siyah art arda iyi hamleler yapar."),
'A-1-1-5-2-3': ("Merdiven iyiyse siyah taşı alır", "Merdiven siyahın lehineyse siyah bir taşı merdivenle yakalar. Bu siyah için çok büyük bir kazançtır."),
'A-1-1-5-2-4': ("Siyah dışarıdan keser – şüpheli", "Siyah 1 ile dışarıdan kesmek şüphelidir. Beyaz taşı alır ve rahat eder."),
'A-1-1-5-2-5': ("Merdiven kötüyse beyaz bağlanır", "Merdiven beyazın aleyhineyse beyaz 1 ile bağlanır. Siyah tenuki yapar ve biraz öndedir."),
'A-1-1-5-2-6': ("Siyah köşeyi kapatır – çok yumuşak", "Siyah 1 çok yumuşaktır. Beyaz rahat oynar, siyah yavaş kalır."),
'A-1-1-5-3-1': ("Siyah aşağı uzanır – duruma bağlı", "Siyah 1 ile uzanmak ancak yakında bir pincer taşı varken oynanır. Normalde savaş beyazın lehinedir."),
'A-1-1-5-3-2': ("Siyah tenuki", "Siyah tenuki de yapabilir. Beyaz iyi bir noktayı alır ve merkez kurar."),
'A-1-1-5-3-3': ("Beyaz hemen itip keser", "Beyaz 1 ve 3 ile hemen kesmek çok serttir. Karışık bir savaş başlar."),
'A-1-1-5-4-1': ("Siyah pincer", "Siyah 1 ile pincer de olur. İki taraf sade oynar; sonuç eşit."),
'A-1-1-5-4-2': ("Siyah dışarıdan uzanır – iyi değil", "Siyah 1 ile dışarıdan uzanmak iyi değildir. Beyaz güzel bir şekil kurar."),
'A-1-1-6': ("Beyaz büyük keima (tuzak)", "Beyaz büyük keima ile yaklaşır; bu hamle bir tuzaktır. Siyah için en iyisi tenuki yapmaktır. Burada oynarsa A güvenlidir, B ise tuzağa düşer."),
'A-1-1-6-1-1': ("Siyah tenuki – en iyisi", "Siyah tenuki yaparsa beyaz için en iyi devam 1'dir. Siyah yine tenuki yapabilir."),
'A-1-1-6-1-2': ("Beyaz pincer yaparsa", "Beyaz pincer yaparsa siyah da karşı pincer yapıp hafifçe çıkabilir."),
'A-1-1-6-2-1': ("Siyah kosumi-tsuke – kayıpsız", "Siyah 1 güvenli bir hamledir. Beyaz 2'den sonra A-1-1-1'deki şekle döner."),
'A-1-1-6-2-2': ("Siyah güçlüyse beyaz kosumi ile döner", "Siyahın çevresi güçlüyse beyaz 1 esnek bir hamledir. Siyah tenuki yapmalıdır."),
'A-1-1-6-2-3': ("Beyaz geri çekilir – çok yavaş", "Beyaz 1 ile geri çekilmek çok yavaştır."),
'A-1-1-6-3-1': ("Siyah yapışır – yeterince iyi değil", "Siyah 1 ile yapışmak yeterince iyi değildir. Siyah bir taş alır ama sonuç sadece eşit."),
'A-1-1-6-3-2': ("Merdiven kötüyse içeriden atari", "Merdiven siyahın aleyhineyse siyah içeriden atari vermek zorundadır ve biraz kayıpta kalır."),
'A-1-1-6-3-3': ("Beyaz kosumi – kötü", "Beyaz 1 kötüdür. Siyah bir kez bağlanıp tenuki yapar; beyazın şekli zayıf kalır."),
'A-1-1-7': ("Beyaz tenuki", "Beyaz tenuki yapmıştır. Siyah A ya da B ile pincer yapabilir veya C ile yapışabilir."),
'A-1-1-7-1-1': ("Bir boşluklu pincer", "Siyah 1 ile bir boşluklu pincer yapar. Siyah 5 iyi bir hamledir. Sonuç eşit."),
'A-1-1-7-1-2': ("Eski yol: atari", "Siyah 1 ile atari eskiden çok oynanırdı. Siyah sente alır ama merkezi zayıftır; memnun olamaz."),
'A-1-1-7-1-3': ("Siyah sertçe uzanır", "Siyah 1 serttir ve beyazın kolayca yerleşmesine izin vermez. Beyaz karşı pincer ile çıkar. İki taraf için de oynanabilir."),
'A-1-1-7-1-4': ("Beyaz ko açar", "Beyazın yeterli ko tehdidi varsa 1 ile ko açmak da iyidir."),
'A-1-1-7-1-5': ("Siyah çift hane – biraz zayıf", "Siyahın çift hanesi biraz zayıftır. Beyaz 4 iyi bir hamledir; beyaz sade oynayıp memnun olur."),
'A-1-1-7-1-6': ("Beyaz 2. sıradan keima", "Beyaz 1 ile 2. sıradan keima da yapabilir. A-1-1-2-2-2'deki şekle döner."),
'A-1-1-7-2-1': ("İki boşluklu pincer", "Siyah 1 ile iki boşluklu pincer yapar. Beyaz karşı pincer ile cevap verir. İki taraf için de oynanabilir."),
'A-1-1-7-2-2': ("İki boşluklu pincerde ko – dikkat", "İki boşluklu pincerde beyazın ko açması dikkat ister; bir boşluklu pincerdeki kadar iyi olmaz."),
'A-1-1-7-2-3': ("Siyah çift hane", "Siyah çift hane de yapabilir. Beyaz 2 iyi bir hamledir ve beyaz yerinde yaşar. Sonuç eşit."),
'A-1-1-7-2-4': ("Siyah hane", "Siyah 1 ile hane de yapabilir. Sonuç eşit."),
'A-1-1-7-2-5': ("Siyah uzanır – biraz yumuşak", "Siyah 1 biraz yumuşaktır. Beyaz sente yaşar ve memnun olur."),
'A-1-1-7-2-6': ("Beyaz josekiyi ezbere oynar", "Beyaz josekiyi ezbere oynarsa işaretli siyah taş tam yerinde kalır. Siyah biraz öndedir."),
'A-1-1-7-2-7': ("Siyah atari – biraz zayıf", "Siyah 1 ile atari biraz zayıftır. İşaretli siyah taş iyi çalışmaz; beyaz biraz daha iyi."),
'A-1-1-7-2-8': ("Beyaz kaplan ağzı – kötü", "Beyaz 1 ile kaplan ağzı kötüdür. Siyah 2 ile beyazı kapatır; beyaz yaşar ama çok sıkışır."),
'A-1-1-7-2-9': ("Beyaz aktif yapışır", "Beyaz 1 ile aktif oynar. Bir ko çıkar ve durum çok karışık olur."),
'A-1-1-7-2-10': ("Siyah bağlanır – sade", "Siyah 1 ile bağlanmak sadedir. Taşlar takas edilir; sonuç eşit."),
'A-1-1-7-2-11': ("Beyaz içeriden atari", "Beyaz 1 ile içeriden atari de verebilir. Beyaz köşeyi, siyah merkezi alır. Sonuç eşit."),
'A-1-1-7-2-12': ("Beyaz itip çıkar – aşırı", "Beyaz 1 aşırıdır. Siyah doğru sırayla köşeyi alır ve beyaz zorlanır."),
'A-1-1-7-2-13': ("Siyah araya girip bağlanır – kötü", "Siyah 1 ve 3 kötüdür. Beyaz köşeyi alır; işaretli siyah taş boşa gider."),
'A-1-1-7-2-14': ("Siyah kapatır – biraz zayıf", "Siyah 1 biraz zayıftır. Beyaz aktif oynar ve rahat bir tempoyla ilerler."),
'A-1-1-7-2-15': ("Siyah içeriden keser – iyi değil", "Siyah 1 ile içeriden kesmek iyi değildir. İşaretli siyah taş yine boşa gider."),
'A-1-1-7-3-1': ("Kosumi-tsuke ve geniş pincer", "Siyah 1 ile yapışır, 3 ile geniş bir pincer yapar. Beyaz karşı pincer ile cevap verir; zor bir savaş başlar."),
'A-1-1-7-3-2': ("Bir boşluklu pincer – fazla sıkı", "Siyah 1 ile bir boşluklu pincer burada fazla sıkıdır. Beyaz iyi karşılık verir ve biraz daha rahattır."),
}
