# Son, sade metinler (başlık, açıklama).
FINAL = {
'A-1-3': ("Başlangıç pozisyonu", "Siyah 1 ile alçak bir boşluklu pincer çok sık oynanır. Beyazın seçenekleri: A'da 3-3 işgali, B'de zıplama, C ve D'de çift kakari, E'de karşı pincer, F'de çapraz keima, G'de yapışma ya da tenuki."),
'A-1-3-1-1-1': ("3-3 işgali – en yaygın", "Beyaz 1 en çok oynanan hamledir. Siyah 8 ile sürünmek yapay zekânın önerisi; eskiden A'da bağlanılırdı. Sağ alt beyazsa sonuç eşit, siyahsa beyaz biraz kayıpta."),
'A-1-3-1-1-2': ("Beyazın sonraki iyi noktası", "İleride beyaz 1 iyi bir noktadır; siyah 2 ile tamamlamak zorundadır. İki taraf da istediğini alır."),
'A-1-3-1-1-3': ("Siyah tenuki – iyi değil", "Siyahın tenuki yapması genelde iyi değildir. Beyaz 1 ile şeklini tamamlar ve A'daki kesme siyah için tehlike olarak kalır."),
'A-1-3-1-1-4': ("Siyah bağlanır – eski joseki", "Siyah 1 eski bir josekidir. Beyaz ileride A'yı sente oynar ve siyahın şekli biraz tekrarlı olur."),
'A-1-3-1-1-5': ("Sürünmenin faydası", "Siyah A'da süründüğü için beyaz 1'e cevap vermek zorunda değildir. Beyaz 3 ile keserse siyah 4 ile sente alır."),
'A-1-3-1-1-6': ("Sağ alt beyazsa beyaz pincer ile çıkar", "Sağ alt beyazsa beyaz 1 güçlüdür. Siyah iki hane ile sabırlı oynar; beyaz sente kazanç sağlar."),
'A-1-3-1-1-7': ("Siyah uzanır – aşırı", "Siyah 1 aşırıdır. Beyaz savaşarak çıkar ve 2. sırada yaşar; siyahın merkezi zayıf kalır."),
'A-1-3-1-1-8': ("Sağ alt siyahsa", "Sağ alt siyahsa beyaz önce keser, sonra 5 ile çıkmak zorunda kalır. Beyaz biraz kayıpta."),
'A-1-3-1-1-9': ("Siyah hane – kötü", "Siyah 1 kötüdür. Beyaz 2 ile güçlüce çıkar, siyah bağlanmak zorunda kalır; beyaz sente kazanır."),
'A-1-3-1-1-10': ("Beyaz 2. sıradan keima", "Beyaz 1 ile 2. sıradan keima da olur. Sonuç eşit olan şekle çok benzer."),
'A-1-3-1-2-1': ("Siyah dıştan kapatır – iyi değil", "Siyah 1 pek iyi değildir. Beyaz sakin oynar, sente şeklini kurar ve ileride A ya da B'den birini mutlaka alır."),
'A-1-3-1-2-2': ("Sağ alt siyahsa beyaz sağlam bağlanır", "Sağ alt siyahsa beyaz 1 ile sakin oynayabilir ve ileride A ile savaşır. Beyaz biraz daha iyi."),
'A-1-3-1-2-3': ("Beyaz yapışıp yükselir", "Beyaz 1 de iyi bir hamledir. Siyah sente alır ama merkezi zayıftır; beyaz daha memnundur."),
'A-1-3-1-2-4': ("Siyah uzanır – aşırı", "Siyah 1 aşırıdır. Beyaz 2'den sonra siyah iki tarafta da zayıf kalır."),
'A-1-3-1-2-5': ("Siyah hane – kötü", "Siyah 1 kötüdür. Beyaz 2 ile rahatça çıkar, sonra A ya da B'yi seçer."),
'A-1-3-1-2-6': ("Siyah dıştan keser – kötü", "Siyah 1 kötüdür. Beyaz açıkça kazançlı çıkar."),
'A-1-3-1-2-7': ("Beyaz hemen bağlanır – yetersiz", "Beyaz 1 yeterince iyi değildir. Siyah 2 ile beyazı kapatır; sonuç eşit."),
'A-1-3-2': ("Beyaz zıplar", "Beyaz 1 ile zıplamak savaşmak demektir. Siyah genelde A, B ya da C ile köşeyi korur. Sağ taraf önemliyse D'de zıplayabilir."),
'A-1-3-2-1-0': ("Siyah bir boşluklu zıplar", "Siyah 1 normal bir hamledir, eskiden çok oynanırdı. Beyaz A'da omuz vuruşu, B'de karşı pincer ya da C'de sıkıştırma seçer."),
'A-1-3-2-1-1': ("Beyaz omuz vuruşu", "Sağ alt siyahsa ve merdiven beyazın lehineyse beyaz 1 iyidir. Siyah sürünerek güçlü oynar, beyaz 3-3'ü işgal eder; zor bir savaş başlar."),
'A-1-3-2-1-2': ("Beyaz uzanır – plansız", "Beyaz 1 plansızdır. Siyah beyazı ayırır ve sonunda çok alan kazanır."),
'A-1-3-2-1-3': ("Siyah 1 ve 3 – eski joseki", "Bu eski bir josekidir. Beyaz 4 ve 6 iyi hamlelerdir; savaşta beyaz biraz öndedir."),
'A-1-3-2-1-4': ("Beyaz kapatır – kötü", "Beyaz 1 kötüdür. Siyah sente hane yapar ve köşede çok alan kazanır."),
'A-1-3-2-1-5': ("Siyah hemen sürünür", "Siyah 1 ile sürünür, 7 ile güçlüce keser. Beyaz dört taşı alır, siyah sente merkez kurar. Sonuç eşit."),
'A-1-3-2-1-6': ("Beyaz yukarıdan atari", "Beyaz 1 de bir yoldur. Siyah sert karşılık verir; beyaz köşeyi işgal etse de siyah A ile yaşayabilir. Sonuç kabul edilebilir."),
'A-1-3-2-1-7': ("Beyaz bağlanırsa", "Beyaz 1 ile bağlanırsa siyahın iki atarisi serttir. Beyaz dar bir yerden çıkmak zorunda kalır; siyah biraz rahattır."),
'A-1-3-2-1-8': ("Siyah zıplar – sıradan", "Siyah 1 çok sıradandır. Beyaz 3-3'ü işgal ederek karşılık verir; siyah memnun değildir."),
'A-1-3-2-1-9': ("Siyah hemen araya girer", "Siyah 1 ile araya girip taş feda ederek merkez alabilir. Sonuç eşit."),
'A-1-3-2-1-10': ("Beyaz yapışıp feda eder", "Beyaz 1 ile taş feda etmek de bir yoldur; beyaz 11 iyi bir noktadır. İki taraf için de oynanabilir."),
'A-1-3-2-1-11': ("Siyah itip keser", "Siyah 1 ve 3 de bir yoldur. Siyah 7 ile uzanıp taş feda eder; iki taraf da kabul edebilir."),
'A-1-3-2-1-12': ("Siyah döner", "Siyah 1 ile dönerse beyaz 2 ile sert oynar. Beyaz biraz öne geçer."),
'A-1-3-2-1-13': ("Merdiven kötüyse atari işe yaramaz", "Merdiven siyahın aleyhineyse siyah 1 ile kesip atari vermek işe yaramaz."),
'A-1-3-2-1-14': ("Siyah merdiveni bozan taş oynar", "Siyah 1 ile merdiveni bozan bir taş oynamak da olur; beyaz 2 ile tamamlamalıdır. Siyah 3 iyi bir hamledir; siyah sente kazanç sağlar."),
'A-1-3-2-1-15': ("Beyaz peşinden gelirse", "Beyaz 1 ile peşinden gelirse siyah itip keser. Siyah sonunda sente bir taşı alır ve memnundur."),
'A-1-3-2-1-16': ("Beyaz kaplan ağzı", "Beyaz 1'e karşı siyah 2 iyidir. Beyaz dört taşı alır ama siyah sente beyazı kapatır; beyaz kazandığından fazlasını kaybeder."),
'A-1-3-2-1-17': ("Beyaz keser – çok sert", "Beyaz 1 çok serttir. Siyah 10'dan sonra beyaz zorlanır; saldırıyı siyah yönetir."),
'A-1-3-2-1-18': ("Beyaz yapışırsa", "Beyaz 1'e karşı siyah 2 ve sonrası çok güçlüdür. Beyaz çok zor durumda kalır."),
'A-1-3-2-1-19': ("Sağ alt beyazsa karşı pincer", "Sağ alt beyazsa beyaz 1 ile karşı pincer iyidir. Beyaz önce solu çözer; sonuç eşit."),
'A-1-3-2-1-20': ("Beyaz sıkıştırır", "Beyaz 1 ile sıkıştırmak da olur; siyah köşeyi güçlendirir. Zor bir savaş başlar."),
'A-1-3-2-1-21': ("Beyaz omuz vuruşu – biraz zayıf", "Beyaz 1 biraz zayıftır. Merdiven ne olursa olsun siyahın sürünerek çıkması iyidir; siyah biraz öndedir."),
'A-1-3-2-1-22': ("Beyaz 3-3 işgali", "Beyaz 1 ile 3-3 işgali de bir cevaptır. Beyaz 7 ile kalın oynar; siyah yine biraz daha iyi."),
'A-1-3-2-1-23': ("Siyah hemen araya girer", "Siyah 1 ile araya girebilir. Beyaz itip keser, siyah sakince taş feda eder; siyah biraz öndedir."),
'A-1-3-2-1-24': ("Beyaz önce atari verirse", "Beyaz önce atari verirse siyah sert karşılık verir. Savaşta siyah daha rahattır."),
'A-1-3-2-1-25': ("Sağ alt beyazsa siyah keser", "Sağ alt beyazsa siyahın itip kesmesi kazanç getirmez. Sert ve çok karışık bir savaş olur."),
'A-1-3-2-1-26': ("Beyaz kapatır – oynanabilir", "Merdiven beyazın aleyhine olsa bile beyaz 1 ile kapatıp savaşabilir. İki taraf için de oynanabilir."),
'A-1-3-2-1-27': ("Siyah çıkar – aşırı", "Siyah 1 biraz aşırıdır. Beyaz 8 ile keser, taş feda edip merkez alır; siyah memnun değildir."),
'A-1-3-2-1-28': ("Beyaz kaplan ağzı – biraz zayıf", "Beyaz 1 biraz zayıftır. Siyah güçlü oynar ve biraz daha iyi olur."),
'A-1-3-2-1-29': ("Beyaz önce keserse", "Beyaz 1 ile önce keserse siyah sürünerek güçlüce devam eder. Beyazın köşesi tam yaşamaz; savaşı siyah yönetir."),
'A-1-3-2-1-30': ("Siyah bağlanır – kötü", "Siyah 1 kötüdür. Beyaz sıkı oynar; siyah geri adım atmak zorunda kalır."),
'A-1-3-2-1-31': ("Siyah kesip atari verir – çok sert", "Siyah 1 çok serttir. Beyaz dört taşı alır ve köşede kolayca yaşar; siyah zorlanır."),
'A-1-3-2-1-32': ("Siyah kosumi-tsuke – eski fikir", "Eskiden siyah 1 iyi sayılırdı. Yapay zekâya göre bu takas siyahın göz alanını azaltır; siyah kayıpta."),
'A-1-3-2-2-0': ("Siyah iki boşluklu zıplar (yapay zekâ)", "Yapay zekâ çoğunlukla siyah 1'i tercih eder. Hızlıdır ama köşe zayıftır. Beyaz A'da omuz vuruşu, B'de karşı pincer, C'de sıkıştırma ya da D'de yapışma seçer."),
'A-1-3-2-2-1': ("Sağ alt siyahsa omuz vuruşu", "Sağ alt siyahsa beyaz 1 yine iyidir. Siyah tenuki yapar, beyaz şeklini tamamlar."),
'A-1-3-2-2-2': ("Aynı yol burada daha kötü", "Siyah aynı şekilde oynarsa işaretli taş A'dakinden biraz daha kötü yerde kalır."),
'A-1-3-2-2-3': ("Beyaz yukarıdan atari", "Beyaz 1 de olur. İki taraf da kendini güçlendirir; sonuç eşit."),
'A-1-3-2-2-4': ("Beyaz 3-3 işgali", "Beyaz 1 ile 3-3 işgali de bir yoldur. Siyah karşılık verir; takas iki taraf için de kabul edilebilir."),
'A-1-3-2-2-5': ("Siyah kapatır – tuzak", "Siyah 1 tuzağa düşer. Beyaz sente kazanç sağlar ve biraz öne geçer."),
'A-1-3-2-2-6': ("Siyah itip keser", "Siyah 1 ve 3 ile savaşabilir. Merdiven beyazın lehineyse beyaz güçlü karşılık verir. Sonuç eşit."),
'A-1-3-2-2-7': ("Siyah döner", "Siyah 1 ile dönmek de olur. Siyah taş feda edip beyazı kapatır; sonuç kabul edilebilir."),
'A-1-3-2-2-8': ("Siyah önce kosumi-tsuke – şüpheli", "Siyah 1 şüphelidir. Beyaz 10 ile köşeyi işgal eder ve memnun olur."),
'A-1-3-2-2-9': ("Sağ alt beyazsa karşı pincer", "Sağ alt beyazsa beyaz 1 çok oynanır. Siyah tenuki yapabilir, sonra A, B ya da C ile savaşır."),
'A-1-3-2-2-10': ("Beyaz sıkıştırır", "Beyaz 1 de iyi bir hamledir, siyah sağlam oynar. İki taraf için de oynanabilir."),
'A-1-3-2-2-11': ("Beyaz omuz vuruşu – kötü", "Beyaz 1 iyi değildir. Siyah basit oynar ve biraz öne geçer."),
'A-1-3-2-2-12': ("Siyah itip keser – kötü", "Siyah 1 ve 3 kötüdür. Beyaz güçlü oynar ve güzel bir şekil kurar."),
'A-1-3-2-2-13': ("Beyazın bu yolu iyi değil", "Merdiven iyi olsa bile beyazın bu yolu iyi değildir; işaretli siyah taş çok iyi yerdedir."),
'A-1-3-2-2-14': ("Sol üst beyazsa beyaz yapışıp keser", "Sol üst beyazsa beyaz yapışıp keserek savaşabilir. Sonunda bir ko çıkar ve durum çok zordur."),
'A-1-3-2-2-15': ("Sol üst siyahsa siyah hane", "Sol üst siyahsa siyah 1 güçlüdür. Beyaz direnir ama siyah 17'den sonra çok zorlanır."),
'A-1-3-2-2-16': ("Sol üst siyahsa beyaz kosumi", "Bu yüzden sol üst siyahsa beyaz 1 ile kosumi yapmak zorundadır. Siyah sert saldırır, beyaz yine zorlanır."),
'A-1-3-2-3-1': ("Siyah keima", "Siyah 1 ile keima da olur. Merdiven beyazın lehineyse beyaz omuz vuruşu yapar; sağ alt siyahsa siyah tenuki yapar."),
'A-1-3-2-3-2': ("Aynı yol burada daha kötü", "Siyah aynı şekilde oynarsa işaretli taş A'dakinden biraz daha kötü yerde kalır."),
'A-1-3-2-3-3': ("Siyah zıplar – memnun değil", "Siyah 1'den sonra beyaz omuz vuruşu yapar. Siyah bir taşı keser ama A'daki 3-3 zayıflığı kalır."),
'A-1-3-2-3-4': ("Siyah itip keser – aşırı", "Siyah 1 ve 3 biraz aşırıdır. Beyaz çok güçlü karşılık verir; siyah zorlanır."),
'A-1-3-2-3-5': ("Siyah kosumi-tsuke – biraz zayıf", "Siyah 1 biraz zayıftır. Beyaz 10 ile 3-3'ü işgal edip yaşar ve alan kazanır."),
'A-1-3-2-3-6': ("Siyah araya girip bağlanır – kötü", "Siyah 1 ve 3 de iyi değildir. Beyaz kesme noktasını kapatır ve dışarıda rahatça gelişir."),
'A-1-3-2-3-7': ("Beyaz omuz vuruşu", "Beyaz 1 aktif bir hamledir; siyah 4 ile sağlam oynar. Sağ alt siyahsa sonuç eşit."),
'A-1-3-2-3-8': ("Sağ alt beyazsa omuz vuruşu", "Sağ alt beyazsa beyaz 1 iyi bir hamledir. Siyah taş feda eder; beyaz biraz öndedir."),
'A-1-3-2-3-9': ("Siyah 2. sıradan keima – zayıf", "Siyah 1 biraz zayıftır. Beyaz omuz vuruşu yapar ve güzel bir şekil kurar."),
'A-1-3-2-4-1': ("Siyah zıplar – destek gerekir", "Siyah 1 çevrede destek ister; normalde biraz kayıptır. Siyah sonra tenuki yapar; köşe A sayesinde güvendedir."),
'A-1-3-2-4-2': ("Siyah başa vurursa", "Siyah 1'e karşı beyaz 4 ile esnek oynar. Beyaz işaretli iki taşı feda eder ve memnun olur."),
'A-1-3-2-4-3': ("Beyaz keser – aşırı", "Beyaz 1 aşırıdır. Siyah beyazı kapatır; nefes yarışında beyazın zayıflıkları çoktur."),
'A-1-3-2-4-4': ("Siyah yapışıp geri çekilir", "Siyah 1 ve 3 beyazı güçlendirir. Beyaz sonra A ile sıkıştırabilir ya da B ile açılabilir."),
'A-1-3-2-4-5': ("Siyah \"altın kuyu\" – karışık", "Siyah 1 eski Çin oyunlarında popüler, çok karışık bir hamledir. İki taraf da geri adım atamaz; sonunda siyahın şekli sıkışır ve savaş siyahın aleyhine döner."),
'A-1-3-2-4-6': ("Siyah 13 yerine aşağı uzanır – kötü", "Önceki şekilde siyah 13'ü 1'de oynamak da kötüdür. Beyaz önemli noktaları alır ve büyük alan kazanır."),
'A-1-3-2-4-7': ("Beyaz keima – yeterince sıkı değil", "Beyaz 1 yeterince sıkı değildir. Siyah 2 ile keskin oynar; beyaz önceki iki şekildeki kadar iyi olmaz."),
'A-1-3-3': ("Beyaz çift kakari", "Beyaz 1 ile çift kakari de çok oynanır; beyaz oyunu sol tarafa taşımak ister. Siyah genelde A ya da B'de yapışır; C'de 3-3 kosumi ile savaşmak da olur."),
'A-1-3-3-1-1': ("Siyah bu taraftan yapışır", "Siyah 1 ile bu taraftan yapışınca beyaz 2 ile hemen 3-3'ü işgal eder, siyah 3 ile dıştan kapatır. Siyah 7 aktif bir pincerdir."),
'A-1-3-3-1-2': ("Beyaz sağlam bağlanır", "Beyaz 1 de bir yoldur ve A'dan çıkmayı hedefler. Sonuç eşit."),
'A-1-3-3-1-3': ("Beyaz kenarda açılır – iyi değil", "Ko tehditleri çok iyi değilse beyaz 1 kötüdür. Siyah 2 ile işgal eder ve A'da bir ko başlar."),
'A-1-3-3-1-4': ("Siyah içeriden kapatır – şüpheli", "Siyah 1 şüphelidir. Beyaz güzel bir şekil kurar ve ileride A'yı da kullanabilir."),
'A-1-3-3-1-5': ("Beyaz hane ile çıkar", "Beyaz 1 siyahı yoklar; siyah 2 ile karşılık vermek zorundadır. Çok karışık bir savaş başlar."),
'A-1-3-3-1-6': ("Siyah keser – kötü", "Siyah 1 kötüdür. Beyaz sente bir taşı alır ve çok rahat eder."),
'A-1-3-3-1-7': ("Siyah kaplan ağzı – gevşek", "Siyah 1 gevşektir. Beyaz sürünerek bağlanır; siyahın taşları verimsiz kalır."),
'A-1-3-3-1-8': ("Beyaz hane ve yapışma – eski joseki", "Bu eski bir josekidir. Siyah solda taşı alıp çok kazanır ve altta da savaşı yönetir; beyaz açıkça kötüdür."),
'A-1-3-3-1-9': ("Beyaz dıştan atari", "Beyaz 1 önceki şekilden iyidir ama siyahın köşesi büyüktür; beyaz yine biraz kayıpta."),
'A-1-3-3-1-10': ("Siyah kaplan ağzı ile atari", "Siyah 1 biraz yumuşaktır; sonuç eşit."),
'A-1-3-3-2-1': ("Siyah güçlü taraftan yapışır", "Siyah 1 \"güçlü taşa yapış\" sözüne uyar. Beyaz 6 ile önce bağlanmalıdır. Siyah beyazı sıkıştırarak merkeze ilerler; savaş dengeli."),
'A-1-3-3-2-2': ("Siyah kapatır", "Siyah 1 ile kapatmak da olur. Beyaz işaretli taşını iyi kullanır; siyah tenuki yapar. Sonuç eşit."),
'A-1-3-3-2-3': ("Beyaz hane – dikkatsiz", "Beyaz 1 dikkatsizdir. Siyah 2 ile ayırır ve beyazın göz alanı azalır."),
'A-1-3-3-2-4': ("Beyaz sürünerek döner", "Beyaz 1 ile dönerse siyah sağlamca yakalar. Siyah 4 çok değerlidir; beyaz memnun değildir."),
'A-1-3-3-2-5': ("Merdiven iyiyse siyah bu taraftan kapatır", "Merdiven siyahın lehineyse siyah 1 ve 3 ile iyi oynar. Beyaz alanı, siyah merkezi alır; iki taraf da kabul edebilir."),
'A-1-3-3-2-6': ("Merdiven kötüyse siyah uzanır", "Merdiven siyahın aleyhineyse siyah 1 ile uzanmak zorundadır. Siyah açıkça kötü durumdadır."),
'A-1-3-3-2-7': ("Beyaz uzanır", "Beyaz 1 az oynanır. Siyah sakin kalır, beyaz taş feda etmek zorunda kalır; siyah daha memnundur."),
'A-1-3-3-2-8': ("Beyaz kosumi ile çıkar – aşırı", "Beyaz 1 aşırıdır. Siyah hazırlık yapıp 12 ile kapatır; beyaz sırayı kaybederek yaşamak zorunda kalır."),
'A-1-3-3-2-9': ("Beyaz yapışır – genelde kötü", "Beyaz 1 genelde iyi değildir. Siyah sağlam oynar ve köşede büyük alan kazanır."),
'A-1-3-3-2-10': ("Beyaz kosumi – aşırı", "Beyaz 1 aşırıdır. Siyah 6 ile keskin keser; sonunda beyazın dört taşı kıpırdayamaz."),
'A-1-3-3-3-1': ("Siyah 3-3 kosumi – genelde kötü", "Çevrede güçlü siyah taş yoksa siyah 1 genelde iyi değildir. Beyaz 2 ile iyi bir noktayı alır ve memnun olur."),
'A-1-3-3-3-2': ("Siyah önce bu taraftan iter", "Siyah 1'den sonra beyaz 4 yine iyi bir hamledir; takasta beyaz açıkça kazançlıdır."),
'A-1-3-4-1-1': ("Beyaz yüksek çift kakari", "Beyaz 1 eskiden sık oynanırdı. Siyah 2 ile bu taraftan yapışır; beyazın taşı iyi yerde değildir, siyah biraz daha iyi."),
'A-1-3-4-1-2': ("Beyaz sade oynar", "Beyaz 1 ve 3 sadedir; siyah 4 ile ustaca atari verir. Bu da siyah için biraz daha iyidir."),
'A-1-3-4-1-3': ("Siyah 3. sıradan atari – eski joseki", "Siyah 1 eski bir josekidir. Beyaz ileride sente kazanç sağlar; sonuç eşit."),
'A-1-3-4-2-1': ("Siyah bu taraftan yapışır – biraz zayıf", "Siyah 1 biraz zayıftır. Beyaz köşeyi alır; işaretli siyah taş fazla yakın kalır."),
'A-1-3-4-2-2': ("Siyah merdivenle yakalar", "Merdiven iyi olsa bile siyahın bir taşı yakalaması avantaj getirmez. Beyaz sente köşeyi alır."),
'A-1-3-4-2-3': ("Siyah geri çekilir", "Siyah 1 ile geri çekilip sert oynayabilir. Uzun bir zorunlu sıra olur ve bir ko kalır; beyaz biraz daha rahattır."),
'A-1-3-4-2-4': ("Siyah keser", "Siyah 1 ile keserse beyaz 6 can alıcı noktadır. Karışık bir savaş başlar; beyaz biraz öndedir."),
'A-1-3-4-2-5': ("Siyah keser – gevşek", "Siyah 1 gevşektir. Beyaz sürünerek bağlanır ve memnun olur."),
'A-1-3-5-1-1': ("Beyaz iki boşluklu karşı pincer", "Beyaz 1 siyaha fazla baskı yapmaz; siyah tenuki yapabilir. Beyaz 3 ile çıkınca siyah köşede yaşar."),
'A-1-3-5-1-2': ("Beyaz 3-3 işgali", "Beyaz 1 ile 3-3'ü de işgal edebilir. Siyah 6 iki tarafın yaşam alanı için önemlidir; sonuç eşit."),
'A-1-3-5-2-1': ("Siyah yapışır", "Siyah 1 ile yapışabilir. Beyaz 3-3'ü işgal edince siyah içeriden kapatır ve sert oynar. İki taraf da kabul edebilir."),
'A-1-3-5-2-2': ("Siyah bağlanır – kötü şekil", "Siyah 1 ile bağlanırsa beyaz iyi hamleler yapar; siyahın şekli bozulur."),
'A-1-3-5-2-3': ("Siyah dıştan kapatır – biraz zayıf", "Siyah 1 biraz zayıftır. Beyaz 6 ile sertçe çıkar ve savaşta biraz daha rahattır."),
'A-1-3-5-3-1': ("Siyah kosumi", "Siyah 1 ile kosumi de olur. Beyaz 3-3'ü işgal edince siyah doğru yöne oynar ve 9 ile güzelce kapatır."),
'A-1-3-5-4-1': ("Siyah keima", "Siyah 1 ile keima yaparsa beyaz zıplar ve A-1-3-2-3-7'deki şekle döner."),
'A-1-3-5-5-1': ("Merdiven iyiyse siyah keima ile çıkar", "Merdiven siyahın lehineyse siyah 1 ile çıkabilir. İki taraf sade oynar; sonuç kabul edilebilir."),
'A-1-3-5-5-2': ("Siyah başa vurur – sert", "Siyah 1 biraz serttir. Beyaz ustaca oynar ve biraz öne geçer."),
'A-1-3-5-5-3': ("Merdiven kötüyse beyaz 3-3'ü işgal eder", "Merdiven siyahın aleyhineyse beyaz 1 çok güçlüdür. Beyaz güzel bir şekil kurar ve biraz daha iyidir."),
'A-1-3-5-5-4': ("Siyah zorla hane – kötü", "Siyah 1 kötüdür. Beyaz 2 ile keser; siyah çok alan kaybeder."),
'A-1-3-5-5-5': ("Merdiven iyiyse 2. sırada hane", "Merdiven siyahın lehineyse siyah 1 iyi bir hamledir. Beyaz taş feda edip kapatır ama merkezi siyahın alanını karşılamaz."),
'A-1-3-6-1-1': ("Beyaz çapraz keima – tuzak", "Beyaz 1 bir tuzaktır; siyah 2 ile kosumi-tsuke yapıp tuzağı bozar. Siyah sade oynar, beyaz memnun olmaz."),
'A-1-3-6-1-2': ("Beyaz uzanır – iyi değil", "Beyaz 1 de iyi değildir. Siyah köşeyi alır; beyazın taşları verimsiz kalır."),
'A-1-3-6-2-1': ("Siyah keima – biraz zayıf", "Siyah 1 biraz zayıftır. Beyaz iyi noktalara oynar ve köşeyi işgal eder; siyah taş feda eder. Sonuç eşit."),
'A-1-3-6-3-1': ("Siyah atlayıp keser – tuzağa düşer", "Siyah 1 tuzağa düşer. Beyaz sente kazanç sağlar ve ileride A'da ko açabilir."),
'A-1-3-7-1-1': ("Beyaz yapışıp uzanır", "Beyaz 1 ve 3 az oynanır. İki taraf şeklini tamamlar; siyah biraz daha iyi."),
'A-1-3-7-1-2': ("Sağ alt beyazsa beyaz pincer", "Sağ alt beyazsa beyaz 1 güçlüdür ama savaşta yine siyah biraz daha rahattır."),
'A-1-3-7-1-3': ("Sağ alt siyahsa beyaz keima", "Sağ alt siyahsa beyaz 1 ile çıkabilir; siyah yine biraz daha iyi."),
'A-1-3-7-2-1': ("Beyaz geri çekilirse", "Beyaz 1'e karşı siyah 2 aktiftir. Beyaz yerinde yaşar; siyah tenuki yapar ve temposu hızlıdır."),
'A-1-3-7-2-2': ("Sağ alt destekliyse siyah kaplan ağzı", "Sağ alt siyahın lehineyse siyah 1 ile savaşabilir. Siyah taş feda edip güzel bir merkez kurar."),
'A-1-3-8': ("Beyaz tenuki", "Siyah pincer yaptıktan sonra beyaz tenuki de yapabilir. Siyahın seçenekleri: A'da 3-3 kosumi, B'de yapışma, C'de kosumi-tsuke ve D'de keima."),
'A-1-3-8-1-1': ("Siyah 3-3 kosumi (yapay zekâ)", "Siyah 1 yapay zekânın yeni fikridir; beyaza yön değiştirme şansı bırakmaz. Siyah bir taşı keser ve çok alan kazanır. Sonuç eşit."),
'A-1-3-8-1-2': ("Beyaz keima ile çıkar", "Beyaz 1 ile çıkar, 3 ile tamamlar. Beyaz 9 iyi bir noktadır; iki taraf için de oynanabilir."),
'A-1-3-8-1-3': ("Beyaz yapışıp çıkar", "Beyaz 1 de bir yoldur. İki taraf sıkı oynar; sonuç eşit."),
'A-1-3-8-1-4': ("Beyaz yön değiştirir", "Beyaz 1 ve 3 ile esnekçe yön değiştirir; iki taraf da kabul edebilir."),
'A-1-3-8-2-1': ("Siyah üstten yapışır", "Siyah 1 çok kullanılır. Merdiven beyazın lehineyse beyaz hemen araya girip bağlanır ve köşede yaşar. Sonuç eşit."),
'A-1-3-8-2-2': ("Çevre destekliyse beyaz sertçe keser", "Çevrede destek varsa beyaz 1 çok serttir. İki taraf da saldırır; iki taraf için de oynanabilir."),
'A-1-3-8-2-3': ("Siyah çift hane", "Siyah 1 güçlüdür, beyaz 4 en iyi cevaptır. Siyah kenarda açılır; ileride A, B ve C sente olur."),
'A-1-3-8-2-4': ("Beyaz zıplar – kötü", "Beyaz 1 iyi değildir. Siyah beyazı kapatır ve çok güçlü bir merkez kurar."),
'A-1-3-8-2-5': ("Beyaz atari – şüpheli", "Beyaz 1 şüphelidir. Siyah 4 iyi bir hamledir; siyah sente beyazı kapatıp çok kazanır."),
'A-1-3-8-2-6': ("Beyaz başa vurur", "Beyaz 1 de bir yoldur; siyah 2 ile sağlamca bağlanır. Karışık bir savaş başlar."),
'A-1-3-8-2-7': ("Siyah uzanır – biraz zayıf", "Siyah 1 biraz zayıftır. Beyaz 8 ile çok iyi bir yoklama yapar ve kazanç sağlar."),
'A-1-3-8-2-8': ("Merdiven beyazın aleyhineyse", "Merdiven beyazın aleyhineyse siyah atari verip bağlandıktan sonra beyaz devam edemez."),
'A-1-3-8-2-9': ("Beyaz yine tenuki", "Beyaz yine tenuki yapabilir; siyah 1 ile şeklini tamamlar."),
'A-1-3-8-3-1': ("Siyah kosumi-tsuke", "Siyah 1 saldırgan bir hamledir, beyaz esnek oynar. Siyah 3-3'e kosumi yapar ve zor bir savaş başlar."),
'A-1-3-8-3-2': ("Siyah 7 yerine tenuki", "Önceki şekilde siyah 7 yerine tenuki yapabilir. Beyaz köşeyi alır; iki taraf da kabul edebilir."),
'A-1-3-8-3-3': ("Beyaz yapışıp savaşır", "Beyaz 1 ile doğrudan savaşırsa siyah güçlüce bastırır. Beyaz yaşar ama savaşta siyah daha rahattır."),
'A-1-3-8-3-4': ("Beyaz yine tenuki", "Beyaz yine tenuki yapabilir; siyah 1 ile A-1-3-8-2-9'a döner."),
'A-1-3-8-4-1': ("Siyah keima", "Siyah 1 dengeli bir hamledir; Keima josekisindeki bir şekle döner."),
}
