# Son, sade metinler (başlık, açıklama).
FINAL = {
'A-1-2': ("Başlangıç pozisyonu", "Siyah 1 ile bir boşluklu zıplama, keimaya göre merkeze daha çok önem verir. Beyazın seçenekleri: A'da keima ile dürtmek, B'de yapışmak, C'de 2. sıradan keima, D'de 3-3 işgali ya da tenuki."),
'A-1-2-1': ("Beyaz keima ile dürter", "Beyaz 1 yapay zekânın ilk tercihidir. Eskiden kaba bir hamle sayılırdı ama siyahın taşlarının verimini düşürür. Siyah için A'da bağlanmak sadedir. B ve C sert cevaplardır; D sağlamdır ama biraz kayıptır."),
'A-1-2-1-1-1': ("Siyah bağlanır – sade", "Siyah 1 ile bağlanmak sadedir; beyaz 2 ile 2. sıradan kayar. Siyah 3 ile kenarda açılmak iyidir. Sonuç eşit."),
'A-1-2-1-1-2': ("Sol üst destekliyse siyah tenuki", "Sol üstte siyah taş varsa siyah tenuki yapabilir. Beyaz 1 ile sıkıştırır, siyah 2 ile karşı pincer yapar ve zor bir savaş başlar."),
'A-1-2-1-2-1': ("Merdiven iyiyse kosumi-tsuke", "Merdiven siyahın lehineyse siyah 1 güçlü bir hamledir. Beyaz 4 ile içeriden keser; devamı yine merdivene bağlıdır."),
'A-1-2-1-2-2': ("Siyah hane ile çıkar", "Merdiven siyahın lehineyse siyah 1 güçlüdür. Siyah 3 ile sakince bağlanır ve sente köşeyi alır; siyah memnundur."),
'A-1-2-1-2-3': ("Siyah sürünür – şüpheli", "Siyah 1 ile sürünmek şüphelidir. Beyaz taşları takas eder; siyah önceki şekildeki kadar iyi değildir."),
'A-1-2-1-2-4': ("Merdiven kötüyse beyaz keser", "Merdiven siyahın aleyhineyse beyaz 1 ile keser ve köşede yaşar. Siyah atari ile sıkıştırır ama 2. sırada sürünmek zorunda kalır. Kimin daha iyi olduğu belli değil."),
'A-1-2-1-2-5': ("Siyah kaplan ağzı", "Siyah 1 ile kaplan ağzı da olur. Karışık bir savaş sürer; iki taraf için de oynanabilir."),
'A-1-2-1-2-6': ("Beyaz hane – iyi değil", "Beyaz 1 ile hane iyi değildir. Siyah 2 iyi bir hamledir; siyah sakin oynayıp biraz öne geçer."),
'A-1-2-1-2-7': ("Siyah hane – biraz zayıf", "Siyah 1 biraz zayıftır. Beyaz 4 kaçırılmaması gereken bir noktadır; beyaz kazançlı çıkar."),
'A-1-2-1-2-8': ("Siyah merkez için keser", "Siyah 1 merkeze önem verir. Beyaz 6 ile köşeyi alır; bu da beyaz için biraz daha iyidir."),
'A-1-2-1-2-9': ("Siyah fazla basit oynar", "Siyah 1 ve 3 fazla basittir. Beyaz 4 iyi bir hamledir; alttaki siyah grup zor yaşar ve çok puan kaybeder."),
'A-1-2-1-2-10': ("Beyaz önce uzanırsa", "Beyaz 1 ile önce uzanırsa siyah 2 ile mutlaka bastırmalıdır. Sonra beyaz A ya da B'yi seçer; iki taraf için de oynanabilir."),
'A-1-2-1-2-11': ("Siyah aşağı uzanır – sıkışık", "Siyah 1 biraz sıkışık bir hamledir. Beyaz sente rahat oynar ve 6 ile güzelce çıkar."),
'A-1-2-1-2-12': ("Beyaz 2. sıradan atari", "Beyaz 1 ile 2. sıradan atari de olur; siyah 2 güçlü bir cevaptır. Beyaz önemli noktaları alır ve karışık bir savaş başlar."),
'A-1-2-1-2-13': ("Siyah köşeyi alır", "Siyah 1 ve 3 ile köşeyi almak da bir yoldur. Sonuç eşit."),
'A-1-2-1-2-14': ("Merdiven iyiyse siyah köşeyi kapatır", "Merdiven siyahın lehineyse siyah 1 ile köşeyi kapatabilir. Beyaz 8 iyi bir hamledir; iki taraf için de oynanabilir."),
'A-1-2-1-2-15': ("Merdiven kötüyse beyaz dıştan keser", "Merdiven siyahın aleyhineyse beyazın 1 ile dıştan kesmesi siyahı zorlar. Savaşı beyaz yönetir."),
'A-1-2-1-2-16': ("Siyah uzanır – işe yaramaz", "Siyah 1 işe yaramaz. Beyaz 2 çok iyi bir hamledir ve siyah büyük kayıp verir."),
'A-1-2-1-2-17': ("Siyah yapışır – aşırı", "Siyah 1 aşırıdır. Beyaz 4 ile güçlü şekilde çıkar; siyahın savaşı çok zordur."),
'A-1-2-1-2-18': ("Siyah atari – kötü", "Siyah 1 ile atari kötüdür. Beyaz 2 ile karşı atari verir ve köşede çok alan kazanır."),
'A-1-2-1-2-19': ("Merdiven iyiyse siyah bağlanır", "Merdiven siyahın lehineyse siyah 1 ile bağlanıp 3 ile çıkabilir. Savaş beyaz için biraz zordur."),
'A-1-2-1-2-20': ("Beyaz uzanır – yumuşak", "Beyaz 1 biraz yumuşaktır. Siyah 2 ile güzel bir şekil kurar; beyaz biraz kayıpta."),
'A-1-2-1-3-1': ("Siyah yapışıp yükselir – şüpheli", "Siyah 1 biraz şüphelidir. Beyaz 2 ile köşeyi işgal eder ve iki taraf da geri adım atamaz. Savaşta beyaz biraz daha rahattır."),
'A-1-2-1-3-2': ("Siyah iki boşluklu açılır – yumuşak", "Siyah 1 biraz yumuşaktır. Beyaz 2 ile güzel bir şekil kurar."),
'A-1-2-1-3-3': ("Siyah keser – aşırı", "Siyah 1 aşırıdır; siyah 3 ile geri dönmek zorunda kalır. Beyaz sakince tamamlar; siyah kayıpta."),
'A-1-2-1-3-4': ("Siyah kosumide ısrar eder – kötü", "Siyah 1'de ısrar etmek kötüdür. Beyaz 4 güçlüdür; sonunda siyahın beş taşı sıkışır."),
'A-1-2-1-3-5': ("Siyah yanlış sırayla işgal eder", "Siyah 1 yanlış sıradır. Beyaz köşede yaşayıp çok puan alır ve açıkça öne geçer."),
'A-1-2-1-3-6': ("Siyah köşeye hane", "Siyah 1 ile köşeye hane yaparsa beyaz doğru sırayla oynar, kenarda açılır ve memnun olur."),
'A-1-2-1-3-7': ("Beyaz bağlanır – şüpheli", "Beyaz 1 şüphelidir. Siyah 2 ile güçlü karşılık verir ve önceki şekilden çok daha iyi olur."),
'A-1-2-1-3-8': ("Beyaz uzanır – biraz yumuşak", "Beyaz 1 biraz yumuşaktır; siyah 2 ile basitçe bağlanır. İki taraf da güçlenir; sonuç eşit."),
'A-1-2-1-3-9': ("Siyah kosumi-tsuke", "Siyah 1'den sonra beyaz itip keser. Sol üst beyazsa beyaz rahat savaşır ve biraz öne geçer."),
'A-1-2-1-3-10': ("Sol üst siyahsa beyaz sürünür", "Sol üst siyahsa beyaz 1 ile sürünmek iyidir. Siyah köşeyi korumak zorunda kalır; beyaz biraz daha iyi."),
'A-1-2-1-3-11': ("Siyah iki kez bastırır", "Siyah 1 ve 3 ile bastırırsa beyaz 4 ile sakince açılır. Bu şekil beyazın lehinedir."),
'A-1-2-1-3-12': ("Siyah keser – kötü", "Siyah 1 kötüdür. Beyaz sente yaşar, siyah kendi grubunu korumak zorunda kalır."),
'A-1-2-1-3-13': ("Beyaz başa hane – aşırı", "Beyaz 1 fazla ileri gider. Siyah keser ve iki taşı sağlamca yakalar. Sonuç eşit."),
'A-1-2-1-4-1': ("Siyah sağlam bağlanır – yetersiz", "Merdiven iyi olsa bile siyah 1 pek iyi değildir. Beyaz 2 ile açılıp memnun olur; siyah ileride A'daki kesmeye dikkat etmelidir."),
'A-1-2-1-4-2': ("Merdiven kötüyse beyaz keser", "Merdiven siyahın aleyhineyse beyaz 1 ve 3 ile hemen keser. Savaş açıkça beyazın lehinedir."),
'A-1-2-1-4-3': ("Siyah atari – takas", "Siyah 1 ile atari verirse taşlar takas edilir; beyaz da memnundur."),
'A-1-2-2-1-1': ("Beyaz yapışıp çift hane – zayıf", "İşaretli siyah taş yüksekte olduğu için beyazın yapışıp çift hane yapması biraz zayıftır. Siyah 4 ve 10 ile baskı kurar."),
'A-1-2-2-2-1': ("Siyah ters kaplan ağzı", "Siyah 1 ile ters kaplan ağzı da olur; işaretli taş yine iyi yerdedir. Beyaz A'yı oynarsa siyah B ile çok güzel bir şekil kurar."),
'A-1-2-2-3-1': ("Siyah atari", "Siyah 1 ile atari de düşünülebilir; işaretli taş burada da iyi çalışır."),
'A-1-2-2-4-1': ("Siyah çift hane – biraz zayıf", "Siyah 1 biraz zayıftır. Beyaz yön değiştirip merkez alır. Siyahın sonra tenuki yapması iyidir."),
'A-1-2-3-1-1': ("Beyaz 2. sıradan keima – siyah tenuki", "Keimadaki gibi beyaz 1 siyahı pek zorlamaz. Siyahın tenuki yapması iyidir."),
'A-1-2-3-1-2': ("Beyaz sonra sıkıştırır", "İleride beyaz 1 ile sıkıştırmak önemli bir noktadır; siyah 2 ile 3-3'e kosumi yapar. Sağ alt beyazsa beyaz 3 iyidir ve zor bir savaş başlar."),
'A-1-2-3-1-3': ("Sol üst beyazsa beyaz keima", "Sol üst beyazsa beyaz 1 iyi bir noktadır; savaş dengeli."),
'A-1-2-3-1-4': ("Neden önce dürtmek?", "Beyaz 1 ile şimdi dürtmek A-1-2-1-1-2'ye dönmez; siyah 2 ile karşılık verir. Bu yüzden yapay zekâ önce dürter, sonra kayar."),
'A-1-2-3-2-1': ("Siyah 3-3 kosumi", "Siyah 1 neredeyse sentedir; beyaz 2 ile iki boşluklu açılır. Yapay zekâya göre siyahın hemen kenarda açılması acil değildir."),
'A-1-2-3-2-2': ("Sağ alt beyazsa beyaz dürter", "Sağ alt beyazsa beyaz 1 aktif bir hamledir; iki taraf da hızla gelişir."),
'A-1-2-3-2-3': ("Siyah pincer", "Siyah 1 ile pincer yaparsa beyaz 2 ile güzelce zıplar ve 4 ile karşı pincer yapar. İki taraf için de oynanabilir."),
'A-1-2-3-2-4': ("Sol üst siyahsa siyah yapışır", "Sol üst siyahsa siyah 1 ile beyazı sarabilir; A-1-2-3-1-4'teki şekle döner."),
'A-1-2-3-2-5': ("Beyaz tenuki yaparsa", "Beyaz tenuki yaparsa siyah 1 ile pincer yapıp saldırır. Bir ko çıkar; siyah biraz öndedir ama beyaz da kurtulur."),
'A-1-2-3-2-6': ("Beyaz hemen hane – riskli", "Beyaz 1 ile hemen hane yaparsa siyah 8 güçlüdür. Koyu kaybederse beyazın bütün grubu ölür."),
'A-1-2-3-2-7': ("Beyaz geri çekilir – zayıf", "Beyaz 1 zayıftır. Siyah 2 çok iyi bir noktadır ve beyaz hâlâ yaşamamıştır."),
'A-1-2-3-2-8': ("Beyaz kosumi-tsuke – uygun değil", "Beyaz 1 uygun değildir. Siyah bir taşı yakalar ve saldırmaya devam eder."),
'A-1-2-3-3-1': ("Siyah yüksek iki boşluklu açılır", "Siyah 1 ile yüksekte açılmak da bir seçenektir; beyaz tenuki yapabilir."),
'A-1-2-3-4-1': ("Siyah üç boşluklu açılır", "Siyah 1 hemen hemen aynıdır; beyaz yine tenuki yapabilir. Beyazın A'sı sente olmadığı için siyah da tenuki yapabilir."),
'A-1-2-3-5-1': ("Sağ alt siyahsa siyah pincer", "Sağ alt siyahsa siyah 1 ile pincer yapar, 3 ile yapışır. İki taraf da memnundur; sağ alt beyazsa siyah biraz kayıpta."),
'A-1-2-3-5-2': ("Beyaz geri çekilir – biraz kayıp", "Beyaz 1 biraz kayıptır. İşaretli siyah taş çok iyi yerdedir; ileride B'deki zıplama siyaha kazanç sağlar."),
'A-1-2-3-5-3': ("Siyah kosumi-tsuke – kaba", "Siyah 1 kaba bir hamledir. Beyaz sente şeklini belirler ve öne geçer."),
'A-1-2-3-6-1': ("Siyah yapışır", "Siyah 1 sıkı bir hamledir; beyaz 2 ile yukarıdan hane yapar. Devamı çevredeki taşlara bağlıdır. Sağ alt siyahsa sonuç eşit."),
'A-1-2-3-6-2': ("Sağ alt beyazsa siyah kosumi", "Sağ alt beyazsa siyah 1 ile kosumi yeterlidir; beyazın taşları iyi durmaz."),
'A-1-2-3-6-3': ("Beyaz başa vurur – aşırı", "Beyaz 1 aşırıdır. Siyah en güçlü şekilde karşılık verir; sağ alt siyahsa savaşı o yönetir."),
'A-1-2-3-6-4': ("Sol üst siyahsa siyah feda eder", "Sol üst siyahsa siyah taş feda edip memnun olur. Merdiven beyazın aleyhineyse siyah doğrudan yakalar."),
'A-1-2-3-6-5': ("Sağ alt beyazsa beyaz aşağı uzanır", "Sağ alt beyazsa beyaz 1 olur; siyah 2 ile sakin kalır. Beyaz iyi noktaları alır ve biraz daha rahattır."),
'A-1-2-3-6-6': ("Siyah keser – acele", "Siyah 1 acelecidir. Beyaz iki kez bastırır ve can alıcı noktaları oynar; savaşı beyaz yönetir."),
'A-1-2-3-6-7': ("Sağ alt siyahsa siyah hane", "Sağ alt siyahsa siyah 1 iyi bir hamledir; siyahın taşları çok iyi durur."),
'A-1-2-3-6-8': ("Beyaz atari ile çıkar – kötü", "Beyaz 1 açıkça kötüdür. Siyah merkezde güçlenir; beyazın alanı bunu karşılamaz."),
'A-1-2-3-6-9': ("Sağ alt beyazsa beyaz bağlanır", "Sağ alt beyazsa beyaz 1 ile bağlanır, 3 ile büyük bir bastırma yapar. İki taraf için de oynanabilir."),
'A-1-2-3-6-10': ("Sağ alt siyahsa beyaz küçük zıplar", "Sağ alt siyahsa beyaz 1 ile küçük zıplamak iyidir. Taşlar takas edilir; siyah biraz öndedir."),
'A-1-2-3-6-11': ("Beyaz dürter", "Beyaz 1 sente şeklini düzeltmek ister; siyah 2 ile sert karşılık verir. Sonuç eşit."),
'A-1-2-3-6-12': ("Siyah bağlanır – yumuşak", "Siyah 1 yumuşaktır. Beyaz rahatça aşağı uzanır; siyah memnun değildir."),
'A-1-2-3-6-13': ("Beyaz aşağı hane – sıkışık", "Beyaz 1 biraz sıkışıktır. Siyah 2 ile basitçe uzanır ve sente merkez alır."),
'A-1-2-3-6-14': ("Siyah keser", "Siyah 1 de iyi bir hamledir. Merdiven beyazın lehine olsa bile takasta siyah daha çok kazanır."),
'A-1-2-3-6-15': ("Merdiven kötüyse beyaz taşı alır", "Merdiven beyazın aleyhineyse beyaz bir taşı almak zorundadır; siyah sente kazanç sağlamıştır."),
'A-1-2-3-6-16': ("Siyah çift hane – uygun değil", "Siyah 1 uygun değildir. Beyaz sente bir taşı alır; sonuç eşit."),
'A-1-2-3-7-1': ("Siyah omuz vuruşu – genelde kötü", "Siyah 1 genelde iyi değildir. Beyaz dürtüp sıkıştırır; siyah A ve B'nin ikisine birden yetişemez."),
'A-1-2-3-7-2': ("Beyaz sürünür – pasif", "Beyaz 1 yeterince aktif değildir. Siyah tenuki yapar, sonra A, B ve C arasından seçer."),
'A-1-2-3-7-3': ("Beyaz yapışır – iyi değil", "Beyaz 1 de iyi değildir. Siyah sıkı oynar ve memnun olur."),
'A-1-2-4-1-1': ("Beyaz 3-3 işgali", "İşaretli yerde siyah taş varsa beyaz 1 ile 3-3'ü işgal edebilir; normalde beyaz biraz kayıptadır. Siyah sakin oynar ve memnun olur."),
'A-1-2-4-1-2': ("Siyah yapışır – aşırı", "Siyah 1 aşırıdır. Beyaz itip keser; siyah A ile B'yi aynı anda koruyamaz."),
'A-1-2-4-1-3': ("Siyah pincer ile tamamlar", "Siyah 1 de bir yoldur. Beyaz sente takastan sonra tenuki yapar; sonuç eşit."),
'A-1-2-4-1-4': ("Beyaz keima – biraz kayıp", "Beyaz 1 biraz kayıptır. Siyah 2 ile kalın bir şekil kurar."),
'A-1-2-4-1-5': ("Beyaz uzanır – ağır", "Beyaz 1 taşlarını ağırlaştırır ve 7 ile güçlenmek zorunda kalır. Siyah rahatça zıplar."),
'A-1-2-4-1-6': ("Beyaz acele keser", "Beyaz 1 ve 3 acelecidir. Beyaz köşesini korumak zorunda kaldığı için savaş ona zor gelir."),
'A-1-2-4-1-7': ("Siyah bağlanır – biraz zayıf", "Siyah 1 biraz zayıftır. Beyaz 6 ile siyahı zorlar ve hem köşede hem kenarda kazanır."),
'A-1-2-4-1-8': ("Siyah hane ile baskı yapar", "Siyah 1 beyaza baskı yapar ama beyazın köşesi artık yaşıyor. Beyaz tenuki yapabilir."),
'A-1-2-4-1-9': ("Beyaz kenarda açılırsa", "Beyaz 1 ile açılırsa siyah 2 ile sağlamca bağlanır. Siyah köşeyi öldürmeye çalışsa da beyaz 7 ile kurtulur."),
'A-1-2-4-1-10': ("Beyaz itip keser", "Beyaz siyahın az nefesinden yararlanır ve 7 ile yaşar. İki taraf için de oynanabilir."),
'A-1-2-4-1-11': ("Beyaz kaplan ağzı – eski yol", "Eskiden oynanan beyaz 1, A'daki pincer imkânını yok eder. Beyaz kazandığından fazlasını kaybeder."),
'A-1-2-4-2-1': ("Siyah döner – sade", "Siyah 1 ile dönmek sade bir çözümdür; çoğu durumda kayıp vermez."),
'A-1-2-5-1-1': ("Beyaz tenuki – siyah kosumi-tsuke", "Beyaz tenuki de yapabilir. Siyah genelde 1 ile kosumi-tsuke yapar; beyaz yine tenuki yapabilir."),
'A-1-2-5-1-2': ("Beyaz keima ile dürter", "Beyaz 1 ile dürtebilir, siyah 2 ile karşılık verir. İki taraf da kabul edebilir."),
'A-1-2-5-1-3': ("Beyaz uzanır – ağır", "Siyah bir boşluklu zıpladıysa beyaz 1 ağır kalır. Siyah 2 ile pincer yapar ve beyaz zorlanır."),
'A-1-2-5-2-1': ("Siyah iki boşluklu pincer", "Siyah 1 ile iki boşluklu pincer yapabilir. Beyaz 6'da tenuki yapar; bu esnek bir düşüncedir. Sonuç eşit."),
'A-1-2-5-2-2': ("Siyah iter – tuzağa düşer", "Siyah 1 tuzağa düşer. Beyaz taşları takas eder; siyah biraz kötü durumdadır."),
'A-1-2-5-2-3': ("Beyaz keima ile dürter", "Beyaz 1 ile dürtebilir, siyah 2 ile doğru şekli kurar. İki taraf için de oynanabilir."),
'A-1-2-5-2-4': ("Beyaz 3-3 işgali – biraz zayıf", "Beyaz 1 biraz zayıftır. Siyah doğal oynar ve biraz öne geçer."),
'A-1-2-5-2-5': ("Beyaz büyük keima ile kapatır", "Beyaz 1 ile büyük keima yapıp köşeyi kapatmak da iyidir. İki taraf için de oynanabilir."),
'A-1-2-5-2-6': ("Siyah kosumi-tsuke – biraz kötü", "Siyah 1'den sonra beyaz 2 ile tam zamanında yoklar, 4 ile 3-3'ü işgal eder. Takasta beyaz biraz öndedir."),
'A-1-2-5-2-7': ("Siyah acele ayırır", "Siyah 1 ve 3 acelecidir. Beyaz 10 ve 16 ile iyi oynar; savaşta beyaz biraz daha rahattır."),
}
