# Son, sade metinler (başlık, açıklama).
FINAL = {
'A-1-10': ("Başlangıç pozisyonu", "Sol üst destekliyse büyük keima ile köşeyi kapatmak hem köşeyi hem kenarı korur ve sol tarafı geliştirmeye yardım eder. Keimaya göre köşe daha boştur; bu yüzden yapay zekânın ilk tercihi A'da 3-3 işgalidir. Büyük keima bir çizgi daha geniş olduğu için B'de keima ve C'de yapışma pek iyi değildir."),
'A-1-10-1-1-1': ("3-3 işgali", "Beyaz 1 doğru hamledir ve bu yaygın bir şekildir. Tahta boşken siyah şimdilik tenuki yapabilir; ileride beyazın A'da kesmesi çok değerlidir."),
'A-1-10-1-1-2': ("Siyah önce sürünür", "Sağ taraf değerliyse siyah 1 ile önce sürünür, sonra 5 ile karşı pincer yaparak oyunu sağa çevirir."),
'A-1-10-1-1-3': ("Siyah bağlanır", "Siyah 1 ile bağlanmak da olur, sonra 3 ile kalınca bastırır; 9 ile keima yapıp tamamlayınca iyi bir şekil kurar. İki taraf da kabul edebilir."),
'A-1-10-1-1-4': ("Beyazın sonraki pinceri", "İleride beyaz 1 ile pincer yapınca siyah tenuki yapabilir. Beyaz 3 ile keser; siyah 4 ve 8 ile sakince taş feda eder. Sonuç eşit."),
'A-1-10-1-1-5': ("Beyaz sürünür", "Beyaz 1 ile sürünmek de olur; siyah 2 ile iyi bir kaplan ağzı yapar. Beyaz 5 ile hane yapıp siyahı yoklar, siyah 8 ile rahatça tamamlar. Beyaz 9 ile pincerden çıkıp alan alır; iki taraf da savaşabilir."),
'A-1-10-1-1-6': ("Siyah vurur – beyaza yarar", "Siyah 1 beyazın işine yarayabilir. Beyaz 2 ile pincer yapıp siyahı yoklar; siyah 3 ile büyük zıplayıp tamamlamalıdır."),
'A-1-10-1-1-7': ("Siyah 1. sırada hane", "Siyah 1 ile 1. sırada hane yapıp bağlantıyı keserse beyaz 2 ile zıplayıp siyahı rahatsız eder. Siyah 3 ile hem başını çıkarır hem keseri korur, beyaz 4 ve 6 ile geri adım atmaz. Siyah 7 ile iki taşın başına hane, 9 ile sıkıca keser ve takas olur; siyah biraz memnun değildir."),
'A-1-10-1-1-8': ("Beyaz geri çekilir – biraz yumuşak", "Beyaz 1 biraz yumuşaktır. Siyah 2 ile geri çekilince şekli tamamlanır; siyah önceki şekilden biraz daha iyi."),
'A-1-10-1-1-9': ("Beyaz hemen sürünür – kötü", "Beyaz 1 kötüdür. Siyah 2 ile köşede hane yapar ve beyazın köşesi açıkça küçülür. Beyaz 7 ve 9 ile itip keserek savaşmak zorundadır ama siyahın iki grubu da rahattır; beyaz biraz zorlanır."),
'A-1-10-1-1-10': ("Beyaz tek keima – kötü", "Beyaz 1 de kötüdür; siyah 2 ile aşağı uzanmak önemli noktadır. Beyaz 3 ile sürünüp sente alsa da siyah 8 ile işgal edince beyazın köşesi çok daralır. Beyaz 9 mecburdur, siyah 10 ile sente açılır."),
'A-1-10-1-2-1': ("Siyah hane – kötü", "Siyah 1 kötüdür. Beyaz 2 ve 4 ile önce hane yapıp bağlanır, sonra 6 ile sente hane yaparak köşede tamamen yaşar. Beyaz 8 ile sıkı bir pincer yapar; siyahın şekli kötüdür."),
'A-1-10-1-2-2': ("Beyaz önce bu taraftan hane – kötü", "Beyaz 1 kötüdür. Siyah 2 ile akıllıca bağlanır; siyahın şekli önceki şekilden çok daha kalındır."),
'A-1-10-2-1-1': ("Beyaz 2. sıradan keima – biraz kayıp", "İşaretli siyah taş A'daki keimadan bir çizgi uzakta olduğu için beyaz 1 ile yine 2. sıradan keima yaparsa siyah 2 ile 3-3'e kosumi yapabilir; beyaz biraz kayıpta."),
'A-1-10-3-1-1': ("Beyaz yapışır – biraz kayıp", "Beyaz 1 ile yapışmak da biraz kayıptır. İşaretli siyah taş A'daki keimadan bir çizgi uzakta olduğu için siyah daha memnundur."),
'A-1-10-4-1-1': ("Beyaz tenuki", "Beyazın tenuki yapması da bir yoldur. Büyük keimanın köşesi zayıf olduğu için siyah 1 ile kosumi-tsuke burada o kadar güçlü değildir. Siyah 3 ile pincer yapınca beyaz 4 keima ile işgal eder, sonra 6 ile doğal olarak uzanıp çıkar; oynanabilir."),
'A-1-10-4-1-2': ("Beyaz iter – fazla sıkı", "Beyaz 1 fazla sıkıdır; siyah 2 ile kaplan ağzı yapıp güçlü karşılık verir. Beyaz sol tarafta biraz kazansa da bütünü inceldiği için kazandığından çok kaybeder."),
'A-1-10-4-2-1': ("Siyah alçak bir boşluklu pincer", "Siyah 1 ile alçak bir boşluklu pincer de olur; beyaz 2 ile zıplayıp savaşabilir. Siyah 3 ile beraber zıplarsa beyaz 4 ile köşeyi işgal etmek sadedir. Siyah 7 ile sağlamca döner; sonuç eşit."),
'A-1-10-4-2-2': ("Siyah aşağı hane", "Siyah 1 ile aşağı hane de olur; beyaz sente köşeyi alır ve dışarıdaki iki taşın imkânlarını saklı tutar. İki taraf da kabul edebilir."),
'A-1-10-4-2-3': ("Beyaz hemen köşeyi işgal eder", "Beyaz 1 ile hemen köşeyi işgal etmek de olur; siyah 4 ile sakince döner. Sonuç eşit."),
'A-1-10-4-2-4': ("Merdiven lehine – siyah keima", "Merdiven siyahın lehineyse siyah 1 ile keima yapmak olur. Beyaz 2 ile iyi bir yapışma yapar, sonra 4 ve 6 ile itip keserek takas eder; sonuç eşit."),
'A-1-10-4-2-5': ("Merdiven siyahın aleyhine", "Merdiven siyahın aleyhineyse beyazın 1 ve 3 ile hemen itip kesmesi yeter; siyah çöker."),
'A-1-10-4-2-6': ("Beyaz büyük keima", "Beyaz 1 büyük keima ilginç bir hamledir; siyah 2 ve beyaz 3 kendini tamamlar. Siyah 4 ile beyaz 5 takası siyaha biraz yarar; iki taraf da savaşabilir."),
}
