# Son, sade metinler (başlık, açıklama).
FINAL = {
'A-1-5': ("Başlangıç pozisyonu", "Alçak iki boşluklu pincer bir zamanlar çok popülerdi. Yapay zekâya göre çoğu durumda alçak bir boşluklu ve üç boşluklu pincerden daha az iyidir; bu yüzden artık seyrek görülür. Beyazın seçenekleri: A'da 3-3 işgali, B'de zıplama, C ve D'de çift kakari, E'de iki boşluklu karşı pincer ya da tenuki."),
'A-1-5-1-1-1': ("3-3 işgali", "Beyaz 1 doğru hamlelerden biridir; siyah 8 ve 10 aşağı yukarı böyledir. İleride beyazın A'da büyük keima ya da B'de pincer sonrası C'de yapışma imkânı var; siyah biraz rahatsızdır."),
'A-1-5-1-1-2': ("Siyah tenuki yaparsa", "Siyah tenuki yaparsa beyaz ileride 1 ile pincer yapıp savaşabilir. Alçak pincerdeki bir şekle döner."),
'A-1-5-1-1-3': ("Siyah sürünür – pek iyi değil", "Siyah 1 de pek iyi değildir. Siyah 3 ile bir hamle daha tamamlamak zorundadır; işaretli siyah taş verimsiz kalır."),
'A-1-5-1-1-4': ("Siyah tenuki – beyaz yapışıp çıkar", "Siyah tenuki yaparsa beyaz 1 ile yapışıp çıkmak serttir. Siyah 2 ile uzanmak en güçlü cevaptır; beyaz 7 keima ile çıkıp çok kazanır."),
'A-1-5-1-1-5': ("Beyaz tek keima – biraz yumuşak", "Beyaz 1 biraz yumuşaktır. Sağ alt siyahı destekliyorsa siyahın A'da zıplaması yine iyi bir noktadır."),
'A-1-5-2-1-1': ("Beyaz zıplar", "Beyaz 1 siyahı pek zorlamaz; siyahın 2 ile beraber zıplaması yeter. Beyaz 3 ile karşı pincer bir yoldur, siyah 4 ile kosumi-tsuke akıllıcadır. Savaşta siyah daha rahattır."),
'A-1-5-2-1-2': ("Beyaz yaklaşır", "Beyaz 1 aktif bir yaklaşmadır. Siyah 2 ve 4 ile sakince kosumi yapar, sonra 6 ile kapatır; bu küçük görünür ama büyüktür. Beyaz iki tarafta da ince kalır, siyah rahattır."),
'A-1-5-2-1-3': ("Beyaz yerinde yaşar", "Beyaz 1 ve 3 ile yerinde yaşamak da bir yoldur; burada da siyah biraz daha iyi."),
'A-1-5-2-1-4': ("Beyaz 3-3 işgali – kötü", "Beyaz 1 kötüdür. Siyah 6 ile sürünmek iyi bir hamledir, 10 ile hane yapınca şekli çok dolgun olur."),
'A-1-5-2-2-1': ("Siyah keima", "Siyah 1 keima da iyidir. Beyaz 8 ile kesme noktasını kapatmak zorundadır. Siyah 9 ile hızlıca açılır; beyazın merkezi işe yaramaz."),
'A-1-5-3': ("Çift kakari", "Beyaz 1 çift kakari çok yaygındır ve siyahın birçok cevabı var. Yapay zekâ en çok A'da keima ile kapatmayı önerir. Eskiden B ve C'de bastırmak daha yaygındı. D'de keima ile baskı, E'de kosumi-tsuke, F'de büyük keima ve G'de fil adımı da olur."),
'A-1-5-3-1-1': ("Siyah keima ile kapatır", "Eskiden oynanan A ve B'deki bastırmalar yerine yapay zekâ siyah 1'i önerir. Beyaz 2 ile köşeyi işgal etmek sade bir yoldur; iki taraf da oynayabilir."),
'A-1-5-3-1-2': ("Yapışıp kesmek", "Beyaz 1 ve 3 ile yapışıp kesmek karışıktır. Siyah 4 ve 6 ile önce dıştan, sonra içeriden atari verir; bu doğru sıradır. Siyah 8 ile itmek bir yoldur; sonuç eşit."),
'A-1-5-3-1-3': ("Siyah bu taraftan iter", "Siyah 1 ile bu taraftan itmek de olur; beyaz 2 ve 4 ile sade cevap verir. İki taraf da kabul edebilir."),
'A-1-5-3-1-4': ("Merdiven beyazın lehine", "Merdiven beyazın lehineyse beyaz 1 ile kesip atari vermek güçlüdür. Siyah 4 ve 6 ile sakince taş feda eder, sonra 8 ile kapatır; bu çok büyüktür. Beyaz 9 ile yine keser ve karışık bir savaş başlar."),
'A-1-5-3-1-5': ("Siyah bağlanır – gevşek", "Siyahın bağlanması gevşektir. Beyaz 2 ile dönüp köşede dolgun bir alan alır; ileride A'da hane imkânı da var, siyahın merkezi kalın değildir."),
'A-1-5-3-1-6': ("Yanlış sıra", "Siyah 1 ve 3 yanlış sıradır. Beyaz 4 ile karşı atari akıllıcadır; siyah biraz kayıpta."),
'A-1-5-3-2-1': ("Siyah bastırır – biraz yavaş", "Siyah 1 biraz yavaştır. Beyaz 2 ve 4 ile köşeyi işgal edip dönmek sade ve iyidir; pincer taşı kötü yerde kalır. Sonra beyaz A'da yaklaşıp B'de aşağı uzanmayı hedefler."),
'A-1-5-3-2-2': ("Beyaz bağlanır – aşırı", "Beyaz 1 fazla serttir. Siyah 2 ile güçlüce kapatır, 6 ile sıkıca yapışır. Beyaz 7 ve 9 mecburdur; siyah 12 ile pincer yapınca memnundur."),
'A-1-5-3-2-3': ("Beyaz bastırır", "Beyaz 1 ile bastırmak da bir yoldur; siyah 2'den sonrası aşağı yukarı böyledir. Siyah 10 güçlüdür, beyaz 11 ile sağlamca açılır; iki taraf da kabul edebilir."),
'A-1-5-3-3-1': ("Bu taraftan bastırmak – kötü", "Siyah 1 ile bu taraftan bastırmak kötüdür. Beyaz 2 ve 4 ile yine hane yapıp köşeyi işgal eder; siyah A-1-5-3-2-1'dekinden de kötü durumdadır."),
'A-1-5-3-3-2': ("Siyah kapatır – şüpheli", "Siyah 1 şüphelidir. Beyaz 2 ile sürünüp bağlanınca siyahın şekli bozulur. Siyah 5 köşeyi tehdit edince beyaz 6 ve 8 ile keskin karşılık verir; takasta beyaz daha çok kazanır."),
'A-1-5-3-3-3': ("Siyah uzlaşmazsa", "Siyah 1 ile uzlaşmak istemezse beyaz 2, 4 ve 6 ile iyi sırayla oynar; siyah 7 mecburdur. Beyaz 8 ile başını çıkarınca köşedeki üç siyah taş boşa gider."),
'A-1-5-3-3-4': ("Siyah bağlanır – çok rahatsız", "Siyah 1 ile bağlanırsa beyaz 2 ve 4 ile hane yapıp bağlanır. Siyah A'da uzansa da B'de bağlansa da işaretli iki beyaz taş siyahın zayıf noktasındadır; siyah çok rahatsızdır."),
'A-1-5-3-3-5': ("Beyaz hemen 3-3", "Beyaz 1 ile hemen köşeyi işgal etmek biraz kötüdür. Beyaz 5 kosumi doğru şekildir, siyah 6 ile itmek akıllıcadır; sonuç eşit."),
'A-1-5-3-3-6': ("Siyah kaplan ağzı – kötü", "Siyah 1 kötüdür. Siyah 3 ile yine tamamlamak zorunda kalır; temposu çok yavaştır."),
'A-1-5-3-3-7': ("Siyah tenuki yaparsa", "Siyah tenuki yaparsa beyaz 1 ile hareket etmek serttir. Siyah en güçlü şekilde cevap verir ama beyaz 9 ve 11 ile güçlü oynar; savaşta siyah zorlanır."),
'A-1-5-3-3-8': ("Siyah bastırır – plansız", "Siyah 1 plansızdır. Beyaz 2 ile hane yapıp rahatça bağlanır; siyahın bütün grubu köksüz kalır."),
'A-1-5-3-4-1': ("Keima ile baskı", "Siyah 1 ile keima baskısı da olur; beyaz 2 ile köşeyi işgal etmek sadedir. Siyah 1 taşı A-1-5-3-1-1'deki A noktasından biraz kötüdür; işaretli beyaz taş daha canlı olur."),
'A-1-5-3-4-2': ("Beyaz yapışıp keser – kötü", "Beyaz 1 ve 3 kötüdür. Siyah 4 ve 6 ile doğru sırayla oynar, sonra 8 ve 10 ile güçlüce iter. Beyaz 11 ile sakince geri dönmek zorundadır; siyah açıkça iyidir."),
'A-1-5-3-4-3': ("İki taşı sarmak – eski yol", "Eskiden beyaz 1 ve 3 ile iki taşı sarıp almak oynanırdı. Ama siyah 12 ile köşeyi alınca beyazın iki taraftaki şekli de kötüdür; savaş çok zordur."),
'A-1-5-3-4-4': ("Siyah bu taraftan iter – şüpheli", "Siyah 1 biraz şüphelidir. Beyaz 4 ile kesip atari verir, 8 ile hane yaparak şeklini düzeltir; siyah önceki iki şekildeki kadar rahat değildir."),
'A-1-5-3-4-5': ("Yanlış sıra – ko", "Siyah 1 ve 3 yanlış sıradır; beyaz 4 ile karşı atari akıllıcadır. Beyaz 10 ile sertçe uzanır ve ko ile karşılık verir; siyah zorlanır."),
'A-1-5-3-4-6': ("Beyaz keima ile çıkar – plansız", "Beyaz 1 plansızdır. Siyah 2 ve 4 ile ayırıp savaşır, sonra 10 ile köşeyi kapatan önemli noktayı alır; beyaz zor bir savaşa girer."),
'A-1-5-3-5-1': ("Kosumi-tsuke ve yapışma", "Siyah 1 ve 3 ile kosumi-tsuke yapıp yapışmak da bir yoldur; beyaz 4'ten sonra doğal olarak köşeyi işgal eder. Siyah 11 ile iyi bir taş fedası yapar; iki taraf da kabul edebilir."),
'A-1-5-3-5-2': ("Merdiven beyazın lehine – büyük savaş", "Merdiven beyazın lehineyse beyaz 1 ile 3-3'e zıplamak da olur ve iki taraf da geri adım atmaz. Siyah 6 en güçlü cevaptır, beyaz 7 ve 9 iyi sıradır. Siyah 30'a kadar çözümü zor, karışık bir savaş olur."),
'A-1-5-3-6-1': ("Siyah büyük keima", "Siyah 1 biraz meydan okumadır; beyaz 2 keima ile keserek karşılık verir. Siyah 9 ve 11 güçlüdür, 13 ile sakince taş feda eder. Siyah merkezi, beyaz alanı alır; beyaz biraz daha iyi."),
'A-1-5-3-6-2': ("Siyah hane – kötü", "Siyah 1 kötüdür. Beyaz 2 ve 4 ile düzgün sırayla oynar, sonra 8'den itibaren atarilerle siyahı sıkıştırır; siyah açıkça kötüdür."),
'A-1-5-3-6-3': ("Siyah kosumi – biraz yavaş", "Siyah 1 biraz yavaştır. Siyah 3 ve 5 ile kurtulsa da köşeyi tamamen beyaza kaptırır; memnun olamaz."),
'A-1-5-3-6-4': ("Beyaz yapışıp çıkar – tuzağa düşer", "Beyaz 1 tuzağa düşer. Siyah 2 ve 4 ile doğal şekilde itip keser, 10 ile saldırarak savunur, 22 ile verimli tamamlar; beyaz zor bir savaşa girer."),
'A-1-5-3-6-5': ("Siyah yapışır – biraz pasif", "Siyah 1 biraz pasiftir. Beyaz 2 ve 4 ile rahatça başını çıkarır; sonuç eşit."),
'A-1-5-3-7-1': ("Siyah fil adımı", "Siyah 1 fil adımı ilginç bir hamledir. Beyaz 2 ve 4 ile yapışıp kesmek bir yoldur; sonuç eşit. Sonra beyazın tenuki yapması iyidir; ileride siyah A'da alır, beyaz B'de zıplar."),
'A-1-5-3-7-2': ("Beyaz köşeyi işgal eder", "Beyaz 1 ile köşeyi işgal etmek sadedir. İşaretli siyah taş A-1-5-3-4-1'deki A noktasından biraz daha aktiftir."),
'A-1-5-3-7-3': ("Beyaz 2. sıradan keima", "Beyaz 1 ile 2. sıradan keima da olur; siyah 2 ve 4 ile yapışarak iyi şekil kurar. Beyaz 9'dan sonra köşede yaşar, siyah 12 ile dışarıda savaşır; iki taraf da savaşabilir."),
'A-1-5-3-7-4': ("Beyaz araya girer – tuzağa düşer", "Beyaz 1 fil adımının ortasına girer ve tuzağa düşer; siyah 2 ve 4 ile itip keser. Beyaz 9 ile tam zamanında yapışır ve 19'da pincer imkânı doğar. İki taraf da yaşar ama siyah daha memnundur."),
'A-1-5-4-1-1': ("Yüksek çift kakari", "Beyaz 1 ile yüksek çift kakari de bir yoldur; siyah 2 ile bu taraftan bastırmak yaygındır. Beyaz 3 ile hemen köşeyi işgal etmek iyidir; sonuç eşit."),
'A-1-5-4-1-2': ("Beyaz hane yaparsa", "Beyaz 1 ile hane yaparsa siyah 2 ile çapraz kesmek iyidir; beyaz 3 ve 5 en güçlü cevaptır. Siyah 8'den sonra sakince taş alır, sonra duruma göre A'da uzanır ya da B'de kosumi yapar. Beyazın merkezi incedir, siyah memnundur."),
'A-1-5-4-1-3': ("Siyah döner", "Siyah 1 ile dönmek de olur. Beyaz 2 ve 6 ile A'daki siyah taşı kesse de siyah 7 ve 9 ile iki iyi keima yapar; savaşta siyah daha rahattır."),
'A-1-5-4-1-4': ("Beyaz aşağı iter", "Beyaz 1 ile aşağı iterse siyah 2'den sonra taş feda ederek sade ve avantajlı oynar."),
'A-1-5-4-1-5': ("Beyaz köşede yaşar – olmaz", "Beyaz 1'den sonra köşede yaşamak doğru değildir; işaretli beyaz taş ağır hasar görür."),
'A-1-5-4-1-6': ("Siyah uzanır – kötü", "Siyah 1 kötüdür. Beyaz 2 ile sürünüp bağlanınca siyahın şekli bozulur; işaretli beyaz taş ileride de tehlike olarak kalır."),
'A-1-5-4-1-7': ("Beyaz önce hane – şüpheli", "Beyaz 1 ile önce hane biraz şüphelidir. Beyaz 3 ile uzanmak bir yoldur, sonra 5 ile yapışıp tempo arar. Siyah 6 ve 8 ile doğal şekilde karşılık verir; siyah biraz daha rahattır."),
'A-1-5-4-1-8': ("Beyaz yapışırsa", "Beyaz 1 ile yapışırsa siyah 2 ile akıllıca keser; takasta siyah biraz öndedir."),
'A-1-5-4-1-9': ("Siyah da hane yapar – biraz yavaş", "Siyah 1 biraz yavaştır. Beyaz 4 ile verimli şekilde keseri kapatır, sonra 8 ve 10 ile itip keserek savaşır. Siyah 13 ve 15 ile sıkı oynar; beyaz duruma göre A ya da B'den çıkar ve iki yol da karışık bir savaştır."),
'A-1-5-4-1-10': ("Beyaz 3-3 – kötü", "Beyaz 1 kötüdür. Beyaz 5 ile tamamlamak zorundadır, yoksa siyahın A'da yapışması çok serttir."),
'A-1-5-4-1-11': ("Siyah hemen yapışır", "Siyah 1 ile hemen yapışmak da olur; beyaz 2 ve 4 ile zorlamamalıdır. Siyah 3 ve 5 ile basitçe cevap verir, beyaz 6 ile bağlanınca 7 ile tamamlar; siyahın temposu rahattır."),
'A-1-5-4-1-12': ("Beyaz dıştan hane – ko", "Beyaz 1 dıştan hane yaparsa siyah 2 ile vurup keser ve karışık bir nefes yarışı başlar. Beyaz 5 ile direnir; yarış ko ile biter. Beyazın tenuki yapıp ko tehdidi araması iyidir; durum çok karışıktır."),
'A-1-5-4-1-13': ("Beyaz hemen koyu alır – yanlış", "Beyaz 1 ile hemen koyu almak yanlıştır. Siyah 2 ve 4 keskindir; siyah 10 ile geri alınca beyaz zor durumda kalır."),
'A-1-5-4-1-14': ("Siyah kapatır – kötü", "Siyah 1 kötüdür. Beyaz 2 ile sürünüp bağlanır ve A-1-5-4-1-6'daki şekle döner."),
'A-1-5-4-2-1': ("Bu taraftan bastırmak", "Siyah 1 ile bu taraftan da bastırabilir. Merdiven beyazın lehineyse beyaz 4 ile hemen 3-3'ü işgal eder; sonuç eşit."),
'A-1-5-4-2-2': ("Merdiven beyazın aleyhine", "Merdiven beyazın aleyhineyse beyaz 1 ile önce bastırmak zorundadır. Beyaz 7 ile sürünüp bağlanınca siyahın hemen tenuki yapması iyidir."),
'A-1-5-4-2-3': ("Beyaz kaplan ağzı", "Beyaz 1 ile kaplan ağzı yaparsa siyah 2 ile vurmak doğru şekildir. Beyaz 3 ile köşeyi işgal etmek artık biraz geç kalır; siyah 4 keima iyidir, beyazın şekli incedir."),
'A-1-5-4-2-4': ("Siyah yapışır – biraz kötü", "Siyah 1 biraz kötüdür. Beyaz 2 ile güçlüce köşeyi işgal eder. Siyah 3 ile iyi keser ama beyaz 4 ile sakince sürünür, 6 ile hane yapıp rahatlar; beyaz biraz iyi."),
'A-1-5-4-2-5': ("Beyaz aşağı uzanır", "Beyaz 1 ile aşağı uzanırsa siyah 2 ile güçlüce kapatır. Beyaz 5 uzanınca siyah 6 ile hane yapar ve takas olur; sonuç eşit."),
'A-1-5-4-2-6': ("Siyah aşağı kapatır", "Siyah 1 ile aşağı kapatmak da bir yoldur. Siyah 3 kaplan ağzı ve beyaz 4 uzanma iki iyi noktadır; iki taraf da kabul edebilir."),
'A-1-5-4-2-7': ("Siyah geri çekilir", "Siyah 1 ile geri çekilirse beyaz 2 ile yine köşeyi işgal eder; siyah 3 ve 5 en güçlü cevaptır. Beyaz 12 siyahı çok rahatsız eder, 14 ile iyi bir keima yapar; savaşta beyaz biraz öndedir."),
'A-1-5-4-2-8': ("Siyah aşağı hane – aşırı", "Siyah 1 fazladır. Beyaz 4 ile iyi bir kaplan ağzı yapar. Siyah 9 mecburdur, beyaz 12 ile aktifçe yapışır; siyah zor savaşır."),
'A-1-5-4-2-9': ("Siyah zıplar – olmaz", "Siyah 1 doğru değildir. Beyaz 2'den sonra tek hamlede taş feda eder; siyah çok kötü durumdadır."),
'A-1-5-4-2-10': ("Beyaz döner – kötü", "Beyaz 1 kötüdür. Siyah 2'den sonrası zorunludur; siyah 14 ile hane yapıp merkeze rahatça çıkar. İleride beyazın A'da yapışması iyi bir hamledir; sonuç eşit."),
'A-1-5-4-2-11': ("Siyah keser – biraz yumuşak", "Siyah 1 biraz yumuşaktır. Beyazın 2 ile sürünüp bağlanması yeterlidir."),
'A-1-5-4-2-12': ("Beyaz hane ile keser – aşırı", "Beyaz 1 fazladır. Siyah 4 ve 6 ile çok güçlü hane yapar. Beyaz 9 ile sıkıca yapışır, siyah 10 ve 12 ile doğru karşılık verir. Köşedeki yarışı siyah kazanır; beyaz 23 ile taş feda etmek zorunda kalır ve siyah açıkça iyidir."),
'A-1-5-4-2-13': ("Atari ve kapatma – eksik", "Siyah 1 ve 3 iyi değildir. Merdiven beyazın lehineyse beyaz 4 ile güçlüce döner, sonra 12 ile keskin şekilde işgal eder; siyah zor bir seçimle karşı karşıya kalır."),
'A-1-5-4-2-14': ("Siyah hane", "Siyah 1 ile hane bir yoldur, sonra 5 önemli noktadır. Beyaz 8 ile hane yapınca siyah 9 ile keskin bir pincer yapar; savaş dengeli."),
'A-1-5-4-2-15': ("Siyah sakince köşeyi tamamlar", "Siyah 1 ve 3 ile sakince köşeyi tamamlamak da olur; beyaz 4'ten sonra iki taraf da başını çıkarır. İki taraf da savaşabilir."),
'A-1-5-4-2-16': ("Siyah aşağı hane – ko", "Siyah 1 fazladır. Beyaz 2 ile işgal eder, siyah 9 ile atari verene kadar ko olur. Beyaz 10 ile ko tehdidi arar, siyah 11 ile karşılık verir, beyaz 12 sağlamdır. Sonunda uzlaşırlar; savaşta beyaz biraz öndedir."),
'A-1-5-4-2-17': ("Beyaz üstten atari – biraz kötü", "Beyaz 1 biraz kötüdür. Siyah 2 ile kesip atari vermek zorunludur; takasta beyaz önceki şekildeki kadar iyi değildir."),
'A-1-5-4-2-18': ("Merdiven beyazın aleyhine", "Merdiven beyazın aleyhineyse siyah 1 ile hane yapabilir; beyaz çöker."),
'A-1-5-4-2-19': ("Merdiven aleyhine – taş feda", "Merdiven beyazın aleyhineyse beyaz 1 ile kosumi yapıp taş feda etmek zorundadır; siyah biraz daha iyi."),
'A-1-5-4-2-20': ("Siyah alan alır – biraz yumuşak", "Siyah 1'den sonra alan almak biraz yumuşaktır; sonuç eşit."),
'A-1-5-5-1-1': ("İki boşluklu karşı pincer", "Beyaz 1 ile iki boşluklu karşı pincer de oynanır; siyah 2 ile sağlam bir keima yapar. Beyaz merkeze rahatça çıkar, siyah iki tarafı da alır ve memnundur."),
'A-1-5-5-1-2': ("Beyaz köşeye yapışır – biraz kötü", "Beyaz 1 biraz kötüdür. Siyah 4 ile iyi bir şekilde aşağı uzanır; beyaz 9 ile bir kez daha tamamlamak zorunda kalır, taşları verimsizdir."),
'A-1-5-5-2-1': ("Siyah bastırır", "Siyah 1 ile bastırmak da bir yoldur. Beyaz 2 ve 4 ile tempoyla çıkar, 10 ile göz yapar ve esnek kalır; sonuç eşit."),
'A-1-5-5-2-2': ("Beyaz köşeye yapışır", "Beyaz 1 ile köşeye yapışmak da olur; siyah 6 ile sıkıca yapışır. Beyaz 7 ve 9, siyah 8 ve 10 ile önemli noktaları paylaşırlar; iki taraf da savaşabilir."),
'A-1-5-5-2-3': ("Beyaz köşeyi işgal eder", "Beyaz 1 ile köşeyi işgal etmek de bir yoldur; siyahın 2 ile kaplan ağzı yapması yeter. Siyah 4 ve beyaz 5 kendini tamamlar; iki şekil de sağlamdır."),
'A-1-5-5-2-4': ("Beyaz araya girer – pek iyi değil", "Merdiven beyazın lehine olsa bile beyaz 1 pek iyi değildir. Siyah 4 ile güçlüce köşeyi kapatır; beyaz 5 ile yapışıp yararlanmaya çalışır, siyah 6 ile uzanıp savaşır ve biraz öndedir."),
'A-1-5-5-2-5': ("Merdiven beyazın aleyhine", "Merdiven beyazın aleyhineyse siyah 1 ile sertçe uzanır; beyaz 2 ile itip taş feda etmek zorunda kalır. Beyaz 10'dan sonra köşeyi alsa da siyah 15 ile rahatça iter; beyaz açıkça kötüdür."),
'A-1-5-5-3-1': ("Siyah zıplar", "Siyah 1 ile zıplamak da bir yoldur; sonra 3 ve 5 ile sakince köşeyi korur. Sonuç eşit."),
'A-1-5-5-4-1': ("Merdiven lehine – siyah keima", "Merdiven siyahın lehineyse siyah 1 ile keima yapıp çıkabilir. Beyaz 2 ile yapışınca siyah 3 ile sıkıca hane yapar; beyaz 4 ve 6 ile sade oynar ve A-1-5-4-2-1'e döner."),
'A-1-5-5-4-2': ("Beyaz keser", "Beyazın 1 ile kesmesi için merdivenin beyazın lehine olması gerekir. Siyah 2, 4 ve 6 ile doğal olarak alan alır, beyaz 7 ile bir taşı merdivenle yakalar; sonuç eşit."),
'A-1-5-5-4-3': ("Merdiven siyahın aleyhine", "Merdiven siyahın aleyhineyse beyaz 1 ile hemen köşeyi işgal etmek güçlüdür. Siyah 4 mecburdur; beyazın köşesi dolgundur, siyah memnun değildir."),
'A-1-5-5-4-4': ("Siyah hane – beyaz keser", "Siyah 1 ile hane yaparsa beyaz 2 ile sertçe keser. Siyah 5 ve 7 mecburdur; beyazın köşedeki alanı çok büyüktür."),
'A-1-5-5-4-5': ("Merdiven siyahın lehine", "Merdiven siyahın lehineyse siyah 1 ile hane yapıp bağlanmak işe yarar; beyaz 4 ve 6 mecburdur. Beyazın köşesi öncekinden çok farklıdır; siyah açıkça iyidir."),
'A-1-5-5-4-6': ("Merdiven aleyhine – beyaz önce hane", "Merdiven beyazın aleyhineyse beyaz 1 ile önce hane yapmak zorundadır, sonra 5 ile keserek fedakârlık yapar; siyah biraz daha iyi."),
'A-1-5-5-5-1': ("Siyah kosumi-tsuke – biraz kötü", "Siyah 1 biraz kötüdür. Beyaz 4 ile büyük zıplama çok rahattır. Siyah 5 ile yapışıp tempo arar; takasta beyaz biraz öndedir."),
'A-1-5-6-1-1': ("Beyaz tenuki", "Beyaz tenuki yaparsa siyah genelde 1 ile kosumi-tsuke yapar. Beyaz yine tenuki yapabilir; siyah 3 kaplan ağzı büyüktür, ileride beyazın A'da işgal ve B'de hane imkânları kalır."),
'A-1-5-6-1-2': ("Beyaz uzanıp savaşır", "Sağ alt beyazı destekliyorsa beyaz 1 ile uzanıp savaşabilir."),
'A-1-5-6-1-3': ("Beyaz esnekçe döner", "Sol taraf değerliyse beyaz 1 ve 3 ile esnekçe dönmek de olur."),
'A-1-5-6-2-1': ("Siyah 3-3 kosumi", "Siyah 1 ile 3-3'e kosumi serttir; beyaz 2 keima ile çıkar ve Bir Boşluklu Zıplama josekisindeki bir şekle döner."),
'A-1-5-6-3-1': ("Siyah keima", "Siyah 1 ile keima yaparsa Keima josekisindeki bir şekle döner."),
}
