# Son, sade metinler (başlık, açıklama).
FINAL = {
'A-1-6': ("Başlangıç pozisyonu", "Yüksek iki boşluklu pincer de bir zamanlar popülerdi. Alçak iki boşluklu pincer gibi, yapay zekâya göre genelde alçak bir boşluklu ve üç boşluklu pincerden daha az iyidir. Beyazın seçenekleri: A'da 3-3 işgali, B'de zıplama, C ve D'de çift kakari, E'de iki boşluklu karşı pincer ya da tenuki."),
'A-1-6-1-1-1': ("3-3 işgali", "Beyaz 1 ile 3-3'ü işgal etmek sade ve iyidir. Siyah 8 ve 10 ile kalın olur ama temposu yavaştır."),
'A-1-6-1-1-2': ("Siyah tenuki – yanlış", "Siyahın tenuki yapması yanlıştır. Beyaz 1 ile hemen uzanıp çıkar; siyah zor savaşır."),
'A-1-6-1-1-3': ("Beyaz uzanır – fazla iyimser", "Beyaz 1 biraz fazla iyimserdir; siyah 2 ile dönüp sert karşılık verir. Köşedeki yarışı siyah bir nefesle kazanır ama beyaz 13 ile sente dönüp bir şey alır. Siyah biraz daha iyi."),
'A-1-6-1-1-4': ("Siyah bağlanır", "Siyah 1 ile bağlanıp sente alabilir ama şeklinde bir zayıflık kalır. İleride beyazın A'da zıplama ve B'de yaklaşma gibi rahatsız edici hamleleri var."),
'A-1-6-1-1-5': ("Beyaz zıplar – karışık savaş", "Beyaz 1 sonraki imkânlardan biridir; siyah 2 ile pincer en güçlü cevaptır, beyaz 3 ve 5 ile sertçe iter. Siyah 6 ile önce bastırmak incedir, beyaz 7 iyi bir hamledir. Siyah 12 ile sakince üç taşı alır, beyaz 13 ile döner; çözümü zor bir savaş olur."),
'A-1-6-1-1-6': ("Siyah aşağı uzanır", "Siyah 1 ile aşağı uzanıp savaşmak da olur; sonra 3 ile keskin şekilde işgal eder. Savaş dengeli."),
'A-1-6-1-1-7': ("Beyaz uzanır – şüpheli", "Beyaz 1 şüphelidir. Siyaha 8 ve 10 ile itip kesme imkânı doğar, sonra 14 ve 16 ile üst üste bastırır; beyaz çok pasif kalır."),
'A-1-6-1-1-8': ("Önce araya girip bağlanmak", "Siyah 1 ve 3 ile önce araya girip bağlanmak durumu değiştirir. Siyah ileride A'da bastırınca beyaz B'de uzanır; siyah A-1-6-1-1-5'tekinden çok daha kötüdür."),
'A-1-6-1-1-9': ("Siyah uzanır, sonra bastırır", "Siyah 1 ile uzanıp 3 ile bastırırsa beyaz 4 ile geri bağlanır; bu iyi bir hamledir ve siyah 5 mecburdur. Beyaz 6 ile hane yapınca merkezdeki üstünlük hemen beyaza geçer."),
'A-1-6-1-1-10': ("Beyaz önce pincer", "Beyaz 1 ile önce pincer yaparsa siyah 2 ile güçlü bir kaplan ağzı yapar, sonra 4 ile bastırıp beyazı zorlar. Beyaz 5 ile uzanırsa siyah 6 ve 8 yeter; beyaz tenuki yapıp kaybını sınırlamalıdır. Beyaz A'da uzanmakta ısrar ederse A-1-6-1-1-7'ye döner."),
'A-1-6-1-1-11': ("Beyaz kapatır", "Beyaz 1 ile kapatırsa siyah 2 ve 4 ile hane yapıp bağlanabilir, sonra 10 ve 12 ile sıkı oynar; beyazın oyunu biraz sıkıcı kalır."),
'A-1-6-1-1-12': ("Beyaz yaklaşır", "Beyaz 1 ile yaklaşmak da iyidir; siyah 2 ile genelde aşağı zıplar, beyaz sente kazanç sağlar."),
'A-1-6-2-1-1': ("Beyaz zıplar", "Beyaz 1 nispeten az oynanır. Sağ alt beyazsa beyaz 3 ile 3-3'ü işgal edebilir. Beyaz 9 ile önce zıplamak akıllıcadır, siyah 10 ve 12 sakindir; sonuç eşit."),
'A-1-6-2-1-2': ("Sağ alt siyahsa", "Sağ alt siyahsa beyaz 1, 3 ve 5 ile yaşamaya çalışmak iyidir. Siyah 6 ile akıllıca kosumi yapar, beyaz 7 ve 9 ile çok iyi savunur; siyah biraz daha iyi."),
'A-1-6-2-1-3': ("Beyaz büyük keima – eski joseki", "Beyaz 1 büyük keima eski bir josekidir; siyah 2 ile güçlü bir kosumi yapar. Beyaz 3 ile yaklaşmak biraz geç kalır, siyah 4 ile keskin şekilde yapışır; takasta siyah açıkça kazanır."),
'A-1-6-2-1-4': ("Beyaz sürünüp bağlanır – duyarsız", "Beyaz 1 duyarsızdır. Siyah 2 ve 4 ile beyazın şeklini çok iyi sıkıştırır; beyaz çok dar kalır."),
'A-1-6-2-1-5': ("Siyahın tuzağı", "Siyah 1 ve 3 tuzak hamleleridir; beyaz 4 ile köşeye kosumi yaparak çözer. Siyah 5 ve 7 ile ayırınca beyaz 8 ile iyi bir hamle yapar; dışarıdaki grubu idare etmek zor değildir."),
'A-1-6-3': ("Çift kakari", "Beyaz 1 çift kakari çok yaygındır ve siyahın birçok seçeneği var. Eskiden A ve B'de bastırmak çok oynanırdı, C'de keima ile baskı da görülürdü. D'de omuz vuruşu, E'de fil adımı, F'de kosumi-tsuke ve G'de büyük keima da olur."),
'A-1-6-3-1-1': ("Güçlü taraftan bastırmak", "Siyah 1 \"güçlü tarafı bastır, zayıfı değil\" kuralına uyar. Beyaz 2 ve 4 aşağı yukarı böyledir; sonuç iki taraf için de kabul edilebilir."),
'A-1-6-3-1-2': ("Beyaz bastırır", "Beyaz 1 ile bastırmak da olur; siyah 2 ile kaplan ağzı önemli noktadır. Beyaz 5 ile 3-3'ü işgal edince siyah 6 ve 8 ile ayırır. Siyah 10 ve 12 ile rahat sente hamleler yapar, sonra 16 ile hane yapıp canlı bir şekil kurar."),
'A-1-6-3-2-1': ("Bu taraftan bastırmak – biraz kötü", "Siyah 1 biraz kötüdür. Beyaz 2 ve 4 ile hane yapıp 3-3'ü işgal etmek sade ve iyidir."),
'A-1-6-3-2-2': ("Beyazın sonraki yapışması", "İleride beyaz 1 ile yapışmak iyi bir hamledir; siyah 2'den sonra en güçlü şekilde cevap verir. Beyaz 13 ve 15 ile basitçe yaşar ve memnundur."),
'A-1-6-3-2-3': ("Siyah sürünür – aşırı", "Siyah 1 fazladır; beyaz 2'den sonra rahatça yaşar. Siyah 7 ve 9 ile öldürmekte ısrar ederse beyaz 12 ve 14 ile güçlü oynar. Sonra ya A'da merdivenle iki taşı alır ya da B'de siyahı öldürür; siyah çöker."),
'A-1-6-3-2-4': ("Beyaz uzanır – eski joseki", "Beyaz 1 eski bir josekidir. Siyah 6 ile sade ve güçlü bir kaplan ağzı yapar, sonra 10 ve 12 ile bir taşı alır; bu çok büyüktür. Siyah biraz daha iyi."),
'A-1-6-3-2-5': ("Beyaz yapışır – biraz ağır", "Beyaz 1 biraz ağırdır. Beyaz 5 ile yapışıp çıkınca siyah 6 ve 8 ile saldırının önemli noktalarını alır; beyaz 9'dan sonra sakince takas yapar, siyah biraz daha iyi."),
'A-1-6-3-2-6': ("Beyaz hemen 3-3 – biraz kötü", "Beyaz 1 ile hemen 3-3'ü işgal etmek biraz kötüdür; siyah 2 ile kapatınca şekli kalın olur."),
'A-1-6-3-2-7': ("Beyaz bağlanır", "Beyaz 1 önceki şekilden kötüdür; beyaz 3 ve 5 ile doğrudan hane yapıp bağlanmak daha iyidir. Beyaz 3 yerine A'da hane yapıp siyahın B'de geri çekilmesiyle takas yapmak kârlı değildir."),
'A-1-6-3-2-8': ("Siyah kaplan ağzı – kötü", "Siyah 1 kötüdür. Beyaz 2 ile sürünüp bağlanınca siyah A'da tamamlasa mı tamamlamasa mı ikilemde kalır; tamamlarsa taşları verimsiz olur."),
'A-1-6-3-2-9': ("Siyah tenuki yaparsa", "Siyah tenuki yaparsa beyaz 1 ve 3 ile geçip bağlanır ve siyahın bütün grubu köksüz kalır. Beyaz 5 ile dürtmek de iyidir; siyah 6'dan sonrası böyledir ama şeklinde yine zayıflık kalır."),
'A-1-6-3-2-10': ("Siyah ısrarla ayırır", "Siyah 1 ve 3 ile ayırmakta ısrar ederse beyaz 6 ve 8 ile çok güçlü oynar. Siyah 11 ile beş taşı alsa da ileride iki tarafta da nefes darlığı çeker; kazandığından çok kaybeder."),
'A-1-6-3-3-1': ("Keima ile baskı", "Siyah 1 ile keima baskısı da bir yoldur; beyaz 2 ve 4 ile köşeyi almak iyidir. Sonuç eşit."),
'A-1-6-3-3-2': ("Beyaz 2. sırada hane – biraz kötü", "Beyaz 1 biraz kötüdür. Siyah 2'den sonra sol tarafa dönerek memnun olur."),
'A-1-6-3-3-3': ("Beyaz yapışıp keser – şüpheli", "Beyaz 1 ve 3 şüphelidir. Beyaz 7 ile karşı atari mecburdur; siyahın şekli çok dolgun olur."),
'A-1-6-3-3-4': ("Beyaz uzanırsa", "Beyaz 1 ile uzanırsa siyah 2 ve 4 ile iyi sırayla oynar; takasta siyah açıkça kazanır."),
'A-1-6-3-4-1': ("Siyah omuz vuruşu", "Siyah 1 omuz vuruşu aktiftir; beyaz 2 ile itip karşılık verir. Beyaz 6 kosumi doğru şekildir, siyah 7 ile sakince yapışır; takas iki taraf için de kabul edilebilir."),
'A-1-6-3-4-2': ("Sağ alt siyahı destekliyorsa", "Sağ alt siyahı destekliyorsa önceki şekildeki siyah 7 yerine 1 ile başını çıkarmak da olur. Beyaz 2, 4 ve 6 en güçlü cevaptır, sonra 10 ve 12 ile sakince taş feda eder; beyaz biraz daha iyi."),
'A-1-6-3-4-3': ("Sağ alt siyahı desteklemiyorsa", "Sağ alt siyahı desteklemiyorsa önceki şekildeki beyaz 10 yerine 1 ile geri çekilmek olur, sonra beyaz 5 ile sertçe keser. Beyaz 13 ile hane yapınca siyah iki tarafı birden kurtaramaz."),
'A-1-6-3-4-4': ("Beyaz yapışıp keser – biraz kötü", "Beyaz 1 ve 3 biraz kötüdür. Siyah 4 ve 6 ile önce dıştan, sonra içeriden atari verir; bu doğru sıradır. Beyaz A-1-6-3-4-1'deki kadar iyi değildir."),
'A-1-6-3-4-5': ("Beyaz 3-3 – biraz yumuşak", "Beyaz 1 biraz yumuşaktır; işaretli siyah taş A-1-6-3-3-1'deki A noktasından biraz daha iyi yerdedir."),
'A-1-6-3-5-1': ("Siyah fil adımı", "Siyah 1 fil adımı ilginçtir; beyaz 2 ile sağlam bir büyük keima yapar, sonra siyahın tenuki yapması iyidir. Beyaz 4 ile keima yapınca siyah 5 ve 7 ile iki kez yapışarak sadece şeklini düzeltir; sonuç eşit."),
'A-1-6-3-5-2': ("Beyaz köşeyi işgal eder", "Beyaz 1 ile köşeyi işgal etmek sadedir. İşaretli siyah taşın değeri A-1-6-3-3-1 ile A-1-6-3-4-5'teki taşlar arasındadır."),
'A-1-6-3-5-3': ("Beyaz yapışıp keser", "Beyaz 1 ve 3 ile yapışıp kesmek de olur; siyah 4 ve 6 doğru hamlelerdir. İleride siyah A'da alır, beyaz B'de zıplar; iki taraf da savaşabilir."),
'A-1-6-3-5-4': ("Beyaz araya girer – tuzağa düşer", "Beyaz 1 fil adımının ortasına girer ve tuzağa düşer; siyah 2 ve 4 ile doğal olarak itip keser ve çözümü zor bir savaş olur. Siyah 26 ve 28 ile cesurca taş feda edip merkez alır; çoğu durumda siyah daha iyidir."),
'A-1-6-3-6-1': ("Merdiven lehine – kosumi-tsuke", "Merdiven siyahın lehineyse siyah 1 ile kosumi-tsuke de bir yoldur. Siyah 8 ile sertçe işgal eder, beyaz 14 ve 16 ile itip keser; siyah 17'den sonra 2. sırada zorla yaşar. Beyaz biraz daha iyi."),
'A-1-6-3-6-2': ("Merdiven aleyhine", "Merdiven siyahın aleyhineyse siyah 1 ile kapatmak zorundadır; beyaz 2 ve 4 doğru sıradır. Siyah 7 ile 2. sırada zıplamak mecburdur; siyah 25 ile dönene kadar savaşta beyaz biraz öndedir."),
'A-1-6-3-6-3': ("Beyaz sürünür – yetersiz", "Beyaz 1 yeterince iyi değildir. Siyah 4 ve 6 ile iyi bir taş fedası yapar, sonra 12 ile güzel bir açılma yapar; beyaz önceki iki şekildeki kadar rahat değildir."),
'A-1-6-3-7-1': ("Siyah büyük keima – tuzak", "Siyah 1 biraz tuzak kokan bir hamledir; beyaz 2 keima ile sakince çıkar. Siyah 3 ve 5 ile en iyi şekilde toparlanır; beyaz 6'dan sonra basitçe köşeyi alıp memnun olur."),
'A-1-6-3-7-2': ("Beyaz karşı saldırır", "Beyaz 1 ve 3 ile doğrudan karşılık verirse siyah 8 ve 10 ile önce köşede yaşar, sonra 12 ile zıplayıp güçlüce kapatır; beyaz biraz sıkışır."),
'A-1-6-3-7-3': ("Beyaz yapışıp çıkar – biraz kötü", "Beyaz 1 biraz kötüdür; siyah 2 ile doğal olarak yapışıp çıkar. Beyaz 3'ten sonrası böyledir; iki taraf da savaşabilir."),
'A-1-6-4-1-1': ("Yüksek çift kakari", "Beyaz 1 ile yüksek çift kakari de olur; siyah 2 ile bastırmak normaldir. Beyaz 5 ve 7 ile köşeyi işgal eder, siyah 8 ile kalınca döner; iki taraf da kabul edebilir."),
'A-1-6-4-1-2': ("Beyaz 3-3 – kötü", "Beyaz 1 kötüdür. Beyaz 5 ile tamamlamak zorundadır, yoksa siyahın A'da yapışma imkânı var."),
'A-1-6-4-1-3': ("Siyah hemen yapışır", "Siyah 1 ile hemen yapışmak da çok keskindir; devamı alçak iki boşluklu pincerdeki şekille hemen hemen aynıdır."),
'A-1-6-4-1-4': ("Beyaz hemen 3-3 – yanlış", "Beyaz 1 yanlıştır. Siyah 2 ile kapatınca şekli kalın olur, işaretli beyaz taş kötü yerde kalır."),
'A-1-6-4-1-5': ("Beyaz hane yaparsa", "Beyaz 1 ile hane yaparsa siyah 2 keima burada iyi bir hamledir; siyah biraz daha iyi."),
'A-1-6-4-2-1': ("Bu taraftan yapışmak", "Siyah 1 ile bu taraftan da yapışabilir. Merdiven beyazın lehineyse beyaz 2 ve 4 ile hane yapıp köşeyi işgal etmek sadedir. Siyah 9 ve 11 ile esnek bir ko kurar, beyaz 18 ile sakince geri çekilir; iki taraf da kabul edebilir."),
'A-1-6-4-2-2': ("Siyah döner – biraz yavaş", "Siyah 1 biraz yavaştır. Beyaz 2 ile bağlanınca kalın olur; siyah 3 ve 5 ile hane yapıp bağlanmak zorundadır. İleride beyazın A ve B'de rahatsız etme imkânları var."),
'A-1-6-4-2-3': ("Merdiven aleyhine – beyaz yapışmaya devam eder", "Merdiven beyazın aleyhineyse beyaz 1 ile yapışmaya devam edebilir. Siyah 4 keima ile merkezdeki önemli noktayı alır, beyaz 5'ten sonra alt tarafta yaşar, siyah 10 ile yaklaşıp saldırır; iki taraf da savaşabilir."),
'A-1-6-4-2-4': ("Siyah yapışır", "Siyah 1 ile yapışmak da olur; beyaz 2 ile 3-3'ü işgal etmek bir yoldur. Siyah 3 ile önce kesmek doğru sıradır; böylece siyah 5 kapatması sente olur. Beyaz 6 ile sakince taşı sarar; iki taraf da kabul edebilir."),
'A-1-6-4-2-5': ("Siyah uzanır", "Siyah 1 ile uzanmak da bir yoldur; beyaz 2 ile önce uzanmak akıllıcadır. Siyah 5 ve 7 ile itip kesince beyaz 8 ile sakince taşı sarar; iki taraf da savaşabilir."),
'A-1-6-4-2-6': ("Beyaz sürünüp bağlanır", "Beyaz 1 ile sürünüp bağlanmak da olur; siyah 2 ve beyaz 3 başlarını çıkarır. Siyah tenuki ya da A'da tamamlamayı düşünebilir; iki taraf da oynayabilir."),
'A-1-6-4-2-7': ("Siyah önce kapatır – hata", "Siyah 1 ile önce kapatmak hatadır. Siyah 3 ile kesince beyaz 4 ile dıştan atari verip taş feda eder; siyahın şekli tekrarlı olur."),
'A-1-6-4-2-8': ("Beyaz iki taşın başına hane", "Beyaz 1 ile iki taşın başına hane de bir yoldur; iki taraf da birer taş alır ve kabul edebilir."),
'A-1-6-4-2-9': ("Siyah geri çekilir", "Siyah 1 ile geri çekilmek de düşünülebilir, sonra 5 ile güçlü bir hane yapar; beyaz 18'e kadar iki taraf da geri adım atamaz. Beyaz 20 ile iyi bir yapışma yapar ve birçok imkân yaratır; iki taraf da savaşabilir."),
'A-1-6-4-2-10': ("Siyah keser – biraz aşırı", "Siyah 1 biraz fazladır. Beyaz 2 ve 4 ile sakin oynar, sonra 8 ile tam yerinde bir fil adımı yapar. İki taraf başını çıkarmaya çalışır; savaşta beyaz daha rahattır."),
'A-1-6-4-2-11': ("Siyah keser – biraz yumuşak", "Siyah 1 biraz yumuşaktır. Beyazın 2 ile sürünüp bağlanması yeterlidir."),
'A-1-6-4-2-12': ("Beyaz hane ile keser – aşırı", "Beyaz 1 fazladır. Siyah 4 ile güçlüce bastırır ve A-1-6-3-5-4'e döner."),
'A-1-6-4-2-13': ("Atari ve kapatma – biraz yumuşak", "Siyah 1 ve 3 biraz yumuşaktır. Beyaz 4 ile kosumi yapıp taş feda etmek iyidir; sonuç eşit."),
'A-1-6-4-2-14': ("Beyaz döner – zorlama", "Merdiven beyazın lehine olsa bile beyaz 1 zorlamadır. Beyaz 9 ve 11 en güçlü cevaptır, siyah 12 ile geri adım atmaz. Beyaz 19 ve 21 ile iyi ko hamleleri yapar ama takastan sonra siyah 28 ile önemli noktaya zıplar; savaşta siyah daha rahattır."),
'A-1-6-4-2-15': ("Merdiven beyazın aleyhine", "Merdiven beyazın aleyhineyse siyah 1 ile hane yapabilir; beyaz devam edemez."),
'A-1-6-4-2-16': ("Siyah sürünür", "Siyah 1'den sonra art arda sürünmek sade bir yoldur, sonra 11 ile iyi bir keima yapar. Genelde sağ altı elinde tutan taraf daha iyidir."),
'A-1-6-5-1-1': ("İki boşluklu karşı pincer", "Beyaz 1 ile iki boşluklu karşı pincer bir zamanlar çok popülerdi; siyah 2 ile bastırmak bir yoldur. Beyaz 3 ile sadece 3-3'ü işgal eder, siyah 6 ve beyaz 7 kendini tamamlar; sonuç eşit."),
'A-1-6-5-1-2': ("Siyah kapatır – biraz kötü", "Siyah 1 biraz kötüdür. Siyah 5 ile yine kosumi yapıp tamamlamak zorundadır; beyaz 6 ile iki boşluklu açılarak hızlanır."),
'A-1-6-5-1-3': ("Beyaz hane", "Beyaz 1 ile hane de bir yoldur, sonra 7 ile sertçe keser; siyah 8 ve 10 ile geri adım atmaz. Beyaz 11 ile köşeye yapışınca siyah 12 ile sıkıca yapışır; takas iki taraf için de kabul edilebilir."),
'A-1-6-5-1-4': ("Merdiven lehine – beyaz araya girer", "Merdiven beyazın lehineyse beyaz 1 ile araya girmek güçlüdür. Siyah 4 ile sertçe kapatır, beyaz 5 ile keser ve karışık bir savaş başlar. Siyah 10 ve 12 ile sertçe kapatır, beyaz 13 ve 15 ile keskin oynar; iki taraf da yaşar ve kabul edebilir."),
'A-1-6-5-1-5': ("Siyah bağlanır – biraz yumuşak", "Siyah 1 biraz yumuşaktır. Beyaz 2 ve 4 ile güçlü şekilde taş feda eder, sonra 6 ve 8 ile çok rahat eder; siyahın şekli ağırdır."),
'A-1-6-5-1-6': ("Siyah sadece bağlanır", "Siyah 1 ile bağlanmak sadedir; beyaz 4'ten sonra iki taraf istediğini alır. Siyah merkezi, beyaz alanı alır."),
'A-1-6-5-1-7': ("Merdiven beyazın aleyhine", "Merdiven beyazın aleyhineyse siyah 1 ve 3 işe yarar; beyaz iki tarafı birden kurtaramaz."),
'A-1-6-5-2-1': ("Merdiven lehine – siyah keima", "Merdiven siyahın lehineyse siyah 1 ile keima da bir yoldur; beyaz 2'den sonra sade oynar. Sonuç eşit."),
'A-1-6-5-2-2': ("Merdiven siyahın aleyhine", "Merdiven siyahın aleyhineyse beyaz 1 ile köşeyi işgal etmek güçlüdür. Siyah 4 ile uzanmak zorundadır; beyazın şekli çok dolgundur, siyah memnun değildir."),
'A-1-6-5-2-3': ("Siyah ısrarla hane yapar", "Siyah 1 ile ısrarla hane yaparsa beyaz 2 ile keser ve siyah zor durumda kalır; siyah açıkça kayıpta."),
'A-1-6-5-2-4': ("Merdiven siyahın lehine", "Merdiven siyahın lehineyse siyah 1 ve 3 ile hane yapıp bağlanmak işe yarar. Beyaz 4 ve 6 mecburdur; siyah 9 ile iki taşı alıp çok kazanır."),
'A-1-6-5-3-1': ("Siyah keima", "Siyah 1 ile keima da düşünülebilir; beyaz 2 ile köşeye keima yapmak sadedir. Siyah 7 keima ile baskıya devam eder, beyaz 8 ile yerinde yaşar; sonuç eşit."),
'A-1-6-5-3-2': ("Beyaz köşeye yapışır – biraz kötü", "Beyaz 1 biraz kötüdür. Siyah 4 ile iyi bir kaplan ağzı yapar, sonra 6 ve 8 ile uzanıp hane yaparak rahat bir şekil kurar; beyaz memnun değildir."),
'A-1-6-5-4-1': ("Siyah kosumi-tsuke – biraz kötü", "Siyah 1 biraz kötüdür. Beyaz 4 ile itip kesmek basit ama güçlüdür; siyah 5 ile aşağı uzanıp sabretmelidir. Beyaz biraz daha iyi."),
'A-1-6-5-4-2': ("Siyah bağlanırsa", "Siyah 1 ile bağlanırsa beyaz 2 ve 4 ile sert oynar. Sonra 10 ve 14 ile çok iyi taş feda eder; siyahın taşları ağır kalır."),
'A-1-6-5-4-3': ("Beyaz köşeye yapışır – kötü", "Beyaz 1 kötüdür. Siyah 2 ve 4 ile geniş bir şekil kurar; beyaz memnun değildir."),
'A-1-6-6-1-1': ("Beyaz tenuki – genelde kötü", "Beyazın tenuki yapması genelde iyi değildir; siyah 1 ile sertçe kosumi-tsuke yapar. Beyaz 4 ve 6 ile esnekçe dönmelidir; savaşta siyah daha rahattır."),
}
