# Son, sade metinler (başlık, açıklama).
FINAL = {
'A-1-9': ("Başlangıç pozisyonu", "Siyah 1 kosumi-tsuke eskiden kaba bir hamle sayılırdı ve genelde beyazın uzandıktan sonra üç boşluklu açılamayacağı durumlarda oynanırdı. Yapay zekâ bunu doğrudan oynamayı da iyi bulur; son zamanlarda sık görülür. Beyaz neredeyse her zaman A'da uzanır. B'de aşağı uzanmak eski Çin oyunlarında görülür; C'de hane ve D'de 3-3 işgali duruma göre oynanır."),
'A-1-9-1-1-1': ("Beyaz uzanır", "Beyaz 1 ile genelde uzanır. Siyah 2 ile zıplayıp merkeze önem verir, beyaz 3 ile üç boşluklu açılıp iyi bir şekil kurar. İki taraf da oynayabilir."),
'A-1-9-1-1-2': ("Siyah 2. sıradan işgal eder", "Siyah 1 bu şekle karşı sık kullanılan bir işgaldir; beyaz 2 ile yapışmak normaldir. Beyaz 4 ile tam zamanında köşeyi işgal eder, siyah 5 ile sakince kapatır. Sağ alt beyazsa beyaz 6 ile kalınca kapatmak sadedir; köşede biraz imkân kalır, iki taraf da kabul edebilir."),
'A-1-9-1-1-3': ("Sağ alt siyahsa", "Sağ alt siyahsa beyaz 1 ile hane iyi bir hamledir, sonra 3 ile uzanmak doğru şekildir. Siyah 4 iki tarafın göz alanı için önemlidir, sonra 6 ile sürünüp çıkar ve takas olur. Beyaz rahatça savaşabilir."),
'A-1-9-1-1-4': ("Siyah aşağı uzanır – kötü", "Siyahın aşağı uzanması kötüdür. Beyaz 2 ile kapatınca siyah 3 ile köşeyi tamamlamak zorunda kalır; beyaz 4 ile dönüp taşı almak çok rahattır."),
'A-1-9-1-1-5': ("Beyaz hemen kapatır – biraz kötü", "Beyaz 1 biraz kötüdür; siyah 2'den sonra geçip bağlanır. Beyaz ileride A'da 3-3'ü işgal ederse siyah B'de zıplayıp öldürür; siyahın köşesi A-1-9-1-1-2'dekinden biraz daha sağlamdır."),
'A-1-9-1-1-6': ("Beyaz kosumi", "Beyaz 1 kosumi sade ve oynanabilir bir hamledir; siyah 2 ile hane yapıp bağlanarak alan kazanır."),
'A-1-9-1-1-7': ("Beyaz kosumi-tsuke ile ayırır", "Beyaz 1 ile ayırmak serttir; siyah 2 ile zıplayıp karşı saldırmak zorundadır. Beyaz 5 ile doğru bir pincer yapar, siyah 6 ve 8 ile doğal olarak iter ve takas olur. İleride beyazın A'da hanesi güçlüdür; iki taraf da savaşabilir."),
'A-1-9-1-1-8': ("Siyah bağlanır – katı", "Siyah 1 katıdır. Beyaz 2 ve 6 ile rahatça başını çıkarır; savaşta siyah biraz zorlanır."),
'A-1-9-1-1-9': ("Beyaz üstten kapatır – fazla güçlü", "Beyaz 1 fazla güç kullanır. Siyah 2 ile sente atari verip kazanç sağlar, 4 ile hafifçe keima yapar; beyazın iyi bir devamı kalmaz."),
'A-1-9-1-1-10': ("Beyaz atarilerle sıkıştırır", "Beyaz 1 ve 3 ile sıkıştırmak hoş görünür ama beyazın kendi kesme noktaları çok, nefesi azdır. Siyah 12 ile yapışıp çıkınca beyaz zor durumda kalır."),
'A-1-9-1-1-11': ("Beyaz keser – kötü", "Beyaz 1 ile kesmek de kötüdür. Siyah 2 ve 4 ile taşı alıp çiçek şekli yapar; bu çok değerlidir. Beyazın taşları verimsizdir."),
'A-1-9-1-1-12': ("Beyaz doğrudan kapatır", "Beyaz 1 ile doğrudan kapatırsa siyah 2 ile aşağı uzanmak önemli noktadır. Beyaz 3 ile genelde araya girer, siyah 4'ten sonra hemen hareket eder ve beyaz zorlanır. Siyah sente biraz alan alır, beyazın merkezi de kalın değildir; siyah daha iyidir."),
'A-1-9-1-1-13': ("Beyaz aşağı uzanır", "Beyazın sağ tarafta desteği varsa beyaz 1 ile aşağı uzanmak da bir yoldur. Siyah 2 ile zıplar, beyaz 3 kosumi ile çıkıp savaşır; iki taraf da savaşabilir."),
'A-1-9-1-1-14': ("Beyaz yapışır", "Beyaz 1 ile yapışmak da bir yoldur; siyah 2 ile dıştan hane doğrudur. Beyaz 3 ile köşeyi işgal edip siyahın cevabını yoklar, siyah 4 ve 6 ile karşılık vermek iyidir; sonuç eşit."),
'A-1-9-1-1-15': ("Siyah aşağı kapatır – aşırı", "Siyah 1 fazladır; sonrası iki taraf için de zorunlu hamlelerdir. Beyaz 14 ile siyahın köşesini delip çok kazanır, siyah 15 ile tamamen tamamlamalıdır; takasta beyaz kazançlıdır."),
'A-1-9-1-1-16': ("Beyaz dürter – işe yaramaz", "Beyaz 1 işe yaramaz; siyah 2 ve 4 ile yine karşı saldırır. Beyaz 5 ve 7 ile itip kesmek zorundadır; siyah 18 ile bastırıp çıkana kadar savaşta siyah biraz daha rahattır."),
'A-1-9-1-1-17': ("Beyaz hemen keser – düşüncesiz", "Beyaz 1 düşüncesizdir. Siyah 2 ve 4 ile atari verip çıkınca işaretli üç beyaz taşı idare etmek zorlaşır."),
'A-1-9-1-1-18': ("Beyaz araya girer", "Beyaz 1 ile araya girerse siyah 2 ve 4 ile bağlanıp keser; bu keskindir. Beyaz 5 ve 7 mecburdur, siyah 8 ile bir taşı ağla yakalayıp çok kazanır. Beyaz 9 ile hane yapıp şeklini düzeltse de siyah daha değerli yerleri almıştır."),
'A-1-9-1-1-19': ("Siyah içeriden hane – şüpheli", "Siyah 1 şüphelidir. Beyazın 2 ile araya girip geçmesi yeterlidir; siyah 5 ile taşı alıp çiçek şekli yapar ama sıra beyaza geçer, temposu yavaştır."),
'A-1-9-1-1-20': ("Siyah işgal eder – kötü", "Siyah 1 kötüdür; beyaz 2 ile yapışınca şekli tamamlanır. Siyah 3 ve 5 ile hane yapıp bağlanmak alan getirir ama açılışta yavaştır; beyazın tenuki yapıp başka önemli yerleri alması iyidir."),
'A-1-9-1-1-21': ("Siyah tenuki yaparsa", "Siyah tenuki yaparsa beyaz 1 ile yaklaşmak harika bir noktadır. Sol üst destekliyorsa siyah 2 ile aktif bir karşı pincer yapar; beyaz 3 ile 3-3'ü işgal eder, siyah 4 ile sabırla bağlanır. Beyaz 7 kosumi doğru şekildir, siyah 8 keima ile tamamlar; iki taraf da oynayabilir."),
'A-1-9-1-1-22': ("Siyah hemen tamamlar", "Siyah 1 ile hemen tamamlamak da olur; beyaz 2 ile merkeze çıkar. Sonuç eşit."),
'A-1-9-1-1-23': ("Siyah aşağı uzanırsa", "Siyah 1 ile aşağı uzanırsa beyaz 2 ve 4 ile siyahın kenar ve köşe alanını tamamen alır; siyah biraz memnun değildir."),
'A-1-9-1-1-24': ("Siyah hane ile karşılık – kötü", "Siyah 1 ile hane yapıp karşı saldırmak da kötüdür. Beyaz 4 ve 6 ile sente bir taş alıp çok kazanır."),
'A-1-9-1-1-25': ("Siyah köşeyi kapatır", "Siyah 1 ile köşeyi kapatırsa beyaz 2'den sonra çok alan kazanır. Siyah merkezde kalın olsa da işaretli beyaz taş hâlâ canlıdır; ileride beyazın A'da yapışması siyahı çok rahatsız eder."),
'A-1-9-1-1-26': ("Beyaz büyük keima", "Beyaz 1 büyük keima da iyi bir noktadır; siyah 2 ile 3-3'e kosumi yaparak sağlamlaşır, beyaz 3 ile zıplayıp karşılıklı saldırır. İleride beyazın A'da hanesi siyah için bir sınavdır."),
'A-1-9-1-1-27': ("Siyah kosumi-tsuke", "Siyah 1 ile kosumi-tsuke de bir yoldur. Beyaz 4 ile akıllıca pincer yapar; siyah 5 kaplan ağzıyla bu takas beyaza biraz yarar ve siyahın A'da hane yapıp tamamlamasını önler. Siyah 7 ile sakince tamamlar; iki taraf da kabul edebilir."),
'A-1-9-1-1-28': ("Beyaz önce zıplar", "Beyaz 1 ile önce zıplamak da olur, sonra 3 ile sakince kosumi yapar. Siyah 6 tam zamanındadır, sonra 8 ve 10 ile hane yapıp bağlanarak köşeyi korur; sonuç eşit."),
'A-1-9-1-1-29': ("Beyaz büyük keima – şüpheli", "Beyaz 1 büyük keima durumu değiştirir; siyah 2 ile yapışıp güçlüce karşılık verir. Beyaz 5 ile sakince zıplar, siyah 6 iyi bir hamledir, sonra 8 ve 10 ile kararlılıkla takas yapar; beyaz biraz kayıpta."),
'A-1-9-1-1-30': ("Üç taşı yakalamaya çalışmak – olmaz", "Beyaz 1, 3 ve 5 ile üç taşı yakalayamaz; siyah 8 ile keskin şekilde işgal eder, beyaz 9 ile sabretmek zorunda kalır. Siyah 12 ile rahatça atari verir; beyazın A ile siyahın B takası beyaz için büyük kayıptır. Sonra siyah 18 ile işgal eder ve beyazın alt tarafı ağır hasar görür."),
'A-1-9-1-1-31': ("Siyah bastırır – biraz uzlaşmaz", "Siyah 1 biraz uzlaşmazdır. Beyaz 4 ile iyi bir kosumi yapar; siyahın burada iyi bir cevabı kalmaz, genelde tenuki yapar."),
'A-1-9-1-1-32': ("Beyaz uzanır", "Beyaz 1 ile uzanmak da olur, sonra 3 ile büyük keima yapıp memnun olabilir."),
'A-1-9-1-1-33': ("Siyah 2. sıradan keima", "Siyah 1 ile 2. sıradan keima sağlamdır; beyaz sente kazanç sağlamıştır ve tenuki yapabilir."),
'A-1-9-1-1-34': ("Siyah kosumi-tsuke – kötü", "Siyah 1 kötüdür. Beyaz 2 ile uzanınca siyah hâlâ A ve B'deki iki imkânı birden önleyemez."),
'A-1-9-1-1-35': ("Beyaz alçak üç boşluklu açılır", "Beyaz 1 ile alçak üç boşluklu açılmak alana önem verir ve oynanabilir. İleride siyahın A'da işgal imkânı var."),
'A-1-9-1-1-36': ("Beyaz tenuki – pek iyi değil", "Beyazın tenuki yapması pek iyi değildir. Siyah 1 ile iki boşluklu pincer yapınca Bir Boşluklu Zıplama josekisindeki bir şekle döner; iki beyaz taş biraz ağırdır."),
'A-1-9-1-2-1': ("Siyah keima", "Siyah 1 keima da çok yaygındır. A'daki zıplamadan daha çok alana önem verir ama beyazı daha az zorlar; beyaz 2 ile yüksek üç boşluklu açılıp iyi şekil kurar."),
'A-1-9-1-2-2': ("Merdiven beyazın lehine", "Merdiven beyazın lehineyse beyaz 1 ve 3 keskin bir ikilidir. Siyah 4 ile genelde toplanır; beyaz 5, 7 ve 9 ile sente takaslar yapıp çok rahat eder, siyahın şekli biraz ağırdır."),
'A-1-9-1-2-3': ("Merdiven beyazın aleyhine", "Merdiven beyazın aleyhineyse siyah 1 ile toplanabilir; beyaz bir şey kazanamaz."),
'A-1-9-1-2-4': ("Beyaz hemen 3-3 – aceleci", "Beyaz 1 acelecidir; siyah 2 ile hane yapıp sert karşılık verir. Beyaz 3 ile sürünüp köşede yaşasa da siyah 10 keima ile çıkınca beyaz kazandığından çok kaybeder."),
'A-1-9-1-2-5': ("Siyah aşağı uzanır", "Siyah 1 ile uzanmak da olur. Beyaz 2 keima ile yaşamaya çalışınca siyah 3 ile sertçe kapatır. Beyaz 4 ile itip kesmek zorunda kalır ama siyah 15 keima ile çıkınca savaşta beyaz zorlanır."),
'A-1-9-1-2-6': ("Merdiven lehine – yapışıp 3-3", "Merdiven beyazın lehineyse beyaz 1 ve 3 ile doğrudan yapışıp 3-3'ü işgal etmek de güçlüdür. Siyah 4 ile genelde toplanır, 10 ile önce kesmek akıllıcadır; dengeli bir savaş olur."),
'A-1-9-1-2-7': ("Beyaz uzanır – genelde kötü", "Beyaz 1 genelde kötüdür. Siyah 2 ile sertçe aşağı uzanır, beyaz 3 ile zıplar. İleride siyahın A'da omuz vuruşu sol tarafı genişletmek için iyi bir hamledir; siyah biraz daha iyi."),
'A-1-9-1-2-8': ("Beyaz keser", "Beyazın 1 ile kesmesi için çevrede destek gerekir; yoksa siyah 2 ve 4 ile itip çıkar ve beyaz zor savaşır."),
'A-1-9-1-2-9': ("Siyah hane yapıp bağlanır", "Siyah 1 ve 3 ile hane yapıp bağlanırsa beyaz 4 ile iyi bir kaplan ağzı yapar. Beyaz A-1-9-1-2-7'dekinden açıkça kalındır; sonuç eşit."),
'A-1-9-1-2-10': ("Siyah hane – zorlama", "Siyah 1 biraz zorlamadır; beyaz 2 ile sertçe keser. Siyah 3 ile dirençli toplanır, beyaz 6 ve 8 ile zıplayarak siyahı sıkıştırır; savaşta beyaz daha rahattır."),
'A-1-9-1-2-11': ("Siyah atari verirse", "Siyah 1 ile atari verirse beyaz 2 ile hane yapıp geçer ve çok kazanır. Siyah 9 ile kalınca döner ama beyaz artık tenuki yapabilir; siyahın temposu biraz yavaştır."),
'A-1-9-1-2-12': ("Siyah bağlanır – zayıf", "Siyah 1 zayıftır; beyaz 2 ile yine köşeyi alır. Yapay zekâya göre siyah 3 ile hane yapmak zorundadır; siyah 1 taşı önceki şekildekinden açıkça kötüdür."),
'A-1-9-1-2-13': ("Siyah boyun eğer – olmaz", "Beyazın çevresi çok güçlü değilse siyahın 1 gibi boyun eğen bir hamlesi kesinlikle düşünülmemelidir."),
'A-1-9-1-2-14': ("Siyah toplanır – yine kayıp", "Siyah 1 önceki şekilden biraz iyidir ama siyah yine açıkça kayıptadır. Beyazın 2 ile kenarda açılması yeter; sente kazanç sağlamıştır."),
'A-1-9-1-2-15': ("Beyaz tenuki", "Beyazın tenuki yapması da çok yaygındır; bu şekil bir zamanlar çok popülerdi. Beyaz 2 ile büyük zıplama bu şekilde başını çıkarmanın sık yoludur, sonra 4 ile iyi bir omuz vuruşu yapar."),
'A-1-9-1-3-1': ("Siyah karşı pincer – genelde kötü", "Siyah 1 karşı pincer genelde kötüdür; beyaz 2 ile sıkıca yapışır. Beyaz 4 ile sadece uzanır, sonra 6 ile tek hane iyi bir hamledir; beyaz sade ve avantajlıdır."),
'A-1-9-1-3-2': ("Taş feda edip kapatmak", "Beyaz 1 ve 3 eskiden taş feda edip kapatan iyi hamleler sayılırdı ama siyahın köşesini sağlamlaştırır; beyaz önceki şekildeki kadar iyi değildir."),
'A-1-9-1-3-3': ("Beyaz çift hane", "Beyaz 1 ile çift hane de çok güçlüdür; siyah 2 ve 4 ile toplanıp kesmek en güçlü cevaptır. Ama siyah 18 ile sonunda köşeyi tamamlamak zorunda kaldığı için savaşta beyaz daha rahattır."),
'A-1-9-1-3-4': ("Siyah aradan çıkar – kötü", "Siyah 1 ve 3 ile aradan itip çıkmak kötüdür; beyaz 4 ve 6 ile bir taşı alıp çok kazanır."),
'A-1-9-1-4-1': ("Siyah büyük keima – ince", "Siyah 1 büyük keima incedir. Beyaz tenuki de yapabilir, üç boşluklu da açılabilir; siyahın köşesinde ileride birçok zayıflık kalır."),
'A-1-9-2-1-1': ("Beyaz aşağı uzanır – eski yol", "Beyaz 1 eski Çin oyunlarında görülür, bugün genelde biraz kayıp sayılır. Siyahın 2 ile zıplaması yeter; beyaz 3 ile verimli zıplarsa siyah 4 ile iyi bir pincer yapar. Siyah daha rahattır."),
'A-1-9-2-1-2': ("Beyaz üç boşluklu açılır", "Beyaz 1 ile üç boşluklu açılırsa işaretli beyaz taş A noktasındaki kadar iyi yerde değildir."),
'A-1-9-2-1-3': ("Beyaz sente arar", "Beyaz 1 ve 3 sente almak için oynanır; siyah 6 keima ile tamamlamak zorundadır. Beyaz biraz alan kaybettiği için burada da siyah biraz daha iyi."),
'A-1-9-2-2-1': ("Siyah kaplan ağzı", "Siyah 1 her zaman avantajlı değildir. Beyaz 8 ile kenarda açılınca siyahın köşesi biraz boş kalır; sonuç eşit."),
'A-1-9-2-2-2': ("Siyah çift hane – kötü", "Siyah 1 kötüdür. Beyaz 2 ile siyahı kötü bir şekle sokar, sonra 4 ile sakince uzanıp taş feda eder; beyaz sade ve avantajlıdır."),
'A-1-9-2-2-3': ("Merdiven siyahın lehine – kesme", "Merdiven siyahın lehineyse siyah 1 ile kesmek güçlüdür; beyaz 2 ve 4 ile önemli noktaları alır. Siyah 5 ile beyazın nefesini daraltmak zorundadır, beyaz 6 ile keskin şekilde işgal eder; takasta beyaz daha çok kazanır."),
'A-1-9-2-2-4': ("Siyah kötü şekilde bağlanır", "Siyah 1 ile kötü şekilde bağlanmak cesaret ister. Beyaz 2, 4 ve 6 şeklin önemli noktalarıdır; siyah 7 ve 9 ile uzlaşmak zorundadır. Beyaz 10'dan sonra sente köşeyi boşaltır; siyah açıkça kayıpta."),
'A-1-9-2-2-5': ("Merdiven siyahın aleyhine", "Merdiven siyahın aleyhineyse beyaz 1 ve 3 güçlüdür; A ya da B'deki merdivenlerden biri kesin olur ve siyah çöker."),
'A-1-9-2-3-1': ("Siyah kapatır", "Siyah 1 de yeterince iyi değildir; beyaz 2 ile zıplamak bir yoldur, siyah 4 ile aktif bir büyük zıplama yapar. İki tarafın şekli de dolgundur; sonuç eşit."),
'A-1-9-2-3-2': ("Beyaz sağlamca uzanır", "Beyaz 1 sağlamdır; siyah 2 ile küçük zıplama iyidir. Önceki şekille hangisinin daha iyi olduğunu söylemek zor."),
'A-1-9-3-1-1': ("Beyaz hane yapıp bağlanır", "Beyaz 1 ve 3 ile hane yapıp bağlanmak da genelde iyi değildir; siyah 4 ile zıplayınca A-1-9-2-1-3'e döner."),
'A-1-9-3-1-2': ("Siyah keima", "Siyah 1 ile keima da olur; merdiven beyazın lehineyse beyaz 2 ile iyi bir keima yapar. Siyah 3 ile hane yapıp şekli hemen belirlemek bir yoldur; siyah 7 ile tenuki yapıp merdiveni bozar, beyaz 8 ile büyük keima yapıp tamamlar. Siyah biraz daha iyi."),
'A-1-9-3-1-3': ("Siyah tenuki", "Siyah tenuki yapmayı da düşünebilir; beyaz 1'den sonra rahat sente hamleler yapar ama yine siyah biraz daha iyi."),
'A-1-9-3-1-4': ("Merdiven beyazın aleyhine", "Merdiven beyazın aleyhineyse beyaz 1 ile zıplamak doğru ölçüdür; siyah 2 ile zıplayıp köşeyi tamamlar ve alanı çok dolgundur."),
'A-1-9-3-2-1': ("Siyah kaplan ağzı – biraz kötü", "Siyah 1 biraz kötüdür; beyaz 2 ile bağlanınca A-1-9-2-2-1'e döner."),
'A-1-9-3-2-2': ("Beyaz çift hane", "Beyaz 1 çift hane daha sıkıdır; siyah 2 ile çift hane ile karşılık verir. Beyaz 3 ile 2. sırada bağlanmak iyi bir hamledir; iki taraf istediğini alır, sonuç eşit."),
'A-1-9-3-2-3': ("Beyaz önce atari verir", "Beyaz 1 ile önce atari vermek de olur; siyah 6 ile bağlanınca çok kalındır, beyaz 7 keima ile köşeyi alıp yaşar. İki taraf da kabul edebilir."),
'A-1-9-3-2-4': ("Siyah açgözlü – kötü", "Siyah 1 ve 3 ile açgözlülük kötüdür; beyaz 4 ile atari verip çok esnek bir şekil kurar."),
'A-1-9-4-1-1': ("Beyaz 3-3 işgali", "Sol taraf değerliyse beyaz 1 ile 3-3'ü işgal edip dönmek de olur ama normal durumda beyaz için iyi değildir. Siyah 2 ve 4 ile sert oynar; beyaz 9 ile kesince siyah 10 ile önce atari vermelidir, beyaz 13 ile dönmek bir yoldur. İki taraf şeklini tamamlar; siyah daha iyi."),
'A-1-9-4-1-2': ("Beyaz feda etmek için keser", "Beyaz 1 ile taş feda etmeye çalışır; siyah 2'den sonra hepsini alır. Beyaz 11 ile sente dönüp biraz kazansa da köşede çok alan kaybeder; ileride işaretli siyah taşın da imkânları var. Beyaz memnun değildir."),
'A-1-9-4-1-3': ("Siyah taşı sarar", "Siyah 1 ile taşı sarmak sade ve oynanabilir ama önceki iki şekildeki kadar aktif değildir."),
'A-1-9-4-2-1': ("Siyah aşağıdan hane", "Siyah 1 ile aşağıdan hane de bir yoldur; beyaz 2 ve 4 ile köşede yaşamak zorundadır. Siyah 5 ile yine tamamlamalıdır; temposu biraz yavaştır."),
'A-1-9-4-3-1': ("Siyah kapatır – biraz sıkışık", "Siyah 1 biraz sıkışıktır; beyaz 6 ile başını çıkarmak çok güçlüdür."),
}
