# Son, sade metinler (başlık, açıklama).
FINAL = {
'A-1-4': ("Başlangıç pozisyonu", "Yüksek bir boşluklu pincer, altı pincer türü içinde en az oynananıdır. Beyazın seçenekleri: A'da 3-3 işgali, B'de zıplama, C ve D'de çift kakari, E'de yapışma, F'de çapraz keima ya da tenuki."),
'A-1-4-1-1-1': ("3-3 işgali – en iyi cevap", "Beyaz 1 en iyi cevaptır. Beyaz 5 ve 7 ile hane yapıp bağlanınca siyahın şekli biraz rahatsız olur. Alçak pincerdeki şekilden açıkça daha kötüdür."),
'A-1-4-1-1-2': ("Beyazın sonraki iyi noktası", "İleride beyaz 1 iyi bir hamledir. Siyah 2 ve 4 ile sabırla cevap vermelidir; beyaz sente kazanç sağlar."),
'A-1-4-1-1-3': ("Beyaz pincer – kötü", "Beyaz 1 kötüdür. Siyah 2 ile kaplan ağzı yapınca işaretli siyah taş tam yerinde olur."),
'A-1-4-1-1-4': ("Siyah sürünür – kötü", "Siyah 1 kötüdür, sonra siyah iki arada kalır. Tamamlarsa verimsiz olur; tenuki yaparsa beyaz 4 ile sertçe uzanır. Siyah ikiye bölünür ve savaş çok zorlaşır."),
'A-1-4-1-2-1': ("Siyah dıştan kapatır – kötü", "Siyah 1 kötüdür. Beyaz 4 kosumi doğru şekildir; siyah 5 ile bastırmak zorunda kalır ve işaretli taşı kötü yerde durur."),
'A-1-4-2-1-1': ("Beyaz zıplar", "Beyaz 1, 3-3 işgalinden biraz kötüdür. Siyah 2 ile küçük zıplama bir yoldur. Sağ alt siyahsa beyaz 3 ve 5 ile yerinde yaşar; sonuç eşit."),
'A-1-4-2-1-2': ("Üç kosumi ile kesmek", "Siyah 1, 3 ve 5 ile sert oynayıp işaretli beyaz taşı keser. Ama beyaz 6 ve 8 ile basitçe cevap verir; dışarıdaki üç siyah taş yalnız kalır."),
'A-1-4-2-1-3': ("Ko açmak – genelde kötü", "Siyah 1 ve 3 ile ko açmak genelde kötüdür. Çok güçlü bir ko tehdidi yoksa beyazın A'da koyu bitirmesi siyaha pahalıya patlar."),
'A-1-4-2-1-4': ("Beyaz karşı pincer", "Sağ alt beyazı destekliyorsa beyaz 1 ile karşı pincer güçlüdür; savaşta beyaz biraz önde olur."),
'A-1-4-2-2-1': ("Siyah büyük zıplar", "Yapay zekâ siyah 1 ile büyük zıplamayı daha çok sever. Beyaz 2 ile boş kalan köşeyi işgal eder. İki taraf birbirini sıkıştırır ve karışık bir savaş başlar."),
'A-1-4-2-3-1': ("Siyah keima – biraz yumuşak", "Siyah 1 biraz yumuşaktır. Beyaz 4 omuz vuruşu harika bir noktadır; beyaz 8 ile karşı pincer de yapınca rahat eder."),
'A-1-4-3-1-1': ("Çift kakari – genelde kötü", "Beyaz 1 çift kakari genelde iyi değildir. Siyah sade ve sağlam oynar, sonra 8 ile pincer yapar. Beyaz 1 siyahın güçlü taşlarına çok yakın kalır."),
'A-1-4-3-1-2': ("Siyah bu taraftan kapatır", "Siyah 1 ile bu taraftan kapatmak da olur. İki tarafın şekli de dolgundur."),
'A-1-4-3-2-1': ("Siyah dıştan bastırır", "Siyah 1 ile dıştan da bastırabilir. Beyaz 2 ve 4 ile hane yapıp köşeyi işgal eder. Siyah 9 ve 11 ile sente kapatır, sonra 13 ile pincer yapar ve sert bir savaş başlar."),
'A-1-4-3-2-2': ("Beyaz sürünüp bağlanır", "Beyaz 1 ile hemen sürünüp bağlanırsa siyah 2 atari ile çok kalın olur; beyaz biraz kayıpta."),
'A-1-4-4-1-1': ("Yüksek çift kakari – kötü", "Beyaz 1 yüksek çift kakari de kötüdür. Siyah 2 ile bastırınca şekli tamamlanır; beyaz 1 garip bir yerde kalır."),
'A-1-4-5-1-1': ("Beyaz yapışır – tuzak", "Beyaz 1 biraz tuzak kokan bir hamledir. Siyah 2 ile içeriden hane en güçlüsüdür, 4 ile sağlamca uzanır. İki taraf istediğini alır ama siyah daha memnundur."),
'A-1-4-5-1-2': ("Atari verip uzanmak", "Siyah 1 ve 3 ile atari verip uzanmak da olur. Beyaz taş feda etmek zorunda kalır; siyah sente köşeyi alır ve memnundur."),
'A-1-4-5-1-3': ("Beyaz keser – şüpheli", "Beyaz 1 şüphelidir. Siyah 2 ve 4 ile doğru sırayla atari verir. Beyaz bir taş alsa da hâlâ yaşamamıştır; siyah çok rahattır."),
'A-1-4-5-2-1': ("Siyah dıştan hane – hata", "Siyah 1 hatadır. Beyaz 2 ve 4 ile hane yapıp bağlanır, siyah 5 ile kesme noktasını kapatmak zorunda kalır. Beyaz sente köşeyi alır, siyahın merkezi eksik kalır."),
'A-1-4-6-1-1': ("Beyaz çapraz keima", "Beyaz 1 değişik bir fikirdir. Siyah 2 ile kosumi-tsuke sadedir, beyaz 3 ile yumuşakça kosumi yapar; siyah biraz daha iyi."),
'A-1-4-6-2-1': ("İtip kesmek – plansız", "Siyah 1 ve 3 ile itip kesmek plansızdır. Beyaz 4 ve 6 ile atari verip bağlanınca siyah zorlanır: köşesi dar kalır, işaretli beyaz taş da her an kaçabilir."),
'A-1-4-7-1-1': ("Beyaz tenuki", "Beyaz tenuki de yapabilir. Siyah 1 ile kosumi-tsuke bir yoldur. Beyaz 4 esnek bir karşı pincer, siyah 5 sert bir zıplamadır; beyaz yine tenuki düşünebilir. Sonuç eşit."),
'A-1-4-7-2-1': ("Siyah üstten bastırır", "Sağ alt siyahı iyi destekliyorsa siyah 1 ile bastırabilir. Beyaz 2 ile köşeyi işgal edip dönmelidir; siyah 5 ile yönünü sağa çevirir."),
'A-1-4-7-2-2': ("Beyaz dıştan uzanır – kötü", "Beyaz 1 kötüdür. Beyaz 3 ve 5 ile yapışıp bağlanınca siyah 6 ile aşağı döner; siyahın merkezi öncekinden açıkça iyidir."),
}
