# Son, sade metinler (başlık, açıklama).
FINAL = {
'A-1-12': ("Başlangıç pozisyonu", "Siyah 1, 2. sıradan keimadır; beyazın kökünü alıp saldırmak ister ve duruma göre oynanır. Beyazın dört ana cevabı var: A ve B'de kakari yapıp dönmek, C'de kapatmak ve D civarında açılmak."),
'A-1-12-1-1-1': ("Beyaz karşı kakari", "Beyaz 1 ile karşı kakari çok yaygındır; siyah 2 ile sade bir karşı pincer yapar, beyaz 3 ile basitçe açılır. Bu, beyazın diğer taraftan kakari yapmasına benzer; siyah A ile beyaz B takası beyaza biraz yarar."),
'A-1-12-1-2-1': ("Siyah kosumi", "Siyah 1 kosumi de olur; beyaz 2 ile 3-3'ü işgal etmek iyidir, 4 ile akıllıca ters kosumi yapar. Beyaz 6 ile önce itmek iyi sıradır; siyah 13 ile yine keima yapıp tamamlamak zorunda kalır. Burada da beyaz biraz daha iyi."),
'A-1-12-1-2-2': ("Beyaz iki boşluklu açılır – biraz yavaş", "Beyaz 1 ile iki boşluklu açılmak ya da A'da çok büyük keima biraz yavaştır; siyah tenuki yapabilir ya da B'de karşı pincer yapabilir."),
'A-1-12-1-3-1': ("Siyah kosumi-tsuke – şüpheli", "Siyah 1 şüphelidir; beyaz 2 ile uzanınca sol taraf güçlenir. Siyah 3 keima ile ayırırsa beyazın 4 ile keima yapması yeter. Siyahın şekli zayıftır; A civarında destek gelse bile beyaza etkili saldıramaz."),
'A-1-12-2-1-1': ("Beyaz yüksek kakari", "Beyaz 1 yüksek kakari genelde alçak kakariden kötüdür. Siyah 2 ile sıkı bir karşı pincer yapar, beyaz 3 ile yapışmak bir yoldur; sonuç eşit."),
'A-1-12-2-1-2': ("Beyaz zıplayıp ayırır", "Beyaz 1 ile aşağı zıplayıp ayırmak da düşünülebilir; iki taraf da birer taşı kontrol eder, sonuç eşit."),
'A-1-12-2-2-1': ("Siyah yapışıp geri çekilir – kötü", "Siyah 1 kötüdür; beyaz A ile siyah B takası açıkça beyaza yarar, siyahın köşesinde incelik de kalır."),
'A-1-12-3-1-1': ("Beyaz kapatır", "Beyaz 1 ile yerinde yaşamaya çalışır; siyah 2 ile sağlamca yapışınca Kosumi-tsuke josekisindeki bir şekle döner."),
'A-1-12-3-2-1': ("Siyah karşı pincer – sert", "Siyah 1 ile karşı pincer serttir; beyaz 2 ile siyahın zayıflığını vurgular. Siyah 5 ile ters kaplan ağzı doğru şekildir; savaş dengeli."),
'A-1-12-3-2-2': ("Siyah aşağı uzanırsa", "Siyah 1 ile aşağı uzanırsa beyaz 2 ile sert bir pincer yapar; siyah 3 ve 5 ile sıkıca başını çıkarır. İki taraf birbirinin şeklini bozar; savaşta beyaz biraz öndedir."),
'A-1-12-3-2-3': ("Merdiven beyazın lehine – pincer", "Merdiven beyazın lehineyse beyaz 1 ile pincer de iyidir; siyah 2 ile bağlanıp sabretmek zorundadır. Beyaz 5 ile aktif bir karşı pincer yapar, 7 ile hem şeklini tamamlar hem siyaha baskı yapar; savaşta beyaz öndedir."),
'A-1-12-3-2-4': ("Merdiven beyazın aleyhine", "Merdiven beyazın aleyhineyse siyah 1 ile itip karşı saldırabilir. Beyaz 2 ile dolambaçlı bir yapışma yapar, siyah 3 ile dönünce takas olur; sonuç eşit."),
'A-1-12-4-1-1': ("Beyaz açılır", "Beyaz 1 ile açılmak sade ve oynanabilir; siyah 2 ile geniş açılmak iyidir. İki tarafın da birbirinin alanını işgal etme imkânı var."),
'A-1-12-4-1-2': ("Siyah hemen işgal eder – karışık", "Siyah 1 ile hemen işgal etmek çok karışıktır; siyah 3 ve 5 çok güçlü hamlelerdir, beyaz 8 ile önce atari vermek zorundadır. Siyah 15 atari iki tarafın kalınlığı için önemlidir; burada göz alanı köşeden daha önemlidir. Savaşta beyaz biraz daha rahattır."),
'A-1-12-4-1-3': ("Beyaz önce iter – kötü", "Beyaz 1 kendi nefesini azaltır, kötüdür. Siyah 4 ile uzanınca beyaz 5 ile sabretmek zorundadır; siyah 10 ile zıplayıp dolgun bir şekil kurar, beyaz 11 ile sırayı kaybederek tamamlar. Siyah açıkça kazançlıdır."),
'A-1-12-4-2-1': ("Beyaz büyük keima", "Beyaz 1 büyük keima da oynanır; siyah 2 ile buna göre küçük açılır. Sonuç eşit."),
'A-1-12-4-2-2': ("Siyah işgal eder – aşırı", "Siyah 1 fazladır; beyaz 2 ile yapışıp güçlü karşılık verir. Siyah biraz merkez kazansa da köşesi boşalır; kazandığından çok kaybeder."),
'A-1-12-4-2-3': ("Siyah yapışır – biraz aşırı", "Merdiven lehine olsa bile siyah 1 biraz fazladır. Beyaz 4 ile sakince uzanır, sonra 6 ve 8 ile taş feda edip savaşır. Beyaz 14 ve 16 siyahı çok rahatsız eder; köşedeki ölü taşları kullanıp iki taraftan kazanır, siyah biraz sıkışır."),
'A-1-12-4-2-4': ("Merdiven beyazın lehine – hane", "Merdiven beyazın lehineyse beyaz 1 ile başa hane keskindir. Siyah 2 ile hane yapmak zorundadır, beyaz 5 ile doğal olarak aşağı zıplar; siyahın iki tarafı da zayıftır ve savaş çok zordur."),
'A-1-12-4-2-5': ("Siyah keser – kötü", "Siyah 1 kötüdür; beyaz 2 ve 4 ile atari verip çıkınca siyahın köşesi ağır hasar görür. Beyaz 8 ile 1. sırada iyi bir hane yapar, siyah 9 ile merkezi korumak zorundadır. Beyaz 10 ile sente geçer, sonra 12 ile köşeyi boşaltmaya devam eder."),
'A-1-12-4-2-6': ("Beyaz sürünür – biraz yumuşak", "Beyaz 1 biraz yumuşaktır; siyah 2 ile sıkıca bastırır, beyaz 3 ve 5 ile itip kesme noktası yaratmak zorundadır. Beyaz biraz iyidir ama önceki şekillerdeki kadar değil."),
}
