S = {
'A-1-1-4': "Beyaz 3-3 noktasına girer (işgal). Hemen oynanırsa genellikle biraz kayıptır. Siyah A veya B ile beyazı ayırmalıdır.",
'A-1-1-4-1-1': "Siyah 1 ile engellemek sade ve iyidir. Beyazın köşesi tam yaşamadığı için siyah savaşta daha rahattır.",
'A-1-1-4-1-2': "Siyah 1 ile aşağı uzanmak da olur. Siyah kalın oynar; bu da siyah lehinedir.",
'A-1-1-4-1-3': "Siyah 1 ile sürünmek de bir seçenektir. Siyah iyi bir şekil kurar.",
'A-1-1-4-1-4': "Beyaz 1 ile uzansa bile siyah endişelenmez. Beyazın savaşı zordur.",
'A-1-1-4-2-1': "Siyah 1 ile keima yapay zekânın yeni fikridir. Beyaz köşede yaşar ama siyah açıkça avantajlıdır.",
'A-1-1-4-2-2': "Beyaz 1 ile yapışıp takas arar. Siyah sağlam oynar ve sente alarak memnun olur.",
'A-1-1-4-2-3': "Siyah 1 şüphelidir. Beyaz itip keserek rahatça çıkar.",
'A-1-1-4-2-4': "Beyaz 1 ve 3 ile doğrudan kesmek aşırıdır. Siyah 4 ile nefes yarışı başlatır.",
'A-1-1-4-2-5': "Önceki diyagramın devamı. Siyah dışarıda kazanç sağlar ve sonra köşeyi yer; çok büyük alan kazanır.",
'A-1-1-5': "Beyaz yandan yapışır; bu yapay zekâdan gelen bir fikirdir. Çevre boşken beyaz için biraz kötüdür. Siyahın en iyi cevapları A ve B'dir.",
'A-1-1-5-1-1': "Siyah 1 ile dışarıdan hane güçlüdür. Siyah doğru sırayla oynar ve avantajlı olur.",
'A-1-1-5-1-2': "Beyaz 1 aşırıdır. Beyaz nefes yarışını kazansa da kazandığından fazlasını kaybeder.",
'A-1-1-5-1-3': "Siyah 1 ile köşeye hane biraz zayıftır. Beyaz çıkar ve karışık bir savaş başlar.",
'A-1-1-5-1-4': "Siyah 1 ile geri çekilmek çok yumuşaktır. Beyaz iyi bir şekil kurar.",
'A-1-1-5-1-5': "Beyaz 1 ile doğrudan kesmek kötüdür. Siyah 2 güçlüdür ve beyazın taşları ağır kalır.",
'A-1-1-5-1-6': "Beyaz 1 çalışmaz. Köşedeki nefes yarışını beyaz kaybeder.",
'A-1-1-5-2-1': "Siyah 1 ile engellemek sadedir. Beyaz köşeye girip sente alır. Sonuç iki taraf için de kabul edilebilir.",
'A-1-1-5-2-2': "Beyaz 1 ile dışarıda uzanmak kötüdür. Siyah art arda iyi hamleler yapar.",
'A-1-1-5-2-3': "Merdiven siyah lehineyse siyah bir taşı merdivenle yakalar. Bu siyah için çok büyük bir kazançtır.",
'A-1-1-5-2-4': "Siyah 1 ile dışarıdan kesmek şüphelidir. Beyaz taşı alır ve rahattır.",
'A-1-1-5-2-5': "Merdiven beyaz aleyhineyse beyaz 1 ile bağlanır. Siyah başka yere oynar ve biraz avantajlıdır.",
'A-1-1-5-2-6': "Siyah 1 çok yumuşaktır. Beyaz rahat oynar, siyah yavaş kalır.",
'A-1-1-5-3-1': "Siyah 1 ile uzanmak ancak yakında bir pincer taşı varken oynanır. Normalde savaş beyaz lehinedir.",
'A-1-1-5-3-2': "Siyah başka yere de oynayabilir. Beyaz iyi bir noktayı alır ve güç kurar.",
'A-1-1-5-3-3': "Beyaz 1 ve 3 ile doğrudan kesmek çok serttir. Karmaşık bir savaş başlar.",
'A-1-1-5-4-1': "Siyah 1 ile pincer de oynanabilir. İki taraf sade oynar; sonuç eşittir.",
'A-1-1-5-4-2': "Siyah 1 ile dışarıdan uzanmak iyi değildir. Beyaz güzel bir şekil kurar.",
'A-1-1-6': "Beyaz ōgeima (büyük keima) ile yaklaşır. Bu hamle bir tuzaktır. Siyah için en iyisi başka yere oynamaktır; yerel oynarsa A güvenlidir, B ise tuzağa düşer.",
'A-1-1-6-1-1': "Siyah başka yere oynarsa beyaz 1 en iyi devamdır. Siyah yine başka yere oynayabilir.",
'A-1-1-6-1-2': "Beyaz pincer yaparsa siyah da karşı pincer yapabilir ve hafifçe çıkar.",
'A-1-1-6-2-1': "Siyah 1 güvenli bir hamledir. Beyaz 2'den sonra A-1-1-1 ile aynı şekle döner.",
'A-1-1-6-2-2': "Siyahın çevresi güçlüyse beyaz 1 esnek bir hamledir. Siyah başka yere oynamalıdır.",
'A-1-1-6-2-3': "Beyaz 1 ile geri çekilmek çok yavaştır.",
'A-1-1-6-3-1': "Siyah 1 ile yapışma yeterince iyi değildir. Siyah bir taşı yakalar ama sonuç sadece eşittir.",
'A-1-1-6-3-2': "Merdiven siyah aleyhineyse siyah içeriden atari vermek zorundadır ve biraz kayıpta kalır.",
'A-1-1-6-3-3': "Beyaz 1 kötüdür. Siyah bir kez bağlanıp başka yere oynar; beyazın şekli zayıf kalır.",
'A-1-1-7': "Beyaz başka yere oynamıştır (tenuki). Siyah A veya B ile pincer yapabilir ya da C ile yapışabilir.",
'A-1-1-7-1-1': "Siyah 1 ile bir aralık pincer yapar. Siyah 5 iyi bir hamledir. Sonuç eşittir.",
'A-1-1-7-1-2': "Siyah 1 ile atari eskiden çok oynanırdı. Siyah sente alır ama dışı zayıftır; siyah memnun olamaz.",
'A-1-1-7-1-3': "Siyah 1 serttir ve beyazın kolayca yerleşmesine izin vermez. Beyaz karşı pincer ile çıkar. İki taraf için de oynanabilir.",
'A-1-1-7-1-4': "Beyazın yeterli ko tehdidi varsa 1 ile ko yapmak da iyidir.",
'A-1-1-7-1-5': "Siyahın çift hanesi biraz zayıftır. Beyaz 4 iyi bir hamledir ve beyaz sade oynayarak memnun olur.",
'A-1-1-7-1-6': "Beyaz 1 ile 2. sıradan keima da oynayabilir. A-1-1-2-2-2 ile aynı şekle döner.",
'A-1-1-7-2-1': "Siyah 1 ile iki aralık pincer yapar. Beyaz karşı pincer ile cevap verir. İki taraf için de oynanabilir.",
'A-1-1-7-2-2': "İki aralık pincer'da beyazın ko yapması dikkat ister. Bir aralık pincer'daki kadar iyi olmaz.",
'A-1-1-7-2-3': "Siyah çift hane de yapabilir. Beyaz 2 iyi bir hamledir ve beyaz yerinde yaşar. Sonuç eşittir.",
'A-1-1-7-2-4': "Siyah 1 ile hane de yapabilir. Sonuç eşittir.",
'A-1-1-7-2-5': "Siyah 1 biraz yumuşaktır. Beyaz sente olarak yaşar ve memnun olur.",
'A-1-1-7-2-6': "Beyaz josekiyi körü körüne uygularsa siyahın × taşı tam yerinde kalır. Siyah biraz avantajlıdır.",
'A-1-1-7-2-7': "Siyah 1 ile atari biraz zayıftır. Siyahın × taşı iyi çalışmaz; beyaz biraz daha iyidir.",
'A-1-1-7-2-8': "Beyaz 1 ile kaplan ağzı kötüdür. Siyah 2 ile beyazı kapatır; beyaz yaşar ama çok sıkışır.",
'A-1-1-7-2-9': "Beyaz 1 ile aktif oynar. Bir ko çıkar ve pozisyon çok karmaşık olur.",
'A-1-1-7-2-10': "Siyah 1 ile bağlanmak sadedir. Taşlar takas edilir; sonuç eşittir.",
'A-1-1-7-2-11': "Beyaz 1 ile içeriden atari de verebilir. Beyaz köşeyi, siyah dış gücü alır. Sonuç eşittir.",
'A-1-1-7-2-12': "Beyaz 1 aşırıdır. Siyah iyi bir sırayla köşeyi yer ve beyaz zorlanır.",
'A-1-1-7-2-13': "Siyah 1 ve 3 kötüdür. Beyaz köşeyi alır; siyahın × taşı boşa gider.",
'A-1-1-7-2-14': "Siyah 1 biraz zayıftır. Beyaz aktif oynar ve rahat bir tempoyla ilerler.",
'A-1-1-7-2-15': "Siyah 1 ile içeriden kesmek iyi değildir. Siyahın × taşı yine boşa gider.",
'A-1-1-7-3-1': "Siyah 1 ile yapışıp 3 ile geniş pincer yapar. Beyaz karşı pincer ile cevap verir; zor bir savaş başlar.",
'A-1-1-7-3-2': "Siyah 1 ile bir aralık pincer fazla sıkıdır. Beyaz iyi karşılık verir ve biraz daha rahattır.",
}
