# Sade açıklamalar: kod -> metin (başlık ve değerlendirme tr*.py'den gelir)
S = {
'A-1-1': "Siyah 1 ile keima yapmak doğru cevaptır. Beyazın en iyi devamı genellikle A'daki yapışmadır. B ve C eskiden popülerdi ama biraz yavaştır. D, E ve F ancak uygun durumlarda oynanır. Beyaz başka yere de (tenuki) oynayabilir.",
'A-1-1-1': "Beyaz yapışıp iki kez hane yapar ve siyahı hemen karar vermeye zorlar. Siyah için A normal cevaptır, B ve C yapay zekânın yeni fikirleridir. D ve E eski hamlelerdir, F ise genellikle kötüdür.",
'A-1-1-1-1-1': "Günümüzde en çok oynanan şekillerden biri. Siyah dışarıda güç kurar, beyaz köşede alan kazanır. Sonuç eşittir.",
'A-1-1-1-1-2': "Siyah 1 alanı korur. Beyaz 2 siyahın nefeslerinin az olmasından yararlanır. Merdiven siyah lehineyse siyah 3 güçlüdür. İki taraf için de oynanabilir.",
'A-1-1-1-1-3': "Siyah 1'i şimdi oynamak erkendir. Beyaz 2'den sonra siyah A'ya giremez; bu siyah için küçük bir kayıptır.",
'A-1-1-1-1-4': "Beyazın iki sıçrayışı çok serttir (AlphaGo'nun oyunu). Beyaz 5 ve 7 gereklidir. Sonuç yapay zekâ tarzı eşit bir josekidir.",
'A-1-1-1-1-5': "Siyah 1 dört taşı yakalar ama gote kalır. Açılışta bu çok yavaştır; beyaz sente güç kurar. Siyah için kötüdür.",
'A-1-1-1-1-6': "Siyah 1 ile taşı almak kötüdür. Beyaz 2'den sonra rahat oynar ve beyaz 16 ile köşedeki siyah taşlar zor duruma düşer.",
'A-1-1-1-1-7': "Beyaz 1 ile önce uzanmak yanlış sıradır. Kesme artık sente olmaz ve beyaz dışarıda çok kaybeder.",
'A-1-1-1-1-8': "Beyaz keser ve hane yapar. Burada merdiven önemlidir. Merdiven siyah lehineyse siyah 6 ile çıkar. Sonuç yaklaşık eşittir.",
'A-1-1-1-1-9': "Siyah 10 yerine 1'de iterse taşlar takas edilir. Ardından çıkan savaşta beyaz biraz daha iyidir.",
'A-1-1-1-1-10': "Sol üst köşe siyahsa siyah 1 güçlüdür. Siyah birkaç taşı feda eder ve dışarıda çok iyi bir güç kurar.",
'A-1-1-1-1-11': "Merdiven siyah aleyhineyse siyah başka yere oynamak zorunda kalır. Beyazın A'daki hamlesi çok büyük olur; siyah biraz geride kalır.",
'A-1-1-1-1-12': "Sağ üstte beyazın × taşı varsa merdiven işlemez. Siyah 1 ile dışarı çıkmaya çalışırsa taşları dağılır.",
'A-1-1-1-1-13': "Merdiven siyah aleyhineyse siyah 1 ile hemen sıkıştırmak doğrudur. Sonuç eşittir.",
'A-1-1-1-1-14': "Beyaz omuz vuruşu yapar, sonra 7'de pincer ile karşılık verir. İki taraf için de oynanabilir.",
'A-1-1-1-1-15': "Beyaz 1 ile sakin bir açılma yapar. Biraz kayıp ama karışık savaşlardan kaçınır.",
'A-1-1-1-1-16': "Beyaz 1 ile köşeyi almak genelde iyi değildir. Siyah 2 çok büyüktür ve siyah biraz daha iyidir.",
'A-1-1-1-1-17': "Beyaz 1 kaba bir hamledir. Siyah ileride A–C noktalarını sente kullanır ve dışarıda sağlam kalır.",
'A-1-1-1-1-18': "Siyah 1, 3 ve 5 ile şeklini hemen belirler. Beyaz 14'te keserek savaşır; siyah biraz daha rahattır.",
'A-1-1-1-1-19': "Siyah 1 önceki iki diyagramdan zayıftır. Siyah 5 ile tamamlamak zorundadır, yoksa beyazın A'daki kesmesi çok acı olur.",
'A-1-1-1-1-20': "Eskiden oynanan bir yol: siyah taş feda edip güç alır. Yapay zekâya göre siyahın dışı hâlâ zayıftır; siyah biraz kayıptadır.",
'A-1-1-1-1-21': "Siyah 1 ile aşağı itmek eski bir josekidir. Beyaz A'dan hemen çıkarsa zor bir savaş başlar.",
'A-1-1-1-1-22': "Beyaz 1 ile bağlanıp çıkar. Beyaz 7 bu şeklin kilit hamlesidir. Beyaz 11'den sonra siyah bir seçim yapmalıdır.",
'A-1-1-1-1-23': "Siyah 1 ile kesip taşları feda etmek iyidir. Beyaz üç taşı yakalar ama gote kalır. Sonuç iki taraf için de kabul edilebilir.",
'A-1-1-1-1-24': "Siyah 1 ve 3 ile beyazın taşlarını yakalamaya çalışmamalıdır. Beyaz yön değiştirir ve siyahın duvarına bir taş yerleştirir.",
'A-1-1-1-1-25': "Siyah yumuşak ama sağlam oynar. Beyaz rahatça çıkar, siyah hafif baskı kurar. İki taraf için de oynanabilir.",
'A-1-1-1-1-26': "Siyah 1 ile yukarıdan atari de oynanabilir. Beyaz 2 ile hemen uzanmalıdır; ardından zor bir savaş başlar.",
'A-1-1-1-1-27': "Beyaz hemen çıkmazsa siyah 1 ile rahatça tamamlar. Beyaz biraz geride kalır.",
'A-1-1-1-1-28': "Beyaz önce 1'de bağlanabilir. Siyah 2 ile hane yaparsa A-1-1-1-1-22 ile aynı şekle döner.",
'A-1-1-1-1-29': "Beyazın × taşı varken siyah 1 çalışmaz. Nefes yarışını siyah bir nefes farkla kaybeder.",
'A-1-1-1-1-30': "Beyaz 1 ile köşeyi almak zayıftır. Siyah 2'den sonra A-1-1-1-1-16 ile aynı şekle döner.",
'A-1-1-1-1-31': "Siyah 1 ile kaplan ağzı da olur. Beyaz 2'den sonra A-1-1-1-1-1 ile aynı şekle döner.",
'A-1-1-1-1-32': "Beyaz 1 ile köşeyi almak şüphelidir. Siyah 4 ile sağlam yakalar ve ileride A'daki atari beyazı zorlar.",
'A-1-1-1-2-1': "Ters kaplan ağzı yapay zekânın bulduğu bir hamledir. Siyah 3 ile başını çıkarır, beyaz 4 ile yükselir. İki taraf için de oynanabilir.",
'A-1-1-1-2-2': "Beyaz başka yere oynayabilir. Siyah 1 ile sıkıştırırsa beyaz köşede yaşar.",
'A-1-1-1-2-3': "Beyaz 1 ile dışarı çıkarak karşılık verebilir. Siyah 2 önemli noktadır; beyaz 5'ten sonra siyah takip edemez.",
'A-1-1-1-2-4': "Siyahın doğrudan saldırısı işe yaramaz. Beyaz 6 ve 8 ile rahat kurtulur, siyah bir şey kazanmaz.",
'A-1-1-1-2-5': "Siyahın başka yere oynaması iyi değildir. Beyaz 1 ile şeklini güçlendirir.",
'A-1-1-1-3-1': "Siyah 1 ile aşağı uzanmak alana önem verir. Yapay zekâya göre sonuç eşittir: siyah en çok alanı alır ama merkezde zayıf kalır.",
'A-1-1-1-3-2': "Beyaz 1 ile atari şüphelidir. Siyah 2 ile iyi bir yere çıkar; köşe zaten yaşadığı için beyaz sadece kendi taşlarını ağırlaştırır.",
'A-1-1-1-3-3': "Siyah 1 ile uzanmak kötüdür. Beyaz 2'den sonra dengeler beyaz lehine döner; siyah 10 puandan fazla kaybeder.",
'A-1-1-1-3-4': "Beyaz 1 ile kaplan ağzı kötüdür. Siyahın taşları iyi yerde durur ve siyahın nefes sorunu da yoktur.",
'A-1-1-1-4-1': "Siyahın çift hanesi eski bir hamledir. Normalde siyah biraz kayıptadır; ancak A civarında siyah taş varsa oynanabilir.",
'A-1-1-1-4-2': "Beyaz 1 ile basitçe bağlanır. Bu da beyaz için biraz daha iyidir.",
'A-1-1-1-4-3': "Beyaz başka yere oynayabilir. Siyah köşeyi alır ama buraya fazladan hamle harcamıştır; beyaz için de kabul edilebilir.",
'A-1-1-1-4-4': "Siyah 1 ve 3 kötüdür. Beyaz yön değiştirir; siyahın aldığı taşlar az değerlidir.",
'A-1-1-1-4-5': "Beyazın karşı saldırısı aşırıdır. Beyaz taşlarını feda etmek zorunda kalır ve zayıf düşer.",
'A-1-1-1-5-1': "Siyah 1 ile bağlanmak biraz yumuşaktır. Beyaz 2 ile şeklini tamamlar; yapay zekâya göre siyah biraz kayıptadır.",
'A-1-1-1-6-1': "Siyah 1 ile 2. sıradan atari kayıptır. Beyaz bu değişimden açıkça kazançlı çıkar.",
'A-1-1-1-6-2': "Siyah ısrarla kaçmaya çalışırsa beyaz 2 çok iyi bir hamledir. Siyah kaçtıkça daha kötü duruma düşer.",
'A-1-1-1-6-3': "Siyah kesme noktası yaratmaya çalışır ama beyaz 6 ile rahat oynar. Siyahın şekli verimsizdir.",
'A-1-1-1-6-4': "Siyah 1 ile dönmek çok kötüdür. Beyaz 2 ile daha da güçlenir.",
}
