S = {
'A-1-1-2': "Beyaz 2. sıradan keima ile kayar. Eskiden standarttı, bugün biraz yavaş bulunur. Siyah için en iyisi genellikle başka yere oynamaktır.",
'A-1-1-2-1-1': "Beyaz 1 eskiden standart hamleydi, yapay zekâ biraz yavaş bulur. Siyahın başka yere oynaması iyidir.",
'A-1-1-2-1-2': "Beyaz saldırırsa siyah 2 ile köşeyi korur ve 4 ile rahatça çıkar. Beyazın hamlesi siyaha fazla baskı yapmaz.",
'A-1-1-2-2-1': "Siyah 1 ile 3-3'e kosumi yapmanın değeri azdır. Siyah biraz kayıptadır.",
'A-1-1-2-2-2': "Sağ alt köşe beyazsa beyaz başka yere oynayabilir. Siyah pincer yaparsa beyaz sakin şekilde çıkar. Sonuç eşittir.",
'A-1-1-2-2-3': "Sol üstte siyah taş varsa siyah 1 ile yukarıdan bastırmak da olur. Beyaz 2 ile çıkar; sonuç eşittir.",
'A-1-1-2-2-4': "Siyah 1 küçük bir hatadır. Beyaz 2 ve 4 ile sıkı oynar ve taşlar takas edilir.",
'A-1-1-2-2-5': "Siyah 1 kötü bir şekildir. Beyaz 2 ile sorunu çözer; siyahın başka yere oynaması daha iyidir.",
'A-1-1-2-2-6': "Siyah 1 ile köşeye hane kötüdür. Beyaz 2 ve 4 ile kolayca üstün duruma geçer.",
'A-1-1-2-2-7': "Beyaz 1 ile hane biraz zayıftır. Siyah 2 ve 4 ile iyi karşılık verir.",
'A-1-1-2-3-1': "Siyah 1 ile karşı pincer eskiden popülerdi. Beyaz 2 ile çıkar, 8 ile karşılık verir. Savaş dengelidir.",
'A-1-1-2-3-2': "Siyah 1 ile araya girmek serttir. Sol üst beyazsa beyaz rahat çıkar ve zor bir savaş başlar.",
'A-1-1-2-3-3': "Sol üst siyahsa beyaz 1 ile sakince sıçrar. Sonuç eşittir.",
'A-1-1-2-3-4': "Beyaz 1 biraz yavaştır. Siyah basit oynar ve sonra başka yere geçer.",
'A-1-1-2-3-5': "Beyaz 1 ile çıkmak aşırıdır. Siyah iyi şekil kurar, savaş beyaz için kötüdür.",
'A-1-1-2-3-6': "Merdiven siyah lehineyse siyah 1 de oynanabilir. Beyaz 4 ve 6 iyi hamlelerdir. Sonuç eşittir.",
'A-1-1-2-3-7': "Beyaz 1 eski bir josekidir. Siyah bir taşı merdivenle yakalar; bu beyaz için büyük kayıptır.",
'A-1-1-2-3-8': "Merdiven siyah aleyhineyse siyah 1 ile uzanmak zorundadır. Siyah biraz geride kalır.",
'A-1-1-2-3-9': "Beyaz 1 kötüdür. Siyah bir taşı sararak yakalar ve biraz avantajlı olur.",
'A-1-1-2-3-10': "Beyaz 1 ile atari çok kötüdür. Siyah beyazın şeklini bozar.",
'A-1-1-2-3-11': "Beyaz 1 zorlamadır. Siyah karşılık verir ve köşeyi yiyerek çok kazanır.",
'A-1-1-2-4-1': "Merdiven siyah lehineyse siyah 1 ile yapışma eski bir moda josekidir. Beyaz 2 doğru cevaptır. Sonra beyaz A–C arasından seçer.",
'A-1-1-2-4-2': "Sağ alt beyazsa beyaz 1 iyidir. Siyah köşeye yaklaşır ve taş feda eder; sonuç eşittir.",
'A-1-1-2-4-3': "Siyah 1 uygun değildir. Beyaz rahatça bastırır ve üstün duruma geçer.",
'A-1-1-2-4-4': "Sağ alt siyahsa siyah 1 ile uzanabilir. Beyaz sakince tamamlar; iki taraf için de oynanabilir.",
'A-1-1-2-4-5': "Siyah 1 ile doğrudan dönmek de olur. Önceki diyagramla hemen hemen aynıdır.",
'A-1-1-2-4-6': "Siyah 1 ile kesmek acelecidir. Beyaz 2'den sonra siyah toparlanamaz.",
'A-1-1-2-4-7': "Sağ alt siyahsa beyaz 1 iyi bir hamledir. Beyaz sonra büyük bir bastırma yapar ve iki taşı yakalayıp memnun olur.",
'A-1-1-2-4-8': "Siyah 12 yerine 1'de bağlanırsa beyaz taş feda eder ve iyi bir noktayı alır.",
'A-1-1-2-4-9': "Beyaz 1 serttir. Beyaz yine taş feda edip sente alır, ama önceki diyagramdan biraz geridedir.",
'A-1-1-2-4-10': "Siyah 2 yerine 1'i oynamak uygun değildir. Beyaz rahat atari verir ve savaşı yönetir.",
'A-1-1-2-4-11': "Sağ alt beyazsa beyaz 1 ile önce uzanmak iyidir. Sonuç eşittir.",
'A-1-1-2-4-12': "Beyaz doğrudan büyük bastırma da yapabilir. Siyah sağlam oynar; iki taraf için de oynanabilir.",
'A-1-1-2-4-13': "Merdiven beyaz lehineyse beyaz 1 güçlüdür. Sağ alt siyahsa beyaz çok iyi durumdadır.",
'A-1-1-2-4-14': "Sağ alt beyazsa beyaz büyük bastırma ile saldırır; siyah zorlanır.",
'A-1-1-2-4-15': "Siyah 1 aşırıdır. Beyaz güçlü hamlelerle karşılık verir ve açıkça üstün olur.",
'A-1-1-2-4-16': "Merdiven beyaz aleyhineyse siyah 1'i oynayabilir. Siyah açıkça kazançlıdır.",
'A-1-1-2-4-17': "Beyaz 1 ile kesemez. Siyah atari verip bastırır; beyaz A ve B'yi aynı anda koruyamaz.",
'A-1-1-2-4-18': "Merdiven beyaz aleyhineyse beyaz geri çekilmek zorundadır. Beyaz biraz kayıptadır.",
'A-1-1-2-4-19': "Beyaz 1 biraz yumuşaktır. Siyah taş feda edip beyazı kapatır ve memnun olur.",
'A-1-1-2-4-20': "Beyazın karşı saldırısı iyi değildir. Siyah köşeyi alır ve biraz avantajlı olur.",
'A-1-1-2-4-21': "Siyah 1 biraz zayıftır. Beyaz sente olarak taşı alır. Sonuç eşittir.",
'A-1-1-2-4-22': "Beyaz 1 kötüdür. Siyah kazançlı çıkar ve başka yere oynayabilir.",
'A-1-1-2-5-1': "Siyah 1 ile omuz vuruşu güç almayı amaçlar. Sağ alt siyahsa sonuç eşittir; sağ alt beyazsa siyah için kötüdür.",
'A-1-1-2-5-2': "Sağ alt beyazsa siyah 1 ile uzanmak iyidir. Savaş dengelidir.",
'A-1-1-2-5-3': "Beyaz 1 ile çıkabilir. Sağ alt siyahsa beyaz yerinde yaşar; sonuç eşittir.",
'A-1-1-2-5-4': "Sağ alt beyazsa beyaz 1 sakin bir hamledir, sonra 5 ve 7 ile serttir. Sonuç eşittir.",
'A-1-1-2-5-5': "Beyaz 1 biraz yumuşaktır. Siyah kalın bir şekil kurar.",
'A-1-1-3': "Beyaz kenara açılır. Eskiden doğru sayılırdı, bugün az oynanır. Siyah köşeye yapışabilir ya da beyazın alanına girebilir.",
'A-1-1-3-1-1': "Beyaz 1 ile kenara açılmak eskiden çok oynanırdı. Yapay zekâ önce köşede şekil kurmayı daha verimli bulur; bu yüzden artık nadirdir.",
'A-1-1-3-1-2': "Beyazın 1 ile köşeye yapışması her zaman büyük bir hamledir.",
'A-1-1-3-2-1': "Merdiven siyah lehineyse ve sağ alt beyazsa siyah 1 ile içeri girer. Bir ko savaşı çıkar; iki taraf da bir şey kazanır.",
'A-1-1-3-2-2': "Beyaz 10 yerine hemen ko başlatırsa uygun değildir. Siyahın taşları daha rahattır.",
'A-1-1-3-2-3': "Merdiven siyah aleyhineyse beyaz 1 ile bağlanması yeterlidir. Beyaz iyi durumdadır.",
'A-1-1-3-2-4': "Beyaz 1 biraz gevşektir. Siyah beyazın alanında rahatça yaşar.",
'A-1-1-3-2-5': "Beyaz 1 ile taş feda etmek kötüdür. Siyah büyük alan kazanır.",
'A-1-1-3-2-6': "Sağ alt siyahsa beyaz 1 ile geri çekilmek yeterlidir. Beyaz iyi bir noktayı alır.",
'A-1-1-3-3-1': "Siyahın × taşı varsa siyah 1 ile yüksekten girmek iyidir. Zor bir savaş başlar.",
'A-1-1-3-3-2': "Siyah 1 ve 3 acelecidir. Beyaz iyi sırayla oynar ve temposu hızlıdır.",
'A-1-1-3-3-3': "Beyaz 1 ve 3 aşırıdır. Siyah 8'den sonra savaşta siyah daha rahattır.",
}
