# code: (title, rating, text)   rating: best | ok | bad | situational
T = {
'A-1-1': ("Başlangıç pozisyonu", 'best',
 "Siyah 1 ile keima cevabı tartışmasız doğru hamledir; insanlar ve yapay zekâ burada hemfikir. Beyaz için çoğu durumda en iyi cevap A noktasına tsuke (köşeye yapışma) yapmaktır. İnsan oyuncular eskiden B'deki keima kaymasını ve C'deki kenara açılmayı çok severdi, ancak yapay zekâ bunları biraz gevşek bulur. D'deki 3-3 işgali yön değiştirmeyi amaçlar; E'deki yandan yapışma, yakında bir pincer taşı varken iyi bir sabaki hamlesidir; F'deki ōgeima ise tuzak kokan bir hamledir. Bu üçü duruma bağlı hamlelerdir. Ayrıca sağ alt köşe beyazsa, beyazın tenuki yapması da çok yaygındır."),
'A-1-1-1': ("Beyaz tsuke + çift hane", 'best',
 "Beyaz 1 ve 3 ile önce yapışıp sonra art arda hane yapar; sıkı ve güçlü bir şekildir, siyahı hemen şeklini belirlemeye zorlar. Siyah için A'daki atari normal hamledir; B'deki ters kaplan ağzı ve C'deki sagari yapay zekânın yeni fikirleridir. D'deki çift hane ve E'deki bağlanma geleneksel hamlelerdir; F'deki 2. sırada atari genellikle iyi değildir."),
# ---- 1-1 Atari
'A-1-1-1-1-1': ("Siyah 3–5 ile sente dış güç", 'best',
 "Bu şekil günümüzün en popüler varyasyonlarından biridir. Siyah 3 ve 5 ile sente olarak dışarıda güç kurar; beyaz ise belli bir alan kazanır. Sonuç yaklaşık eşittir."),
'A-1-1-1-1-2': ("Siyah sagari, beyaz yapışır", 'ok',
 "Siyah 1 ile sagari alana önem verir; beyaz 2 ile yapışarak siyahın nefeslerinin az olması zaafını vurgular. Merdiven (shicho) siyah lehineyse siyah 3'teki nokta sert bir hamledir. Beyazın 4 ve 6 ile sade şekilde oynaması bir yoldur; ileride siyah duruma göre A–C noktalarından birini seçebilir. Her iki taraf için de oynanabilir."),
'A-1-1-1-1-3': ("Siyah 1 erken sagari", 'bad',
 "Siyah 1'i doğrudan buraya oynarsa, beyaz 2'nin bir aralık açılmasıyla yapılan değişim siyah için biraz kayıptır. Bu durumda siyah artık A noktasına giremez; beyaz tabii ki B'de engeller."),
'A-1-1-1-1-4': ("Beyazın iki sıçraması (AlphaGo)", 'ok',
 "Beyaz 1 ve 3'ün iki sıçraması çok serttir; bu şekil ilk kez Ke Jie – AlphaGo maçının 2. oyununda görüldü. Beyaz 5 ve 7 gereklidir; ancak bu sayede beyaz 9 işe yarar. Burada yerel çatışma bir sona erer. İleride siyah A ve B'de fırsat arayabilir. Devamı çok zengin olan, tipik bir yapay zekâ tarzı eşit josekidir."),
'A-1-1-1-1-5': ("Siyah 1 dört taşı yakalar (gote)", 'bad',
 "Siyah 1 ile keserek dört taşı yakalamak yaklaşık 20 puanlık gote bir yose hamlesidir. Açılışta bu tempo çok yavaştır; beyaz 2 ve 4 ile sente güç kurar. Siyah kazandığından fazlasını kaybeder."),
'A-1-1-1-1-6': ("Siyah 1 taşı alır – kötü", 'bad',
 "Siyah 1 ile taşı almak kötüdür; beyaz 2'nin atarisi çok rahattır. Ardından beyaz 6 keima iyi bir hamledir. 8 ve 11 noktalarından biri mutlaka alınacağı için siyah 7'de doğrudan taşı alabilir. Beyaz 16 ile sıkıştırmak çok serttir; siyahın sol alt köşesi hâlâ tam yaşamış değildir ve siyah zor bir mücadeleye girer."),
'A-1-1-1-1-7': ("Beyaz sırayı karıştırır", 'bad',
 "Beyaz 1 ile önce uzanmak yanlış sıralamadır. Siyah 2 ile ittiğinde beyaz 3 ile kesmek artık sente değildir. Siyah 6'daki kaplan ağzı güçlüdür; beyazın dışarıdaki kaybı çok büyüktür."),
'A-1-1-1-1-8': ("Beyaz keser ve hane yapar", 'situational',
 "Beyaz 1 ile kesip 3 ile hane yapmak güçlü bir hamledir; burada merdiven (shicho) meselesi devreye girer. Merdiven siyah lehineyse siyah 6 ile bastırarak dışarı çıkmak serttir. Beyaz 7'deki hane acil durum için iyi bir hamledir. Siyah 8'de seçim yapmalıdır: sol üst köşe beyazsa, siyah 8 ve 10 ile basitçe bağlanıp uzanmak iyidir; sonuç yaklaşık eşittir."),
'A-1-1-1-1-9': ("Siyah 10 yerine ittir-yakala (takas)", 'ok',
 "Önceki diyagramda siyah 10'u 1'e oynayıp iterek yakalarsa bir takas oluşur. Beyaz 4 ile önce kafa atmak incelikli bir hamledir; ardından beyaz 8'deki nokta güçlüdür. Karşılıklı saldırıda beyaz biraz üstündür."),
'A-1-1-1-1-10': ("Sol üst siyahsa: siyah 1 döner", 'situational',
 "Sol üst köşe siyahsa, siyah 1 ile dönmek güçlüdür. Ardından siyah 3 ve sonrası ile itip taşları feda ederek tek hamlede dışarı çıkar; siyahın dış gücü çok canlıdır."),
'A-1-1-1-1-11': ("Merdiven kötüyse siyah tenuki", 'situational',
 "Merdiven siyah aleyhineyse, beyaz 1 ile uzandığında siyah tenuki yapmak zorunda kalır. İleride beyazın A'da uzanarak tamamlaması çok büyüktür; siyah bu durumdan biraz memnun değildir."),
'A-1-1-1-1-12': ("× merdiven kırıcı varken aşırı", 'bad',
 "Sağ üst köşede beyazın × noktasında merdiven kırıcı taşı varsa, siyah 1 ile bastırarak çıkmak aşırıdır. Beyaz 2 ve 4 ile takip etmek yeterlidir; siyah 5 ve sonrasıyla ısrarla dışarı çıkmaya çalışırsa çöker."),
'A-1-1-1-1-13': ("Merdiven kötüyse siyah hemen sıkıştırır", 'best',
 "Bu yüzden merdiven siyah aleyhineyse, siyah 1 ile doğrudan sıkıştırmak iyidir. Beyaz 2'deki kaplan ağzı sağlamdır. İleride siyahın A'daki ōgeimasi iyi bir noktadır. Sonuç yaklaşık eşittir."),
'A-1-1-1-1-14': ("Beyaz omuz vuruşu + karşı pincer", 'ok',
 "Beyaz 1 ile omuz vuruşu çok aktiftir; ardından beyaz 7'deki karşı pincer karşılıklı bir saldırı yaratır. Her iki taraf için de oynanabilir."),
'A-1-1-1-1-15': ("Beyaz güvenli açılır", 'ok',
 "Beyaz 1 ile bir aralık açılmak barışçıl bir seçimdir. Yerel olarak biraz kayıp olsa da büyük ve karmaşık varyasyonlardan kaçınır; sağlam bir stratejidir."),
'A-1-1-1-1-16': ("Beyaz köşeyi yer – genelde kötü", 'bad',
 "Beyaz 1 ile köşeyi yemek genellikle iyi değildir. Siyah 2 ile aşağı itmek çok büyüktür; beyaz 3 ile sakince taşı alır. Siyah biraz üstündür."),
'A-1-1-1-1-17': ("Beyaz 1 kafa atar – kaba hamle", 'bad',
 "Beyaz 1 ile kafa atmak kaba bir hamle (zokusuji) hissi verir. İleride siyahın A–C noktalarında sente kullanımları olur; siyahın dış gücü çok sağlamdır."),
'A-1-1-1-1-18': ("Siyah 1-3-5 sıkı şekil", 'ok',
 "Siyah 1, 3 ve 5 ile sıkı biçimde şekil belirlemek de bir yoldur. Beyaz 8 ile önce iterek kesme noktası yaratır, ardından beyaz 14 ile kesip savaşır. Siyah biraz daha inisiyatif sahibidir."),
'A-1-1-1-1-19': ("Siyah 1 osae – daha zayıf", 'bad',
 "Siyah 1 ile engellemek genellikle önceki iki diyagramdan daha zayıftır. Siyah 5 ile tamamlamak gereklidir; aksi halde beyazın A'daki kesmesi çok serttir."),
'A-1-1-1-1-20': ("Eski yol: taş feda edip güç almak", 'bad',
 "Eskiden siyah 1 ve sonrasıyla taş feda edip güç almak yaygındı. Bu diyagramda siyah sente alsa da dış gücünde hâlâ zayıflık vardır; yapay zekâ siyahı biraz kayıplı görür."),
'A-1-1-1-1-21': ("Siyah doğrudan iter – eski joseki", 'ok',
 "Siyah 1 ile doğrudan aşağı itmek de mümkündür; bu eski bir josekidir. Eskiden siyahın dış gücünün çok canlı olduğu düşünülürdü; ancak yapay zekâya göre beyazın A'dan hemen bağlanarak çıkması çok güçlüdür ve zor bir savaş başlar."),
'A-1-1-1-1-22': ("Beyaz bağlanıp çıkar", 'ok',
 "Beyaz 1 ile bağlanarak dışarı çıkmak serttir. Siyah 2 ile yapışmak bir yoldur; beyaz 7'deki dürtme (nozoki) bu şeklin can alıcı hamlesidir. Beyaz 11 ile hane yaptığında siyah bir seçim yapmak zorundadır."),
'A-1-1-1-1-23': ("Siyah keser ve feda eder", 'best',
 "Siyah 1 ile kesip taşları feda etmek iyidir. Sonrasında beyaz gote olarak üç taşı yakalar; sonuç her iki taraf için kabul edilebilir."),
'A-1-1-1-1-24': ("Siyah 'anahtar taşları' yakalayamaz", 'bad',
 "Siyah 1 ve 3 ile beyazın üç 'anahtar taşını' yakalamayı düşünmemelidir. Beyaz 2 ve 4 ile esnekçe yön değiştirir; bu hem basit hem avantajlıdır. Şimdi beyaz A ile siyah B arasındaki değişimin inceliği ortaya çıkar: beyaz neredeyse bedavaya siyahın kalın duvarına bir kama çakmıştır."),
'A-1-1-1-1-25': ("Siyah yumuşak kosumi", 'ok',
 "Siyah 1'deki küçük kosumi yumuşak bir hamledir; ardından siyah 3'teki kosumi-tsuke sıkıdır. Beyaz 4 ile sıkıştırmak zorunludur; siyah 5 ile bağlanıp doğal şekilde şeklini düzeltir. Beyaz 6 ve sonrasıyla rahat yol alır; siyah 11 ve 13 ile hafif baskı kurar. Her iki taraf için de oynanabilir."),
'A-1-1-1-1-26': ("Siyah 4. sıradan atari", 'ok',
 "Siyah 1 ile 4. sıradan atari de bir hamledir. Beyaz 2 ile hemen uzanmalıdır; ardından zor bir karşılıklı saldırı savaşı oluşur."),
'A-1-1-1-1-27': ("Beyaz hemen çıkmazsa", 'best',
 "Beyaz hemen dışarı çıkmazsa, siyah 1'deki fil adımı (zō) ile rahatça tamamlar; beyaz biraz memnun değildir."),
'A-1-1-1-1-28': ("Beyaz önce bağlanır", 'ok',
 "Beyaz 1 ile önce bağlanarak A-1-1-1-1-26 varyasyonundan kaçınabilir; siyah 2 ile hane yaparsa A-1-1-1-1-22 varyasyonuna geri dönülür."),
'A-1-1-1-1-29': ("× taşı varken itme çalışmaz", 'bad',
 "Dikkat: beyazın × noktasında taşı varken siyah 1 ile aşağı itmek çalışmaz; yerel nefes yarışında (semeai) siyah bir nefes geride kalır."),
'A-1-1-1-1-30': ("Beyaz doğrudan köşeyi yer – zayıf", 'bad',
 "Beyaz 1 ile doğrudan köşeyi yemek zayıftır; siyah 2 ile bağlanırsa A-1-1-1-1-16 varyasyonuna geri dönülür."),
'A-1-1-1-1-31': ("Siyah kaplan ağzı", 'ok',
 "Siyah 1 ile kaplan ağzı yapmak da mümkündür; beyaz 2 ile atari verip geçerse A-1-1-1-1-1 varyasyonuna geri dönülür."),
'A-1-1-1-1-32': ("Beyaz köşeyi yiyerek karşı saldırı – şüpheli", 'bad',
 "Beyaz 1 ile köşeyi yiyerek karşı saldırmak şüphelidir; siyah 4 ile sararak yakalamak kalındır. İleride ko tehditleri siyah lehine olursa, siyahın A'daki atarisi beyazı çıkmaza sokar."),
}
