T = {
# ---- 1-2 ters kaplan ağzı
'A-1-1-1-2-1': ("Ters kaplan ağzı (AI imzası)", 'best',
 "Siyah 1'deki ters kaplan ağzı yapay zekânın imza hamlelerinden biridir; eski oyun kayıtlarında hiç görülmemiştir. Siyah 3 ile kafa çıkarmak önemlidir; beyaz 4 ile yapışarak yükselmek çok büyüktür. İki taraf için de oynanabilir. Sağ tarafta destek varsa beyaz 4 yerine A'da ōgeima da oynayabilir. A-1-1-1-1-2 varyasyonuyla karşılaştırıldığında siyah 1, B'deki sagari kadar puan getirmez; ancak C'de bir atari eksik olduğu için siyahın nefes zaafı da yoktur. Artısı ve eksisi dengelidir."),
'A-1-1-1-2-2': ("Beyaz tenuki yapabilir", 'ok',
 "Beyazın tenuki yapması da oynanabilir. Siyah 1 ile sıkıştırmak iyi bir noktadır; beyaz 2 ve 4 ile yerinde yaşamak bir yoldur."),
'A-1-1-1-2-3': ("Beyaz yapışarak karşı saldırır", 'ok',
 "Beyaz 1 ile yapışıp dışarı çıkarak karşı saldırmak da mümkündür; siyah 2'deki kosumi can alıcı noktadır. Beyaz 5 ile kosumi yapıp çıktıktan sonra siyahın takibi sürdürmesi zordur."),
'A-1-1-1-2-4': ("Siyahın dümdüz saldırısı işe yaramaz", 'bad',
 "Siyah 1 ve sonrasıyla dümdüz saldırmak doğru değildir; beyaz 6 ve 8'deki iki yapışma iyi hamlelerdir ve siyah bir şey kazanamaz. Siyah 7'yi A'da hane olarak oynarsa, beyazın B'deki kesmesiyle işler daha da zorlaşır."),
'A-1-1-1-2-5': ("Siyah tenuki – uygun değil", 'bad',
 "Siyahın tenuki yapması uygun değildir; beyaz 1'deki kaplan ağzı sente niteliğindedir. İki tarafın kalınlık dengesi A-1-1-1-2-1'den çok farklıdır."),
# ---- 1-3 sagari
'A-1-1-1-3-1': ("Siyah sagari – AI'ya göre eşit", 'best',
 "Siyah 1 ile sagari alana önem verir. İnsan oyuncular sezgisel olarak biraz kayıp sanıyordu, ancak yapay zekâ bunu da eşit görür. Beyaz 2'deki kaplan ağzı siyahın başının yumuşaklığını vurgular; siyah 5 ile mutlaka köşeyi yemelidir. Önceki varyasyonlara göre siyah en çok puanı burada alır, ama merkezdeki gelişimi feda eder."),
'A-1-1-1-3-2': ("Beyaz atari – şüpheli", 'bad',
 "Beyaz 1 ile atari şüphelidir; siyah 2 ile keima yükselmek iyi bir noktadır. Siyah köşe tamamen yaşadığı için beyazın A'dan itmeye devam etmesi siyaha hiçbir tehdit oluşturmaz; tersine beyaz kendi taşlarını ağırlaştırır."),
'A-1-1-1-3-3': ("Siyah uzanır – kötü", 'bad',
 "Siyah 1 ile uzanmak kötüdür; beyaz 2 ile süründükten sonra iki tarafın kalınlığı bir anda tersine döner. Sadece köşedeki puana bakılsa bile A-1-1-1-3-1'e göre 10 puandan fazla fark vardır."),
'A-1-1-1-3-4': ("Beyaz kaplan ağzı – kötü", 'bad',
 "Beyaz 1'deki kaplan ağzı kötüdür; siyahın A'daki taşının yeri, A-1-1-1-2-1'deki B noktasından açıkça daha iyidir. Siyah C ile beyaz D değişimi yapılmadığı için siyahın nefes sorunu da yoktur; siyahın merkeze bakan başı A-1-1-1-1-2'dekinden daha sağlamdır."),
# ---- 1-4 çift hane
'A-1-1-1-4-1': ("Siyah çift hane – geleneksel", 'situational',
 "Siyah 1 ile çift hane geleneksel hamlelerden biridir. Beyaz 2 ve sonrasıyla hafif oynar; normal durumda siyah biraz kayıptadır. Ancak A civarında siyah taş varsa bu diyagram da oynanabilir."),
'A-1-1-1-4-2': ("Beyaz basitçe bağlanır", 'ok',
 "Beyaz 1 ile bağlanıp şekli sade biçimde belirlemek de beyaz için biraz daha iyidir."),
'A-1-1-1-4-3': ("Beyaz tenuki", 'ok',
 "Beyazın tenuki yapması da bir yoldur; siyah 1 ve 3 ile köşeyi alarak dolgun bir alan elde eder. Siyahın buraya fazladan bir hamle yatırdığı düşünülürse beyaz için de kabul edilebilir."),
'A-1-1-1-4-4': ("Siyah atari + itme – kötü", 'bad',
 "Siyah 1 ile atari verip 3 ile aşağı itmek kötüdür; beyaz 4 ve sonrasıyla doğal şekilde yön değiştirir. Siyahın üç taşı alması verimsizdir; beyazın × noktasındaki kalan taşı hâlâ canlıdır."),
'A-1-1-1-4-5': ("Beyazın karşı saldırısı aşırı", 'bad',
 "Beyaz 1 ve 3 ile karşı saldırmak aşırıdır; beyaz 5 ile taşları ağa alıp feda etmek zorunda kalır. Beyazın bütünü çok zayıftır."),
# ---- 1-5 bağlanma
'A-1-1-1-5-1': ("Siyah bağlanır – biraz yumuşak", 'bad',
 "Siyah 1 ile bağlanmak biraz yumuşaktır; beyaz 2'deki kaplan ağzıyla şekli tamamlanır. Eskiden insanlar bu şekli tartışırdı; yapay zekâ siyahı biraz kayıplı bulur. Siyah bundan sonra yine A'da uzanırsa, siyah 1 taşı göz açısından B'deki kadar iyi değildir."),
# ---- 1-6 2. sıra atari
'A-1-1-1-6-1': ("2. sırada atari – kayıp", 'bad',
 "Merdiven siyah lehine olsa bile siyah 1 ile 2. sıradan atari biraz kayıptır. Bu diyagram, A-1-1-1-3-2'deki A taşını 4'e taşımak gibidir; beyaz açıkça çok kazanır."),
'A-1-1-1-6-2': ("Siyah ısrarla kaçarsa", 'bad',
 "Siyah 1 ile ısrarla kaçmaya çalışırsa beyaz 2'deki ōgeima harikadır; bu hamle A'daki doğrudan ağdan açıkça daha iyidir. Siyah zararı durdurmak için büyük olasılıkla tenuki yapmalıdır; nasıl çıkmaya çalışırsa çalışsın daha da batar."),
'A-1-1-1-6-3': ("Siyah inatçı ama verimsiz", 'bad',
 "Siyah 1 ve 3 inatla beyaza kesme noktası yaratmaya çalışır. Ancak beyaz 6 ile başa hane vurmak çok rahattır; siyahın şekli verimsizdir."),
'A-1-1-1-6-4': ("Siyah döner – düşünülemez", 'bad',
 "Siyah 1 ile dönmek düşünülemez; beyaz 2'nin çift hanesi çok acıdır ve siyah daha da kötü duruma düşer."),
# ---- 2 keima kayma
'A-1-1-2': ("Beyaz 2. sıradan keima kayar", 'situational',
 "Beyaz 1 ile 2. sıradan keima kayması yapay zekâ öncesinin standart hamlesiydi. Yapay zekâ bunu yeterince sıkı bulmaz; bu yüzden profesyonel oyunlarda giderek azalmıştır. Siyahın cevapları: tenuki (en iyisi), A'da 3-3 kosumi, B'de karşı pincer, C'de yapışma (Kore stili) ve D'de omuz vuruşu."),
'A-1-1-2-1-1': ("Siyah tenuki en iyisi", 'best',
 "Yapay zekâ öncesinde beyaz 1 ile 2. sıradan keima standart hamleydi; ancak yapay zekâ bu hamleyi yeterince sıkı bulmaz, bu nedenle profesyonel oyunlarda giderek azalmıştır. Siyahın bundan sonra tenuki yapması iyidir. Beyazın A'daki 3-3 kosumisi ile siyahın B'deki açılması arasındaki değişim genellikle beyaz için biraz kayıptır."),
'A-1-1-2-1-2': ("Beyaz saldırırsa siyah kolayca çıkar", 'best',
 "Beyaz 1 ile saldırırsa, siyah 2 ile köşede kosumi yapıp savunmak yeterlidir. Beyaz 3 ile sürünmeye devam ederse siyah 4 ile büyük sıçrayışla rahatça dışarı çıkar; beyaz baskıyı sürdüremez. Önceki diyagramla birlikte düşünülürse, siyah A ve 2 noktalarından birini mutlaka alacağı için B'deki 2. sıra keima siyaha yeterli baskı yapmaz, üstelik siyaha daha fazla seçenek bırakır. Bu yüzden yapay zekâ doğrudan C'de sıkı tsuke yapmayı tercih eder; böylece köşe sahibi tenuki yapamaz."),
'A-1-1-2-2-1': ("Siyah 3-3 kosumi – değeri az", 'situational',
 "Siyah 1 ile 3-3 kosumi yapmanın değeri büyük değildir; beyaz 2'nin iki aralık açılmasıyla değişimi genellikle siyah için biraz kayıptır."),
'A-1-1-2-2-2': ("Sağ alt beyazsa beyaz tenuki", 'situational',
 "Sağ alt köşe beyazsa beyazın tenuki yapması aktif bir seçimdir. Siyah 1 ile pincer yaparsa beyaz 2'deki kosumi-tsuke ile şeklini düzeltir. Siyah 3 ile sıçrayıp yavaşça saldırmak en iyisidir; beyaz 4 ile sadece sıçrayarak çıkar. İki taraf için de kabul edilebilir. Ancak sağ alt siyahsa bu diyagram beyaz için kötüdür. Bu diyagramlardan anlaşılıyor ki buradaki 3-3 kosumi iki taraf için de yeterince büyük değildir."),
'A-1-1-2-2-3': ("Sol üstte destek varsa çapraz bastırma", 'situational',
 "Sol üstte destek varsa siyah 1 ile çapraz bastırma (boshi) da bir yoldur. Beyaz 2 ile küçük kosumi yaparak kafa çıkarmak sıkı bir hamledir; sonuç yaklaşık eşittir."),
'A-1-1-2-2-4': ("Siyah küçük sıçrayış – uygun değil", 'bad',
 "Siyah 1 ile küçük sıçrayış biraz uygunsuzdur; beyaz 2 ve 4 sıkıdır ve siyah 5 ile bir takas oluşur. Beyaz 12 ile sürünmek hem puan hem göz alanı için önemlidir. Bundan sonra siyah tenuki yapabilir ya da A'da köşeye hane yaparak beyazın B'ye girme imkânını ortadan kaldırabilir."),
'A-1-1-2-2-5': ("Siyah topak şekil – kötü", 'bad',
 "Siyah 1 ile topak (dango) şekil yapmak kötüdür; beyaz 2 ile köşeye sürünerek sorunu çözer. Siyahın 3. hamlede tenuki yapması iyidir; beyaz 4 ile sente olarak şeklini tamamlar."),
'A-1-1-2-2-6': ("Siyah köşeye hane – kötü", 'bad',
 "Siyah 1 ile köşeye hane kötüdür; beyaz 2'deki topak hamle can alıcı noktadır, ardından beyaz 4 ile keima çıkarak basit ve avantajlı bir sonuç alır. Bu, önceki diyagramda siyahın tenuki yerine değeri düşük siyah 1 hanesini oynamasına eşdeğerdir."),
'A-1-1-2-2-7': ("Beyaz hane – biraz zayıf", 'bad',
 "Beyaz 1 ile hane biraz zayıftır; siyah 2 ve 4 ile çok zekice karşı saldırır. Beyaz 5 ile aşağı ittikten sonra bir takas oluşur; beyaz önceki diyagrama göre biraz geridedir."),
}
