T = {
# ---- 2-3 karşı pincer
'A-1-1-2-3-1': ("Siyah karşı pincer", 'ok',
 "Siyah 1 ile karşı pincer da bir zamanlar popüler bir hamleydi; yapay zekâ beyazın 2 ile sıçrayıp çıkmasını iyi bulur. Beyaz 4 ile omuz vuruşu yaparak kendini güçlendirir, ardından beyaz 8'deki karşı pincer aktiftir; savaş dengelidir."),
'A-1-1-2-3-2': ("Siyah deler – sol üst beyazsa", 'situational',
 "Siyah 1 ile delerek çıkmak serttir. Sol üst köşe beyazsa beyaz 2 ve 4 ile itip sonra sıçramak mümkündür; ardından beyaz 6 ile aşağı hane çok büyüktür. Siyah 7 ve sonrasıyla şiddetli saldırıya geçer; savaş çok zordur."),
'A-1-1-2-3-3': ("Sol üst siyahsa beyaz sakince sıçrar", 'situational',
 "Sol üst köşe siyahsa beyaz 1 ile tek başına sıçramak sakin bir hamledir. Ardından iki taraf kendi işine bakar; sonuç yaklaşık eşittir."),
'A-1-1-2-3-4': ("Beyaz 3-3 kosumi – yavaş", 'bad',
 "Beyaz 1 ile 3-3 kosumi biraz yavaştır; siyah 2 ile basitçe yapışır, beyaz 3 ile sağlamca geri çekilir. Siyahın tenuki yapması iyidir."),
'A-1-1-2-3-5': ("Beyaz hane ile çıkar – aşırı", 'bad',
 "Beyaz 1 ile hane yapıp çıkmak biraz aşırıdır; siyah 6 ve 8 iyi şekillerdir ve savaş beyaz için kötüdür."),
'A-1-1-2-3-6': ("Merdiven iyiyse siyah kosumi-tsuke", 'situational',
 "Merdiven siyah lehineyse siyah 1 ile kosumi-tsuke de mümkündür. Beyaz 4 ile kafa atmak yapay zekânın getirdiği yeni bir fikirdir; ardından beyaz 6 ile girmek iyi bir sıralamadır ve siyah karşı saldıramaz. İleride siyah beyaz 8 taşını alsa bile A'daki kesme noktası bir yük olarak kalır. Sonuç yaklaşık eşittir."),
'A-1-1-2-3-7': ("Beyaz hane – eski joseki, merdiven kaybı", 'bad',
 "Beyaz 1 ile hane yaparak çıkmak eski bir josekidir; yapay zekâya göre siyah 2 ve 4 ile bir taşı merdivenle yakalaması beyaz için büyük kayıptır. Beyaz 5 ile tenuki yaparak merdiven kırıcı arar; siyah 6'daki ōgeima ile merdiveni tamamlamak iyi bir hamledir ve A'daki keimadan biraz daha iyidir."),
'A-1-1-2-3-8': ("Merdiven kötüyse siyah uzanır", 'situational',
 "Merdiven siyah aleyhineyse siyah 1 ile uzanmak zorundadır; ileride beyazın çok fazla kullanımı (kikashi) olur ve siyah biraz memnun değildir."),
'A-1-1-2-3-9': ("Beyaz sıkıştırır – kötü", 'bad',
 "Beyaz 1 ile sıkıştırmak kötüdür; siyah 2 ve 4 ile bir taşı sararak yakalaması yeterlidir. Beyaz 5 ile yapışma yerel olarak en güçlü hamledir; siyah 6 ile itip çıkmak güçlüdür ve siyah 12 ile sıçrayarak tamamlamak doğru şekildir. Siyah biraz avantajlıdır."),
'A-1-1-2-3-10': ("Beyaz atari – çok kötü", 'bad',
 "Beyaz 1 ile atari çok kötüdür; siyah 4 ve 6 ile beyazın şeklini bozar. Beyaz 7 ile keima çıkmak zorunda kalır; siyah 8'deki küçük kosumi yine iyi bir hamledir ve beyazın taş verimliliği çok düşüktür."),
'A-1-1-2-3-11': ("Beyaz kosumi – zorlama", 'bad',
 "Beyaz 1 ile kosumi çok zorlamadır; siyah 2 ve sonrasıyla doğrudan karşılık verir. Siyah 12 ile ağ kurmak keskindir; beyaz 13 ve 15 ile katlanmak zorundadır. Siyah 16 ile keima ile girmek sıkıdır; ardından siyah köşeyi yiyerek çok büyük kazanç elde eder."),
# ---- 2-4 Kore stili yapışma
'A-1-1-2-4-1': ("Kore stili yapışma josekisi", 'situational',
 "Merdiven siyah lehineyse siyah 1 ile yapışma bir zamanlar çok moda olan 'Kore stili' josekidir. Beyaz 2 ile yukarı hane doğru hamledir; diğer hamlelerin biraz kayıp olduğu çoktan kabul edilmiştir. Siyah 3 ile uzandıktan sonra beyaz A–C arasında seçim yapar; bu seçim çevredeki taşlara ve merdivene sıkı sıkıya bağlıdır."),
'A-1-1-2-4-2': ("Sağ alt beyazsa beyaz sagari", 'situational',
 "Sağ alt köşe beyazsa beyaz 1 ile sagari iyidir. Siyah 2 ile doğrudan köşeye kakari yapmak esnektir, ardından siyah 4 ile başa hane vurup taşları feda eder; sonuç yaklaşık eşittir."),
'A-1-1-2-4-3': ("Siyah 3-3 kosumi – uygun değil", 'bad',
 "Siyah 1 ile 3-3 kosumi uygun değildir; beyaz 2 ve 4 ile art arda bastırmak çok rahattır, ardından beyaz 8 ve 10 ile tempolu oynar. Beyaz inisiyatifi tamamen elinde tutar."),
'A-1-1-2-4-4': ("Sağ alt siyahsa siyah uzanır", 'situational',
 "Ama sağ alt köşe siyahsa siyah 1 ile uzanabilir; beyaz 2 ile kaplan ağzı yapıp sakince tamamlar. Siyah 3 ile başa dönmek güçlüdür; iki taraf için de oynanabilir."),
'A-1-1-2-4-5': ("Siyah doğrudan döner", 'ok',
 "Siyah 1 ile doğrudan dönmek de bir yoldur; beyaz 2 ile köşede kosumi yaparak sakin kalır. Önceki diyagramla aralarında belirgin bir fark yoktur."),
'A-1-1-2-4-6': ("Siyah acele keser", 'bad',
 "Siyah 1 ile kesmek acelecidir; beyaz 2 ile atari verip çıktıktan sonra siyah durumu toparlayamaz."),
'A-1-1-2-4-7': ("Sağ alt siyahsa beyaz bağlanır", 'situational',
 "Sağ alt köşe siyahsa beyaz 1 ile bağlanmak iyi bir hamledir. Beyaz 3 ile omuz vuruşu yaparak hazırlık yapar, ardından beyaz 5 ile büyük bastırma (ōboshi) güçlüdür. Siyah 6 ile tsuke en güçlü cevaptır; beyaz 7 ile sakince uzanır ve 9 ile iki taşı yakalayarak memnun olur."),
'A-1-1-2-4-8': ("Siyah 12 yerine bağlanırsa", 'ok',
 "Önceki diyagramda siyah 12'yi 1'de bağlanarak oynarsa, beyaz 2 ve sonrasıyla taş feda etmek güçlüdür. Beyaz 12 ile sıçrayarak iyi bir nokta alır; bütün oyunu çok canlıdır."),
'A-1-1-2-4-9': ("Beyaz sert hane", 'ok',
 "Beyaz 1 ile aşağı hane serttir; siyah 2 ile çapraz kesme (kiri-chigai) kaçınılmazdır. Beyaz yine taş feda edip sente alır; sonuç önceki diyagrama göre biraz geridedir."),
'A-1-1-2-4-10': ("Siyah 2 yerine kaplan ağzı – uygun değil", 'bad',
 "Önceki diyagramda siyah 2'yi 1'de kaplan ağzı ile çıkarak oynarsa uygun değildir. Beyaz 2 ile sente atari çok rahattır, ardından beyaz 4'teki kaplan ağzı iyi şekildir; savaşta inisiyatif beyazdadır."),
'A-1-1-2-4-11': ("Sağ alt beyazsa beyaz önce uzanır", 'situational',
 "Sağ alt köşe beyazsa beyaz 1 ile önce uzanmak iyidir. Siyah 2 ile bir aralık açılmak sakin bir hamledir; beyaz 3 ile aşağı dönmek güçlüdür. Sonuç yaklaşık eşittir."),
'A-1-1-2-4-12': ("Beyaz doğrudan büyük bastırma", 'ok',
 "Beyaz 1 ile doğrudan büyük bastırma da yapılabilir; siyah 2 ve 4 ile kosumi yapıp kaplan ağzı kurmak kaba ama güçlüdür. Beyaz 7 ve 9 ile sol alta saldırıyı çevirir; iki taraf için de oynanabilir."),
'A-1-1-2-4-13': ("Merdiven iyiyse beyaz bastırır", 'situational',
 "Merdiven beyaz lehineyse beyaz 1 ile bastırmak çok güçlüdür; siyah 2 ile uzanmak zorundadır. Sağ alt siyahsa beyaz 5 ile sıçrayıp bastırmak aktiftir; siyah 6 ve 8 ile katlanmak zorundadır ve beyaz çok canlıdır."),
'A-1-1-2-4-14': ("Sağ alt beyazsa büyük bastırma", 'situational',
 "Sağ alt köşe beyazsa beyaz 1 ile büyük bastırma aktiftir, ardından beyaz 3 ile sagari yaparak savaşır; siyah da çok zorlanır."),
'A-1-1-2-4-15': ("Siyah hane – aşırı", 'bad',
 "Siyah 1 ile hane aşırıdır; beyaz 2 ile kafa atarak durdurmak güçlüdür. Siyah 5 ile kafa çıkarmak en güçlüsüdür; beyaz 6 ve sonrasıyla güçlü hamleleri art arda sıralar, siyah taşları feda etmek zorunda kalır. Beyaz açıkça avantajlıdır."),
'A-1-1-2-4-16': ("Merdiven beyaz aleyhineyse", 'situational',
 "Merdiven beyaz aleyhineyse, önceki diyagramda siyah 5'i 1'de hane olarak oynayabilir. Beyaz 2 ve 4 zorunludur; siyah açıkça kazançlıdır."),
'A-1-1-2-4-17': ("Beyaz kesemez", 'bad',
 "Beyaz 1 ile kesemez; siyah 2 ve 4 ile atari verip bastırmak çalışır ve beyaz A ile B'yi aynı anda koruyamaz."),
'A-1-1-2-4-18': ("Merdiven kötüyse beyaz geri çekilir", 'situational',
 "Merdiven beyaz aleyhineyse beyaz 1 ile geri çekilmek zorundadır; siyah 6 ile keima ile girmek iyi bir hamledir. Beyaz biraz kayıptadır."),
'A-1-1-2-4-19': ("Beyaz aşağı hane – yumuşak", 'bad',
 "Beyaz 1 ile aşağı hane biraz yumuşaktır; siyah 2 ile keserek taş feda edip beyazı kapatması yeterince memnun edicidir."),
'A-1-1-2-4-20': ("Beyazın karşı saldırısı kötü", 'bad',
 "Merdiven beyaz lehine olsa bile beyaz 1 ve 3 ile karşı saldırmak iyi değildir. Siyah 4 ve 6 ile köşeyi alarak somut kazanç sağlar, ileride merdiven kırıcı kullanımı da vardır; siyah biraz avantajlıdır."),
'A-1-1-2-4-21': ("Siyah çift hane – biraz zayıf", 'ok',
 "Siyah 1 ile çift hane biraz zayıftır; beyaz 2 ve sonrasıyla sente olarak taşı alıp 'çiçek' (ponnuki) şekli kurar. Sonuç yaklaşık eşittir."),
'A-1-1-2-4-22': ("Beyaz tek sagari – kötü", 'bad',
 "Beyaz 1 ile tek başına sagari kötüdür; beyaz A ile siyah B değişimi yapılmadığı için siyah çok hafiflemiştir. Siyah yerel olarak sente kazanç sağlamıştır ve tenuki yapabilir."),
# ---- 2-5 omuz vuruşu
'A-1-1-2-5-1': ("Siyah omuz vuruşu", 'situational',
 "Siyah 1 ile omuz vuruşu güç almayı amaçlar; beyaz 2 ile sürünmek sağlamdır. Sağ alt siyahsa siyah 3 ile geri yapışmak güçlü bir hamledir. Beyaz 4 ile siyah 5 karşı karşıya gelir; ardından oluşan takas yaklaşık eşittir. Dikkat: sağ alt beyazsa bu diyagram siyah için açıkça kayıptır."),
'A-1-1-2-5-2': ("Sağ alt beyazsa siyah uzanır", 'situational',
 "Sağ alt köşe beyazsa siyah 1 ile uzanıp çıkmak iyidir. Beyaz 2 ile dönerek karşı saldırır; siyah 3 ile aşağı dönmek serttir. Savaş dengelidir."),
'A-1-1-2-5-3': ("Beyaz yapışarak çıkar", 'ok',
 "Beyaz 1 ile yapışarak çıkmak da mümkündür; siyah 2 ile engellemek sıkıdır. Sağ alt siyahsa beyaz 3 ve sonrasıyla yerinde yaşaması yeterlidir; sonuç yaklaşık eşittir."),
'A-1-1-2-5-4': ("Sağ alt beyazsa beyaz sagari", 'situational',
 "Sağ alt köşe beyazsa beyaz 1 ile sagari sakin bir hamledir, ardından beyaz 5 ve 7 ile çift hane serttir. Siyah 8 ile çift hane yaparak geri adım atmaz; ardından oluşan takas yaklaşık eşittir."),
'A-1-1-2-5-5': ("Beyaz 3-3 kosumi – yumuşak", 'bad',
 "Beyaz 1 ile 3-3 kosumi biraz yumuşaktır; siyah 2 ile dönerek kalın bir şekil kurar ve beyaz biraz memnun değildir."),
# ---- 3 kenara açılma
'A-1-1-3': ("Beyaz kenara açılır", 'situational',
 "Beyaz 1 ile doğrudan kenara açılmak yapay zekâ öncesinde doğru hamlelerden biriydi. Günümüzde yapay zekâ köşede şekli belirleyip taşları kenara ve merkeze doğal biçimde yaymayı daha verimli bulur. Siyahın cevapları: tenuki / köşe tsukesi, A'da alçak içeri girme (uchikomi) ve B'de yüksek içeri girme."),
'A-1-1-3-1-1': ("Kenara açılma – artık nadir", 'situational',
 "Yapay zekâ öncesinde beyaz 1 ile doğrudan kenara açılmak doğru hamlelerden biriydi. 'Altın köşe, gümüş kenar, çimen merkez' ilkesine göre kenara açılmanın değeri, köşeyi almaktan hemen sonra geldiği düşünülürdü. Ancak yapay zekâ açılışta köşede şekli belirleyip taşları kenara ve merkeze doğal biçimde yaymanın daha verimli olduğunu düşünür. Bu yüzden günümüz oyunlarında böyle salt kenara açılma çok az görülür."),
'A-1-1-3-1-2': ("Beyaz köşeye tsuke hep büyüktür", 'ok',
 "Bundan sonra beyazın 1 ile köşeye tsuke yapması her zaman çok büyük bir hamledir. Beyazın × taşı olduğu için beyaz 9 ile çift hane iyi bir hamledir ve A'da uzanmaktan biraz daha iyidir."),
'A-1-1-3-2-1': ("Siyah uchikomi – ko savaşı", 'situational',
 "Merdiven siyah lehineyse ve sağ alt beyazsa, siyah 1 ile içeri girmek bu şekilde sık kullanılan bir tekniktir; siyah 9 ile atari kaçınılmazdır. Beyaz 10 ve 12 ile önce ko hazırlar, ardından beyaz 14 ile sert biçimde ko başlatır. Sonrasındaki takasta iki taraf da bir şeyler kazanır."),
'A-1-1-3-2-2': ("Beyaz hemen ko başlatır – uygun değil", 'bad',
 "Önceki diyagramda beyaz 10'u 1'de oynayıp hemen ko başlatırsa uygun değildir. Bu durumda beyaz 3'ün ko tehdidi yeterince sert değildir; siyahın sol taraftaki iki taşının esnekliği önceki diyagrama göre açıkça daha fazladır."),
'A-1-1-3-2-3': ("Merdiven kötüyse beyaz bağlanır", 'situational',
 "Merdiven siyah aleyhineyse beyaz 1 ile bağlanması yeterlidir; siyah 2 ile uzanmak zorundadır. Bundan sonra beyaz ister A'da yapışıp savaşsın ister B'de köşeye keima ile yerleşsin, beyaz iyi durumdadır."),
'A-1-1-3-2-4': ("Beyaz yukarıdan atari – gevşek", 'bad',
 "Beyaz 1 ile yukarıdan atari biraz gevşektir; beyaz 3 ile bağlanmak doğru hamledir. Siyah 4 ve sonrasıyla beyazın alanı içinde rahatça bir grup kurar ve memnundur."),
'A-1-1-3-2-5': ("Beyaz engelleyip feda eder – kötü", 'bad',
 "Beyaz 1 ile engelleyip taş feda etmek doğru değildir; siyah 6 ile yapışarak yükselir ve dolgun bir alan kazanır. Beyaz açıkça kötü durumdadır."),
'A-1-1-3-2-6': ("Sağ alt siyahsa beyaz geri çekilir", 'situational',
 "Ama sağ alt köşe siyahsa beyaz 1 ile sade biçimde geri çekilmek yeterince iyidir. Beyaz 5 ile omuz vuruşu noktasını alır; siyahın taş dizilimi iyi değildir."),
'A-1-1-3-3-1': ("× taşı varken yüksek uchikomi", 'situational',
 "Siyahın × noktasında taşı varsa siyah 1 ile yüksekten içeri girmek iyi bir hamledir; beyaz 2 ile köşeye esnekçe tsuke yapar. Siyah 5 ile sagari serttir; ardından zor bir karşılıklı saldırı savaşı başlar."),
'A-1-1-3-3-2': ("Siyah acele ayırır", 'bad',
 "Siyah 1 ve 3 ile ayırmaya çalışmak biraz acelecidir; beyaz 6 ile önce uzanmak ustaca bir sıralamadır. Beyaz 12 ile omuz vuruşu rahat bir sente kazançtır; beyazın temposu hafif ve hızlıdır."),
'A-1-1-3-3-3': ("Beyaz tsuke-kesme – aşırı", 'bad',
 "Beyaz 1 ve 3 ile tsuke yapıp keserek doğrudan karşılık vermek biraz aşırıdır; siyah 8 ile kafa çıkarmak güçlüdür ve savaşta siyah daha inisiyatiflidir."),
}
