T = {
# ---- 4 3-3 işgali
'A-1-1-4': ("Beyaz 3-3 işgali", 'situational',
 "Beyaz 1 ile 3-3 işgali duruma bağlı bir tekniktir; doğrudan oynanırsa genellikle biraz kayıptır. Siyah burada mutlaka ayırmalıdır: A'da engelleme (osae) veya B'de keima olmak üzere iki seçenek vardır."),
'A-1-1-4-1-1': ("Siyah osae – sade", 'best',
 "Siyah 1 ile engellemek sade bir hamledir; beyaz 10'a kadar iki taraf da hemen hemen böyle oynar. Siyah 11 ile hane bir yoldur; beyaz 12 ile keser ve karışık bir savaş başlar. Beyazın köşesi henüz tam yaşamadığı için siyah iki tarafı da kolayca idare eder; savaşta inisiyatif siyahtadır."),
'A-1-1-4-1-2': ("Siyah sagari", 'ok',
 "Siyah 1 ile sagari de mümkündür; beyaz 2 ile bir kez keser, ardından beyaz 4 ile yaşamak için tamamlaması gerekir. Siyah 5 ve 7 kalındır; bu diyagram da siyah lehinedir."),
'A-1-1-4-1-3': ("Siyah sürünür", 'ok',
 "Beyazın 2. sıradan pincer'ından hoşlanmıyorsa siyah 1 ile sürünmeyi de seçebilir. Siyah 3 ile hane yapıp yükselerek iyi bir şekil kurar; bu da siyah için iyidir."),
'A-1-1-4-1-4': ("Beyaz uzanırsa siyah korkmaz", 'ok',
 "Siyah, beyazın 1 ile uzanmasından korkmaz; siyah × noktasına bir kez süründüğü için beyaz 2. sıradan pincer kullanımını kaybetmiştir ve savaşta zorlanır."),
'A-1-1-4-2-1': ("Siyah keima – AI fikri", 'best',
 "Siyah 1 ile keima yapay zekânın yeni fikridir; beyaz 2 ile sürünüp yaşamak bir yoldur ve siyah açıkça avantajlıdır."),
'A-1-1-4-2-2': ("Beyaz tsuke ile takas arar", 'ok',
 "Beyaz 1 ile tsuke yapıp takas arar; siyah 2 ve 6 ile sağlam oynar. Beyaz 7 ile yapışarak yön değiştirir; siyah sente aldığı için memnundur."),
'A-1-1-4-2-3': ("Siyah hane – şüpheli", 'bad',
 "Siyah 1 ile hane şüphelidir; bu durumda beyazın 2 ve 4 ile itip kesmesi çalışır. Ardından beyaz rahatça dışarı çıkar; siyah önceki diyagram kadar avantajlı değildir."),
'A-1-1-4-2-4': ("Beyaz itip keser – aşırı", 'bad',
 "Beyaz 1 ve 3 ile doğrudan itip kesmek aşırıdır; siyah 4 ile 2. sıradan dönerek nefes yarışı (semeai) başlatır."),
'A-1-1-4-2-5': ("Önceki diyagramın devamı", 'bad',
 "Önceki diyagramın devamı. Beyaz 1 ve 3 ile zorla kapatmak zorundadır; siyah 4 ile keserek önce dışarıda kazanç arar. Ardından siyah 12 ile köşeyi yemeye döner ve çok büyük alan kazanır."),
# ---- 5 yandan yapışma
'A-1-1-5': ("Beyaz yandan yapışma (AI)", 'situational',
 "Beyaz 1 ile yapışma kalıpların dışında bir hamledir ve yapay zekâdan ilham alınmıştır. Bu hamlenin belli bir aldatıcılığı vardır; genellikle çevre boşken beyaz biraz kötü durumdadır. Siyahın dört cevabı vardır: A'daki hane ve B'deki engelleme doğru hamlelerdir. C'deki sagari genellikle siyahın sağ tarafta pincer taşı varken oynanır; D'deki pincer da bir karşı saldırıdır ama neredeyse hiçbir zaman A'dan daha iyi değildir."),
'A-1-1-5-1-1': ("Siyah dış hane", 'best',
 "Siyah 1 ile dışarıdan hane güçlüdür; beyaz 2'deki pincer tutarlı bir fikirdir. Siyah 3 ve 5 ile kazıyıp (warikomi) bağlandıktan sonra siyah 7 ile içeriden kesmek doğru hamledir. Merdiven siyah aleyhine olsa bile siyah 11 ile atari vermek zorundadır; beyaz A'da uzanırsa siyahın B'de kaplan ağzı yapması yeterlidir. Bu diyagram siyah lehinedir."),
'A-1-1-5-1-2': ("Beyaz kaplan ağzı – aşırı", 'bad',
 "Beyaz 1 ile kaplan ağzı biraz aşırıdır; siyah 4 ile süründükten sonra nefes yarışı oluşur. Beyaz 9 ile çift hane iyi bir hamledir ve nefes yarışını kazanmayı garantiler. Ancak beyazın köşede hâlâ nefes doldurması gerekir ve ileride siyahın A'daki sıçrayışı hâlâ sentedir; beyaz kazandığından fazlasını kaybeder."),
'A-1-1-5-1-3': ("Siyah köşeye hane – biraz zayıf", 'bad',
 "Siyah 1 ile köşeye hane biraz zayıftır; beyaz 2 ve 4 ile savaşarak çıkabilir ve karışık bir savaş başlar."),
'A-1-1-5-1-4': ("Siyah geri çekilir – çok yumuşak", 'bad',
 "Siyah 1 ile geri çekilmek çok yumuşaktır; beyaz 2 ve 4 ile dolgun bir şekil kurar."),
'A-1-1-5-1-5': ("Beyaz doğrudan keser – kötü", 'bad',
 "Beyaz 1 ile doğrudan kesmek kötüdür; siyah 2 ile sagari güçlü bir hamledir ve beyaz 3 ile itip çıkmak zorunda kalır. Beyaz 5 ile atari verdiğinde siyahın tenuki yapması yeterlidir; beyazın taşları biraz ağır kalır."),
'A-1-1-5-1-6': ("Beyaz itemez – nefes yetmez", 'bad',
 "Beyaz 1 ile aşağı itmek çalışmaz; köşedeki nefes yarışında beyazın nefesi yetmez."),
'A-1-1-5-2-1': ("Siyah osae – sade", 'best',
 "Siyah 1 ile engellemek sadedir; beyaz 2'deki pincer yine can alıcı noktadır ve siyah 3 ile uzanıp çıkmak kaçınılmazdır. Merdiven beyaz lehineyse beyaz 4 ile köşeye girmek somut kazançtır; ardından beyaz 6 ile geri bağlanıp sente alır. Sonuç iki taraf için de kabul edilebilir."),
'A-1-1-5-2-2': ("Beyaz dışarıda uzanır – kötü", 'bad',
 "Beyaz 1 ile dışarıda uzanmak kötüdür; siyah 2, 4 ve 6 ile tek hamlede işi bitirir ve beyaz karşı saldıramaz. Beyaz 9 ile mutlaka dönmelidir; aksi halde siyahın sente atarisine katlanmak çok zor olur."),
'A-1-1-5-2-3': ("Merdiven iyiyse siyah taşı yakalar", 'situational',
 "Merdiven siyah lehineyse siyah 1 ve sonrasıyla bir taşı merdivenle yakalamak çok büyük kazançtır. Bu diyagram, A-1-1-5-1-1'deki siyah A taşını B'ye taşımak gibidir; böylece beyaz C'deki keima yose tekniğini kaybeder ve puan farkı çok büyür."),
'A-1-1-5-2-4': ("Siyah dışarıdan keser – şüpheli", 'bad',
 "Siyah 1 ile dışarıdan kesmek şüphelidir; beyaz 2 ve 4 ile sente olarak taşı alıp ponnuki yapar ve çok rahattır. Siyahın taşları ağır ve verimsizdir."),
'A-1-1-5-2-5': ("Merdiven kötüyse beyaz bağlanır", 'situational',
 "Merdiven beyaz aleyhineyse beyaz 1 ile sakince bağlanır. Beyaz 3 ile başa dönerek güç biriktirir; siyahın tenuki yapması iyidir. Bu diyagram siyah için biraz avantajlıdır."),
'A-1-1-5-2-6': ("Siyah köşeyi engeller – çok yumuşak", 'bad',
 "Siyah 1 ile köşeyi engellemek çok yumuşaktır; beyaz 2 ile sente kaplan ağzı ve atari çok rahattır. Siyahın temposu çok yavaştır."),
'A-1-1-5-3-1': ("Siyah sagari – duruma bağlı", 'situational',
 "Siyah 1 ile sagari duruma bağlı bir hamledir; genellikle bir pincer desteği gerekir, normal durumda siyah için kötüdür. Beyaz 2 ile hane sıkıdır; siyah 3 ile kesmek bir yoldur ve beyaz 10 ile aşağı dönerek savunma amaçlı saldırır. Siyahın köşesinde hâlâ zayıflık olduğu için beyaza baskıyı sürdüremez; savaş beyaz lehinedir."),
'A-1-1-5-3-2': ("Siyah tenuki", 'ok',
 "Siyahın tenuki yapması da bir yoldur. Beyaz 1 ile keima iyi bir noktadır; siyah büyük olasılıkla yine tenuki yapar, beyaz 3 ve 5 ile itip keserek güç alır ve memnundur."),
'A-1-1-5-3-3': ("Beyaz doğrudan itip keser", 'ok',
 "Beyaz 1 ve 3 ile doğrudan itip kesmek çok serttir; siyah 6 ile keserek atari verip karşı saldırmak zorundadır. Ardından siyah 10 ile sıkıştırmak sıkı bir hamledir, beyaz 15 ile burun vuruşu (hana-zuke) ustaca kaçar; karmaşık bir savaş başlar."),
'A-1-1-5-4-1': ("Siyah pincer", 'ok',
 "Siyah 1 ile pincer da bir hamledir; ardından iki taraf sade oynar ve sonuç yaklaşık eşittir."),
'A-1-1-5-4-2': ("Siyah dışarıdan uzanır – iyi değil", 'bad',
 "Siyah 1 ile dışarıdan uzanmak iyi değildir; beyaz 2 ve 4 ile dolgun bir şekil kurar."),
# ---- 6 ōgeima
'A-1-1-6': ("Beyaz ōgeima (tuzak)", 'situational',
 "Beyaz 1'deki ōgeima (büyük at) tuzak kokan bir hamledir. B'deki küçük keima gibi bu hamle de siyaha fazla baskı yapmaz; bu yüzden siyah için en iyi seçim tenukidir. Yerel olarak oynamak isterse A'daki kosumi-tsuke kayıp vermez; B'deki yapışma ise tuzağa düşme riski taşır."),
'A-1-1-6-1-1': ("Siyah tenuki – en iyisi", 'best',
 "Siyah tenuki yaparsa beyaz için en iyi hamle 1'deki kosumi-tsukedir. Ancak siyah çok esnektir ve yine tenuki yapabilir. Aynı köşe alma olsa da yapay zekâya göre beyazın şekli A-1-1-2-1-1'deki A noktasındaki 3-3 kosumiden biraz daha kötüdür."),
'A-1-1-6-1-2': ("Beyaz pincer yaparsa", 'ok',
 "Beyaz 1 ile pincer yaparsa siyah 2 ile karşı pincer düşünebilir. Beyaz 3 ile kosumi yapınca siyah 4 ile yapışıp hafifçe çıkar. Siyah bu bölgede iki hamle az harcadığı için beyazın bazı taşları kesip almasına izin verebilir."),
'A-1-1-6-2-1': ("Siyah kosumi-tsuke – kayıpsız", 'best',
 "Siyah 1 ile kosumi-tsuke kesinlikle kayıp vermez; beyaz 2 ile sıkıştırmak doğru hamledir ve A-1-1-1 pozisyonuna geri dönülür."),
'A-1-1-6-2-2': ("Siyah güçlüyse beyaz geri kosumi", 'situational',
 "Siyahın çevresi güçlüyse beyaz 1 ile geri kosumi çok esnektir. Siyahın tenuki yapması en iyisidir; ileride beyazın A'daki sıkıştırması çok büyüktür."),
'A-1-1-6-2-3': ("Beyaz geri çekilir – çok yavaş", 'bad',
 "Beyaz 1 ile geri çekilmek çok yavaştır; bu, A'daki sürünme yosesini oynamaya eşdeğerdir."),
'A-1-1-6-3-1': ("Siyah yapışma – yeterince iyi değil", 'bad',
 "Merdiven siyah lehine olsa bile siyah 1 ile yapışma yeterince iyi değildir. Siyah 3 ile dışarıdan atari verip bir taşı merdivenle yakalar ve yerel oyun biter. Bu diyagramda beyaz, A-1-1-5-1-1'deki beyaz A ile siyah B arasındaki kayıplı değişimi yapmadığı için sonuç yaklaşık eşittir."),
'A-1-1-6-3-2': ("Merdiven kötüyse içeriden atari", 'bad',
 "Merdiven siyah aleyhineyse siyah 1 ile içeriden atari vermek zorundadır ve siyahın biraz kayıpta olduğu A-1-1-1-6-1 varyasyonuna geri dönülür."),
'A-1-1-6-3-3': ("Beyaz kosumi – kötü", 'bad',
 "Beyaz 1 ile kosumi kötüdür; siyah 2 ile sente olarak bir kez bağlanıp tenuki yapması yeterlidir. Beyazın şekli zayıftır."),
# ---- 7 beyaz tenuki
'A-1-1-7': ("Beyaz tenuki", 'situational',
 "Beyazın tenuki yapması da çok yaygındır, ancak genellikle sağ alt köşenin beyaz olması gerekir. Sağ alt siyahsa, siyahın pincer'ına karşı beyaz biraz kötü durumdadır. Siyahın yaygın üç cevabı vardır: A ve B'deki pincer'lar ile C'deki kosumi-tsuke."),
'A-1-1-7-1-1': ("Ikken basami", 'best',
 "Siyah 1 ile bir aralık pincer (ikken basami) bir yoldur. Beyaz 2 ve 4 ile tsuke yapıp hane yaptığında siyah 5 ile tek uzanmak iyi bir hamledir. İleride siyahın A'daki kafa atması büyük ölçüde sentedir; beyaz B'de bükülerek yaşamını tamamlamalıdır. Sonuç yaklaşık eşittir."),
'A-1-1-7-1-2': ("Eski yol: atari", 'bad',
 "Eskiden siyah 1 ile atari daha sık oynanırdı; devamı A-1-1-1-1-20 varyasyonuyla aynıdır. Bu diyagramda siyah sente alsa da dış gücü önceki diyagram kadar kalın değildir ve siyah × taşının verimi de yeterince yüksek değildir; siyah memnun olamaz."),
'A-1-1-7-1-3': ("Siyah sert sagari", 'ok',
 "Siyah 1 ile sagari serttir ve beyazın kolayca yerleşmesine izin vermez. Beyaz 2 ve 4 değişiminden sonra beyaz 6 ile karşı pincer aktiftir, ardından beyaz 8 ile hafifçe keima çıkar. İki taraf için de oynanabilir."),
'A-1-1-7-1-4': ("Beyaz ko yapar", 'situational',
 "Uygun ko tehditleri varsa beyazın 1 ile ko yapması da iyidir."),
'A-1-1-7-1-5': ("Siyah çift hane – biraz zayıf", 'bad',
 "Siyah 1 ile çift hane biraz zayıftır; beyaz 4 ile sıkıştırmak varyasyonları saklı tutan iyi bir hamledir. Siyah 5 ile sıçramak hemen hemen böyledir; beyaz 6 ve sonrasıyla sade oynaması yeterlidir."),
'A-1-1-7-1-6': ("Beyaz 2. sıradan keima", 'ok',
 "Beyaz 1 ile 2. sıradan keima da oynayabilir; devamı A-1-1-2-2-2 varyasyonuna geri döner."),
'A-1-1-7-2-1': ("Niken basami", 'best',
 "Siyah 1 ile iki aralık pincer (niken basami) da bir yoldur; beyaz 2 ve sonrası yaygın cevaplardır. Beyaz 10 ile karşı pincer aktiftir, siyah 11 ile keima saldırısı iyi bir noktadır; iki taraf için de oynanabilir."),
'A-1-1-7-2-2': ("Niken basamide ko – dikkat", 'bad',
 "İki aralık pincer'da beyazın 1 ile ko yapması dikkat ister. Bu diyagramda beyaz ko'yu kazansa da kaybetse de A-1-1-7-1-4 varyasyonu kadar avantajlı değildir."),
'A-1-1-7-2-3': ("Siyah çift hane", 'ok',
 "Siyah 1 ile çift hane de bir yoldur; beyaz 2 ile yapışma iyi bir hamledir. Siyah 5 ile sakince köşeyi tamamlar, beyaz 6 ile pincer'dan çıkarak yerinde yerleşir. İki taraf için de kabul edilebilir."),
'A-1-1-7-2-4': ("Siyah hane", 'ok',
 "Siyah 1 ile hane de yapabilir; beyaz 2 ve sonrası kaçınılmaz karşı saldırıdır. Bu diyagram da eşittir."),
'A-1-1-7-2-5': ("Siyah uzanır – biraz yumuşak", 'bad',
 "Siyah 1 ile uzanmak biraz yumuşaktır; beyaz 4 ile yapışarak yükselmek sıkıdır ve beyaz sente olarak yaşayıp memnun olur."),
'A-1-1-7-2-6': ("Beyaz josekiyi körü körüne uygular", 'bad',
 "Beyaz 1, 3 ve 5 ile josekiyi aynen uygulamak iyi değildir; siyahın × pincer taşı tam yerindedir ve savaş siyah için biraz avantajlıdır."),
'A-1-1-7-2-7': ("Siyah atari – biraz zayıf", 'bad',
 "Siyah 1 ile atari biraz zayıftır; beyaz 4 ve 6 doğru seçimdir. Siyahın × taşının konumu yarım kalmıştır ve güçlü saldırıyı sürdürmek zordur. Siyah 9 ile iki aralık açılmak sakin bir hamledir; beyaz biraz daha iyidir."),
'A-1-1-7-2-8': ("Beyaz kaplan ağzı – kötü", 'bad',
 "Beyaz 1 ile kaplan ağzı kötüdür; siyah 2 ile sıçrayıp kapatmak serttir. Beyaz 3 ve 5 ile sente yerleşse de bu çok boyun eğen bir sonuçtur."),
'A-1-1-7-2-9': ("Beyaz aktif yapışma", 'ok',
 "Beyaz 1 ile yapışma aktiftir; siyah 2 ve 4 ile geri adım atmamalıdır. Beyaz 7 ile itip çıkarak savaşır, siyah 8 ile uzanmak serttir. Ardından yerel olarak ko oluşur; ileride beyaz A'ya girerek ko başlatabilir. Pozisyon çok karmaşıktır."),
'A-1-1-7-2-10': ("Siyah bağlanır – sade", 'ok',
 "Siyah 1 ile bağlanmak görece sadedir; beyaz 2 ve 4 tempolu hamlelerdir. Siyah 7 ile sıçradığında beyaz 8 ve sonrasıyla sade bir takas yapar; sonuç yaklaşık eşittir."),
'A-1-1-7-2-11': ("Beyaz içeriden atari", 'ok',
 "Beyaz 1 ile içeriden atari de bir yoldur, ardından beyaz 5 ve 7 ile köşeyi alır; siyah güç, beyaz alan kazanır. İki taraf için de kabul edilebilir."),
'A-1-1-7-2-12': ("Beyaz itip çıkar – aşırı", 'bad',
 "Merdiven beyaz lehine olsa bile beyaz 1 ile itip çıkmak biraz aşırıdır. Siyah 6'dan 18'e kadar köşeyi yemek için ustaca bir sıralama izler ve beyaz karşı saldıramaz. Beyaz 19 ve 21 ile zorlukla saldırıya geçse de beyaz 23 ile geri yapışıp kalınlaşmak zorundadır; savaş beyaz için biraz zordur."),
'A-1-1-7-2-13': ("Siyah kazıyıp bağlanır – kötü", 'bad',
 "Siyah 1 ve 3 ile kazıyıp bağlanmak kötüdür; beyaz 4 ve 6 ile köşeyi alması yeterlidir. A-1-1-5-1-1 varyasyonuyla karşılaştırıldığında siyahın × noktasında fazladan bir taşı vardır ve bu taş son derece gereksiz (üst üste) kalır."),
'A-1-1-7-2-14': ("Siyah engeller – biraz zayıf", 'bad',
 "Siyah 1 ile engellemek de biraz zayıftır; beyaz 2 ve 4 yine aynıdır ve siyah 7 ile dışarıdan kesmek iyidir. Beyaz 12 ve 14 ile aktif şekilde saldırır, ardından beyaz 20 ile tsuke yapıp geçer; beyazın temposu rahattır."),
'A-1-1-7-2-15': ("Siyah içeriden keser – iyi değil", 'bad',
 "Merdiven siyah lehine olsa bile siyah 1 ile içeriden kesmek iyi değildir; siyahın × noktasındaki taşının verimi yine çok düşüktür."),
'A-1-1-7-3-1': ("Siyah kosumi-tsuke + geniş pincer", 'ok',
 "Siyah 1 ile kosumi-tsuke de oynanabilir, ardından siyah 3 ile geniş pincer yaklaşık doğru ölçüdür. Beyaz 4 ile karşı pincer yaparak karşılıklı saldırı başlatır; pozisyon çok zordur."),
'A-1-1-7-3-2': ("Siyah ikken basami – fazla sıkı", 'bad',
 "Siyah 1 ile bir aralık pincer fazla sıkıdır; beyaz 2 ile karşı pincer aktiftir, ardından beyaz 6 ile sagari iyi bir hamledir. Siyah 7 ile kaba kafa atmak zorunda kalır; savaşta beyaz biraz daha inisiyatiflidir."),
}
