# Hoshi + beyaz alttan yapışma (A-3, 托)
T = {
'A-3': ("Başlangıç pozisyonu", 'ok', "Beyaz hoshinin hemen altına yapışır. Bu hamle genelde alt taraf değerliyken oynanır. Siyahın dört cevabı vardır: dıştan hane, içeriden hane, içeriye uzama ve dışarıya uzama."),
'A-3-1-1-1-1': ("Siyah dıştan hane", 'best', "Siyah 1 dıştan hane merkez kurmak içindir; siyah 5 keima iyi noktadır. Beyaz 6'dan itibaren sente ile köşede yaşar, iki taraf da oynanabilir."),
'A-3-1-1-1-2': ("Beyaz itip keser", 'ok', "Beyaz 1 ve 3 ile itip kesmek çok etkindir; siyah 4 ile engelleyip köşeye baskıyı sürdürür. Beyaz köşeden biraz alan bırakır, karşılığında merkezde birçok imkân kazanır; sonuç sonraki savaşa bağlıdır."),
'A-3-1-1-1-3': ("Beyaz tenuki", 'ok', "A-3-1-1-1-1'de beyaz 6 yerine tenuki de yapabilir; o zaman siyah 1 ile aşağı inip köşeyi sıkıştırır. Beyaz 2'den itibaren ikinci sırada sürünerek yaşamak zorundadır ama yerel olarak siyahtan iki hamle az harcadığı için bu da kabul edilebilir."),
'A-3-1-1-1-4': ("Siyah aşağı iner – kötü", 'bad', "Siyah 1 ile aşağı inmek genelde iyi değildir; beyaz 2'den itibaren sade şekilde alan alıp memnun kalır."),
'A-3-1-2-1-1': ("Siyah engellerse", 'bad', "Siyah 1 ile engellerse beyaz 2 hanesi A-2-1-1-1-1 diyagramına döner. O şekil genelde eşittir ama beyaz alt taraf değerli olduğu için alttan yapışmıştı; beyazın değerli tarafı alması siyahı memnun etmez."),
'A-3-1-2-1-2': ("Siyah uzarsa", 'bad', "Siyah 1 ile uzarsa A-2-1-1-2-1 diyagramına döner, siyah biraz memnun değildir. Siyahın gelişme yönü de değeri az olan tarafa döner; beyaz başarılıdır."),
'A-3-2-1-1-1': ("Siyah içeriden hane", 'best', "Siyah 1 içeriden hane alan içindir, siyah 3 bağlantısı kalındır. Sağ alt destekliyse beyaz 4 ile dönmek güçlüdür, siyah 5 hanesi ile iki taraf birbirini çevreler; iki taraf da kabul edebilir."),
'A-3-2-1-1-2': ("Sağ alt siyahken", 'bad', "Sağ alt siyahsa siyah 1 karşı pinceri serttir; siyah 3 büyük zıplama ile baskıyı sürdürür, beyaz biraz sıkışır."),
'A-3-2-1-2-1': ("Beyaz iki boşluklu açılır", 'ok', "Sağ alt siyahsa beyaz 1 ile iki boşluklu açılmak sade ve iyidir. İleride beyazın A'da keimasi güzel bir duruştur, siyahın B'de bastırması da çok değerlidir."),
'A-3-2-2-1-1': ("Siyah aşağı iner", 'ok', "Siyah 1 ile aşağı inmek saldırı niyetlidir; beyaz 2 ile sade açılır, ileride burada iki tarafın da birçok imkânı vardır."),
'A-3-2-2-2-1': ("Beyaz keima", 'ok', "Beyaz 1 keimasi iyi şekildir; siyah 2 de keima ile karşılık verir, iki tarafın şekli de rahattır."),
'A-3-2-2-3-1': ("Beyaz karşılık verir – fazla", 'bad', "Beyaz 1 ile karşılık vermek fazladır; siyah 2 ağı serttir. Beyaz 3 ve 5 ile itip kesmek zorunda kalır, siyah 8 ve 10 ile art arda güçlüce bastırır; beyaz bir seçim yapmak zorundadır."),
'A-3-2-2-3-2': ("Beyaz uzarsa", 'bad', "Beyaz 1 ile uzarsa siyah 2 çift hanesi sıkıdır; alttaki dört beyaz taş hareket edemez, beyaz 3'ten itibaren taş feda eder. Siyah 10 kosumi ile çıktıktan sonra beyazın iyi bir kapatma hamlesi yoktur, alan kaybı çok büyüktür."),
'A-3-2-2-3-3': ("Beyaz hane – çok riskli", 'bad', "Beyaz 1 hanesi çok risklidir; siyah 2 kesmesi serttir, siyah 10 yapışması gözü bozarken 12 pincerini sente yapar. Siyah 18 ile çift hane yapıp taş feda eder, siyah 24 ile niyetini gösterir; beyaz artık kesin yaşayamaz ve savaşta çok geride kalır."),
'A-3-2-3-1-1': ("Siyah bastırır", 'ok', "Siyah 1 ile bastırmak da savaşılabilir; ileride siyah için A ve B büyük hamlelerdir."),
'A-3-2-3-1-2': ("Siyah çift hane", 'ok', "Siyah 1 ile çift hane şekli hemen bitirmek içindir; iki taraf da kabul edebilir."),
'A-3-3-1-1-1': ("Siyah içeriye uzar", 'ok', "Siyah 1 ile içeriye uzarsa beyaz 2 ile köşeye sürünür ve A-2 pozisyonuna döner."),
'A-3-3-2-1-1': ("Beyaz dışarıya uzar", 'ok', "Beyaz 1 ile dışarıya da uzayabilir; siyah 2 ile dönünce A-3-2-1-1-1 diyagramına döner."),
'A-3-4-1-1-1': ("Siyah dışarıya uzar", 'ok', "Siyah 1 ile dışarıya uzarsa beyaz 2 ile 3-3'e uzamak daha iyidir; siyah 3 ile engelleyince A-2-3 diyagramına döner."),
'A-3-4-1-2-1': ("Siyah döner", 'ok', "Siyah 1 ile dönerse A-3-1-1-1-1 diyagramına döner."),
'A-3-4-2-1-1': ("Beyaz dışarı sürünür", 'ok', "Beyaz 1 ile dışarıya da sürünebilir; A-3-2-3-1-1 diyagramına döner."),
}
