# Hoshi + yüksek bir aralık pincer (一间高夹)
T = {
'A-1-4': ("Başlangıç pozisyonu", 'best', "Yüksek bir aralık pincer, altı pincer türü içinde en az oynananıdır. Beyazın seçenekleri: A'da 3-3 işgali, B'de sıçrama, C ve D'de çift kakari, E'de yapışma, F'de çapraz keima ya da tenuki."),
'A-1-4-1-1-1': ("3-3 işgali – en iyi cevap", 'best', "Beyaz 1 en iyi cevaptır. Beyaz 5 ve 7 ile hane yapıp bağlanınca siyahın şekli biraz rahatsız olur; alçak pincerdeki şekilden belirgin şekilde kötüdür."),
'A-1-4-1-1-2': ("Beyazın sonraki iyi noktası", 'ok', "İleride beyaz 1 iyi bir hamledir. Siyah 2 ve 4 ile sabırla cevap vermelidir; beyaz sente kazanç sağlar."),
'A-1-4-1-1-3': ("Beyaz pincer – kötü", 'bad', "Beyaz 1 kötüdür. Siyah 2 ile kaplan ağzı yapınca işaretli siyah taş tam yerinde olur."),
'A-1-4-1-1-4': ("Siyah sürünür – kötü", 'bad', "Siyah 1 kötüdür, sonra siyah iki arada kalır. Tamamlamak verimsizdir; tenuki yaparsa beyaz 4 ile uzanması serttir. Siyah ikiye bölünür ve savaş çok zorlaşır."),
'A-1-4-1-2-1': ("Siyah dıştan kapatır – kötü", 'bad', "Siyah 1 kötüdür. Beyaz 4 kosumi doğru şekildir; siyah 5 ile bastırmak zorunda kalır ve işaretli siyah taş kötü yerde durur."),
'A-1-4-2-1-1': ("Beyaz sıçrar", 'ok', "Beyaz 1, 3-3 işgalinden biraz kötüdür. Siyah 2 ile küçük zıplama bir yoldur. Sağ alt siyahsa beyaz 3 ve 5 ile yerinde yaşar; sonuç eşittir."),
'A-1-4-2-1-2': ("Üç kosumi ile kesme", 'bad', "Siyah 1, 3, 5 ile sert oynayıp işaretli beyaz taşı keser. Ama beyaz 6 ve 8 ile basitçe cevap verir; dışarıdaki üç siyah taş yalnız kalır."),
'A-1-4-2-1-3': ("Ko açmak – genelde kötü", 'bad', "Siyah 1 ve 3 ile ko açmak genelde kötüdür. Çok güçlü ko tehdidi yoksa beyazın A'da koyu bitirmesinin kaybını kaldıramaz."),
'A-1-4-2-1-4': ("Beyaz karşı pincer", 'situational', "Sağ alt beyazı destekliyorsa beyaz 1 karşı pincer güçlüdür; savaşta beyaz biraz önde olur."),
'A-1-4-2-2-1': ("Siyah büyük zıplar", 'best', "Yapay zekâ siyah 1 büyük zıplamayı daha çok sever. Beyaz 2 ile boş köşeye 3-3 işgali yapar; iki taraf birbirini sıkıştırır ve karışık bir savaş başlar."),
'A-1-4-2-3-1': ("Siyah keima – biraz yumuşak", 'bad', "Siyah 1 biraz yumuşaktır. Beyaz 4 omuz vuruşu harika bir noktadır; beyaz 8 ile karşı pincer de yapınca beyaz rahat eder."),
'A-1-4-3-1-1': ("Çift kakari – genelde kötü", 'bad', "Beyaz 1 çift kakari genelde iyi değildir. Siyah 2'den sonra sade ve sağlam oynar; siyah 8 ile pincer yapar, beyaz 1 siyahın gücüne çok yakın kalır."),
'A-1-4-3-1-2': ("Siyah bu taraftan kapatır", 'ok', "Siyah 1 ile bu taraftan kapatmak da olur. İki tarafın şekli de dolgundur."),
'A-1-4-3-2-1': ("Siyah dıştan bastırır", 'ok', "Siyah 1 ile dıştan da bastırabilir. Beyaz 2 ve 4 ile hane yapıp köşeye girer. Beyaz 6 ile siyah 7 gerekli değişimdir; siyah 9 ve 11 sente ile kapatır, sonra siyah 13 pincer ile sert savaş başlar."),
'A-1-4-3-2-2': ("Beyaz sürünüp bağlanır", 'bad', "Beyaz 1 ile hemen sürünüp bağlanırsa siyah 2 atari ile çok kalın olur; beyaz biraz kayıptadır."),
'A-1-4-4-1-1': ("Yüksek çift kakari – kötü", 'bad', "Beyaz 1 yüksek çift kakari de kötüdür. Siyah 2 ile bastırınca şekli tamamlanır; beyaz 1 garip bir yerde kalır."),
'A-1-4-5-1-1': ("Beyaz yapışır – tuzak", 'best', "Beyaz 1 yapışma biraz tuzak hamlesidir. Siyah 2 ile içeriden hane en güçlüsüdür. Siyah 4 sağlam uzanır; iki taraf istediğini alır, siyah daha memnundur."),
'A-1-4-5-1-2': ("Atari ve uzanma", 'ok', "Siyah 1 ve 3 ile atari verip uzanmak da olur. Beyaz 4'ten sonra taş feda etmek zorunda kalır; siyah sente köşeyi alır ve memnundur."),
'A-1-4-5-1-3': ("Beyaz keser – şüpheli", 'bad', "Beyaz 1 kesmesi şüphelidir. Siyah 2 ve 4 ile doğru sırayla atari verir. Beyaz bir taşı alsa da hâlâ yaşamamıştır; siyah çok rahattır."),
'A-1-4-5-2-1': ("Siyah dıştan hane – hata", 'bad', "Siyah 1 hatadır. Beyaz 2 ve 4 ile hane yapıp bağlanır, siyah 5 ile kesme noktasını kapatmak zorunda kalır. Beyaz sente köşeyi alır, siyahın dış gücü eksik kalır."),
'A-1-4-6-1-1': ("Beyaz çapraz keima", 'best', "Beyaz 1 çapraz keima değişik bir fikirdir. Siyah 2 kosumi ile vurmak sadedir, beyaz 3 yumuşak kosumi yapar; siyah biraz daha iyidir."),
'A-1-4-6-2-1': ("İtip kesmek – plansız", 'bad', "Siyah 1 ve 3 ile itip kesmek plansızdır. Beyaz 4 ve 6 ile atari verip bağlanınca siyah zor durumda kalır: köşesi dar, dışarıda da işaretli beyaz taşın kaçması tehdidi vardır."),
'A-1-4-7-1-1': ("Beyaz tenuki", 'ok', "Beyaz tenuki de yapabilir. Siyah 1 kosumi ile vurmak bir yoldur. Beyaz 4 esnek karşı pincer, siyah 5 sert zıplamadır; beyaz yine tenuki düşünebilir, sonuç eşittir."),
'A-1-4-7-2-1': ("Siyah üstten bastırır", 'situational', "Sağ alt siyahı iyi destekliyorsa siyah 1 ile bastırabilir. Beyaz 2 ile köşeye girip dönmesi doğrudur; siyah 5 ile gelişme yönünü sağa çevirir."),
'A-1-4-7-2-2': ("Beyaz dıştan uzanır – kötü", 'bad', "Beyaz 1 kötüdür. Beyaz 3 ve 5 ile yapışıp bağlanınca siyah 6 ile aşağı dönmek güçlüdür; siyahın dış gücü öncekinden belirgin şekilde iyidir."),
}
