# Komoku + keima kakari → siyah keima (B-1-1), kosumi (B-1-2), kosumi-tsuke (B-1-3)
T_KEIMA = {
'B-1-1': ("Başlangıç pozisyonu", 'best', "Siyah 1 keima bugün en popüler cevaplardan biridir. Beyazın dört yolu vardır: A civarında hemen açılmak, B'de köşeye alttan yapışıp yerinde yerleşmek, C'de yaklaşıp siyah 1'in yüksek duruşunun zayıflığını göstermek ya da tenuki; kakari taşı siyahın saldırısından korkmaz."),
'B-1-1-1-1-1': ("İki boşluklu açılış", 'best', "Beyaz 1 iki boşluklu açılış doğru hamlelerden biridir, birçok durumda işe yarar. İleride beyazın A'da yaklaşması çok değerlidir."),
'B-1-1-1-2-1': ("Yüksek üç boşluklu açılış", 'ok', "Beyaz 1 yüksek üç boşluklu açılış da iyidir; hızlıdır ama şekli biraz incedir, ileride siyahın A–C gibi imkânları vardır."),
'B-1-1-2-1-1': ("Köşeye alttan yapışma", 'ok', "Beyaz 1 alttan yapışarak yerinde yerleşmek ister, beyaz 3 ile sakince aşağı iner; sonuç eşittir."),
'B-1-1-2-2-1': ("Beyaz bükerek keser", 'bad', "Beyaz 1 ile bükerek kesmek genelde siyahın A civarında taşı varken, siyahın verimini düşürmek için oynanır. Doğrudan oynanırsa siyahı güçlendirir; siyah 2 ve 4 ile bir taşı alıp sade şekilde öne geçer."),
'B-1-1-2-2-2': ("Siyah köşeye uzar", 'ok', "Siyah 1 ile köşeye uzamak beyaza biraz kazanç verir; beyaz 2 ve siyah 3 sakince kapatır, iki taraf da kabul edebilir."),
'B-1-1-2-2-3': ("Atari ve bağlantı", 'ok', "Siyah 1 ve 3 ile atari yapıp bağlanmak da bir yoldur; değiş tokuş eşittir."),
'B-1-1-2-3-1': ("Beyaz kaplan ağzı – kötü", 'bad', "Beyaz 1 kaplan ağzı iyi değildir; siyah 2 atarisi güçlüdür, beyaz 3'ten itibaren ters atari ile değiş tokuş etmek zorundadır. Siyah açıkça önde."),
'B-1-1-2-3-2': ("Siyah geri çekilir – yumuşak", 'ok', "Siyah 1 ile geri çekilmek biraz yumuşaktır; beyaz 2 ile aşağı inince yerleşmiş olur, sonuç eşittir."),
'B-1-1-3-1-1': ("Beyaz yaklaşır", 'ok', "Beyaz 1 ile yaklaşmak çok etkindir; siyah 2 pinceri sağ tarafa önem verir, beyaz 3 zıplayıp büyür. İşaretli beyaz taş hâlâ canlıdır, iki taraf da oynanabilir."),
'B-1-1-3-2-1': ("Siyah karşı pincer", 'ok', "Siyah 1 ile sert karşı pincer yapar, sonra siyah 3 omuz vuruşu iyi hamledir. Beyaz 6 iki boşluklu açılışı ilginçtir, siyah 7 ile sakince dayanır; iki taraf da savaşabilir."),
'B-1-1-3-2-2': ("Siyah engeller – tuzak", 'bad', "Önceki diyagramda siyah 7 yerine 1'de engellemek tuzağa düşmektir; beyaz 2 ve 4 iyi sıradır, siyah 7 ile mecburen kapatır, beyaz 8 omuz vuruşunu alıp hızlı oynar."),
'B-1-1-3-3-1': ("Siyah kosumi ile dayanır – kaba", 'bad', "Siyah 1 ile dayanmak biraz kabadır; beyaz 2 ile uzayıp kalkar ve kazanç sağlar."),
'B-1-1-3-4-1': ("Siyah tenuki", 'ok', "Siyah tenuki de yapabilir; beyaz 1 ikinci sırada keima ile tabanı alınca siyah 2 ile yapışıp bastırarak yerinde yerleşir."),
'B-1-1-3-4-2': ("Beyaz keima ile bastırır", 'ok', "Beyaz 1 ile keima şeklinde bastırıp merkez kurmak da olur; işaretli beyaz taşın ileride hâlâ hareket alanı vardır."),
'B-1-1-3-4-3': ("Beyaz dayanır – kazançsız", 'bad', "Beyaz 1 ile dayanmak kazançlı değildir; siyah 2'den 6'ya sakin cevap verir. Siyah A ve B'den birini mutlaka alır, beyaz biraz memnun değildir."),
'B-1-1-3-4-4': ("Siyah 3-3'e uzar – fazla", 'bad', "Siyah 1 ile 3-3'e uzamak fazla güçlüdür; beyaz 2 ile hane yapıp keser, savaş çok zorlaşır. Siyah 5 dayanması beyazı meşgul ederek köşeyi dolaylı korur; beyaz 10 kümelenmesi kilit noktadır, savaş dengelidir."),
'B-1-1-3-4-5': ("Siyah alttan hane – yumuşak", 'bad', "Siyah 1 ile alttan hane savaştan kaçan yumuşak bir hamledir; beyaz taşı alıp çok kalınlaşır, siyah memnun değildir."),
'B-1-1-4-1-1': ("Beyaz tenuki", 'ok', "Beyazın tenuki yapması da çok yaygındır; siyah 1 ile iki boşluklu alçak pincer iyi noktadır. Beyaz yine tenuki yapabilir; siyah nasıl kapatırsa kapatsın beyazın bir devam yolu vardır."),
'B-1-1-4-1-2': ("Siyah zıplar", 'ok', "Siyah 1 zıplaması etkindir; beyaz 2 ile köşeye alttan yapışıp yaşamak iyidir, sonuç eşittir."),
'B-1-1-4-1-3': ("Siyah dayanırsa", 'bad', "Siyah 1 ile dayanırsa beyaz 2 ve 4 hafif oynar, siyahın verimini kolayca düşürür."),
'B-1-1-4-1-4': ("Siyah keima ile kapatır – zayıf", 'bad', "Siyah 1 keima ile kapatmak biraz zayıftır; beyaz tenuki yapabilir. İleride beyaz 2 ve 4 ile alttan yapışıp çift hane yapar; siyah 5 ve 7 en güçlüsüdür ama beyaz 8 yapışmasından sonra siyah beyazın kaçmasını önleyemez."),
'B-1-1-4-1-5': ("Siyah plansız oynar", 'bad', "Siyah 1 ve 3 plansızdır; beyaz sade şekilde köşede yaşayıp memnun kalır, siyahın verimi düşüktür."),
'B-1-1-4-1-6': ("Beyaz alttan yapışır – yavaş", 'ok', "Beyaz 1 ile alttan yapışmak biraz yavaştır, siyah 4 ile sakince geri çekilir. İşaretli siyah taş tam yerindedir; ileride A'da keima iyi devam noktasıdır."),
'B-1-1-4-1-7': ("Siyah atari", 'ok', "Siyah 1 atarisi de bir yoldur, beyaz 2 ters atari zorunludur. Siyah 7 ve 9 ile kovalamaya devam etmek çok serttir; iki taraf da savaşabilir."),
'B-1-1-4-1-8': ("Siyah keser", 'ok', "Siyah 1 kesmesi sade ve oynanabilirdir; beyaz 4 ile sadece açılmak iyidir, 5'te bastırıp siyahın A'da uzamasını kabul etmek kazançlı değildir."),
'B-1-1-4-2-1': ("Üç boşluklu pincer", 'ok', "Siyah 1 ile üç boşluklu pincer de yapabilir, beyaz yine tenuki yapabilir. Siyah 3 ile dayanmak aşağı yukarı böyledir; beyaz 4 ve 6 ile hafifçe yönetir."),
'B-1-1-4-2-2': ("Siyah zıplar – zayıf", 'bad', "Siyah 1 zıplaması biraz zayıftır; beyaz 2 ile köşeye alttan yapışmak iyi hamledir, beyaz A ve B'den birini mutlaka alıp tamamen yerleşir."),
'B-1-1-4-2-3': ("Beyaz hemen yerleşir", 'ok', "Beyaz 1 ve 3 ile doğrudan yerleşmeyi de arayabilir; siyah önceki diyagramdaki A zıplamasından tasarruf eder, sonuç eşittir."),
'B-1-1-4-2-4': ("Siyah sert atari", 'ok', "Siyah 1 atarisi serttir, beyaz 2 ters atari zorunludur. Siyah 7 kesmesi kaçınılmazdır; sonra beyazın merkezi siyahın alanına karşı durur."),
'B-1-1-4-2-5': ("Beyaz çift hane – şüpheli", 'bad', "Beyaz 1 çift hanesi şüphelidir; siyah 6 işgali mükemmeldir. Beyaz 9 ile mecburen taş alır, siyah 12 ile iki taşı keserek memnun kalır."),
'B-1-1-4-3-1': ("Sıkı pincer", 'ok', "Siyah 1 ile sıkı pincer de olur. Beyaz 2 ve 4 ile alttan yapışıp kaplan ağzı yapınca siyah 5 ile mutlaka atari yapmalıdır; değiş tokuş eşittir."),
'B-1-1-4-3-2': ("Siyah geri çekilir – yumuşak", 'bad', "Siyah 1 ile geri çekilmek yumuşaktır; beyaz 2 omuz vuruşu etkindir. İleride beyaz A'da hane ile ko yapabilir; bu ko beyaz için hafif, siyah için ağırdır, siyah zorlanır."),
}

T_KOSUMI = {
'B-1-2': ("Başlangıç pozisyonu", 'best', "Siyah 1 kosumi 'Shusaku'nun kosumisi' olarak bilinir, komisiz dönemde çok popülerdi. Komi gelince biraz yavaş sayıldı ama yapay zekâ bu eski hamleyi yeniden moda yaptı. Beyazın genelde üç cevabı vardır: A'da iki boşluklu açılış, B'de büyük keima ya da tenuki."),
'B-1-2-1-1-1': ("İki boşluklu açılış", 'best', "Beyaz 1 iki boşluklu açılış sadedir; iki taraf da sağlam olduğu için burada oynamaya devam etmenin değeri şimdilik azdır. İleride beyazın A'da keimasi ve siyahın B'de dayanması alan için büyüktür; beyazın C'de işgal imkânı da vardır."),
'B-1-2-2-1-1': ("Büyük keima", 'ok', "Beyaz 1 büyük keima merkeze daha çok önem verir, o da yaygındır."),
'B-1-2-2-1-2': ("Siyahın zıplaması", 'ok', "İleride siyah 1 zıplaması sente gibidir; beyaz 2 kosumi ile sağlam cevap verir."),
'B-1-2-2-1-3': ("Beyaz tenuki", 'ok', "Beyaz tenuki de yapabilir; o zaman siyahın alttan yapışması çok büyüktür. Beyaz yine tenuki yapabilir ya da 2 ile uzayıp yerinde yaşar."),
'B-1-2-3-1-1': ("Beyaz tenuki", 'ok', "Beyazın tenuki yapması da çok yaygındır; siyah 1 iki boşluklu pincer mükemmel yerdedir. İşaretli siyah kosumi A'daki keimadan daha sağlamdır ve beyazın B'de alttan yapışarak yerleşmesini neredeyse önler."),
'B-1-2-3-1-2': ("Beyaz kosumi ile çıkar", 'ok', "Beyaz 1 kosumi ile çıkmayı düşünebilir, siyah 2 zıplayıp baskıyı sürdürür, beyaz 3 ikinci sırada keima ile yerleşir. İleride siyahın A'da yapışması çok iyidir, beyaz genelde B'de kosumi ile kapatmalıdır."),
'B-1-2-3-1-3': ("Siyah ikinci sırada keima", 'ok', "Siyah ikinci sırada keima ile alana önem verir, beyaz 2 genelde zıplayıp çıkar, siyah 3 zıplaması sağ tarafa önem verir. Beyaz 4 ve 6 sakince çıkar; sonuç eşittir."),
'B-1-2-3-1-4': ("Beyaz ikinci sırada keima – yavaş", 'bad', "Beyaz 1 ikinci sırada keima biraz yavaştır; siyah 2 keima ile rahatça kapatır, beyaz 3 ile yine bir hamle eklemek zorunda kalır."),
'B-1-2-3-1-5': ("Siyah sıkı yapışır", 'bad', "Siyah 1 yapışması sıkıdır; beyaz 4 ve 6 ile geri adım atamaz. Siyah 7 ile sakince dönerek atari yapar, beyaz 8 ile iterek değiş tokuş eder; siyah biraz önde."),
'B-1-2-3-1-6': ("Beyaz yine tenuki", 'ok', "Beyaz bir kez daha tenuki de yapabilir; siyah 1 keima ile rahatça kapatır. İşaretli beyaz taş hâlâ canlıdır, fırsatını bekler."),
'B-1-2-3-1-7': ("Beyazın iyi hamleleri", 'ok', "Beyaz 1 ve 3 iyi hamlelerdir; siyah 4 ve 6 alanı korumak ister. Beyaz 7 ile ters iterek taş feda eder, siyah 8 ikinci sırada hane sıkıdır. Beyaz 9'dan itibaren sente ile siyahı sıkıştırır; siyah 14 ile kapatmak zorundadır, iki taraf da oynanabilir."),
'B-1-2-3-1-8': ("Siyah tenuki yaparsa", 'bad', "Önceki diyagramda siyah 14 yerine tenuki yaparsa beyaz 1 ve 3 çok serttir; beyaz siyahı tamamen kapatıp çok kazanır."),
'B-1-2-3-1-9': ("Beyaz döner – kötü", 'bad', "Beyaz 1 ile dönmek iyi değildir; siyah 6 çift hanesinden sonra beyazın şekli sıkışır."),
'B-1-2-3-1-10': ("İkinci sırada atari", 'situational', "Siyah 1 ile ikinci sırada da atari yapabilir, sonra siyah 3 atarisinin yönü doğru olmalıdır. Beyaz 4 yapışması sente ile birçok imkân bırakır; sonuç çevreye bağlıdır."),
'B-1-2-3-1-11': ("Yanlış yönden atari", 'bad', "Siyah 1 ile bu taraftan atari yanlış yöndedir; beyaz 2 ve 4 serttir, siyah çok zorlanır. Siyah 9 zıplarsa beyaz 10 ve 12 ile atari yapıp çıkar. Siyah 17 ile mecburen kapatır, beyaz 18 ile başa dönüp karşı saldırıya geçer."),
'B-1-2-3-1-12': ("Siyah hane – fazla", 'bad', "Siyah 1 hanesi fazla güçlüdür; beyaz 8 zıplaması keskindir. Beyaz A'da hane ile çıkma ya da B'de köşeyi öldürmeden birini mutlaka alır; siyah çöker."),
'B-1-2-3-1-13': ("Diğer taraftan almak", 'ok', "Öbür taraftan almakla karşılaştırınca: beyaz 2 aşağı inince siyah 3 ile dışarıda kaplan ağzı yapabilir; beyaz zorla yaşasa bile kazançlı değildir."),
'B-1-2-3-2-1': ("Üç boşluklu alçak pincer", 'ok', "Siyah 1 üç boşluklu alçak pincer de bir seçimdir. Beyaz 2 keimasi olur, siyah 3 yapışması sıkıdır, sonra siyah 7 ile sakince yan yana oynar; iki taraf da kabul edebilir."),
'B-1-2-3-2-2': ("Siyah dayanırsa", 'bad', "Siyah 1 ile dayanırsa beyaz 2 ile önce itmek zekicedir; sonra beyaz 6 ve 8 ile keskin karşılık verir, siyah zorlanır."),
'B-1-2-3-2-3': ("Beyaz tenuki", 'ok', "Beyaz tenuki de yapabilir; siyah 1 ile tek boşluklu açılmak iyi noktadır. İleride beyaz A'da keima yaparsa siyahın B'de dayanması mükemmeldir."),
'B-1-2-3-3-1': ("Bir boşluklu pincer", 'ok', "Siyah 1 ile bir boşluklu pincer de yapabilir, beyazın tenuki yapması bir yoldur. Siyah 3 kosumi ile kalınca kapatır; ileride beyaz için A iyi noktadır."),
'B-1-2-3-3-2': ("Beyaz yapışıp çıkar", 'ok', "Beyaz 1 ile yapışıp çıkabilir, beyaz 7 keima ile bastırmak iyi noktadır. Siyah 8 ile iki boşluklu açılıp hafif oynar; iki taraf da kabul edebilir."),
}

T_KOSUMITSUKE = {
'B-1-3': ("Başlangıç pozisyonu", 'best', "Eskiden siyah 1 ile kosumi şeklinde dayanmak kaba bir hamle sayılırdı; yapay zekânın getirdiği yeni bakışla bugün çok normal bir hamledir. Beyazın A'da uzama ya da B'de keima olmak üzere iki cevabı vardır."),
'B-1-3-1-1-1': ("Beyaz uzar", 'best', "Beyaz 1 ile uzamak sıradandır, siyah 2 ile tek boşluklu açılmak sağlamdır; ileride A'da vurma beyazın sente hakkıdır."),
'B-1-3-1-2-1': ("Siyah keima – ince", 'bad', "Siyah 1 keimasi şekil olarak incedir; bugün siyah A–beyaz B değiş tokuşu yapmadan doğrudan 1'de keima oynamak daha iyi sayılır."),
'B-1-3-1-2-2': ("Beyaz yaklaşır", 'bad', "İleride beyaz 1 ile yaklaşınca siyah 2 ile kapatmak zorundadır; bu iki hamlelik değiş tokuş beyaza puan kazandırır."),
'B-1-3-1-2-3': ("Siyah tenuki yaparsa", 'bad', "Siyah tenuki yaparsa beyaz 1 ile keima arasına girip kesmek çok serttir. Siyah 2'den itibaren sabretmek zorunda kalır, işaretli taş kesilir ve kayıp büyüktür."),
'B-1-3-1-2-4': ("Beyaz hemen keser", 'ok', "Beyaz 1 ile hemen araya girip kesmek de savaşılabilir; siyah 6 ve 8 en güçlü cevaplardır, sonrası neredeyse zorunlu şekillenmedir. Beyaz 19 atarisinde siyah artık cevap veremez; değiş tokuş beyazı memnun eder."),
'B-1-3-2-1-1': ("Beyaz keima ile bastırır", 'ok', "Beyaz 1 ile keima şeklinde bastırmak merkez içindir, siyah 2 ile sade şekilde sürünür; siyah sente ile alan alır, çok kârlıdır."),
'B-1-3-2-1-2': ("Beyaz sıkışır – çığ josekisi", 'ok', "Beyaz 1 ile sıkışmak da olur; bu durumda 'çığ josekisi' denen şekle dönüşür, ayrıntısı kitapta B-2-1-2 diyagramındadır."),
'B-1-3-2-2-1': ("Siyah hane yapıp keser – kötü", 'bad', "Merdiven iyi olsa bile siyah 1 ile hane yapıp kesmek iyi değildir. Siyah 5 ve 9 zıplamaları yerel olarak en güçlüsüdür; beyaz iki taşı feda edip sade şekilde öne geçer."),
'B-1-3-2-2-2': ("Merdiven siyaha kötüyse", 'bad', "Merdiven kötüyse siyah 1 ile önce atari yapmak zorundadır; beyaz 4 ve 10 ile iki kez dönmek çok güçlüdür. Siyah 11'den itibaren taş feda edip merkez kurmak zorunda kalır, beyaz 18 ve 20 ile sakince köşeyi alır; beyaz açıkça kazançlıdır."),
'B-1-3-2-2-3': ("Atari sonra bastırma", 'bad', "Beyaz 1 ve 3 ile atari yapıp bastırmak yeterince iyi değildir; beyaz sadece biraz iyidir."),
'B-1-3-2-2-4': ("Beyaz ters atari – kötü", 'bad', "Beyaz 1 ters atarisi iyi değildir; siyah 6 ve 8 ile köşeyi sağlamca alır, beyaz hâlâ yerleşmemiştir."),
'B-1-3-2-3-1': ("Siyah alttan hane", 'ok', "Siyah 1 ile alttan hane de oynanabilir, beyaz 2 çift hanesi sıkıdır. A'da taş alma imkânı olduğu için alttaki üç beyaz taş şimdilik saldırı altında değildir; beyaz tenuki yapabilir."),
'B-1-3-2-4-1': ("Kümelenip kesme – fazla", 'bad', "Çevrede destek yoksa siyah 1 ve 3 ile kümelenip kesmek fazladır; beyaz 4 ile yapışıp inince siyah zorlanır. Siyah 9 şeklin kilit noktası olsa da beyaz 14 ile yapışıp çıkınca siyah yine zor savaşır."),
}
