# Komoku + keima kakari → siyah üstten yapışıp bastırır (B-1-5), bir boşluklu alçak pincer (B-1-6)
T_BASTIRMA = {
'B-1-5': ("Başlangıç pozisyonu", 'situational', "Siyah 1 ile üstten yapışıp bastırmak sol tarafı büyütmek içindir; genelde çevrede destek ister, normalde biraz kayıptır. Beyazın A'da hane, B'de uzama ya da C'de araya girme gibi üç cevabı vardır."),
'B-1-5-1-1-1': ("Hane ve uzama", 'ok', "Beyaz 1 ve 3 ile hane yapıp uzamak sıradandır, sonra beyaz 5 ile yapışıp kalkar ve iki taraf da büyür. İleride beyazın A civarında birçok imkânı vardır, siyah biraz boştur; beyaz biraz iyidir."),
'B-1-5-1-1-2': ("Beyaz tenuki", 'ok', "Beyazın tenuki yapması sorun değildir; siyah 1 keima ile büyümeye devam eder, beyaz 2 keima ile sağlamlaşır."),
'B-1-5-1-1-3': ("Siyah karşı pincer", 'bad', "Siyah 1 ile karşı pincer yaparsa beyaz 2 ve 4 ile sertçe karşılık verir. Siyah 5 ve 7 ile keserek atari en güçlüsüdür, beyaz 8 ve 10 ile itip kesmek zorunludur; değiş tokuşta siyah biraz memnun değildir."),
'B-1-5-1-1-4': ("Siyah keima ile kapatır", 'ok', "Siyah 1 keima ile sade şekilde kapatır, beyaz 2 hafifçe çıkar. Siyah 3 saldırının kilit noktasıdır ama beyaz rahat çıktığı için tamamen savaşabilir."),
'B-1-5-1-1-5': ("Beyaz büyük keima ile açılır", 'ok', "Beyaz 1 büyük keima açılışı da olur, siyah 2 ile o da geniş açılır; beyaz biraz iyidir."),
'B-1-5-1-1-6': ("Beyaz kaplan ağzı – ağır", 'bad', "Beyaz 1 kaplan ağzı biraz ağırdır; siyah 2 keima hem büyür hem A'da yaklaşma noktasını hazırlar."),
'B-1-5-1-1-7': ("Beyaz kosumi – kötü", 'bad', "Beyaz 1 kosumi iyi değildir; siyah 2 kaplan ağzı ve sıkışma kaba ama güçlüdür. Siyah 6 ile köşeyi alır, beyaz memnun değildir."),
'B-1-5-1-1-8': ("Beyaz alttan yapışır – kötü", 'bad', "Beyaz 1 ile alttan yapışmak da iyi değildir; siyah 2 ile araya girince önceki diyagrama döner."),
'B-1-5-1-2-1': ("Siyah kaplan ağzı", 'bad', "Siyah 1 kaplan ağzı alana önem verir; beyaz 4 kaplan ağzı ustacadır, beyaz sente ile siyahın gelişmesini sınırlar ve memnun kalır."),
'B-1-5-1-2-2': ("Beyaz hemen açılır", 'bad', "Beyaz 1 ile doğrudan açılabilir, siyah 2 açılınca beyaz 3 büyük keima ile merkeze ilerler. Siyah 6 işgali sıkıdır, beyaz 7'yi dönüp almaya zorlar ve beyazın 8'de aşağı inme imkânını sente ile siler. Ama beyaz 9 bastırması çok kalındır; beyaz yine memnundur."),
'B-1-5-1-2-3': ("Siyah hemen keser – aceleci", 'bad', "Siyah 1 ile hemen kesmek acelecidir; beyaz 2 uzayınca işaretli beyaz taş tam yerinde olur, ileride A'da işgal gibi rahatsız etme imkânı da vardır."),
'B-1-5-1-2-4': ("Beyaz aşağı iner", 'bad', "Beyaz 1 ile aşağı inmek de iyidir; siyah 4 ile sağlam uzar, beyaz 5 iki boşluklu açılışla dolgun şekil kurar."),
'B-1-5-1-2-5': ("Siyah bastırır – kazançsız", 'bad', "Siyah 1 ile bastırmak kazançlı değildir; beyaz 2 ve 4 ile sade şekilde uzayıp memnun kalır."),
'B-1-5-1-2-6': ("Beyaz bağlanır – ağır", 'ok', "Beyaz 1 bağlanması biraz ağırdır; siyah 2 ve 4 yine bir taş alır, beyaz 5 ile bir hamle daha harcamak zorunda kalır. Sonuç eşittir."),
'B-1-5-2-1-1': ("Beyaz uzar – tuzak", 'ok', "Beyaz 1 uzaması bir tuzaktır; siyah 2 ile köşeyi engelleyip niyeti bozar, beyaz 3 hane yapınca B-1-5-1-1-1 diyagramına döner."),
'B-1-5-2-1-2': ("Beyaz itip keser", 'ok', "Beyaz 1 ve 3 ile itip keserse siyah 6 ile aşağı inmek güçlüdür. Beyaz 7 ve 9 ile bir taşı alıp kalınlaşır ama siyahın köşesi dolgundur; sonuç eşittir."),
'B-1-5-2-1-3': ("Beyaz köşeye hane – kötü", 'bad', "Beyaz 1 ile köşeye hane iyi değildir; siyah 2 kaplan ağzı ile sakince kapatır. Beyaz 3 ile önce işgal etmek incedir ama siyah biraz iyidir."),
'B-1-5-2-1-4': ("Atari ve kaplan ağzı", 'ok', "Beyaz 1 ve 3 ile atari yapıp kaplan ağzı kurarsa siyah 4 ile köşeye hane yapıp memnun kalır."),
'B-1-5-2-2-1': ("Siyah bağlanır – zayıf", 'bad', "Siyah 1 bağlanması biraz zayıftır; beyaz 2 ile hane yapıp kalkmak iyidir. Siyah 3 ile başa hane merkeze önem verir, beyaz 10 keima iyi noktadır. Beyazın alanı dolgundur, ileride A'da işgal imkânı da vardır; siyah memnun değildir."),
'B-1-5-2-2-2': ("Siyah dönerse", 'bad', "Siyah 1 ile dönerse beyaz 2 kaplan ağzı ile kapatıp memnun kalır; ileride beyazın A'da zıplaması iki tarafın alanı için önemlidir."),
'B-1-5-2-2-3': ("Beyaz sürünürse", 'ok', "Beyaz 1 ile sürünürse A-2-3-2 varyasyonlarına döner."),
'B-1-5-3-1-1': ("Beyaz araya girer", 'ok', "Beyaz 1 ile araya girerse siyah 2 ile yukarıdan atari yapar ve B-1-5-2-1-2 diyagramına döner."),
'B-1-5-3-2-1': ("Siyah alttan atari – kötü", 'bad', "Merdiven iyi olsun olmasın siyah 1 ile alttan atari iyi değildir; B-1-3-2-2-1 diyagramına döner."),
}

T_PINCER = {
'B-1-6': ("Başlangıç pozisyonu", 'ok', "Siyah 1 bir boşluklu alçak pincer eskiden çok popülerdi. Beyaz genelde A'da keima ile bastırır; B'de zıplayıp çıkma, C'de büyük zıplama, D'de yapışıp bastırma ve tenuki de oynanır."),
'B-1-6-1-1-1': ("Beyaz keima ile bastırır", 'best', "Beyaz 1 ile keima şeklinde bastırmak doğru hamledir; siyah 4 ikinci sırada keima ile beyaza destek vermez. Beyaz 5 ile önünü kesmek iyi noktadır, sonra beyaz 7 ile bastırıp savaş başlar; iki taraf da savaşabilir."),
'B-1-6-1-1-2': ("Beyaz karşı pincer", 'ok', "Beyaz 1 ile karşı pincer de yapabilir; siyah 2 keima şeklin kilit noktasıdır. İki taraf da çıkar, savaş dengelidir."),
'B-1-6-1-1-3': ("Siyah zıplar – kötü", 'bad', "Siyah 1 ile zıplayıp çıkmak iyi değildir; beyaz 2 ve 4 ile art arda bastırınca siyah tenuki yapamaz. Siyah 5 ve 7 ile inatla çift hane yapar, beyaz 10'dan itibaren doğru sırayla oynar; beyaz 16 ile karşı pinceri alıp çok etkin olur."),
'B-1-6-1-1-4': ("Siyah bir kez daha sürünür – kötü", 'bad', "Siyah 1 ile bir kez daha sürünmek de iyi değildir; beyaz 2 ile bir kez daha uzayıp merkezini güçlendirir."),
'B-1-6-1-1-5': ("Beyaz zıplar – ince", 'ok', "Beyaz 1 zıplaması şekil olarak biraz incedir; siyah 2'den 8'e kadar araya girip keserek güçlüce oynar. Beyaz 11 ve 13 ile doğrudan karşılar, durum çok zordur."),
'B-1-6-1-1-6': ("Siyah araya girip bağlanır – yumuşak", 'bad', "Siyah 1 ve 3 ile araya girip bağlanmak biraz yumuşaktır; beyazın şekli rahatlar."),
'B-1-6-1-2-1': ("Siyah itip keser", 'best', "Siyah 1 ve 3 ile itip kesmek de çok yaygındır, siyah 7 kosumi şekildir. Beyaz 8 ile bir taşı kontrol eder; iki taraf da kabul edebilir."),
'B-1-6-1-2-2': ("Siyah keima – eski", 'bad', "Eskiden siyah 1 keimasi daha çok oynanırdı; beyaz 2 ile asılmak iyi hamledir, siyah biraz kayıptır."),
'B-1-6-1-2-3': ("Siyah hane ile kalkar – fazla", 'bad', "Siyah 1 ile hane yapıp kalkmak biraz fazladır; beyaz 2'den itibaren art arda bastırıp rahatça ilerler, sonra beyaz 8 kosumi ile çıkmak çok serttir."),
'B-1-6-1-2-4': ("Siyah büyük keima", 'bad', "Siyah 1 büyük keima en güçlü cevaptır; beyaz 2 ile sakince zıplar, siyah 3 ve 5 mecburidir. Beyaz 6 ile itip keser, sonra beyaz 10 ve 12 birbirine bağlı iyi hamlelerdir; beyaz sente ile merkez kurup çok memnun kalır."),
'B-1-6-1-2-5': ("Siyah güç kullanırsa", 'bad', "Siyah 1 ve 3 ile güç kullanırsa beyaz 4 ve 6'dan itibaren yine taş feda etmeyi arar. Beyaz 18 ve 20 ile işgal edip ağ kurmak sıkıdır, siyah 21 ile gote taş almak zorunda kalır. İleride beyazın A'da zıplaması mükemmeldir; siyah önceki diyagramdan da kötü."),
'B-1-6-1-2-6': ("Siyah keima ile kapatır – işlemez", 'bad', "Siyah 1 ile keima şeklinde kapatmak işlemez; beyaz 2 ve 4 ile sade şekilde çıkar, siyah zor duruma düşer."),
'B-1-6-1-2-7': ("Siyah ısrarla keser", 'bad', "Siyah 1 ile ısrarla itip keserse beyaz 2'den itibaren ağ kurarak siyahı bir çırpıda alır."),
'B-1-6-1-2-8': ("Beyaz zıplar – kötü", 'bad', "Beyaz 1 zıplaması iyi değildir; siyah 2 ile itip çıkar ve çok alan kazanır. Beyazın merkezi hâlâ tam değildir, ileride siyahın A'da rahatsız etme imkânı vardır."),
'B-1-6-1-3-1': ("Siyah iki boşluklu açılır – tuzak", 'ok', "Siyah 1 iki boşluklu açılışı bir tuzaktır; beyaz 2 ve 4 bunu bozmanın bir yoludur. Siyahın köşesi alınır, dışarıda da pek kazancı olmaz; kayıp açıktır."),
'B-1-6-1-3-2': ("İtip dönme", 'ok', "Beyaz 1 ve 3 ile itip dönmek de bir yoldur, sonra beyaz 5 omuz vuruşu ile rahatça öne geçer; ileride beyazın A ve B'de iyi devam noktaları vardır."),
'B-1-6-1-3-3': ("On sekiz buçuk puan tuzağı", 'bad', "Beyaz 1 ve 3 ile hane yapıp bağlanmak tuzağa düşmektir. Beyaz 7'den sonra da yanlışta ısrar ederse 'on sekiz buçuk puan' denen tuzak oluşur ve siyah ezici bir kalınlık kurar."),
'B-1-6-2-1-1': ("Beyaz zıplayıp çıkar", 'ok', "Beyaz 1 ile zıplayıp çıkmak sadedir, siyah 2 keima ile etkin oynar; beyaz tenuki düşünebilir. İki beyaz taş çok esnektir, feda edilebilir de kurtarılabilir de."),
'B-1-6-2-1-2': ("Siyah zıplayıp kovalar", 'ok', "Siyah 1 ile zıplayıp kovalarsa beyaz 2 ile esnekçe karşı pincer yapar, sonra beyaz 4 ile ikinci sırada alttan yapışıp bağlanır."),
'B-1-6-2-1-3': ("Siyah dayanırsa", 'ok', "Siyah 1 ile dayanırsa beyaz 4 omuz vuruşu ile rahatça ilerler."),
'B-1-6-2-1-4': ("Beyaz art arda bastırır", 'ok', "Beyaz 1, 3 ve 5 ile art arda bastırıp sonra A ya da B civarından pincer yapmak da savaşılabilir."),
'B-1-6-2-1-5': ("Beyaz omuz vuruşu", 'ok', "Beyaz 1 ile doğrudan omuz vuruşu da olur, siyah 2 dayanması sente ile köşeyi korur. Beyaz 5 ile önce bastırıp kesmeyi önlemek gerekir; siyah alan, beyaz merkez alır, sonuç eşittir."),
'B-1-6-3-1-1': ("Beyaz büyük zıplama", 'ok', "Beyaz 1 büyük zıplaması hafiftir; oyuncular bunu daha önce denememişti. Siyah 2 küçük zıplama ile sağlam kalır, beyaz tenuki yapabilir; sonuç eşittir."),
'B-1-6-3-2-1': ("Siyah yapışır", 'ok', "Siyah 1 yapışması da bir yoldur; beyaz 2 kosumi ile akışında çıkar. Siyah 3 hanesi sağlamdır, beyaz 4 ile sade şekilde engeller; iki taraf da kabul edebilir."),
'B-1-6-3-2-2': ("Beyaz çift hane", 'situational', "Merdiven iyiyken beyaz 1 çift hanesi sıkıdır; iki taraf birbirinden tempo alır, sonuç yine eşittir."),
'B-1-6-3-2-3': ("Siyah iterek çıkar", 'ok', "Siyah 1 ile iterek de çıkabilir; beyaz 6 ile aşağı inene kadar denk bir değiş tokuş olur."),
'B-1-6-4-1-1': ("Beyaz yapışıp bastırır", 'situational', "Beyaz 1 ile yapışıp bastırmak da bir yoldur; siyah 6 ile iki boşluklu açılmak sadedir, beyaz 13 uzayarak şeklini onarır. Merdiven iyiyken siyah 14 ve 16 ile güçlüce karşılık verir; beyaz 17 ile aşağı inmek zorunda kalır, siyah biraz önde."),
'B-1-6-4-1-2': ("Merdiven beyaza iyiyse", 'ok', "Merdiven beyazın lehineyse beyaz 1 ve 3 ile itip keserek bir taşı merdivenle alır; sonuç eşittir."),
'B-1-6-4-1-3': ("Siyah aşağı zıplar", 'situational', "Merdiven iyiyken siyah 1 ile aşağı zıplamak da iyidir; beyaz 2 keima ile vurmak saldırının kilit noktasıdır, siyahın biraz daha etkin olduğu karışık bir savaş çıkar."),
'B-1-6-4-1-4': ("Merdiven beyaza iyiyse", 'ok', "Merdiven beyazın lehineyse beyaz 1 ve 3 doğru sıradadır; siyah 6 ile başa dönüp karşılık vermek zorunda kalır. Beyaz 7 ve 9 ile bir taşı merdivenle alır; sonuç eşittir."),
'B-1-6-4-1-5': ("Siyah keima ile kalkar", 'situational', "Siyah 1 ile keima şeklinde kalkmak da olur; beyaz 2 yapışması sente ile kesmeyi kapatır, sonra beyaz 4 karşı pinceri ile savaş başlatır. Sonuç çevredeki taşlara bağlıdır."),
'B-1-6-4-1-6': ("Beyaz karşı pincer", 'ok', "Beyaz 1 karşı pinceri de bir yoldur; siyah 2 kosumi ile sağlamca çıkar, sonra beyaz 5 ve 7 ile güçlüce saldırır ve karışık bir savaş olur."),
'B-1-6-4-1-7': ("Siyah uzar", 'ok', "Önceki diyagramda siyah 4 yerine 1'de uzarsa beyaz 2 ve 4 ile alttan yapışıp çift hane yapar. Siyah 7 ve 11 ile sertçe karşılık verir, beyaz 14 ile önce sakince bağlanır, sonra beyaz 18 keima ile önünü kesmek kilit noktadır. Siyah 19 ve 21 ile uzlaşır; sonuç kabul edilebilir."),
'B-1-6-4-1-8': ("Beyaz keima ile bastırır – kötü", 'bad', "Beyaz 1 keima ile bastırmak etkin görünür ama siyah 6 ile sakince keima ile çıkınca beyaz şeklini onaramaz. Beyaz 7 ve 9 mecburidir, siyah 8 ve 10 ile iki tarafa da ulaşıp memnun kalır."),
'B-1-6-4-2-1': ("Beyaz geri çekilir – yavaş", 'bad', "Beyaz 1 ile geri çekilmek biraz yavaştır; siyah 2 büyük keima ile solu güçlendirir. Beyaz 3'ten itibaren merkeze rahat çıkar ama merkezi hâlâ incedir, beyaz memnun değildir."),
'B-1-6-4-2-2': ("Beyaz bir taşı keser – küçük", 'bad', "Beyaz 1 ile bir taşı kesip almak küçüktür; siyah 2 ve 4 ile sade şekilde taş feda edip memnun kalır."),
'B-1-6-4-2-3': ("Siyah kaplan ağzı", 'situational', "Sağ tarafı büyütmek istiyorsa siyah 1 kaplan ağzı da olur, sonra siyah 3 zıplayıp büyümeye devam eder. İleride siyah A'da zıplayabilir, köşede hâlâ geniş hareket alanı vardır."),
'B-1-6-5-1-1': ("Beyaz tenuki", 'ok', "Beyaz tenuki yaparsa siyah 1 kosumi ile kapatmak çok büyüktür; beyaz 2 ve 4 ile genelde hemen hareket etmelidir. Siyah 5 bağlanması güçlüdür, beyaz 6'dan itibaren sakince taş feda eder; sonuç eşittir."),
'B-1-6-5-1-2': ("Siyah beyazı yaşatır", 'bad', "Siyah 1'den itibaren beyazın yaşamasına izin vermek biraz isteksizdir; ileride beyazın A'da vurması siyahı rahatsız eder."),
'B-1-6-5-1-3': ("Beyaz yine tenuki – kötü", 'bad', "Beyazın bir kez daha tenuki yapması iyi değildir; siyah 1 ile kapatmak hem kalın hem büyüktür."),
'B-1-6-5-2-1': ("Siyah yapışıp bastırır", 'situational', "Merdiven iyiyken siyah 1 ile yapışıp bastırabilir; beyaz 2 ve 4 ile genelde yaşamak zorundadır, iki taraf da kabul edebilir."),
'B-1-6-5-2-2': ("Beyaz araya girer", 'bad', "Beyaz 1 ile araya girerse siyah 2 ve 4 ile karşılık vermek işler; değiş tokuşta siyah açıkça kazançlıdır."),
'B-1-6-5-2-3': ("Merdiven siyaha kötüyse", 'bad', "Merdiven kötüyse siyah 1 ile dıştan atari yapmak zorundadır; merkezinde kesme noktası kalır, siyah biraz kayıptır."),
'B-1-6-5-2-4': ("Beyaz tenuki – kötü", 'bad', "Beyazın tenuki yapması iyi değildir; siyah 1 ile geri çekilince B-1-6-5-1-3 diyagramına döner. Siyah A'da da dayanabilir, sonuç hemen hemen aynıdır."),
'B-1-6-5-3-1': ("Siyah keima", 'ok', "Siyah 1 ile keima da oynayabilir; B-1-1-4-3-1 diyagramına döner."),
'B-1-6-5-4-1': ("Siyah kosumi", 'ok', "Siyah 1 ile kosumi de oynayabilir; B-1-2-3-3-1 diyagramına döner."),
}
