# Komoku köşe kapatmaları: keima kapatma (B-6-1), bir boşluklu kapatma (B-6-2)
T_KEIMAKAPATMA = {
'B-6-1': ("Başlangıç pozisyonu", 'best', "Siyah 1 keima ile köşeyi kapatır; 'kaygısız köşe' olarak bilinir ve yapay zekâdan önce en yaygın kapatmaydı. Köşedeki alanı çok sağlamdır ama merkeze etkisi azdır. Beyazın üç yolu vardır: A'da yapışma, B'de omuz vuruşu ve C'de alttan yapışma."),
'B-6-1-1-1-1': ("Beyaz yapışır", 'best', "Beyaz 1 yapışması kaygısız köşenin gelişmesini sınırlamak içindir. Siyah 2 ve 4 sadedir; beyaz duruma göre A ya da B civarında açılabilir."),
'B-6-1-1-1-2': ("Beyaz döner – kayıp", 'bad', "Beyaz 1 ile dönmek genelde biraz kayıptır; siyah 2 ile uzayınca şekli güçlenir, beyaz A'daki yapışma imkânını kaybeder."),
'B-6-1-1-1-3': ("Siyah bastırır", 'ok', "Siyah 1 ile bastırmak merkez içindir; beyaz 2 ile sade şekilde zıplar, siyah 3 ve 5 ile araya girip bağlanmak gereklidir. Beyaz A'da yapışıp kalkabilir ya da tenuki yapabilir; beyaz tenuki yaparsa siyahın B'de aşağı inmesi çok değerlidir."),
'B-6-1-1-1-4': ("Beyaz sade şekilde köşeyi alır", 'ok', "Beyaz 1'den 7'ye kadar sade şekilde köşeyi almak da bir yoldur; sonuç eşittir."),
'B-6-1-1-1-5': ("Beyaz atari yapıp iter – fazla", 'bad', "Beyaz 1, 3 ve 5 ile atari yapıp iterek çıkmak biraz fazladır; siyah 6 ve 8 ile inatla direnir. Beyaz 9'dan itibaren taş feda edip yön değiştirmek zorunda kalır; siyah daha çok kazanır."),
'B-6-1-1-1-6': ("Siyah bağlanır – baskısız", 'bad', "Siyah 1 bağlanması beyaza pek baskı yapmaz; beyaz 2 ile iki boşluklu açılıp memnun kalır."),
'B-6-1-1-2-1': ("Siyah geri çekilir", 'ok', "Siyah 1 ile geri çekilmek kalındır; beyaz 2 ile sade şekilde kenara açılır, iki taraf da kabul edebilir."),
'B-6-1-1-3-1': ("Siyah karşı pincer – kötü", 'bad', "Siyah 1 karşı pinceri genelde iyi değildir; beyaz 2 ve 4 ile hemen hareket etmek güçlüdür. Siyah 5 ile zıplayıp kovalar, beyaz 6 ve 8 ile yerleşmeye çalışır ve memnun kalır."),
'B-6-1-1-3-2': ("Beyaz tenuki", 'ok', "Beyaz tenuki de yapabilir ve işaretli beyaz taşı sente kazancı sayar. Siyah 1 ile bir kez daha hane yapsa bile ileride beyazın A'da kesmesi birçok imkân doğurur."),
'B-6-1-2-1-1': ("Beyaz omuz vuruşu", 'best', "Beyaz 1 omuz vuruşu da çok etkindir; siyah 2 genelde yapışır, beyaz 3 ile merkeze zıplar. İleride beyazın A'da engelleme ve B'de yapışma imkânları vardır."),
'B-6-1-2-2-1': ("Siyah sürünür – kötü", 'bad', "Siyah 1 ile sürünmek genelde iyi değildir; beyaz 2 yapışması güçlüdür, siyah 3 ile sakince geri çekilir, beyaz sente ile kazanmış olur."),
'B-6-1-2-2-2': ("Siyah hane – şüpheli", 'bad', "Siyah 1 hanesi şüphelidir; beyaz 2 çift hanesi sıkıdır. Siyah 3 ve 5 en güçlü cevaplardır; beyaz sente ile köşede yaşayıp memnun kalır."),
'B-6-1-2-2-3': ("Siyah çift hane – fazla", 'bad', "Siyah 1 çift hanesi fazla güç kullanır; beyaz 2 ile atari yapıp kesmek çok güçlüdür. Beyaz 10 ile sente dönmek çok kazandırır, siyahın köşedeki verimi düşüktür. Zamanı gelince beyazın A'dan kaçması siyahı iki arada bırakır."),
'B-6-1-2-3-1': ("Siyah doğrudan tenuki", 'ok', "Siyahın doğrudan tenuki yapması da sorun değildir; beyaz 1 ile engellerse B-3-2-2-1-1 diyagramına döner."),
'B-6-1-3-1-1': ("İkinci sırada alttan yapışma", 'bad', "Eskiden beyaz 1 ile ikinci sırada alttan yapışmak çok popülerdi; yapay zekâya göre siyah 2 ile dıştan hane en güçlü cevaptır ve beyaz tenuki yapıp kaybı durdurmalıdır. Beyaz 3 ile keserse siyah 4 ile güçlüce baş kaldırır; beyazın delip geçmesine izin vermek sorun değildir. Siyah 10 küçük zıplama ile saldırıyı sürdürür, beyaz zor bir savaşa düşer."),
'B-6-1-3-1-2': ("Eski yöntem", 'ok', "Siyah 1 ve 3 eski bir yöntemdir; beyaz sente ile siyahı sıkıştırma amacına ulaşır. Sonuç eşittir."),
'B-6-1-3-1-3': ("Siyah açgözlüce taş alır", 'bad', "Siyah 1 ile açgözlüce bir taşı almanın iyi olmadığı çoktan bilinir; beyaz 2 ve 4 ile rahatça iki kez atari yapar, siyahın verimi düşer."),
'B-6-1-3-2-1': ("Siyah dışarıya uzar – gevşek", 'ok', "Siyah 1 ile dışarıya uzamak yeterince sıkı değildir; beyaz 2 ile genelde hemen sürünüp çıkar. Siyah 5 ve 7 ile kovalar ama köşenin nefesi dar olduğu için beyaz kolay saldırıya uğramaz."),
'B-6-1-3-2-2': ("Beyaz köşeye hane – uygun değil", 'bad', "Beyaz 1 ile köşeye hane uygun değildir; siyah 2 ile dönünce beyazın cevabı kalmaz."),
'B-6-1-3-3-1': ("Siyah geri çekilir – kötü", 'bad', "Siyah 1 ile geri çekilmek genelde iyi değildir; beyaz 2 ile hane yapıp kalkınca B-6-1-1-3-1 diyagramına döner."),
'B-6-1-3-4-1': ("Siyah içeriden hane – yumuşak", 'bad', "Siyah 1 içeriden hanesi biraz yumuşaktır; beyaz 2 pinceri ile sade şekilde kazanır."),
}

T_BIRBOSLUKKAPATMA = {
'B-6-2': ("Başlangıç pozisyonu", 'best', "Kaygısız köşeye göre bir boşluklu kapatma merkeze daha çok önem verir ama köşe biraz boştur. En popüler cevap beyazın A'da yapışmasıdır; B'de yapışma, C'de yaklaşma ve D'de 3-3'e yapışma da oynanır."),
'B-6-2-1': ("Beyaz yapışır", 'best', "Beyaz 1 yapışması yapay zekânın getirdiği yeni bir fikirdir. Siyahın dört yaygın cevabı vardır: A'da alttan hane, B'de aşağı inme, C'de üstten hane ve D'de yukarı uzama."),
'B-6-2-1-1-1': ("Siyah alttan hane", 'best', "Siyah 1 alttan hanesi en yaygınıdır; beyaz 2 çift hane yapar, siyah 3 ve 5 en güçlü cevaplardır. Beyaz 10 ile başa dönmek güçlüdür, siyah 11 ile sağlamca sarıp alır; iki taraf da oynanabilir."),
'B-6-2-1-1-2': ("Siyah zıplayıp çıkar", 'ok', "Önceki diyagramda siyah 11 yerine 1'de zıplayıp çıkmak etkindir; beyaz 2 keimasi sade ve oynanabilirdir. Sonucu işaretli beyaz taşın nasıl hareket edeceği belirler."),
'B-6-2-1-1-3': ("Beyaz hemen hareket eder", 'ok', "Beyaz 1 ve 3 ile sente değiş tokuş yapıp 5 ve 7 ile doğrudan hareket etmek de bir seçimdir. Siyah 8'den itibaren art arda bastırıp kalınlaşır, 16 ile keima şeklinde bastırma noktasını alır; iki taraf da savaşabilir."),
'B-6-2-1-1-4': ("Beyaz önünü keser", 'ok', "Beyaz 1 ile önünü kesmek de bir yoldur; siyah 4 ile kıvrılıp çıkmak sade ve güçlüdür. Beyaz 7 zıplaması şeklini onarır, siyah 8 keima ile merkezin yüksek noktasını alır; iki taraf da kabul edebilir."),
'B-6-2-1-1-5': ("Beyaz yan yana – zayıf", 'ok', "Beyaz 1 ile yan yana oynamak biraz zayıftır; siyah 2 hanesi sadedir, sonra 4 keima ile imkân hazırlar. Siyah 6 ile sakince taşı alır, beyaz 7 keima ile merkezi korur; siyah biraz iyidir."),
'B-6-2-1-1-6': ("Siyah bastırıp çıkar", 'ok', "Siyah 1 ile bastırıp da çıkabilir, sonra siyah 3 işgali keskindir. Siyah 9 zıplayıp başa geçer, beyaz 10 büyük keima ile şeklini onarır, siyah 11 ile işgal edip beyazı zorlamayı sürdürür; siyah rahatça savaşabilir."),
'B-6-2-1-1-7': ("Siyah keser", 'ok', "Siyah 1 kesmesi sadedir; beyaz 2 ve 4 ile taş feda edip merkez kurar, iki taraf da kabul edebilir."),
'B-6-2-1-1-8': ("Siyah alttan sürünür – kötü", 'bad', "Siyah 1 ile alttan sürünmek iyi değildir; beyaz 2 ile itip bir taşı almak hem büyük hem kalındır."),
'B-6-2-1-1-9': ("Beyaz içeriden engeller", 'ok', "Beyaz 1 ile içeriden engellemek de bir yoldur; siyah 6 ile önce uzamak doğru sıradır. Beyaz 9 ve 11 rahat sente kazançlarıdır, sonra beyaz 13'ten itibaren sakince taş feda eder; sonuç eşittir."),
'B-6-2-1-1-10': ("Beyaz sadece uzar", 'ok', "Beyaz 1 ile sadece uzamak da oynanabilir; siyah 2 ile bağlanmayı düşünebilir. Beyaz 3 ile başa dönünce siyah 4 ile bir taşı sağlamca alır. Yapay zekâya göre B-6-2-1-1-1 ile eşittir; ama oyuncu gözüyle beyaz bazı devam imkânlarını kaybeder."),
'B-6-2-1-1-11': ("Siyah atari ile karşılık verir", 'situational', "Siyah 1 ile atari yapıp karşılık verebilir; beyaz 2, 4 ve 6 ile siyahın köşesini deler. Siyah 7 ve 9 ile iki kez sert atari yapar; iki taraf burada bir ko etrafında savaşır, durum çok zordur."),
'B-6-2-1-1-12': ("Siyah uzayıp ko'dan kaçar", 'ok', "Önceki diyagramda siyah 7 yerine 1'de uzarsa ko'dan kaçınır; beyaz 2 kaplan ağzı güçlüdür, beyaz 4 hanesi ile taş feda edip şekli bitirir. İki taraf da savaşabilir."),
'B-6-2-1-1-13': ("Siyah sadece bağlanır", 'situational', "Merdiven iyiyken siyah 1 ile sadece bağlanabilir; beyaz 2 yapışması sıkıdır. Siyah 3 pinceri etkindir, beyaz 4'ten itibaren sakince kalınlaşır; sonuç eşittir."),
'B-6-2-1-1-14': ("Atari ve bağlantı", 'ok', "Siyah 1 ve 3 ile atari yapıp bağlanmak sol tarafın gelişmesine önem verir; beyaz 2'den itibaren bir taşı sarıp alarak değiş tokuş eder. İki taraf da kabul edebilir."),
'B-6-2-1-1-15': ("Siyah baş kaldırmaya devam eder – kötü", 'bad', "Siyah 1 ile baş kaldırmaya devam etmek genelde iyi değildir; beyaz 2 ile uzayıp karşılık verir. Siyah 5 zıplaması ile sert saldırır, beyaz 6 fil adımı esnektir; siyah biraz geride."),
'B-6-2-1-1-16': ("Beyaz ko yapar", 'situational', "Beyaz 1 ve 3 ile ko yapmak da bir yoldur; siyah başka yerde ko tehdidi aramayı düşünebilir, bu ko çok zordur."),
'B-6-2-1-1-17': ("Siyah bağlanır", 'ok', "Siyah 1 ile bağlanmak da olur, beyaz 2 ters atarisi doğaldır. Siyah 3 ile sakince uzar, beyaz 4'ten itibaren iki taraf istediğini alır; sonuç kabul edilebilir."),
'B-6-2-1-1-18': ("Siyah kaçar – zayıf", 'bad', "Siyah 1 ile kaçmak biraz zayıftır; beyaz 2 ile rahatça itip çıkar ve çok alan kazanır."),
'B-6-2-1-1-19': ("Siyah sadece bağlanır – yavaş", 'bad', "Siyah 1 ile sadece bağlanmak biraz yavaştır; beyaz zaten sente ile kazanmıştır."),
'B-6-2-1-1-20': ("Siyah merkeze keima", 'bad', "Siyah 1 ile merkeze keima ilginç bir fikirdir; beyaz 2 ile alttan atari doğrudur, sonra beyaz 6 pinceri siyahı çok rahatsız eder. Siyah 7 ile mecburen aşağı iner; beyaz sente ile kazanmıştır."),
'B-6-2-1-1-21': ("Atari ve bağlantı – zayıf", 'ok', "Beyaz 1 ve 3 ile atari yapıp bağlanmak önceki diyagram kadar iyi değildir; işaretli siyah taş iyi yerdedir."),
'B-6-2-1-1-22': ("Beyaz tuzağa düşer", 'bad', "Beyaz 1 ve 3 tuzağa düşmek gibidir; siyahın köşesi dolgun olur, beyaz biraz kayıptır."),
'B-6-2-1-2-1': ("Siyah aşağı iner", 'ok', "Siyah 1 ile aşağı inmek sağlamdır; B-6-1-2-1-1 diyagramına döner."),
'B-6-2-1-3-1': ("Siyah üstten hane", 'ok', "Siyah 1 ile üstten hane merkeze önem verir, beyaz 2 çift hane ile köşeye girer. Siyah 3 ile sakince bağlanır, iki taraf birer taş alır; sonuç kabul edilebilir."),
'B-6-2-1-3-2': ("Beyaz dışarıda bağlanır – kötü", 'bad', "Beyaz 1 ile dışarıda bağlanmak genelde iyi değildir; siyah 2 ile köşeyi engellemek çok değerlidir, beyazın taşları alçakta kalır."),
'B-6-2-1-3-3': ("Siyah önce atari", 'bad', "Siyah 1 ile önce atari değişim getirir; beyaz 4 ile köşeye alttan yapışıp karşılık verebilir. Siyah 5 ve 7 ile araya girip bağlanarak kaybı durdurur, sonra gote üç beyaz taşı alır. Beyaz sente köşeyi alır, siyahın verimi düşüktür; beyaz biraz iyidir."),
'B-6-2-1-3-4': ("Siyah köşeye hane – kötü", 'bad', "Siyah 1 ile köşeye hane açıkça kötüdür; beyazın alanı ve gözleri B-6-2-1-3-2'dekinden çok daha iyidir."),
'B-6-2-1-3-5': ("Siyah alana önem verir", 'bad', "Siyah 1, 3 ve 5 alana önem verir; beyaz 6 ve 8 ile sade şekilde taş feda eder, sonra 10 ile güçlüce yapışıp kalkar; siyah biraz memnun değildir."),
'B-6-2-1-4-1': ("Siyah yukarı uzar – yavaş", 'bad', "Siyah 1 ile yukarı uzamak biraz yavaştır; beyaz 2 ve 4 ile aşağı inip kenara açılarak sade şekilde öne geçer."),
'B-6-2-2-1-1': ("Beyaz diğer taraftan yapışır", 'situational', "Sol taraf değerliyse ya da beyazın desteği varsa beyaz 1 ile bu taraftan yapışmak da iyi hamledir. Siyah 4 ile aşağı inmek çok önemlidir, iki tarafın tabanı buna bağlıdır."),
'B-6-2-2-1-2': ("Siyah bastırır – kötü", 'bad', "Siyah 1 ile bastırmak pek iyi değildir; beyaz 2 ile sente köşeye hane yapınca alan farkı çok büyür."),
'B-6-2-3-1-1': ("Beyaz yaklaşır", 'ok', "Beyaz 1 ile yaklaşmak da çok yaygındır; siyah tenuki düşünebilir. Sonra beyaz 3 yapışması iyi hamledir, siyah 6 ile kaplan ağzı yapıp sağlam kalır; iki taraf da kabul edebilir."),
'B-6-2-3-1-2': ("Siyah aşağı iner", 'ok', "Siyah 1 ile aşağı inmek güçlüdür; beyaz 2 ile dönüp köşeyi tehdit eder, siyah 3 karşı pinceri ile saldırarak savunur. Beyaz 4 keima ile kapatmak iyi noktadır, siyah 5 ve 7 ile itip keserek karışık bir savaş başlatır."),
'B-6-2-3-1-3': ("Beyaz işgal eder – kötü", 'bad', "Beyaz 1 işgali iyi değildir; siyah 2 ve 4 ile sade şekilde yönetmesi yeterlidir, beyaz pek bir şey kazanmaz."),
'B-6-2-3-2-1': ("Siyah karşı pincer", 'ok', "Siyah 1 ile karşı pincer de düşünülebilir; beyaz 2 ile genelde zıplayıp çıkar, siyah 3 ile de zıplayınca savaş başlar."),
'B-6-2-3-3-1': ("Siyah köşeyi kapatır – sıkışık", 'bad', "Siyah 1 ile köşeyi kapatmak biraz sıkışıktır; beyaz sente ile kazanmıştır, ileride A'da vurma imkânı da vardır."),
'B-6-2-4-1-1': ("3-3'e yapışma", 'situational', "İşaretli siyah taş iki yana açılmışken beyaz 1 ile 3-3'e yapışmak yaygın bir yoklamadır. Siyah 2 ile köşede kaplan ağzı yapıp sağlam kalır, beyaz 3'ten itibaren siyahın alanı içinde rahatça bir taban kurar."),
'B-6-2-4-1-2': ("Beyaz doğrudan pincer", 'situational', "Beyaz 1 ile doğrudan pincer de bir yoldur; önceki diyagramla hangisinin daha iyi olduğunu söylemek zordur."),
'B-6-2-4-2-1': ("Siyah kosumi – kazanç verir", 'bad', "Siyah 1 kosumisi beyaza kazanç verir; ileride beyazın A'da sıkışması birçok imkân doğurur."),
}
