# Komoku + büyük keima kakari (B-3), iki boşluklu yüksek kakari (B-4), yandan yapışma (B-5)
T_BUYUK = {
'B-3': ("Başlangıç pozisyonu", 'ok', "Beyaz komokuya büyük keima ile yaklaşır. Kakari uzak olduğu için siyahın seçeneği çoktur: kosumi, zıplama ya da iki boşluklu veya bir boşluklu pincer."),
'B-3-1-1-1-1': ("Siyah kosumi", 'best', "Siyah 1 kosumi sade ve sağlamdır; beyaz 2 ile iki boşluklu açılabilir ya da A'da çok büyük keima oynayabilir. Siyah biraz iyidir."),
'B-3-1-2-1-1': ("Beyaz işgal eder", 'ok', "Beyaz 1 işgali etkindir; siyah 2 ile sade şekilde keima oynar, önceki diyagramla hemen hemen eşittir."),
'B-3-1-2-2-1': ("Siyah sürünür", 'ok', "Siyah 1 ile sürünmek de olur; beyaz 2 zıplayınca siyah tenuki yapar, yine siyah biraz iyidir."),
'B-3-1-2-3-1': ("Siyah kosumi ile çıkar – tuzağa düşer", 'bad', "Siyah 1 kosumisi tuzağa düşmek gibidir; beyaz 2 ile sıkıca engeller. Siyah 3 ile bastırıp çıkması daha iyidir; beyaz 4'ten itibaren merkez kurmak bir yoldur, beyaz memnundur."),
'B-3-1-2-3-2': ("Beyaz sıkışıp alan alır", 'bad', "Önceki diyagramda beyaz 4 yerine 1'de sıkışıp alan da alabilir; siyah 4 pinceri ile oyunu sağa taşır, beyaz yine iyidir."),
'B-3-1-2-3-3': ("Siyah bu taraftan bastırır – zayıf", 'bad', "Siyah 1 ile bu taraftan bastırmak biraz zayıftır; beyaz 2 hanesi sıkıdır, sonra beyaz 4'ten itibaren bir taşı almak çok büyüktür. Alttaki iki beyaz taş hâlâ canlıdır; siyah önceki iki diyagramdan da kötüdür."),
'B-3-2-1-1-1': ("Siyah zıplar", 'ok', "Siyah 1 zıplaması merkez içindir; beyaz 2 ile ikinci sırada keima iki tarafın tabanı için önemlidir, siyah 3 keima ile sente alır. Sonuç eşittir."),
'B-3-2-1-2-1': ("Siyah art arda bastırır", 'ok', "Siyah 1 ve 3 ile art arda bastırmak da olur; önceki diyagramla hemen hemen eşittir."),
'B-3-2-1-2-2': ("Siyah büyük zıplama – fazla", 'bad', "Siyah 1 büyük zıplaması biraz fazladır; beyaz 2 ve 4 ile güçlüce karşılık verir. Siyah 5 ile uzamak doğrudur, beyaz 6 ve 8 ile sağlam şekil kurar; siyah memnun değildir."),
'B-3-2-1-3-1': ("Siyah karşı pincer – eski", 'bad', "Siyah 1 karşı pinceri eskiden popülerdi; beyaz 2 ile dayanıp köşeyi alabilir. Siyah 3 ile kaplan ağzı yapıp sıkışarak kaba ama güçlüce sente alır; beyaz biraz iyidir."),
'B-3-2-1-3-2': ("Beyaz yapışıp çıkar", 'bad', "Beyaz 1 ile yapışıp çıkmak da olur; siyah 2 ve 4 şeklin kilit noktalarıdır. Beyaz 5 ve 7 ile yapışıp uzayarak rahat çıkar, siyah 10 ve 12 ile sağlamca açılır; beyaz biraz daha etkindir."),
'B-3-2-1-3-3': ("Beyaz kaplan ağzı", 'bad', "Önceki diyagramda beyaz 5 yerine 1'de sağlam kaplan ağzı da iyidir; siyah 2 ve 4 aşağı yukarı böyledir, beyaz tenuki yapabilir."),
'B-3-2-1-3-4': ("Siyah hane – fazla", 'bad', "Siyah 1 hanesi fazla güç kullanır; beyaz 2 ile mutlaka hane yapıp karşılık vermelidir. Siyah 3'ten itibaren güçlü hamleler yapar ama beyaz 8 ve 10 ile sakince cevap verir, siyah pek bir şey kazanmaz."),
'B-3-2-1-3-5': ("Beyaz yapışıp çıkar – eski", 'bad', "Eskiden beyaz 1 genelde yapışıp çıkardı; siyah 2 ve 4 ile iki taraftan rahatça yararlanır, beyaz önceki diyagramdan açıkça kötüdür."),
'B-3-2-1-4-1': ("Siyah yüksek pincer – ince", 'bad', "Siyah 1 yüksek pinceri şekil olarak incedir; beyaz 2 ile yapışıp çıkmak güçlüdür. Siyah 3 ile yan yana oynamak yerel olarak en güçlüsüdür, beyaz 4 ve 6 ile hafifçe sıyrılır; siyahın temposu biraz yavaştır."),
'B-3-2-2-1-1': ("Beyaz yapışıp uzar", 'situational', "Sağ alt beyazsa beyaz 1 ve 3 ile yapışıp uzamak da bir yoldur; sonuç eşittir. Ama sağ alt siyahsa siyah A civarında pincer yapar ve beyaz biraz sıkışır."),
'B-3-3-1-1-1': ("İki boşluklu pincer", 'ok', "Siyah 1 iki boşluklu pinceri de bir yoldur; beyaz 2 yapışması iyi hamledir. Siyah 3 ile 3-3'e uzamak doğrudur, beyaz 4 ve 6 ile rahatça çıkar; iki taraf da kabul edebilir."),
'B-3-3-1-2-1': ("Siyah hane – zayıf", 'bad', "Siyah 1 hanesi biraz zayıftır; beyaz 2 çift hanesi sıkıdır, siyah 3 kaplan ağzı şekildir. İki taraf istediğini alır, beyaz memnundur."),
'B-3-3-1-2-2': ("Beyaz keser – şüpheli", 'bad', "Önceki diyagramda beyaz 2 yerine 1'de kesmek şüphelidir; siyah 2 ve 4 ile atari yapıp çıkar ve değiş tokuş olur; siyah biraz önde."),
'B-3-3-1-3-1': ("Siyah dıştan hane", 'bad', "Siyah 1 ile dıştan hane de pek iyi değildir; beyaz 2 ve 4 ile keserek aşağı inmek çok güçlüdür, siyah 5 kosumi en güçlü cevaptır. Beyaz 8 ile zıplayıp çıkınca siyah 9 ve 11 ile sakince taş feda etmesi iyidir; beyaz biraz önde."),
'B-3-3-1-3-2': ("Beyaz sıkışır – fazla", 'bad', "Önceki diyagramda beyaz 6 yerine 1'de sıkışmak fazla güç kullanır; siyah 2 yapışması keskindir, sonrası birbirine bağlı hamlelerdir. Siyah 20'den 32'ye kadar çok güzel bir taş feda etme tekniği gösterir; beyaz önceki diyagramdan açıkça kötüdür."),
'B-3-3-1-3-3': ("Beyaz hane – yumuşak", 'ok', "Beyaz 1 hanesi biraz yumuşaktır; siyah 2 çift hanesi sıkıdır, sonuç eşittir."),
'B-3-3-1-4-1': ("Siyah dışarıya uzar – kötü", 'bad', "Siyah 1 ile dışarıya uzamak iyi değildir; beyaz 2'den itibaren rahatça şekli bitirir, siyahın verimi düşüktür."),
'B-3-3-2-1-1': ("Beyaz alttan yapışır – kötü", 'bad', "Beyaz 1 ile alttan yapışmak iyi değildir; siyah 2 hanesinden sonra B-3-3-1-2-2 diyagramına döner."),
'B-3-4-1-1-1': ("Bir boşluklu pincer – fazla sıkı", 'bad', "Siyah 1 bir boşluklu pinceri fazla sıkıdır; beyaz 2 yapışması yine kilit noktadır. Siyah 3 ve 5 ile çift hane en güçlüsüdür, beyaz 6'dan itibaren yerinde yerleşip memnun kalır."),
'B-3-4-1-2-1': ("Siyah 3-3'e uzar – zayıf", 'bad', "Siyah 1 ile 3-3'e uzamak biraz zayıftır; beyaz 2 ve 4 hafif oynar, işaretli siyah taş beyazın merkezine fazla yakın kalır; siyah memnun değildir."),
'B-3-4-1-3-1': ("Siyah içeriden hane – kötü", 'bad', "Siyah 1 içeriden hanesi iyi değildir; beyaz 2 çift hanesi sıkıdır, siyah 3 ile mecburen kaplan ağzı yapar. Beyaz 4 ve 6 ile siyahı kapatıp memnun kalır."),
'B-3-4-1-3-2': ("Beyaz keser – zayıf", 'bad', "Önceki diyagramda beyaz 2 yerine 1'de kesmek biraz zayıftır; siyah 2 ve 4 atarilerinin sırası değişebilir. Beyaz 7 ile dönmek iki tarafın kalınlığı için önemlidir, siyah 8 zıplaması güçlüdür, beyaz 9 ile sakince dönüp alması iyidir; siyah biraz önde."),
'B-3-4-1-3-3': ("Beyaz iter – kazançsız", 'bad', "Önceki diyagramda beyaz 9 yerine 1'de itmek kazançlı değildir; işaretli beyaz taş bütün canlılığını kaybeder. Nefesi de dar olduğu için beyazın A'da kesmesi siyahı tehdit etmez; beyaz önceki diyagramdan kötüdür."),
'B-3-4-1-4-1': ("Siyah dışarıya uzar – gevşek", 'bad', "Siyah 1 ile dışarıya uzamak biraz gevşektir; beyaz 4'ten itibaren sente ile şekli bitirir, sonra 12 ile karşı pinceri alıp çok canlı oynar."),
'B-3-4-2-1-1': ("Beyaz zıplar – gevşek", 'ok', "Beyaz 1 zıplaması biraz gevşektir; siyah 2 kosumi ile sağlam kalır. Beyaz 3 zıplaması hakkıdır, sonra beyaz 5 omuz vuruşu ile rahatça ilerler. İleride siyah fırsat bulunca A'dan itip savaşabilir; beyaz biraz memnun değildir."),
'B-3-4-2-2-1': ("Siyah vurur", 'ok', "Siyah 1 ile vurmak da bir yoldur, sonra siyah 3 ve 5 ile sade şekilde yönetip memnun kalır."),
'B-3-4-2-2-2': ("Siyah bu taraftan zıplar – fazla", 'bad', "Siyah 1 ile bu taraftan zıplamak biraz fazladır; beyaz 2 keimasi şekildir, sonra beyaz 6 ile karşı pincer güçlüdür; beyaz biraz daha etkindir."),
'B-3-4-2-3-1': ("Siyah keima ile kalkar – baskısız", 'ok', "Siyah 1 ile keima şeklinde kalkmak beyaza yeterince baskı yapmaz; beyaz 2 keimasi yine kilit noktadır, sonra 4 ve 6 ile hızla açılır. Sonuç eşittir."),
'B-3-4-3-1-1': ("Beyaz alttan yapışır – eski joseki", 'bad', "Beyaz 1 ile alttan yapışmak eski bir josekidir; sonrası beyazın biraz kayıp olduğu B-3-4-1-3-2 diyagramına döner."),
'B-3-4-3-2-1': ("Siyah uzar – kötü", 'bad', "Siyah 1 ile uzamak iyi değildir; kitaptaki A-1-3-1-2-1 şekline döner."),
}

T_IKIYUKSEKKAKARI = {
'B-4': ("Başlangıç pozisyonu", 'ok', "Beyaz komokuya iki boşluklu yüksek kakari ile yaklaşır. Siyahın cevapları: keima veya kosumi ile köşeyi kapatmak, keima ile kalkmak, karşı pincer ya da üstten yapışmak."),
'B-4-1-1-1-1': ("Siyah keima ile kapatır", 'best', "Siyah 1 keima ile köşeyi sağlamca kapatır; beyaz tenuki yapabilir. Bu, keima kapatmaya omuz vuruşu şekline döner; ayrıntısı B-6-1-2-1-1 diyagramındadır."),
'B-4-1-2-1-1': ("Beyaz bastırır", 'ok', "Beyaz 1 ile bastırabilir; siyah A'da sürünürse B-2-1-2-2-3, B'de dayanırsa B-2-1-3-2-1, C'de geri çekilirse B-2-1-3-3-1 diyagramına döner."),
'B-4-1-3-1-1': ("Beyaz engeller", 'situational', "Sağ alt beyazı destekliyorsa beyaz 1 ile engelleyebilir; B-3-2-2-1-1 diyagramına döner."),
'B-4-2-1-1-1': ("Siyah keima ile kalkar", 'ok', "Siyah 1 ile keima şeklinde kalkmak da çok yaygındır; beyaz 2 ile sade şekilde açılır, sonuç eşittir."),
'B-4-3-1-1-1': ("Siyah kosumi", 'ok', "Siyah 1 kosumisi sağlamdır; beyaz 2 omuz vuruşu ile B-2-2-3-1-1 diyagramına döner."),
'B-4-4-1-1-1': ("Siyah karşı pincer", 'ok', "Siyah 1 karşı pinceri de olur; beyaz 2 yapışması sıkıdır, siyah 3 dıştan hanesi en güçlüsüdür. Beyaz 6 ve 8 ile atari yapıp sertçe keser, siyah 9 atarisi ile önce köşede yaşar, sonra 11 kosumi ile çıkıp savaşır; iki taraf da savaşabilir."),
'B-4-4-1-1-2': ("Beyaz bağlanır", 'ok', "Beyaz 1 bağlanması sade ve oynanabilirdir; beyaz 3 ile köşeye hane yapınca siyah 4 ile hafifçe açılır. İki taraf da kabul edebilir."),
'B-4-4-1-2-1': ("Siyah 3-3'e uzar – isteksiz", 'bad', "Siyah 1 ile 3-3'e uzamak biraz isteksizdir; beyaz 2, 4 ve 6 ile zarif bir şekil kurar."),
'B-4-4-1-3-1': ("Siyah içeriden hane", 'bad', "Siyah 1 içeriden hanesi de pek iyi değildir; beyaz 2 ve 4 ile hane yapıp engellemek çok sıkıdır. Siyah 5'ten itibaren sakince sürünüp geçmesi iyidir; beyazın merkezi çok ferahtır."),
'B-4-4-1-4-1': ("Siyah dışarıya uzar – uygun değil", 'bad', "Siyah 1 ile dışarıya uzamak uygun değildir; beyaz 2 ve 4 çift hanesi güçlüdür, siyahın yerel olarak cevabı kalmaz. İleride bu, beyaz A–siyah B değiş tokuşu gibi görülebilir."),
'B-4-4-2-1-1': ("Beyaz keima – gevşek", 'bad', "Beyaz 1 keimasi biraz gevşektir; siyah 2 ile önce yapışmak kilit noktadır, sonra 6 ile akışında keima ile çıkar. Beyaz 9 ile omuz vuruşu yaparsa siyah 10'dan itibaren hemen keserek çıkabilir; beyaz savaşta biraz zorlanır."),
'B-4-5-1-1-1': ("Siyah üstten yapışır", 'bad', "Siyah 1 ile üstten yapışmak geçen yüzyılın ortalarında bir ara popülerdi; yapay zekâ bu hamleyi biraz acele görür, beyaz 2 yapışması doğru cevaplardandır. Siyah 3'ten itibaren sakince kaybı durdurmalıdır; beyaz biraz önde."),
}

T_YANDAN = {
'B-5': ("Başlangıç pozisyonu", 'ok', "Beyaz komoku taşının hemen yanına yapışır. Siyahın cevapları: alttan hane, üstten hane, dışarıya uzama ya da 3-3'e uzama."),
'B-5-1-1-1-1': ("Siyah alttan hane", 'best', "Siyah 1 ile alttan hane alana önem verir; beyaz 2 çift hanesi tutarlı bir devamdır. Siyah 3 ile sağlamca bağlanır, beyaz tenuki düşünebilir."),
'B-5-1-1-1-2': ("Beyaz bağlanır", 'bad', "Beyaz 1 ile de bağlanabilir; siyah 2 ile zıplayıp çıkarak memnun kalır. B-1-3-1-1-1'e beyaz A–siyah B gibi kaba bir değiş tokuş eklenmiş gibidir; siyah biraz kazançlıdır."),
'B-5-1-1-1-3': ("Beyaz uzar – ağır", 'bad', "Beyaz 1 ile uzamak biraz ağırdır; siyah 2 ile alttan hane yapıp alan alarak memnun kalır."),
'B-5-1-1-1-4': ("Siyah sürünür – zayıf", 'bad', "Siyah 1 ile sürünmek biraz zayıftır; B-2-1-2-4-1 diyagramına döner."),
'B-5-1-1-2-1': ("Siyah önce atari", 'situational', "Beyazın tenuki yapmasından çekinen siyah 1 ile önce atari yapıp beyazı ağırlaştırabilir. Beyaz 4 keimasi etkindir, siyah 5 yüksek pinceri iyi noktadır. Sağ alt siyahsa beyaz 6 ve 8 ile sabretmesi iyidir; siyah biraz iyidir."),
'B-5-1-1-2-2': ("Sağ alt beyazken", 'ok', "Sağ alt beyazsa beyaz 1 kosumisi inatçıdır, sonra beyaz 5 karşı pinceri ile savaş başlar; durum çok dengelidir."),
'B-5-1-1-2-3': ("Siyah sıkıca yaklaşır", 'ok', "Siyah 1 ile sıkıca yaklaşmak da olur; beyaz 2 ile keima ile inmek iyi noktadır. Siyah 3 ve 5 ile sakince hane yapıp geçer, beyaz 6 ile hızla açılır; iki taraf da kabul edebilir."),
'B-5-1-1-2-4': ("Siyah keser – fazla", 'bad', "Siyah 1 kesmesi biraz fazladır; beyaz 2 ve 4 ile taş feda etmek mükemmeldir. Sonra beyaz 12 ve 16 birbirine bağlı iyi hamlelerdir; siyahın taşları ağırlaşır."),
'B-5-1-1-2-5': ("Beyaz omuz vuruşu – fazla", 'bad', "Beyaz 1 omuz vuruşu fazladır; siyah 2 ve 4 ile sertçe itip keser. Beyaz 5 ile aşağı inip taş feda etmeye çalışır, siyah 6'dan itibaren sente dört taşı alıp memnun kalır."),
'B-5-1-1-2-6': ("Siyah da keima", 'ok', "Siyah 1 ile keima ile takip etmek sadedir; sonuç eşittir."),
'B-5-1-1-2-7': ("Beyaz sadece açılır – yumuşak", 'bad', "Beyaz 1 ile sadece açılmak biraz yumuşaktır; siyah 2 ile güçlüce bastırır, beyaz sıkışır."),
'B-5-1-1-3-1': ("Siyah keserek atari – kötü", 'bad', "Normal durumlarda siyah 1 ile keserek atari iyi değildir; B-1-3-2-2-1 diyagramına döner."),
'B-5-1-1-3-2': ("Çin açılışı gibi destek varken", 'situational', "Ama Çin açılışı gibi işaretli siyah taş olan durumlarda siyah 1 ve 3 ile atari yapıp bağlanarak savaşabilir. Beyaz 4 ve 6 ile sakince bir taşı sarıp almalıdır, siyah 7 atarisi atlanamaz; sonuç eşittir."),
'B-5-1-1-3-3': ("Beyaz dönüp çıkar", 'bad', "Beyaz 1 ile dönüp çıkarsa siyah 2 ile bastırmak güçlüdür. Beyaz 3 ve 5 ile imkân hazırlar, sonra 7 ile taş feda edip yön değiştirir; siyah 8 ile iş bırakmadan kapatır, beyaz biraz kayıptır."),
'B-5-2-1-1-1': ("Siyah üstten hane – kötü", 'bad', "Siyah 1 ile üstten hane genelde iyi değildir; beyaz 2 ile köşeye hane yaparak destek alır. Siyah 3 ile inatla çift hane yapar, beyaz 4 ve 6 ile sertçe atari yapıp keser. Siyah 7 ve 9 ile art arda bastırır, sonra 13 ile yaklaşmak iyi noktadır; değiş tokuşta beyaz öndedir."),
'B-5-2-1-1-2': ("Beyaz bağlanır – yumuşak", 'bad', "Beyaz 1 bağlanması biraz yumuşaktır; siyah 2 çift kaplan ağzı ile güzel şekil kurar, beyaz önceki diyagram kadar iyi değildir."),
'B-5-2-1-2-1': ("Siyahın hamleleri", 'bad', "Merdiven siyahın lehine olsa bile beyaz siyahın 1, 3 ve 5 hamlelerinden korkmaz; beyaz 6 ve 8 ile sente köşede yaşayıp memnun kalır."),
'B-5-2-1-2-2': ("Merdiven siyaha kötüyse", 'bad', "Merdiven siyahın aleyhineyse beyaz 1 ve 3 ile atari yapıp dönmek serttir; siyah 8 ağı ile taş feda etmek zorunda kalır, alan kaybı çok büyüktür."),
'B-5-2-1-3-1': ("Siyah bağlanır – gevşek", 'bad', "Siyah 1 bağlanması gevşektir; beyaz 2 ve 4 ile dolgun bir şekil kurar."),
'B-5-3-1-1-1': ("Siyah dışarıya uzar – kötü", 'bad', "Siyah 1 ile dışarıya uzamak genelde iyi değildir; beyaz 2 ve 4 ile aşağı inip açılarak memnun kalır."),
'B-5-3-2-1-1': ("Beyaz bastırır – çığ", 'ok', "Beyaz 1 ile bastırınca çığ şekli oluşur; ayrıntısı B-2-1-2 diyagramındadır."),
'B-5-3-2-2-1': ("Siyah başa hane", 'ok', "Siyah 1 ile başa hane de bir yoldur; beyaz 2 ile mutlaka köşeye hane yapmalıdır, siyah 3 kesmesi B-2-1-2-1-0 diyagramına döner."),
'B-5-3-2-2-2': ("Kaplan ağzı sonra zıplama", 'situational', "Sol üst siyahı destekliyorsa siyah 1 ve 3 ile kaplan ağzı yapıp zıplamak da olur; sonuç eşittir."),
'B-5-4-1-1-1': ("Siyah 3-3'e uzar", 'ok', "Siyah 1 ile 3-3'e uzarsa 3-3'e omuz vuruşu şekline döner; ayrıntısı kitapta C-1-1 diyagramındadır."),
}
