# Komoku + yüksek kakari → siyah alttan yapışır (B-2-1), kosumi (B-2-2), keima (B-2-3), zıplama (B-2-4)
T_ALTTAN = {
'B-2-1': ("Başlangıç pozisyonu", 'best', "Siyah 1 ile alttan yapışmak alana önem verir; oyuncular hep sevmiştir, yapay zekâ da en iyi seçimlerden biri sayar. Beyazın A'da hanesi sadedir ve sonrasında büyük değişim yoktur. B'de dayanmanın değeri çevreye çok bağlıdır, yapay zekâ birçok karışık josekiyi reddetti. C'de uzama duruma bağlıdır."),
'B-2-1-1-1-1': ("Alttan yapışıp geri çekilme josekisi", 'best', "Bu, 'alttan yapışıp geri çekilme' josekisinin temel şeklidir. Beyaz 3 bağlantısı sente gibidir, siyah 4 zıplaması genelde atlanamaz; ileride beyazın A ve B'de sente imkânları vardır."),
'B-2-1-1-1-2': ("Siyah ikinci sırada sızar", 'ok', "İleride siyah 1 ile ikinci sırada sızmak iyi bir işgal noktasıdır; beyaz 2 ile sıkışmak kaçırılmaması gereken bir sente kazancıdır. Siyah alan, beyaz merkez alır; sonuç eşittir."),
'B-2-1-1-1-3': ("Siyah kaplan ağzı – kötü", 'bad', "Önceki diyagramda siyah 3 yerine 1'de kaplan ağzı iyi değildir; beyaz 2 kesmesi zekicedir ve siyahın A'dan hane yapıp geçmesini sente ile önler."),
'B-2-1-1-1-4': ("Siyah tenuki yaparsa", 'bad', "B-2-1-1-1-1'de siyah 4 yerine tenuki yaparsa beyaz 1 ve 3 çok sıkıdır; siyah 4'ten itibaren kötü şekilde çıkmak zorunda kalır. Beyaz 7 keima ile tempo alır, iki tarafa da ulaşıp memnun kalır."),
'B-2-1-1-1-5': ("Siyah karşılık verir – fazla", 'bad', "Önceki diyagramda siyah 4 yerine 1'de karşılık vermek fazladır; beyaz 4'ten itibaren sente ile bir taşı alıp çok kazanır."),
'B-2-1-1-1-6': ("Siyah keima ile kalkar", 'situational', "Sol taraf destekliyse siyah 1 ile keima şeklinde kalkmak da olur."),
'B-2-1-1-1-7': ("Beyaz hemen yaklaşır", 'bad', "Siyahın desteği yoksa beyaz hemen yaklaşınca çok serttir; siyah 2 ile sabretmek zorunda kalır ve yerel olarak kazanç verir."),
'B-2-1-1-1-8': ("Siyah dayanır – kayıp", 'bad', "Siyah 1 ile dayanmak biraz kayıptır. Beyazın A'da kapatması çok büyük olduğu için siyah 3 ile zıplayıp çıkmak iyidir ama şekli yine incedir."),
'B-2-1-1-2-1': ("Beyaz kaplan ağzı", 'ok', "Beyaz 1 kaplan ağzı eskiden standart hamleydi; yapay zekâya göre siyaha yeterince baskı yapmaz, siyah tenuki yapabilir."),
'B-2-1-1-2-2': ("Beyaz keima", 'ok', "İleride beyaz 1 keimasi iyi hamledir; siyah 2 pinceri biraz iş bırakır, sonra siyah 6 ile keima şeklinde çıkmak çok büyüktür. Beyaz 7 ile güzel şekilde kapatır; iki taraf da kabul edebilir."),
'B-2-1-1-2-3': ("Siyah tenuki yaparsa", 'bad', "Önceki diyagramda siyah 2 yerine tenuki yapmak genelde iyi değildir; beyaz 1 keimasi sente ile kazanç sağlar."),
'B-2-1-1-2-4': ("Beyaz alttan yapışır – eski", 'bad', "Eskiden beyaz 1 ile alttan yapışmak daha yaygındı; siyah 2'den itibaren sade şekilde sente alır. Beyazın merkezi ferah olsa da siyah yerel olarak iki kez tenuki yapmış sayılır; siyah daha memnundur."),
'B-2-1-1-2-5': ("Siyah karşılık verir – fazla", 'bad', "Siyah 1 ile karşılık vermek fazladır; beyaz 2 ve 4 serttir, siyah zorlanır."),
'B-2-1-1-2-6': ("Siyah zorla ayırır – fazla", 'bad', "Siyah 1 ve 3 ile zorla ayırıp savaşmak biraz fazladır; beyazın iki grubu da zayıf değildir, siyahın köşesi de büyük değildir, beyazın korkacak bir şeyi yoktur."),
'B-2-1-1-2-7': ("Siyah vurur", 'ok', "Siyah 1 ile vurursa beyaz 2 ile bağlanması yeterlidir. Siyah 3 ile keima şeklinde kalkıp rahat şekil kurar, beyaz 4 ile bir sıra daha geniş açılabilir; sonuç eşittir."),
'B-2-1-1-2-8': ("Beyaz yapışıp kalkar", 'situational', "Sağ taraf destekliyse önceki diyagramda beyaz 2 yerine yapışıp kalkarak merkez kurabilir. Beyaz 7 ve 9 ile merkez için mücadele eder, siyah 10 ile bir kez itmek önemlidir; iki taraf da kabul edebilir."),
'B-2-1-1-2-9': ("Beyaz sade keima", 'ok', "Beyaz 1 ile sade şekilde keima da olur, siyah 2 keima ile kalkar; sonuç eşittir."),
'B-2-1-1-2-10': ("Beyaz bu taraftan yapışır – kötü", 'bad', "Merdiven iyi olsa bile beyaz 1 ile bu taraftan yapışmak iyi değildir; siyah 2 ve 4 rahat oynar. Beyaz 5 ile alttan yapışabilir ama şekli biraz tekrar eder."),
'B-2-1-1-2-11': ("Siyah zıplar – yavaş", 'ok', "Siyah 1 zıplaması temposu biraz yavaştır; beyaz 2 ile vurmak rahat bir sente kazancıdır. Sonra beyaz tenuki yapabilir ya da 4 civarında açılabilir."),
'B-2-1-1-2-12': ("Siyah işgal eder", 'ok', "İşaretli siyah taş yaklaşmışken siyah 1 ile işgal etmek sık kullanılır; beyaz 2'den itibaren savaştan kaçmaz. Siyah 7 hanesi geçişi önlemek için önemlidir, sonra siyah 11 yapışması etkindir; iki taraf da savaşabilir."),
'B-2-1-1-2-13': ("Beyaz esnek oynar", 'ok', "Beyaz 1 ve 3 esnektir, siyah 4 ile sakince sürünüp geçer. Beyaz 5 zıplaması iyi noktadır, siyah 10 keima ile sertçe saldırır; savaş yine zordur."),
'B-2-1-1-2-14': ("Beyaz bağlanmak ister – sıkışık", 'bad', "Beyaz 1 ile ikinci sırada keima yapıp bağlanmaya çalışmak fazla sıkışıktır; siyah 2 ve 4 ile itip pincer yaparak sertçe sıkıştırır. Siyah 10 kosumi de iyi hamledir; siyah çok kalınlaşır, beyaz hâlâ tamamen canlı değildir."),
'B-2-1-1-2-15': ("İkinci sırada keima – gevşek", 'bad', "Siyahın ikinci sırada keimasi gevşektir; beyaz 2 ile sade şekilde zıplar, siyah pek bir şey kazanmaz."),
'B-2-1-1-2-16': ("Siyah vurarak sorar", 'ok', "Siyah 1 ile vurarak beyazın cevabını sorar; beyaz 2 ile yapışıp kalkmak genelde A'da bağlanmaktan iyidir. Siyah 3 ile yapışıp kalkarak iyi şekil kurar; iki taraf da kabul edebilir."),
'B-2-1-1-2-17': ("Siyah sert işgal", 'ok', "Siyah 1 işgali serttir, beyaz 2 ile aşağı inmek en güçlü cevaptır. Siyahın köşesi B-2-1-1-2-11'dekinden biraz küçülür ama beyazın alanının içine bir pusu bırakır; kazanç ve kayıp dengelidir."),
'B-2-1-1-2-18': ("Beyaz bastırır – kayıp", 'bad', "Önceki diyagramda beyaz 2 yerine 1'de bastırmak biraz kayıptır; siyah 2 ile sente hane yapıp geçmek çok kârlıdır."),
'B-2-1-1-2-19': ("Beyaz tenuki – kötü", 'bad', "Beyazın tenuki yapması iyi değildir; siyah 1 kesmesi çok büyüktür, beyaz yerel olarak hâlâ tamamen yerleşmemiştir."),
'B-2-1-1-2-20': ("Beyaz yine tenuki", 'bad', "Beyaz bir kez daha tenuki yaparsa siyah 1 ile kalınca uzar ve işaretli iki beyaz taş kayıplı hamlelere dönüşür."),
'B-2-1-2': ("Çığ josekisi", 'situational', "Beyaz 1 ile dayanıp 3 ile hane yapınca ünlü 'çığ' şekli oluşur. Siyahın seçeneği çoktur: A'da hane yapıp kalkmak 'küçük çığ'a gider ve genelde en güçlüsüdür; B'de uzamak 'büyük çığ'a gidebilir; C'de aşağı inmek yapay zekânın yeni hamlesidir; D ve E duruma bağlıdır."),
'B-2-1-2-1-0': ("Küçük çığ", 'best', "Çoğu durumda yapay zekâ siyahın başa hane yapmasını önerir; ünlü 'küçük çığ' şekli oluşur. Beyaz A'da uzamakla B'de kaplan ağzı arasında seçim yapar; bu da çevreye ve merdivene çok bağlıdır."),
'B-2-1-2-1-1': ("Beyaz uzar", 'situational', "Merdiven iyiyken beyaz 1 uzaması doğrudur, siyah 2 ile engellemekten başka seçeneği yoktur; siyah 10'da beyaz bir seçim yapmalıdır."),
'B-2-1-2-1-2': ("Sağ alt beyazken", 'situational', "Sağ alt beyazsa beyaz 1 ile bastırıp çıkmak sıkıdır; iki taraf da merkeze koşar, savaş çok zordur."),
'B-2-1-2-1-3': ("Sağ alt siyahken", 'bad', "Sağ alt siyahsa beyaz savaşta dezavantajlıdır; önceki diyagramda siyah 6 yerine 1'de yaklaşmak güçlüdür, beyaz zorlanır."),
'B-2-1-2-1-4': ("Beyaz doğrudan ağ kurar", 'bad', "Bu yüzden sağ alt siyahken B-2-1-2-1-2'de beyazın doğrudan 1'de ağ kurması daha iyidir. Siyah 2 ve 4 ile itip keserek karşılık verir, beyaz 19'a kadar zorunlu hamleler gelir; siyah biraz önde."),
'B-2-1-2-1-5': ("Siyah keser – uygun değil", 'bad', "Önceki diyagramda siyah 4 yerine 1'de kesmek uygun değildir; beyaz 2 ile kaplan ağzı yapıp atari zekicedir, değiş tokuş beyazı memnun eder."),
'B-2-1-2-1-6': ("Beyaz taş feda eder", 'bad', "Beyaz 1 ve 3 ile taş feda etmek sade bir yoldur; siyah 4 ile sakince kapatır, siyah yine biraz iyidir."),
'B-2-1-2-1-7': ("Siyah merdivenle alır – şüpheli", 'bad', "Önceki diyagramda siyah 4 yerine 1'de iki taşı merdivenle almak şüphelidir; beyaz 2 ile engellemek iyi hamledir ve köşedeki nefes azaltmayı kullanarak solda çok kazanır."),
'B-2-1-2-1-8': ("Merdiven beyaza kötüyse", 'bad', "Merdiven beyazın aleyhineyse siyah 1 ile sürünebilir; beyaz ağır kaybeder."),
'B-2-1-2-1-9': ("Beyaz keser – işlemez", 'bad', "Önceki diyagramda beyaz 2 yerine 1'de kesmek işlemez; siyah 2'den itibaren beyazı sade şekilde merdivenle alır."),
'B-2-1-2-1-10': ("Beyaz kaplan ağzı", 'ok', "Bu yüzden merdiven kötüyse beyaz 1 ile kaplan ağzı yapmak zorundadır; siyah 2 yapışması sıkıdır. Siyah 10 ile sürününce beyaz 11 ve 13 ile önce nefes uzatır, sonra 17 ve 19 ile sakince taş feda eder. Siyah 24 ile zıplayıp çıkınca savaş başlar; siyah biraz daha etkindir."),
'B-2-1-2-1-11': ("Beyaz alttan yapışırsa", 'bad', "Önceki diyagramda beyaz 17 yerine 1'de alttan yapışırsa siyah 2 ile hane yapıp kalkmak doğaldır; değiş tokuş siyahı daha çok memnun eder."),
'B-2-1-2-1-12': ("Beyaz plansız uzar", 'bad', "Beyaz 1 ile sadece uzamak plansızdır; siyah 2 ile tek hamlede kapatır, beyazın iki grubu da zayıf kalır."),
'B-2-1-2-1-13': ("Siyah hemen köşeyi kapatır – kötü", 'bad', "Siyah 1 ile doğrudan köşeyi kapatmak iyi değildir; beyaz 2 ile sente dönmek iki tarafın kalınlığını çok etkiler, siyah açıkça kaybeder."),
'B-2-1-2-1-14': ("Siyah köşeyi engeller – yavaş", 'ok', "Siyah 1 ile doğrudan köşeyi engellemek biraz yavaştır. Sol üst siyahsa siyah 7 ile burna dayanmak işler, beyaz 8 ile sakince sarıp alır; sonuç eşittir."),
'B-2-1-2-1-15': ("Sağ alt siyahken uzama", 'bad', "Sağ alt siyahsa siyah 1 ile uzayıp çıkmak daha iyidir; beyaz 4 ve 6 tempolu oynar, siyah 7 kosumi ile iyi şekil kurar ve savaşta biraz önde olur. Yine de siyah B-2-1-2-1-10 kadar iyi değildir."),
'B-2-1-2-1-16': ("Sağ alt beyazken", 'ok', "Sağ alt beyazsa önceki diyagramda beyaz 6 yerine 1'de sakince zıplar, sonra beyaz 3 ile sade şekilde keima oynar; savaş dengelidir."),
'B-2-1-2-1-17': ("Beyaz ağ kurar – uygun değil", 'bad', "Beyaz 1 ağı uygun değildir; siyah 2 ile yapışıp çıkmak iyi hamledir. Beyaz 3'ten itibaren siyahı sıkıştırarak bir anlık keyif alır ama siyah 14 ile başa vurunca soldaki beyaz grup çok sıkışır."),
'B-2-1-2-1-18': ("Siyah atari – eski joseki", 'bad', "Siyah 1 atarisi eski bir josekidir; bu değiş tokuşta siyahın açıkça kaybettiği çoktan bilinir."),
'B-2-1-2-1-19': ("Siyah işgal eder – tuzak", 'bad', "Siyah 1 işgali bir tuzaktır; beyaz 2 ve 4 ile sakince cevap vermesi yeterlidir. Siyah 7 ağı ile beyazı kapatabilir ama yerel olarak çok hamle harcar; beyaz açıkça önde."),
'B-2-1-2-2-1': ("Siyah uzar – büyük çığ", 'bad', "Eski oyunlarda siyah 1 uzaması 'büyük çığ'a giderdi; yapay zekâya göre büyük çığ zorunlu değildir. Genelde beyaz 2 atarisi sade ve iyidir; sonra beyaz duruma göre A ya da B ile kapatır ya da tenuki yapar."),
'B-2-1-2-2-2': ("Siyah pincer yaparsa", 'bad', "Beyaz siyahın 1 pincerinden korkmaz; beyaz 2 ve 4 ile şeklini kolayca düzeltir."),
'B-2-1-2-2-3': ("Büyük çığ", 'situational', "Beyaz 1 ile bastırınca 'büyük çığ' oluşur; eskiden en karışık üç josekiden biriydi ve sonuç çevreye çok bağlıdır. Burada oyuncularla yapay zekâ çok farklı düşünür; eskiden kabul edilen varyasyonların hepsini yapay zekâ zorunlu görmez. Bu temel şekilden sonra siyahın A'da dışarı ve B'de içeri dönme gibi iki yolu vardır."),
'B-2-1-2-2-4': ("Siyah dışarı döner", 'best', "Siyah 1 ile dışarı dönmek en güçlüsüdür, sonra siyah 3 hanesi sıkıdır. Merdiven iyiyken beyaz 4 ile inatla bağlanır. Sağ alt beyazsa siyah 11 ile sakince sürünür, beyaz 14 ile bir taşı merdivenle alır; ileride köşede yavaş bir ko kalır, sonuç eşittir."),
'B-2-1-2-2-5': ("Beyaz uzamaya devam eder", 'situational', "Önceki diyagramda beyaz 12 yerine 1'de uzamaya devam edebilir; siyah 2 ile önce yapışmak gereklidir, beyaz 5 ve 7 ile atari yapıp engellemek en güçlüsüdür. Siyah 8 ve 10 ile sakince kapatır, sonra 12 ile zıplayıp çıkar ve merkezde zor bir savaş olur."),
'B-2-1-2-2-6': ("Siyah keima – fazla", 'bad', "Önceki diyagramda siyah 8 yerine 1'de keima biraz fazladır; beyaz 2 ile alttan yapışmak iyi hamledir, siyah 3 ve 5 ile yine köşede nefes azaltmaya dönmek zorundadır. Beyaz 8 ile keima şeklinde güzelce çıkar, köşede ko imkânı da kalır; siyah geride."),
'B-2-1-2-2-7': ("Siyah hane yaparsa", 'bad', "Siyah 1 ile hane yaparsa beyaz 4 ile dönmek iyi hamledir; siyah 5 ile hane yapıp karşılık vermek zorunda kalır, değiş tokuşta beyaz biraz önde."),
'B-2-1-2-2-8': ("Siyah dört taşı almak ister", 'bad', "Siyah 1 ve 3 ile açgözlüce dört taşı almak istemek iyi değildir; beyaz 6 ile önce keser, sonra 8'den itibaren zorla kapatır. Siyah 29 ve 33 ile nefes azaltarak almak zorunda kalır; siyah açıkça kaybeder."),
'B-2-1-2-2-9': ("Siyah önce yapışır – yanlış sıra", 'bad', "Siyah 1 ile önce yapışmak yanlış sıradır; beyaz 4 ve 6 ile sertçe karşılık verir. Beyaz 14 ile soğukkanlıca döner, siyah 15 ile bastırınca beyaz 16 ile zekice dönüp alır. Siyah 17 ile baş kaldırıp değiş tokuş etmek zorunda kalır; beyaz memnundur."),
'B-2-1-2-2-10': ("Siyah bağlanır – fazla", 'bad', "Siyah 1 bağlanması fazladır; beyaz 2'den itibaren sente değiş tokuşlardan sonra 10 ve 12 ile araya girip ters atari yapar, siyah çok zorlanır."),
'B-2-1-2-2-11': ("Sağ alt siyahken önce yapışma", 'situational', "Ancak sağ alt siyahsa siyah 1 ile önce yapışmak işler; beyaz 4 ile uzayıp çıkması daha iyidir, sonra beyaz 8 ile uzamak doğrudur. Siyah 11 ile beyaz 14 kendini güçlendirir, siyah 15 ile uzama noktasını alıp biraz daha etkin olur."),
'B-2-1-2-2-12': ("Beyaz uzar – fazla", 'bad', "Önceki diyagramda beyaz 14 yerine 1'de uzamak fazladır; siyah 2 keimasi güçlüdür, sonra siyah 6 ve 8 ile sertçe saldırır; beyaz zorlanır."),
'B-2-1-2-2-13': ("Bu durumda beyaz 1 işlemez", 'bad', "B-2-1-2-2-5'ten farklı olarak burada beyaz 1 işlemez; siyah 2'den 18'e kadar art arda güçlü hamleler yapar ve beyaz çökmenin eşiğine gelir."),
'B-2-1-2-2-14': ("Beyaz atari yapıp engeller", 'situational', "Sağ alt siyahsa beyaz 1 ve 3 ile doğrudan atari yapıp engellemek çok karışıktır, sonra beyaz 5 ile inatla dönüp alır. Siyah 16 ile sürünene kadar hepsi en güçlü hamlelerdir; beyaz bir seçim yapmalıdır."),
'B-2-1-2-2-15': ("Beyaz sakin uzar", 'situational', "Beyaz 1 ile sakince uzar, siyah 2 ve 4 ile önce altı yerleştirir; beyaz 5'ten itibaren iki taraf da en güçlü cevapları verir. Beyaz 21 hanesi köşeyi korur, siyah 22 ile başa dönmek çok değerlidir. İleride siyah A'da atari yapıp yerel ko kurabilir; siyah biraz daha etkindir."),
'B-2-1-2-2-16': ("Beyaz önce hane", 'situational', "Beyaz 1 ile önce hane de bir yoldur; beyaz 5'ten itibaren sente ile nefes uzatır, sonra 19 ile yan yana oynayıp siyahı alabilir. Ama beyaz solda çok büyük bedel öder; genel olarak siyah yine iyidir."),
'B-2-1-2-2-17': ("Siyah sadece uzar – gevşek", 'ok', "Siyah 1 ile sadece uzamak yeterince sıkı değildir; beyaz 2'den itibaren siyahı sıkıştırmak rahattır, sonra beyaz 16 ile yan yana oynamak iyi hamledir. Siyah 17 ile işgal edip 27'ye kadar gider; iki grup da yerleşir, sonuç eşittir."),
'B-2-1-2-2-18': ("Siyah doğrudan sürünür", 'situational', "B-2-1-2-2-14 fazla karışık geliyorsa siyah 1 ile doğrudan sürünmek de sade ve oynanabilirdir; sonrası B-2-1-2-2-4 ile aynıdır. Ama burada siyah 7 ile atari yapmak daha iyidir; siyah biraz önde."),
'B-2-1-2-2-19': ("Merdiven beyaza kötüyse", 'bad', "Önceki diyagramda merdiven beyazın aleyhineyse beyaz 1 ve 7 ile iki kez uzamak zorundadır. Siyah 8 ile kalınca kaplan ağzı yapar, sonra 10 ve 12 rahat sente kazançlarıdır; beyazın durumu kötüleşir."),
'B-2-1-2-2-20': ("Beyaz zıplar – gevşek", 'bad', "Beyaz 1 zıplaması gevşektir; siyah 2 ile rahat atari yapar, sonra 4'ten itibaren art arda sürünüp köşeyi alır. Beyaz 9 ile sakince uzar, siyah 10 ile rahatça baş kaldırır; beyaz önceki diyagramdan da kötüdür."),
'B-2-1-2-2-21': ("Beyaz önce solda kazanmak ister", 'bad', "Beyaz 1 ve 3 ile önce solda kazanç arar ama siyah 6 kaplan ağzından sonra beyaz iki arada kalır. Beyaz 7 ile uzarsa siyah 8 ile başa hane çok değerlidir; beyaz memnun değildir."),
'B-2-1-2-2-22': ("Beyaz önce taş alır – kötü", 'bad', "Önceki diyagramda beyaz 7 yerine 1'de önce taş almak köşedeki yarışı olumsuz etkiler; ileride beyazın A ve B hamleleri gote olur, siyah 8 ile kaplan ağzı yapıp çıkması serttir; beyaz savaşta dezavantajlıdır."),
'B-2-1-2-2-23': ("Sağ alt siyahken atari ve sürünme", 'situational', "Sağ alt siyahsa siyah 1 ve 3 ile doğrudan atari yapıp sürünmek de savaşılabilir. Siyah iki tarafta sürünüp beyazın köşesini alır, sonra 17 ile zıplayıp savaşır; siyah biraz daha etkindir."),
'B-2-1-2-2-24': ("Siyah uzar – kötü", 'bad', "Önceki diyagramda siyah 1 yerine uzarsa beyaz 2 ile dönmek iyi hamledir, siyah 3 ve 5 ile nefes uzatmak zorundadır. Beyaz 6 kaplan ağzı şekildir, siyah 13 ile inatla dayanır. Beyaz 14 ile sade değiş tokuş yapıp 18 ile sertçe engeller; köşedeki yarış ko olur, siyah açıkça geride."),
'B-2-1-2-2-25': ("Beyaz uzar", 'situational', "Merdiven iyiyken beyaz 1 ile uzamak da bir yoldur, siyah 2 kesmesi zorunludur. Beyaz 7 sürünmesi mükemmeldir, sonra beyaz 9 ile dönüp beş taşı öldürür ve çok alan kazanır."),
'B-2-1-2-2-26': ("Siyah taş feda eder – uygun değil", 'bad', "Siyah 1, 3 ve 5 ile taş feda etmek uygun değildir; beyaz sente ile üç taşı alıp çok memnun kalır."),
'B-2-1-2-2-27': ("Beyaz sadece kaplan ağzı – eski", 'bad', "Eskiden beyaz 1 ile sadece kaplan ağzı daha çok oynanırdı; siyah 4 ve 6 ile atari yapıp sürünmek doğrudur. Beyaz 7'den itibaren değiş tokuş etmek zorundadır, siyah 14'ten itibaren rahat sente kazanır; beyaz memnun değildir."),
'B-2-1-2-2-28': ("Siyah çift hane – eski joseki", 'bad', "Siyah 1 çift hanesi eski bir josekidir; beyaz 2 ile ikinci sırada dönmek kilit noktadır, siyah 3 ve 5 ile sakince taş feda etmelidir. Beyaz yine öndedir ama siyah B-2-1-2-2-24 ve B-2-1-2-2-26'dan daha iyi durumdadır."),
'B-2-1-2-2-29': ("Siyah içeri döner", 'ok', "Go Seigen içeri dönmeyi oynadıktan sonra siyah 1 içeri dönmesi standart hamle sayıldı; yapay zekâya göre dışarı dönmek daha iyidir. Beyaz A'da aşağı inmek ile B'de dönmek arasında seçim yapar."),
'B-2-1-2-2-30': ("Beyaz aşağı iner", 'best', "Yapay zekâya göre beyaz 1 ile aşağı inmek doğrudur. Beyaz 5 atarisi şekli bölmüş gibi görünür ama bu durumda en iyi hamledir. Sonra beyaz 7 ve 9 ile iki kez yapışıp sade şekilde taş feda eder; sonuç eşittir."),
'B-2-1-2-2-31': ("Beyaz doğrudan sarıp alır – yanlış sıra", 'bad', "Önceki diyagramda beyaz 7 yerine 1'de doğrudan sarıp almak yanlış sıradır; siyah 2 kesmesi keskindir, beyaz çok pasif kalır."),
'B-2-1-2-2-32': ("Beyaz sadece zıplar – yumuşak", 'bad', "Beyaz 1 ile sadece zıplamak biraz yumuşaktır, siyah 2 ile baş kaldırmak doğrudur. Sağ alt siyahsa beyaz 3 işgali taş feda eden iyi bir hamledir; siyah 4'ten itibaren sakince cevap verip memnun kalır."),
'B-2-1-2-2-33': ("Sağ alt beyazken", 'bad', "Sağ alt beyazsa önceki diyagramda beyaz 3 yerine 1'de pincer daha iyidir. Beyaz 3 ve 5 ile siyahın cevabını yoklar, siyah 6 ile nefes azaltmak doğrudur; beyaz 21'e kadar iki taraf da bir şey kazanır, siyah yine biraz iyidir."),
'B-2-1-2-2-34': ("Beyaz önce döner – eski", 'bad', "Eskiden beyaz 1 ile önce dönmek doğru sayılırdı; sonrası yaygın bir şekillenmedir. Siyah 12 ile hane yapıp kalkmak kilit noktadır; yapay zekâ siyahı çok etkin görür."),
'B-2-1-2-2-35': ("Siyah döner", 'bad', "Önceki diyagramda siyah 12 yerine 1'de dönüp sonra 3 ile bastırmak kaba bir hamledir; beyaz 6 ile önce işgal etmek incedir, beyaz 14 ile yapışıp çıkar. Siyah önceki diyagram kadar iyi değildir."),
'B-2-1-2-2-36': ("Siyah önce bağlanır – şüpheli", 'ok', "Siyah 1 ile önce bağlanmak biraz şüphelidir; beyaz 2 ile dönerek zaten kazanır. Siyah 5 ile karenin noktasına sert vurur ama beyaz 8 ve 10 ile iki taraftan sade şekilde açılır; sonuç eşittir."),
'B-2-1-2-2-37': ("Beyaz önce hane", 'best', "Önceki diyagramda beyaz 2 yerine 1'de önce hane de yapabilir; siyah 2 ile sadece aşağı inmek doğrudur. Beyaz 3 ile dönünce siyah 4 ile değiş tokuş etmek doğru karardır. Beyaz 5 kesmesi mükemmel zamanlamayla yoklar, siyah 6 ile sakince uzar; iki taraf da kabul edebilir."),
'B-2-1-2-2-38': ("Siyah merdivenle alır – uygun değil", 'bad', "Merdiven iyi olsa bile önceki diyagramda siyah 6 yerine 1'de bir taşı merdivenle almak uygun değildir. Beyaz 2 ile köşeyi almak sente gibidir, siyah 3 ile taş alıp beyazın A'daki atarisini önlemek zorundadır; siyahın temposu yavaşlar."),
'B-2-1-2-2-39': ("Siyah engeller – tuzağa düşer", 'bad', "Siyah 1 ile engellemek tuzağa düşmektir; beyaz 2 ile dönünce köşe ko ile ölür, siyah 3 ile bir hamle daha eklemek zorunda kalır, beyaz sente alıp memnun kalır."),
'B-2-1-2-2-40': ("Beyaz bu taraftan hane", 'ok', "Eskiden beyaz 1 ile bu taraftan hane daha çok oynanırdı; bu yaygın bir varyasyondur. Yapay zekâya göre beyaz B-2-1-2-2-37'den biraz kötü ama B-2-1-2-2-34'ten iyidir."),
'B-2-1-2-2-41': ("Siyah baş kaldırır – şüpheli", 'bad', "Siyah 1 ile baş kaldırmak şüphelidir; beyaz 2 ve 4 doğrudur, siyah 7 büyük keima en güçlüsüdür. Beyazın A civarında sente hamlesi olduğu için beyaz 8 ve 10 ile alttan yapışıp kesmek çok güçlüdür; savaşta beyaz biraz daha etkindir."),
'B-2-1-2-2-42': ("Siyah alttan yapışır – tuzak", 'bad', "Siyah 1 ile alttan yapışmak tuzak niyeti taşır; beyaz 2 ve 4 ile kesip uzaması yeterlidir, siyah savaşta dezavantajlıdır."),
'B-2-1-2-2-43': ("Siyah aşağı iner", 'ok', "Siyah 1 ile aşağı inmek sade bir yoldur ve karışık büyük çığdan kaçınır; beyaz 2 ve 4 ile art arda uzayıp merkez kurar, sonuç eşittir."),
'B-2-1-2-2-44': ("Siyah uzar – yumuşak", 'bad', "Siyah 1 uzaması yumuşaktır; beyaz B-2-1-2-2-1'e göre bir kez daha bastırmış olur ve açıkça kazanır."),
'B-2-1-2-3-1': ("Siyah aşağı iner – yeni hamle", 'ok', "Siyah 1 ile aşağı inmek de işler, sonra siyah 3 ve 5 ile sade şekilde çıkar; sonuç eşittir."),
'B-2-1-2-3-2': ("Siyah sürünür", 'ok', "Siyah 1 ile sürünmek de olur; B-2-1-2-2-43 diyagramına döner."),
'B-2-1-2-4-1': ("Siyah bağlanır – kayıp", 'bad', "Siyah 1 bağlanması biraz kayıptır; beyaz 2 ile bir kez uzayıp tenuki yapabilir, beyazın grubu saldırıya açık değildir."),
'B-2-1-2-5-1': ("Siyah çift hane – kötü", 'bad', "Siyah 1 çift hanesi genelde iyi değildir; beyaz 2 ve 4 ile bir taşı sarıp alır ve çok kalınlaşır."),
'B-2-1-3-1-1': ("Beyaz uzar", 'situational', "Beyaz 1 uzaması ilginç bir fikirdir; küçük çığdan kaçıp büyük çığa gitmek ister. Siyah 2 ile sürünmek doğru cevaplardan biridir ve B-2-1-2-2-3 diyagramına döner."),
'B-2-1-3-2-1': ("Siyah dayanır", 'ok', "Siyah 1 ile dayanmak da olur; beyaz 4 büyük zıplama ile merkez kurar, sonuç eşittir."),
'B-2-1-3-2-2': ("Beyaz keima", 'ok', "Beyaz 1 keimasi da bir yoldur; siyah 2 ile dönüp sade şekilde sente alır, yine eşittir."),
'B-2-1-3-2-3': ("Beyaz engeller – kötü", 'bad', "Beyaz 1 ile engellemek genelde iyi değildir; siyah 2 büyük zıplama ile ferah şekil kurar, beyaz önceki iki diyagramdan biraz kötüdür."),
'B-2-1-3-3-1': ("Siyah geri çekilir", 'ok', "Siyah 1 ile geri çekilirse beyaz tenuki düşünebilir; beyaz 2 ile dönerse B-2-1-1-1-1 diyagramına döner."),
'B-2-1-3-3-2': ("Beyaz alttan yapışıp merkez kurar", 'bad', "Beyaz 1 ile alttan yapışıp merkez kurmak genelde biraz kayıptır; siyah 2'den itibaren B-1-3-2-1-1 diyagramına döner."),
}

T_KOSUMI2 = {
'B-2-2': ("Başlangıç pozisyonu", 'ok', "Siyah yüksek kakariye 1 ile kosumi oynar. Beyaz engelleyebilir, alttan yapışabilir ya da keima ile kalkabilir; birçok varyasyon keima kakarideki kosumi-tsuke şekillerine döner."),
'B-2-2-1-1-1': ("Beyaz engellerse", 'ok', "Siyah kosumi oynayınca beyaz 2 ile engellerse B-1-3-1-1-1 diyagramına döner."),
'B-2-2-2-1-1': ("Beyaz alttan yapışırsa", 'ok', "Beyaz 1 ile alttan yapışırsa B-1-3-2-1-1 diyagramına döner."),
'B-2-2-3-1-1': ("Beyaz keima", 'ok', "Beyaz 1 keimasi da bir seçimdir; siyah 2 ile bir kez sürünüp tenuki yapabilir, siyah memnundur."),
'B-2-2-3-2-1': ("İkinci sırada keima – gevşek", 'bad', "Siyah 1 ile ikinci sırada keima gevşektir; beyaz 2 ile zekice sıkışır, siyah önceki diyagramdan açıkça kötüdür."),
'B-2-2-3-3-1': ("Siyah alttan yapışır – zayıf", 'bad', "Siyah 1 ile alttan yapışmak biraz zayıftır; beyaz 2 ve 4 ile sente değiş tokuş yapıp biraz kazanır."),
'B-2-2-3-3-2': ("Beyaz hane – fazla", 'ok', "Önceki diyagramda beyaz 2 yerine 1'de hane biraz fazladır; siyah 2 kesmesi serttir. Beyaz 3 ile sakince uzar, siyah 12 ile karşı pincer iyi noktadır, sonra siyah 14 ile güçlüce dayanır; değiş tokuş eşittir."),
'B-2-2-3-3-3': ("Beyaz uzar", 'situational', "Merdiven iyiyken önceki diyagramda beyaz 3 yerine 1'de uzayabilir; siyah 2 ve 4 en güçlü cevaplardır, sonra siyah 6 ile sakince bağlanır ve merkezde zor bir karşılıklı saldırı olur."),
'B-2-2-3-3-4': ("Merdiven beyaza kötüyse", 'bad', "Ama merdiven beyazın aleyhineyse önceki diyagramda siyah 6 yerine 1'de uzayabilir; beyaz 2'den itibaren ikinci sırada art arda sürünmek zorunda kalır, siyah açıkça etkindir."),
'B-2-2-3-3-5': ("Merdiven siyaha kötüyse", 'bad', "Merdiven siyahın aleyhineyse beyaz 1 ve 3 ile atari yapıp bastırmak işler; siyah iki tarafı birlikte kurtaramaz."),
}

T_KEIMA2 = {
'B-2-3': ("Başlangıç pozisyonu", 'bad', "Siyah yüksek kakariye 1 ile keima oynar. Eskiden çok yaygındı ama yapay zekâ bu hamleyi biraz kayıp görür; beyaz genelde köşeye alttan yapışır."),
'B-2-3-1-1-1': ("Beyaz köşeye alttan yapışır", 'bad', "Eskiden siyah 1 keimasi çok yaygındı ama yapay zekâ biraz kayıp görür. Beyaz 2 ile genelde köşeye alttan yapışır, siyah 3 karşı pinceri daha iyidir, beyaz 4 ve 6 ile yerinde yerleşir. Siyah iki tarafa da ulaşır ama köşeyi beyaza kaptırdığı için biraz memnun değildir."),
'B-2-3-1-2-1': ("Siyah hane – kötü", 'bad', "Siyah 1 hanesi iyi değildir; beyaz 2 ile geri çekilince şekli sağlamdır, siyahın tenuki yapması daha iyidir. Siyah A'da uzasa da B'de kaplan ağzı yapsa da beyazın C'de açılmasıyla değiş tokuş kayıplıdır."),
'B-2-3-1-3-1': ("Siyah hane yapıp keser", 'situational', "İşaretli siyah taş varken siyah 1 ile hane yapıp kesmek işler, sonra siyah 3 ve 5 çok güçlüdür. Beyaz 6'dan itibaren sakince köşede yaşar; bundan sonra iki beyaz taşın nasıl hareket edeceği sonucu belirler."),
'B-2-3-1-3-2': ("Beyaz döner – işlemez", 'bad', "Önceki diyagramda beyaz 6 yerine 1'de dönüp almak işlemez; işaretli siyah taş sayesinde siyah 4 ve 6 ile alttan geçer, beyaz çökmenin eşiğine gelir."),
'B-2-3-1-3-3': ("Destek yoksa", 'bad', "Çevrede destek yoksa siyah 1 ile köşeyi engellemek zorundadır; beyaz 4 ve 6 ile art arda rahat atari yapar, siyah açıkça geride."),
'B-2-3-2-1-1': ("Beyaz açılır – gevşek", 'ok', "Beyaz 1 ile açılmak gevşektir; siyah 2 ve 4 ile alttan yapışıp geri çekilerek çok alan kazanır. Sonuç eşittir."),
'B-2-3-2-2-1': ("Siyah işgal eder", 'ok', "Siyah 1 ile işgal etmek de bir yoldur; beyaz 2 ile yapışıp çıkınca siyah 3 ve 5 ile akışında sol taraftaki alanı alır, yine eşittir."),
}

T_ZIPLAMA = {
'B-2-4': ("Başlangıç pozisyonu", 'bad', "Siyah 1 zıplaması sağlamdır ama tempo biraz yavaştır. Beyaz genelde A'da alttan yapışır; B'de vurmak genelde acil durumda oynanan bir hamledir."),
'B-2-4-1-1-1': ("Alttan yapışıp geri çekilme", 'ok', "Beyaz 1 ve 3 ile alttan yapışıp geri çekilmek iyi hamlelerdir; siyahın tenuki yapması daha iyidir. Siyah A'da uzasa da B'de kaplan ağzı yapsa da beyazın C'de açılmasıyla değiş tokuş kayıplıdır."),
'B-2-4-1-2-1': ("Siyah hane yapıp keser", 'bad', "Siyah 1 ile hane yapıp kesmek de bir yoldur ama beyaz 6 ve 8 ile doğrudan yaşayıp memnun kalır. Siyah 11 ile zıplayıp çıktıktan sonra merkezdeki iki beyaz taş hâlâ çok canlıdır."),
'B-2-4-1-2-2': ("Beyaz zıplayıp çıkar", 'bad', "Beyaz 1 ile zıplayıp çıkmak sağlamdır, sonra beyaz 3 omuz vuruşu ile rahatça ilerler; beyaz sade şekilde önde."),
'B-2-4-1-2-3': ("Beyaz omuz vuruşu", 'bad', "Beyaz 1 omuz vuruşu da çok etkindir; siyah 2 ile iterse beyaz 3 yapışması önce siyahın cevabını sorar. Siyah 4 ile sakince uzar, beyaz 5 ile sola dönüp canlı oynar."),
'B-2-4-1-2-4': ("Beyaz bir kez daha atari – kazançsız", 'bad', "Beyaz 1 ile bir kez daha atari yapmak kazançlı değildir; siyah 4 ile dönmek şeklin kilit noktasıdır. Beyaz 5'ten itibaren merkeze rahat çıkar ama 13 ile yine yaşamak için geri dönmek zorundadır; beyaz önceki iki diyagram kadar iyi değildir."),
'B-2-4-1-2-5': ("Siyah kaplan ağzı – tuzak", 'bad', "Siyah 1 kaplan ağzı bir tuzaktır; beyaz 2 ile dönmek onu bozar, sonra beyaz 6 ve 8 sıkı hamlelerdir. Soldaki siyah grup çok sıkışır; beyaz açıkça önde."),
'B-2-4-1-2-6': ("Beyaz dönerek atari – kazançsız", 'bad', "Merdiven iyi olsa bile önceki diyagramda beyaz 2 yerine 1'de dönerek atari kazançlı değildir. Beyaz 3 ve 5 güçlü hamleler olsa da siyah 8 ile sakince taş feda eder; beyaz önceki diyagram kadar iyi değildir."),
'B-2-4-1-2-7': ("Beyaz köşede yaşar – tuzağa düşer", 'bad', "Beyaz 1'den itibaren köşede yaşamak tuzağa düşmektir; beyaz yine biraz iyidir ama önceki iki diyagram kadar değil."),
'B-2-4-2-1-1': ("Beyaz vurur", 'situational', "Siyahın sağ tarafta pinceri varken beyaz 1 ile vurmak acil durumda yerinde yerleşmek için oynanır. Siyahın tenuki yapması daha iyidir; sonuç eşittir."),
'B-2-4-2-2-1': ("Siyah yapışıp kalkar", 'ok', "Önceki diyagramda siyah 2 yerine 1'de yapışıp kalkabilir ama şekli biraz incedir."),
'B-2-4-2-2-2': ("Beyaz pincer", 'situational', "Merdiven iyiyken beyaz 1 pinceri keskin bir devam hamlesidir; siyahın tenuki yapması iyidir. Siyah 2 ile ısrarla iterek çıkarsa beyaz 3 ve 5 iyi sıradır, değiş tokuşta beyaz biraz önde."),
'B-2-4-2-2-3': ("Merdiven beyaza kötüyse", 'bad', "Merdiven beyazın aleyhineyse siyah 1 kaplan ağzından sonra beyazın cevabı yoktur."),
'B-2-4-2-2-4': ("Beyaz büyür", 'ok', "Merdiven kötüyse beyaz 1 ve 3 ile büyümeyi düşünebilir."),
'B-2-4-2-2-5': ("Siyah çiviler – yumuşak", 'bad', "Siyah 1 ile çivilemek biraz yumuşaktır; beyaz 2 ile sade şekilde açılıp memnun kalır."),
}
