# Mokuhazushi diğer kakariler (C-2-3, C-2-4, C-2-5) ve takamoku (C-3)
T_DIGER = {
'C-2-X': ("Başlangıç pozisyonu", 'ok', "Siyah 1 ile mokuhazushi oynar. Beyazın asıl cevapları 3-3 ve komoku kakaridir; burada daha az iyi üç yaklaşma var: A'da hoshi noktası, B'de takamoku kakari, C'de mokuhazushi kakari."),
'C-2-3-1-1-1': ("Hoshi noktasından yaklaşma", 'ok', "Beyaz 1 ile hoshi noktasından yaklaşmak 3-3 ve komoku kakariden biraz geridedir. Siyah 2 ile yapışıp kalkmak iyi hamledir; sonra iki taraf karşılıklı alan çevirir. Eşit."),
'C-2-3-1-1-2': ("Siyah bastırır", 'ok', "Siyah 1 ile bastırmak da olur; beyaz 2 ile aşağı uzayınca B-2-6-1-2-12 diyagramına döner."),
'C-2-3-2-1-1': ("Siyah köşeyi engeller – yumuşak", 'bad', "Siyah 1 ile köşeyi engellemek biraz yumuşaktır; B-5-3-1-1-1 diyagramına döner."),
'C-2-4-1-1-1': ("Takamoku kakari", 'ok', "Beyaz 1 takamoku kakari biraz gevşektir; siyah 2 ve 4 ile köşedeki alanı korur. Eşit."),
'C-2-4-1-1-2': ("Siyah yapışıp kalkar – ağır", 'bad', "Siyah 1 ile yapışıp kalkmak biraz ağırdır; beyaz 4 keima ile merkeze çıkıp memnun kalır."),
'C-2-4-2-1-1': ("Siyah 3-3'e zıplar – fazla sağlam", 'bad', "Siyah 1 ile 3-3'e zıplamak fazla sağlamdır; beyaz 2 ve 4 ile sade şekilde açılır, beyaz biraz iyidir."),
'C-2-4-3-1-1': ("Siyah yapışıp bastırır – kötü", 'bad', "Siyah 1 ile yapışıp bastırmak iyi değildir, beyaz 4 ile alttan yapışmak sıkıdır. Siyah 11 ve 13 en güçlü hamlelerdir; beyaz 14 ile önce yaşar, sonra beyaz 18 pinceri siyahı çok rahatsız eder. Savaşta beyaz açıkça iyidir."),
'C-2-4-3-1-2': ("Beyaz uzar – yeterli değil", 'bad', "Beyaz 1 ile uzamak yeterince iyi değildir; siyah 2 ile sürünürse B-2-6-2-2-1 diyagramına döner."),
'C-2-4-3-1-3': ("Siyah kaplan ağzı – iyi değil", 'bad', "Siyah 1 kaplan ağzı da pek iyi değildir; beyaz 2 ile tam başına atari yapmak çok rahattır. Hemen ardından beyaz 6 ile sertçe bağlar, siyah 7 ile kesip savaşır; beyaz çok aktiftir."),
'C-2-4-3-2-1': ("Beyaz araya girer – kazandırmaz", 'bad', "Merdiven beyazın lehine olsa bile beyaz 1 ile araya girmek ucuz değildir. Siyah 4 ile sakince aşağı uzar; beyaz 5 ile merdivenle alırsa siyah 6 ve 8 ile alanı alıp çok kazanır."),
'C-2-4-3-2-2': ("Beyaz döner", 'bad', "Beyaz 1 ile dönmek de bir yoldur; sonra iki taraf birer taş alır, önceki diyagramla eşit sayılır."),
'C-2-4-3-2-3': ("Siyah dıştan atari – kayıp", 'bad', "Siyah 1 ile dıştan atari alanı çok kaybettirir; beyaz çok memnun kalır."),
'C-2-4-3-3-1': ("Beyaz köşeyi alır", 'ok', "Beyaz 1 ve 3 ile köşeyi çok açık şekilde alır; siyah 4 ve 6 ile art arda hane sıkıdır. Siyahın merkezinde hâlâ kesme noktaları olduğu için beyaz memnundur."),
'C-2-4-3-3-2': ("Siyah sürünür – kötü", 'bad', "Siyah 1 ile sürünmek iyi değildir; C-2-4-3-2-3 diyagramına döner."),
'C-2-5-1-1-1': ("Mokuhazushi kakari", 'bad', "Beyaz 1 ile mokuhazushiden yaklaşmak da biraz gevşektir; siyah 2 ile 3-3'e zıplayınca C-1-4-2-1-1 diyagramına döner."),
}

T_TAKAMOKU = {
'C-3': ("Başlangıç pozisyonu", 'ok', "Siyah 1 ile takamoku oynar: köşe noktası dördüncü sırada, beşinci çizgidedir. Merkeze önem verir ama köşe boştur. Beyazın cevapları: A'da komoku kakari (doğru hamle), B'de 3-3 kakari, C'de mokuhazushi kakari."),
'C-3-1': ("Komoku kakari", 'best', "Beyaz 1 komoku kakari doğru hamledir; devamı B-2-12 diyagramındaki gibidir. Siyah bir köşeyi eksik almış sayıldığı için beyaz orada olduğundan daha iyidir."),
'C-3-2-1-1-1': ("3-3 kakari", 'ok', "Beyaz 1 3-3 kakari biraz daha zayıftır; siyah 2 keima doğru cevaptır ve C-2-1-1-1-1 diyagramına döner."),
'C-3-2-2-1-1': ("Siyah dışarıya keima – gevşek", 'bad', "Siyah 1 ile dışarıya keima gevşektir; beyaz 2 keima ile yerleşir, beyaz biraz iyidir."),
'C-3-2-2-2-1': ("Beyaz alttan yapışıp uzar", 'ok', "Beyaz 1 ve 3 ile alttan yapışıp aşağı uzamak da iyidir; sonra beyaz 7 pinceri ile keskince çıkar, beyazın köşesi doludur."),
'C-3-2-2-2-2': ("Beyaz keser – biraz fazla", 'ok', "Beyaz 1 ile kesmek biraz fazladır; siyah 2 ile uzayıp çıkar. Beyaz 3 ve 5 ile sakince köşeyi tamamlar, siyah 6 ile hızla açılır; beyaz önceki diyagram kadar iyi değildir."),
'C-3-2-3-1-1': ("Siyah kosumi – yavaş", 'bad', "Siyah 1 kosumisi biraz yavaştır, siyah 5 ile alttan yapışmak serttir. Beyaz 6 ve 8 ile dayanıp keserek geri adım atmaz; savaşta beyaz aktiftir."),
'C-3-2-4-1-1': ("Siyah alttan yapışır – fazla sıkı", 'bad', "Siyah 1 ile alttan yapışmak fazla sıkıdır, beyaz 2 pinceri iyi hamledir. Merdiven lehteyse siyah 3 ile aşağı uzamak ve siyah 5 ile içeriden atari en güçlüsüdür; ama beyaz 10 ve 12 ile ağ kurup bir taşı alarak sade şekilde iyidir."),
'C-3-2-4-1-2': ("Merdiven siyahın aleyhine", 'bad', "Merdiven siyahın aleyhineyse beyaz 1 ile merdivenle alır ve siyah çok kaybeder."),
'C-3-2-4-1-3': ("Siyah dıştan atari", 'bad', "Merdiven aleyhteyse siyah 1 ile dıştan atari yapmak zorundadır; beyaz 4 ve 6 ile karşı atari yapıp uzar ve çok memnun kalır."),
'C-3-2-4-1-4': ("Siyah bağlar, içeriden keser", 'bad', "Diğer taraftaki merdiven lehteyse siyah 1 ile bağlayıp siyah 3 ile içeriden kesebilir. Beyaz 4 ile sarıp alır, sonra beyaz 8 keima çok büyüktür; yine beyaz iyidir."),
'C-3-2-4-1-5': ("Siyah dıştan keser", 'bad', "Önceki diyagramda merdiven aleyhteyse siyah 1 ile dıştan kesmek zorundadır; beyaz 2 ve 4 ile sente bir taşı alıp çok kazanır, ileride A'da bakma imkânı da vardır."),
'C-3-2-4-2-1': ("Beyaz araya girer", 'ok', "Beyaz 1 ile araya da girebilir; siyah 2 ile içeriden atari en güçlü cevaptır. Merdiven aleyhteyse beyaz A'da atari ile B-5-2-1-2-1'e, lehteyse B'de dönüp atari ile B-5-2-1-2-2'ye döner; ikisinde de beyaz iyidir."),
'C-3-2-4-2-2': ("Siyah dıştan atari – iyi değil", 'bad', "Siyah 1 ile dıştan atari iyi değildir; beyaz 4'ten itibaren alanı alıp çok kazanır, siyahın merkezinde hâlâ zayıflık vardır."),
'C-3-2-4-2-3': ("Siyah kaplan ağzı", 'bad', "Siyah 1 kaplan ağzı yaparsa beyaz 2 ve 4 rahattır, sonra beyaz 6 ile aşağı uzamak kilit noktadır. Siyah 9 ile yapışıp tempo arar; beyaz 10 ve 12 ile sadece itip çıkarak memnun kalır."),
'C-3-2-4-3-1': ("Beyaz ikinci sırada hane", 'ok', "Beyaz 1 ile ikinci sırada hane de bir yoldur; sonra beyaz 3 ve 5 ile sente almak iyidir, yine beyaz öndedir."),
'C-3-2-4-4-1': ("Beyaz uzar – kötü", 'bad', "Beyaz 1 ile uzamak iyi değildir; siyah 2 ile bağlayınca A-2-3 diyagramına döner."),
'C-3-3-1-1-1': ("Mokuhazushi kakari", 'ok', "Beyaz 1 ile mokuhazushiden yaklaşırsa siyah 2 ile 3-3'ü korumak iyidir; C-1-4-1-1-1 diyagramına döner."),
'C-3-3-2-1-1': ("Siyah yapışır – kötü", 'bad', "Siyah 1 yapışması iyi değildir; beyaz 2 pinceri ile C-3-2-4-1-1 diyagramına döner."),
'C-3-3-2-2-1': ("Beyaz hane yapıp uzar", 'ok', "Beyaz 1 ve 3 ile hane yapıp uzamak da olur. Siyah 4 ile aşağı dönmek kilit noktadır, beyaz 5 ve 7 ile rahat bir şekil kurar."),
}
