# Hoshi + 2. sıradan keima (二路飞, "kapıyı tutan küçük şeytan")
T = {
'A-1-12': ("Başlangıç pozisyonu", 'situational', "Siyah 1, 2. sıradan keimadır; beyazın kökünü alıp saldırma amacı güçlüdür ve duruma göre oynanır. Beyazın dört ana cevabı var: A ve B'de kakari yapıp dönmek, C'de kapatmak ve D civarında açılmak."),
'A-1-12-1-1-1': ("Beyaz karşı kakari", 'best', "Beyaz 1 karşı kakari çok yaygındır; siyah 2 ile sade karşı pincer yapar, beyaz 3 ile basitçe açılır. Bu, beyazın diğer taraftan kakari yapmasına benzer; siyah A ile beyaz B değişimi beyaza biraz yarar."),
'A-1-12-1-2-1': ("Siyah kosumi", 'ok', "Siyah 1 kosumi de olur; beyaz 2 ile 3-3'e girmek iyidir, beyaz 4 ters kosumi akıllıcadır. Beyaz 6 ile önce itmek iyi sıradır; siyah 13 ile yine keima tamamlamak zorunda kalır, burada da beyaz biraz daha iyidir."),
'A-1-12-1-2-2': ("Beyaz iki aralık açılır – biraz yavaş", 'bad', "Beyaz 1 iki aralık açılma ya da A'da çok büyük keima biraz yavaştır; siyah tenuki yapabilir ya da B'de karşı pincer yapabilir."),
'A-1-12-1-3-1': ("Siyah kosumi ile vurur – şüpheli", 'bad', "Siyah 1 şüphelidir; beyaz 2 ile uzanınca sol taraf güçlenir. Siyah 3 keima ile ayırırsa beyaz 4 keima yeterlidir. Siyahın şekli zayıftır; A civarında destek gelse bile beyaza etkili saldıramaz."),
'A-1-12-2-1-1': ("Beyaz yüksek kakari", 'ok', "Beyaz 1 yüksek kakari genelde alçak kakariden kötüdür. Siyah 2 karşı pincer sıkıdır, beyaz 3 ile yapışmak bir yoldur; sonuç eşittir."),
'A-1-12-2-1-2': ("Beyaz zıplayıp ayırır", 'ok', "Beyaz 1 ile aşağı zıplayıp ayırmak da düşünülebilir; iki taraf da birer taşı kontrol eder, sonuç eşittir."),
'A-1-12-2-2-1': ("Siyah yapışıp geri çekilir – kötü", 'bad', "Siyah 1 kötüdür; beyaz A ile siyah B değişimi açıkça beyaza yarar, siyahın köşesinde incelik de kalır."),
'A-1-12-3-1-1': ("Beyaz kapatır", 'ok', "Beyaz 1 ile yerinde yaşamaya çalışır; siyah 2 ile sağlamca yapışınca Kosumi-tsuke josekisindeki bir şekle döner."),
'A-1-12-3-2-1': ("Siyah karşı pincer – sert", 'ok', "Siyah 1 karşı pincer serttir; beyaz 2 ile siyahın zayıflığını vurgular. Siyah 5 ters kaplan ağzı doğru şekildir; savaş dengelidir."),
'A-1-12-3-2-2': ("Siyah aşağı uzanırsa", 'bad', "Siyah 1 ile aşağı uzanırsa beyaz 2 pincer serttir; siyah 3 ve 5 ile sıkıca başını çıkarır. İki taraf birbirinin şeklini bozar; savaşta beyaz biraz öndedir."),
'A-1-12-3-2-3': ("Merdiven beyazın lehine – pincer", 'situational', "Merdiven beyazın lehineyse beyaz 1 pincer de iyi hamledir; siyah 2 ile bağlanıp sabretmek zorundadır. Beyaz 5 karşı pincer aktiftir, beyaz 7 hem şeklini tamamlar hem siyaha baskı yapar; savaşta beyaz öndedir."),
'A-1-12-3-2-4': ("Merdiven beyazın aleyhine", 'situational', "Merdiven beyazın aleyhineyse siyah 1 ile itip karşı saldırabilir. Beyaz 2 yapışma dolambaçlıdır, siyah 3 ile dönünce değişim olur; sonuç eşittir."),
'A-1-12-4-1-1': ("Beyaz açılır", 'ok', "Beyaz 1 ile açılmak sade ve oynanabilir; siyah 2 ile geniş açılmak iyidir. İki tarafın da birbirinin alanına girme imkânı vardır."),
'A-1-12-4-1-2': ("Siyah hemen girer – karışık", 'situational', "Siyah 1 ile hemen girmek çok karışıktır; siyah 3 ve 5 çok güçlü hamlelerdir, beyaz 8 ile önce atari vermek zorundadır. Siyah 15 atari iki tarafın kalınlığı için önemlidir; burada göz alanı köşeden daha önemlidir. Savaşta beyaz biraz daha rahattır."),
'A-1-12-4-1-3': ("Beyaz önce iter – kötü", 'bad', "Beyaz 1 kendi nefesini azaltır, kötüdür. Siyah 4 ile uzanınca beyaz 5 ile sabretmek zorundadır; siyah 10 ile zıplayıp dolgun şekil kurar, beyaz 11 ile gote tamamlar. Siyah belirgin kazançlıdır."),
'A-1-12-4-2-1': ("Beyaz büyük keima", 'ok', "Beyaz 1 büyük keima da oynanır; siyah 2 ile buna göre küçük açılır. Sonuç eşittir."),
'A-1-12-4-2-2': ("Siyah girer – aşırı", 'bad', "Siyah 1 fazladır; beyaz 2 ile yapışıp güçlü karşılık verir. Siyah biraz güç kazansa da köşesi boşalır; kazandığından çok kaybeder."),
'A-1-12-4-2-3': ("Siyah yapışır – biraz aşırı", 'bad', "Merdiven lehine olsa bile siyah 1 biraz fazladır. Beyaz 4 ile sakince uzanır, sonra beyaz 6 ve 8 ile taş feda edip savaşır. Beyaz 14 ve 16 siyahı çok rahatsız eder; köşedeki ölü taşları kullanıp iki taraftan kazanır, siyah biraz sıkışır."),
'A-1-12-4-2-4': ("Merdiven beyazın lehine – hane", 'situational', "Merdiven beyazın lehineyse beyaz 1 ile başa hane keskindir. Siyah 2 ile hane yapmak zorundadır, beyaz 5 ile doğal olarak aşağı zıplar; siyahın iki tarafı da zayıftır, savaş çok zordur."),
'A-1-12-4-2-5': ("Siyah keser – kötü", 'bad', "Siyah 1 kötüdür; beyaz 2 ve 4 ile atari verip çıkınca siyahın köşesi ağır hasar görür. Beyaz 8 ile 1. sırada hane iyi hamledir, siyah 9 ile merkezi korumak zorundadır. Beyaz 10 ile sente geçer, sonra beyaz 12 ile köşeyi boşaltmaya devam eder."),
'A-1-12-4-2-6': ("Beyaz sürünür – biraz yumuşak", 'bad', "Beyaz 1 biraz yumuşaktır; siyah 2 ile bastırmak sıkıdır, beyaz 3 ve 5 ile itip kesme noktası yaratmak zorundadır. Beyaz biraz iyidir ama önceki şekillerdeki kadar değil."),
}
