# Hoshi + yüksek iki aralık pincer (二间高夹)
T = {
'A-1-6': ("Başlangıç pozisyonu", 'best', "Yüksek iki aralık pincer de bir zamanlar popülerdi. Alçak iki aralık pincer gibi, yapay zekâya göre genelde alçak bir aralık ve üç aralık pincerden daha az iyidir. Beyazın seçenekleri: A'da 3-3 işgali, B'de zıplama, C ve D'de çift kakari, E'de iki aralık karşı pincer ya da tenuki."),
'A-1-6-1-1-1': ("3-3 işgali", 'best', "Beyaz 1 ile 3-3'e girmek sade ve iyidir. Siyah 8 ve 10 ile kalın olur ama temposu yavaştır."),
'A-1-6-1-1-2': ("Siyah tenuki – yanlış", 'bad', "Siyahın tenuki yapması yanlıştır. Beyaz 1 ile hemen uzanıp çıkmak serttir; siyah zor savaşır."),
'A-1-6-1-1-3': ("Beyaz uzanır – fazla iyimser", 'bad', "Beyaz 1 biraz fazla iyimserdir; siyah 2 ile dönüp sert karşılık verir. Köşedeki yarışı siyah bir nefesle kazanır ama beyaz 13 ile sente dönerek bir şey alır; siyah biraz daha iyidir."),
'A-1-6-1-1-4': ("Siyah bağlanır", 'ok', "Siyah 1 ile bağlanarak sente alabilir ama şeklinde bir zayıflık kalır; ileride beyazın A'da zıplama ve B'de yaklaşma gibi rahatsız edici hamleleri vardır."),
'A-1-6-1-1-5': ("Beyaz zıplar – karışık savaş", 'ok', "Beyaz 1 sonraki imkânlardan biridir; siyah 2 pincer en güçlü cevaptır, beyaz 3 ve 5 ile sertçe iter. Siyah 6 ile önce bastırmak incedir, beyaz 7 iyi hamledir. Siyah 12 ile sakince üç taşı alır, beyaz 13 ile döner; çözümü zor bir savaştır."),
'A-1-6-1-1-6': ("Siyah aşağı uzanır", 'ok', "Siyah 1 ile aşağı uzanıp savaşmak da olur; sonra siyah 3 ile girmek keskindir. Savaş dengelidir."),
'A-1-6-1-1-7': ("Beyaz uzanır – şüpheli", 'bad', "Beyaz 1 şüphelidir. Siyah 8 ve 10 ile itip kesme imkânı doğar, sonra siyah 14 ve 16 ile üst üste bastırmak güçlüdür; beyaz çok pasif kalır."),
'A-1-6-1-1-8': ("Önce araya girip bağlanmak", 'bad', "Siyah 1 ve 3 ile önce araya girip bağlanmak durumu değiştirir. Siyah ileride A'da bastırınca beyaz B'de uzanır; siyah A-1-6-1-1-5'tekinden çok daha kötüdür."),
'A-1-6-1-1-9': ("Siyah aşağı uzanır, sonra bastırır", 'bad', "Siyah 1 ile uzanıp 3 ile bastırırsa beyaz 4 ile geri bağlanmak iyi hamledir; siyah 5 mecburdur. Beyaz 6 ile hane yapınca merkezdeki üstünlük hemen beyaza geçer."),
'A-1-6-1-1-10': ("Beyaz önce pincer", 'bad', "Beyaz 1 ile önce pincer yaparsa siyah 2 kaplan ağzı güçlüdür, sonra siyah 4 ile bastırmak beyazı zorlar. Beyaz 5 uzanırsa siyah 6 ve 8 yeterlidir; beyaz tenuki ile kaybını sınırlamalıdır. Beyaz A'da uzanmakta ısrar ederse A-1-6-1-1-7'ye döner."),
'A-1-6-1-1-11': ("Beyaz kapatır", 'bad', "Beyaz 1 ile kapatırsa siyah 2 ve 4 ile hane yapıp bağlanabilir, sonra siyah 10 ve 12 sıkıdır; beyazın oyunu biraz sıkıcı kalır."),
'A-1-6-1-1-12': ("Beyaz yaklaşır", 'ok', "Beyaz 1 ile yaklaşmak da iyidir; siyah 2 ile genelde aşağı zıplar, beyaz sente kazanç sağlar."),
'A-1-6-2-1-1': ("Beyaz sıçrar", 'ok', "Beyaz 1 nispeten az oynanır. Sağ alt beyazsa beyaz 3 ile 3-3'e girmek olur. Beyaz 9 ile önce zıplamak akıllıcadır, siyah 10 ve 12 sakindir; sonuç eşittir."),
'A-1-6-2-1-2': ("Sağ alt siyahsa", 'situational', "Sağ alt siyahsa beyaz 1, 3, 5 ile yaşamaya çalışmak iyidir. Siyah 6 kosumi akıllıcadır, beyaz 7 ve 9 çok iyi savunmadır; siyah biraz daha iyidir."),
'A-1-6-2-1-3': ("Beyaz büyük keima – eski joseki", 'bad', "Beyaz 1 büyük keima eski bir josekidir; siyah 2 kosumi güçlüdür. Beyaz 3 ile yaklaşmak yarım adım geç kalır, siyah 4 yapışma keskindir; değişimde siyah belirgin kazanır."),
'A-1-6-2-1-4': ("Beyaz sürünüp bağlanır – duyarsız", 'bad', "Beyaz 1 duyarsızdır. Siyah 2 ve 4 ile beyazın şeklini çok iyi sıkıştırır; beyaz çok dar kalır."),
'A-1-6-2-1-5': ("Siyahın tuzağı", 'bad', "Siyah 1 ve 3 tuzak hamleleridir; beyaz 4 ile köşeye kosumi yaparak çözer. Siyah 5 ve 7 ile ayırınca beyaz 8 iyi hamledir; dışarıdaki grubu idare etmek zor değildir."),
'A-1-6-3': ("Çift kakari", 'best', "Beyaz 1 çift kakari çok yaygındır; siyahın birçok seçeneği vardır. Eskiden A ve B'de bastırma çok oynanırdı, C'de keima ile baskı da görülürdü. D'de omuz vuruşu, E'de fil adımı, F'de kosumi ile vurma ve G'de büyük keima da olur."),
'A-1-6-3-1-1': ("Güçlü taraftan bastırmak", 'best', "Siyah 1 \"güçlü tarafı bastır, zayıfı değil\" kuralına uyar. Beyaz 2 ve 4 aşağı yukarı böyledir; sonuç iki taraf için de kabul edilebilir."),
'A-1-6-3-1-2': ("Beyaz bastırır", 'ok', "Beyaz 1 ile bastırmak da olur; siyah 2 kaplan ağzı önemli noktadır. Beyaz 5 ile 3-3'e girince siyah 6 ve 8 ile ayırır. Siyah 10 ve 12 rahat sente hamlelerdir, sonra siyah 16 hane ile canlı bir şekil kurar."),
'A-1-6-3-2-1': ("Bu taraftan bastırmak – biraz kötü", 'bad', "Siyah 1 biraz kötüdür. Beyaz 2 ve 4 ile hane yapıp 3-3'e girmek sade ve iyidir."),
'A-1-6-3-2-2': ("Beyazın sonraki yapışması", 'ok', "İleride beyaz 1 yapışma iyi hamledir; siyah 2'den sonrası en güçlü cevaptır. Beyaz 13 ve 15 ile basitçe yaşar ve memnundur."),
'A-1-6-3-2-3': ("Siyah sürünür – aşırı", 'bad', "Siyah 1 fazladır; beyaz 2'den sonra rahatça yaşar. Siyah 7 ve 9 ile öldürmekte ısrar ederse beyaz 12 ve 14 güçlüdür; sonra A'da merdivenle iki taşı almak ya da B'de siyahı öldürmek seçeneklerinden biri kesin olur, siyah çöker."),
'A-1-6-3-2-4': ("Beyaz uzanır – eski joseki", 'bad', "Beyaz 1 eski bir josekidir. Siyah 6 kaplan ağzı sade ve güçlüdür, sonra siyah 10 ve 12 ile bir taşı almak çok büyüktür; siyah biraz daha iyidir."),
'A-1-6-3-2-5': ("Beyaz yapışır – biraz ağır", 'bad', "Beyaz 1 biraz ağırdır. Beyaz 5 ile yapışıp çıkınca siyah 6 ve 8 saldırının önemli noktalarıdır; beyaz 9'dan sonra sakince değişim yapar, siyah biraz daha iyidir."),
'A-1-6-3-2-6': ("Beyaz hemen 3-3 – biraz kötü", 'bad', "Beyaz 1 ile hemen 3-3'e girmek biraz kötüdür; siyah 2 ile kapatınca şekli kalın olur."),
'A-1-6-3-2-7': ("Beyaz bağlanır", 'bad', "Beyaz 1 bir önceki şekilden kötüdür; beyaz 3 ve 5 ile doğrudan hane yapıp bağlanmak daha iyidir. Beyaz 3 yerine A'da hane yapıp siyahın B'de geri çekilmesiyle değişmek kârlı değildir."),
'A-1-6-3-2-8': ("Siyah kaplan ağzı – kötü", 'bad', "Siyah 1 kötüdür. Beyaz 2 ile sürünüp bağlanınca siyah A'da tamamlasa mı tamamlamasa mı ikilemde kalır; tamamlarsa taşların verimi düşer."),
'A-1-6-3-2-9': ("Siyah tenuki yaparsa", 'ok', "Siyah tenuki yaparsa beyaz 1 ve 3 ile geçip bağlanır ve siyahın bütün grubu köksüz kalır. Beyaz 5 ile dürtmek de iyidir; siyah 6'dan sonrası böyledir, şeklinde yine zayıflık kalır."),
'A-1-6-3-2-10': ("Siyah ısrarla ayırır", 'bad', "Siyah 1 ve 3 ile ayırmakta ısrar ederse beyaz 6 ve 8 çok güçlüdür. Siyah 11 ile beş taşı alsa da ileride iki tarafta da nefes darlığı çeker; kazandığından çok kaybeder."),
'A-1-6-3-3-1': ("Keima ile baskı", 'ok', "Siyah 1 keima ile baskı da bir yoldur; beyaz 2 ve 4 ile köşeyi almak iyidir. Sonuç eşittir."),
'A-1-6-3-3-2': ("Beyaz 2. sıradan hane – biraz kötü", 'bad', "Beyaz 1 biraz kötüdür. Siyah 2'den sonra sol tarafa dönerek memnun olur."),
'A-1-6-3-3-3': ("Beyaz yapışıp keser – şüpheli", 'bad', "Beyaz 1 ve 3 şüphelidir. Beyaz 7 ile karşı atari mecburdur; siyahın şekli çok dolgun olur."),
'A-1-6-3-3-4': ("Beyaz uzanırsa", 'bad', "Beyaz 1 ile uzanırsa siyah 2 ve 4 iyi sıradır; değişimde siyah belirgin kazanır."),
'A-1-6-3-4-1': ("Siyah omuz vuruşu", 'ok', "Siyah 1 omuz vuruşu aktiftir; beyaz 2 ile itip karşılık verir. Beyaz 6 kosumi doğru şekildir, siyah 7 ile sakince yapışır; değişim iki taraf için de kabul edilebilir."),
'A-1-6-3-4-2': ("Sağ alt siyahı destekliyorsa", 'situational', "Sağ alt siyahı destekliyorsa önceki şekildeki siyah 7 yerine 1'de başını çıkarmak da olur. Beyaz 2, 4, 6 en güçlü cevaptır, sonra beyaz 10 ve 12 ile sakince taş feda eder; beyaz biraz daha iyidir."),
'A-1-6-3-4-3': ("Sağ alt siyahı desteklemiyorsa", 'situational', "Sağ alt siyahı desteklemiyorsa önceki şekildeki beyaz 10 yerine 1'de geri çekilmek olur, sonra beyaz 5 kesmesi serttir. Beyaz 13 hane yapınca siyah iki tarafı birden kurtaramaz."),
'A-1-6-3-4-4': ("Beyaz yapışıp keser – biraz kötü", 'bad', "Beyaz 1 ve 3 biraz kötüdür. Siyah 4 ve 6 ile önce dışarıdan sonra içeriden atari vermek doğru sıradır; beyaz A-1-6-3-4-1'deki kadar iyi değildir."),
'A-1-6-3-4-5': ("Beyaz 3-3 – biraz yumuşak", 'bad', "Beyaz 1 biraz yumuşaktır; işaretli siyah taş A-1-6-3-3-1'deki A noktasından biraz daha iyi yerdedir."),
'A-1-6-3-5-1': ("Siyah fil adımı", 'ok', "Siyah 1 fil adımı ilginçtir; beyaz 2 büyük keima sağlamdır, sonra siyahın tenuki yapması iyidir. Beyaz 4 keima yapınca siyah 5 ve 7 iki yapışma ile sadece şeklini düzeltir; sonuç eşittir."),
'A-1-6-3-5-2': ("Beyaz köşeye girer", 'ok', "Beyaz 1 ile köşeye girmek sadedir. İşaretli siyah taşın değeri A-1-6-3-3-1 ile A-1-6-3-4-5'teki taşlar arasındadır."),
'A-1-6-3-5-3': ("Beyaz yapışıp keser", 'ok', "Beyaz 1 ve 3 ile yapışıp kesmek de olur; siyah 4 ve 6 doğru hamlelerdir. İleride siyah A'da alır, beyaz B'de zıplar; iki taraf da savaşabilir."),
'A-1-6-3-5-4': ("Beyaz araya girer – tuzağa düşer", 'bad', "Beyaz 1 fil adımının ortasına girer ve tuzağa düşer; siyah 2 ve 4 ile doğal olarak itip keser, çözümü zor bir savaş olur. Siyah 26 ve 28 ile cesurca taş feda edip güç alır; çoğu durumda siyah daha iyidir."),
'A-1-6-3-6-1': ("Merdiven lehine – kosumi ile vurma", 'situational', "Merdiven siyahın lehineyse siyah 1 ile kosumi vurmak da bir yoldur. Siyah 8 ile sertçe girer, beyaz 14 ve 16 ile itip keser; siyah 17'den sonra 2. sırada zorla yaşar, beyaz biraz daha iyidir."),
'A-1-6-3-6-2': ("Merdiven aleyhine", 'situational', "Merdiven siyahın aleyhineyse siyah 1 ile kapatmak zorundadır; beyaz 2 ve 4 doğru sıradır. Siyah 7 ile 2. sırada zıplamak mecburdur; siyah 25 ile dönene kadar savaşta beyaz biraz öndedir."),
'A-1-6-3-6-3': ("Beyaz sürünür – yetersiz", 'bad', "Beyaz 1 yeterince iyi değildir. Siyah 4 ve 6 iyi taş fedasıdır, sonra siyah 12 ile iyi bir açılma yapar; beyaz önceki iki şekildeki kadar rahat değildir."),
'A-1-6-3-7-1': ("Siyah büyük keima – tuzak", 'ok', "Siyah 1 biraz tuzak hamlesidir; beyaz 2 keima ile sakince çıkar. Siyah 3 ve 5 en iyi toparlanmadır; beyaz 6'dan sonra basitçe köşeyi alıp memnun olur."),
'A-1-6-3-7-2': ("Beyaz karşı saldırır", 'bad', "Beyaz 1 ve 3 ile doğrudan karşılık verirse siyah 8 ve 10 ile önce köşede yaşar, sonra siyah 12 ile zıplayıp kapatmak güçlüdür; beyaz biraz sıkışır."),
'A-1-6-3-7-3': ("Beyaz yapışıp çıkar – biraz kötü", 'bad', "Beyaz 1 biraz kötüdür; siyah 2 ile doğal olarak yapışıp çıkar. Beyaz 3'ten sonrası böyledir; iki taraf da savaşabilir."),
'A-1-6-4-1-1': ("Yüksek çift kakari", 'ok', "Beyaz 1 ile yüksek çift kakari de olur; siyah 2 ile bastırmak normaldir. Beyaz 5 ve 7 ile köşeye girer, siyah 8 ile kalınca döner; iki taraf da kabul edebilir."),
'A-1-6-4-1-2': ("Beyaz 3-3 – kötü", 'bad', "Beyaz 1 kötüdür. Beyaz 5 ile tamamlamak zorundadır, yoksa siyahın A'da yapışma imkânı vardır."),
'A-1-6-4-1-3': ("Siyah hemen yapışır", 'ok', "Siyah 1 ile hemen yapışmak da çok keskindir; devamı alçak iki aralık pincerdeki şekille hemen hemen aynıdır."),
'A-1-6-4-1-4': ("Beyaz hemen 3-3 – yanlış", 'bad', "Beyaz 1 yanlıştır. Siyah 2 ile kapatınca şekli kalın olur, işaretli beyaz taş kötü yerde kalır."),
'A-1-6-4-1-5': ("Beyaz hane yaparsa", 'bad', "Beyaz 1 ile hane yaparsa siyah 2 keima yerel olarak iyi hamledir; siyah biraz daha iyidir."),
'A-1-6-4-2-1': ("Bu taraftan yapışmak", 'ok', "Siyah 1 ile bu taraftan da yapışabilir. Merdiven beyazın lehineyse beyaz 2 ve 4 ile hane yapıp köşeye girmek sadedir. Siyah 9 ve 11 esnek bir ko kurar, beyaz 18 ile sakince geri çekilir; iki taraf da kabul edebilir."),
'A-1-6-4-2-2': ("Siyah döner – biraz yavaş", 'bad', "Siyah 1 biraz yavaştır. Beyaz 2 ile bağlanınca kalın olur; siyah 3 ve 5 ile hane yapıp bağlanmak zorundadır, ileride beyazın A ve B'de rahatsız etme imkânları vardır."),
'A-1-6-4-2-3': ("Merdiven aleyhine – beyaz yapışmaya devam eder", 'situational', "Merdiven beyazın aleyhineyse beyaz 1 ile yapışmaya devam edebilir. Siyah 4 keima ile merkezdeki önemli noktayı alır, beyaz 5'ten sonra alt tarafta yaşar, siyah 10 ile yaklaşıp saldırır; iki taraf da savaşabilir."),
'A-1-6-4-2-4': ("Siyah yapışır", 'ok', "Siyah 1 yapışma da olur; beyaz 2 ile 3-3'e girmek bir yoldur. Siyah 3 ile önce kesmek doğru sıradır, böylece siyah 5 kapatması sente olur. Beyaz 6 ile sakince taşı sarar; iki taraf da kabul edebilir."),
'A-1-6-4-2-5': ("Siyah uzanır", 'ok', "Siyah 1 ile uzanmak da bir yoldur; beyaz 2 ile önce uzanmak akıllıcadır. Siyah 5 ve 7 ile itip kesince beyaz 8 ile sakince taşı sarar; iki taraf da savaşabilir."),
'A-1-6-4-2-6': ("Beyaz sürünüp bağlanır", 'ok', "Beyaz 1 ile sürünüp bağlanmak da olur; siyah 2 ve beyaz 3 başlarını çıkarır. Siyah tenuki ya da A'da tamamlamayı düşünebilir; iki taraf da oynayabilir."),
'A-1-6-4-2-7': ("Siyah önce kapatır – hata", 'bad', "Siyah 1 ile önce kapatmak hatadır. Siyah 3 ile kesince beyaz 4 dıştan atari ile taş feda eder; siyahın şekli tekrarlı olur."),
'A-1-6-4-2-8': ("Beyaz iki taşın başına hane", 'ok', "Beyaz 1 ile iki taşın başına hane de bir yoldur; iki taraf da birer taş alır ve kabul edebilir."),
'A-1-6-4-2-9': ("Siyah geri çekilir", 'ok', "Siyah 1 ile geri çekilmek de düşünülebilir, sonra siyah 5 hane güçlüdür; beyaz 18'e kadar iki taraf da geri adım atamaz. Beyaz 20 yapışma iyi hamledir ve birçok imkân yaratır; iki taraf da savaşabilir."),
'A-1-6-4-2-10': ("Siyah keser – biraz aşırı", 'bad', "Siyah 1 biraz fazladır. Beyaz 2 ve 4 sakindir, sonra beyaz 8 fil adımı tam yerindedir. İki taraf başını çıkarmaya çalışır; savaşta beyaz daha rahattır."),
'A-1-6-4-2-11': ("Siyah keser – biraz yumuşak", 'bad', "Siyah 1 biraz yumuşaktır. Beyaz 2 ile sürünüp bağlanması yeterlidir."),
'A-1-6-4-2-12': ("Beyaz hane ile keser – aşırı", 'bad', "Beyaz 1 fazladır. Siyah 4 ile bastırmak güçlüdür ve A-1-6-3-5-4'e döner."),
'A-1-6-4-2-13': ("Atari ve kapatma – biraz yumuşak", 'ok', "Siyah 1 ve 3 biraz yumuşaktır. Beyaz 4 ile kosumi yapıp taş feda etmek iyidir; sonuç eşittir."),
'A-1-6-4-2-14': ("Beyaz döner – zorlama", 'bad', "Merdiven beyazın lehine olsa bile beyaz 1 zorlamadır. Beyaz 9 ve 11 en güçlü cevaptır, siyah 12 ile geri adım atmaz. Beyaz 19 ve 21 iyi ko hamleleridir ama değişimden sonra siyah 28 ile önemli noktaya zıplar; savaşta siyah daha rahattır."),
'A-1-6-4-2-15': ("Merdiven beyazın aleyhine", 'situational', "Merdiven beyazın aleyhineyse siyah 1 ile hane yapabilir; beyaz devam edemez."),
'A-1-6-4-2-16': ("Siyah sürünür", 'ok', "Siyah 1'den sonra art arda sürünmek sade bir yoldur, sonra siyah 11 keima iyi noktadır. Genelde sağ altı elinde tutan taraf daha iyidir."),
'A-1-6-5-1-1': ("İki aralık karşı pincer", 'ok', "Beyaz 1 iki aralık karşı pincer bir zamanlar çok popülerdi; siyah 2 ile bastırmak bir yoldur. Beyaz 3 ile sade şekilde 3-3'e girer, siyah 6 ve beyaz 7 kendini tamamlar; sonuç eşittir."),
'A-1-6-5-1-2': ("Siyah kapatır – biraz kötü", 'bad', "Siyah 1 biraz kötüdür. Siyah 5 ile yine kosumi tamamlamak gerekir; beyaz 6 ile iki aralık açılarak hızlı olur."),
'A-1-6-5-1-3': ("Beyaz hane", 'ok', "Beyaz 1 hane de bir yoldur, sonra beyaz 7 ile sertçe keser; siyah 8 ve 10 ile geri adım atmaz. Beyaz 11 köşeye yapışınca siyah 12 yapışma sıkıdır; değişim iki taraf için de kabul edilebilir."),
'A-1-6-5-1-4': ("Merdiven lehine – beyaz araya girer", 'situational', "Merdiven beyazın lehineyse beyaz 1 ile araya girmek güçlüdür. Siyah 4 ile sertçe kapatır, beyaz 5 ile keser ve karışık bir savaş başlar. Siyah 10 ve 12 sert kapatma, beyaz 13 ve 15 keskindir; iki taraf da yaşar ve kabul edebilir."),
'A-1-6-5-1-5': ("Siyah bağlanır – biraz yumuşak", 'bad', "Siyah 1 biraz yumuşaktır. Beyaz 2 ve 4 ile güçlü şekilde taş feda eder, sonra beyaz 6 ve 8 çok rahattır; siyahın şekli ağırdır."),
'A-1-6-5-1-6': ("Siyah sade bağlanır", 'ok', "Siyah 1 ile bağlanmak sadedir; beyaz 4'ten sonra iki taraf istediğini alır. Siyah dış güç, beyaz alan alır."),
'A-1-6-5-1-7': ("Merdiven beyazın aleyhine", 'situational', "Merdiven beyazın aleyhineyse siyah 1 ve 3 işe yarar; beyaz iki tarafı birden kurtaramaz."),
'A-1-6-5-2-1': ("Merdiven lehine – siyah keima", 'situational', "Merdiven siyahın lehineyse siyah 1 keima da bir yoldur; beyaz 2'den sonra sade oynar. Sonuç eşittir."),
'A-1-6-5-2-2': ("Merdiven siyahın aleyhine", 'situational', "Merdiven siyahın aleyhineyse beyaz 1 ile köşeye girmek güçlüdür. Siyah 4 ile uzanmak zorundadır; beyazın şekli çok dolgundur, siyah memnun değildir."),
'A-1-6-5-2-3': ("Siyah ısrarla hane yapar", 'bad', "Siyah 1 ile ısrarla hane yaparsa beyaz 2 ile keser ve siyah zor durumda kalır; siyah belirgin kayıptadır."),
'A-1-6-5-2-4': ("Merdiven siyahın lehine", 'situational', "Merdiven siyahın lehineyse siyah 1 ve 3 ile hane yapıp bağlanmak işe yarar. Beyaz 4 ve 6 mecburdur; siyah 9 ile iki taşı alıp çok kazanır."),
'A-1-6-5-3-1': ("Siyah keima", 'ok', "Siyah 1 keima da düşünülebilir; beyaz 2 ile köşeye keima yapmak sadedir. Siyah 7 keima ile baskıya devam eder, beyaz 8 ile yerinde yaşar; sonuç eşittir."),
'A-1-6-5-3-2': ("Beyaz köşeye yapışır – biraz kötü", 'bad', "Beyaz 1 biraz kötüdür. Siyah 4 kaplan ağzı iyi hamledir, sonra siyah 6 ve 8 ile uzanıp hane yaparak rahat bir şekil kurar; beyaz memnun değildir."),
'A-1-6-5-4-1': ("Siyah kosumi ile vurur – biraz kötü", 'bad', "Siyah 1 biraz kötüdür. Beyaz 4 ile itip kesmek basit ama güçlüdür; siyah 5 ile aşağı uzanıp sabretmelidir, beyaz biraz daha iyidir."),
'A-1-6-5-4-2': ("Siyah bağlanırsa", 'bad', "Siyah 1 ile bağlanırsa beyaz 2 ve 4 serttir. Sonra beyaz 10 ve 14 ile çok iyi taş feda eder; siyahın taşları ağır kalır."),
'A-1-6-5-4-3': ("Beyaz köşeye yapışır – kötü", 'bad', "Beyaz 1 kötüdür. Siyah 2 ve 4 ile geniş bir şekil kurar; beyaz memnun değildir."),
'A-1-6-6-1-1': ("Beyaz tenuki – genelde kötü", 'bad', "Beyazın tenuki yapması genelde iyi değildir; siyah 1 ile kosumi vurmak serttir. Beyaz 4 ve 6 ile esnekçe dönmesi iyidir; savaşta siyah daha rahattır."),
}
