# Hoshi + alçak iki aralık pincer (二间低夹)
T = {
'A-1-5': ("Başlangıç pozisyonu", 'best', "Alçak iki aralık pincer bir zamanlar çok popülerdi. Yapay zekâya göre çoğu durumda alçak bir aralık ve üç aralık pincerden daha az iyidir, bu yüzden artık seyrek oynanır. Beyazın seçenekleri: A'da 3-3 işgali, B'de sıçrama, C ve D'de çift kakari, E'de iki aralık karşı pincer ya da tenuki."),
'A-1-5-1-1-1': ("3-3 işgali", 'best', "Beyaz 1 doğru hamlelerden biridir; siyah 8 ve 10 aşağı yukarı böyledir. İleride beyazın A'da büyük keima ya da B'de pincerden sonra C'de yapışma imkânı var; siyah biraz rahatsızdır."),
'A-1-5-1-1-2': ("Siyah tenuki yaparsa", 'ok', "Siyah tenuki yaparsa beyaz ileride 1 ile pincer yapıp savaşabilir; alçak pincer josekisindeki bir şekle döner."),
'A-1-5-1-1-3': ("Siyah sürünür – pek iyi değil", 'bad', "Siyah 1 de pek tatmin edici değildir. Siyah 3 ile yine bir hamle daha tamamlamalıdır; işaretli siyah taşın verimi düşüktür."),
'A-1-5-1-1-4': ("Siyah tenuki – beyaz yapışıp çıkar", 'ok', "Siyah tenuki yaparsa beyaz 1 ile yapışıp çıkmak serttir. Siyah 2 uzanma en güçlü cevaptır; beyaz 7 keima ile çıkıp çok kazanç sağlar."),
'A-1-5-1-1-5': ("Beyaz tek keima – biraz yumuşak", 'bad', "Beyaz 1 biraz yumuşaktır. Sağ alt siyahı destekliyorsa siyahın A'da zıplaması yine iyi bir noktadır."),
'A-1-5-2-1-1': ("Beyaz sıçrar", 'ok', "Beyaz 1 siyaha pek baskı yapmaz, siyah 2 ile beraber zıplaması yeterlidir. Beyaz 3 karşı pincer bir yoldur; siyah 4 kosumi ile vurmak akıllıcadır ve savaşta siyah daha rahattır."),
'A-1-5-2-1-2': ("Beyaz yaklaşır", 'ok', "Beyaz 1 aktif bir yaklaşmadır. Siyah 2 ve 4 ile sakin kosumiler, sonra siyah 6 ile kapatmak küçük görünür ama büyüktür. Beyaz iki tarafta da incedir, siyah rahattır."),
'A-1-5-2-1-3': ("Beyaz yerinde yaşar", 'ok', "Beyaz 1 ve 3 ile yerinde yaşamak da bir yoldur; yine siyah biraz daha iyidir."),
'A-1-5-2-1-4': ("Beyaz 3-3 işgali – kötü", 'bad', "Beyaz 1 kötüdür. Siyah 6 sürünme iyi hamledir, siyah 10 hane ile şekli çok dolgun olur."),
'A-1-5-2-2-1': ("Siyah keima", 'ok', "Siyah 1 keima da iyidir. Beyaz 8 ile kesme noktasını kapatmak zorundadır. Siyah 9 açılma çok hızlıdır; beyazın dış gücü işe yaramaz."),
'A-1-5-3': ("Çift kakari", 'best', "Beyaz 1 çift kakari çok yaygındır; siyahın birçok cevabı vardır. Yapay zekâ en çok A'da keima ile kapatmayı önerir. Eskiden B ve C'de bastırma daha yaygındı; D'de keima ile baskı, E'de kosumi ile vurma, F'de büyük keima ve G'de fil adımı da olur."),
'A-1-5-3-1-1': ("Siyah keima ile kapatır", 'best', "Eskiden oynanan A ve B'deki bastırmalar yerine yapay zekâ siyah 1'i önerir. Beyaz 2 ile 3-3'e girmek sade bir yoldur; iki taraf da oynayabilir."),
'A-1-5-3-1-2': ("Yapışıp kesmek", 'ok', "Beyaz 1 ve 3 ile yapışıp kesmek karışıktır. Siyah 4 ve 6 ile önce dışarıdan sonra içeriden atari vermek doğru sıradır. Siyah 8 ile itmek bir yoldur; sonuç eşittir."),
'A-1-5-3-1-3': ("Siyah bu taraftan iter", 'ok', "Siyah 1 ile bu taraftan itmek de olur; beyaz 2 ve 4 ile sade cevap verir. İki taraf da kabul edebilir."),
'A-1-5-3-1-4': ("Merdiven beyazın lehine", 'situational', "Merdiven beyazın lehineyse beyaz 1 ile kesip atari vermek güçlüdür. Siyah 4 ve 6 ile sakince taş feda eder, sonra siyah 8 ile kapatmak çok büyüktür. Beyaz 9 ile yine keser ve karışık bir savaş başlar."),
'A-1-5-3-1-5': ("Siyah bağlanır – gevşek", 'bad', "Siyahın bağlanması gevşektir. Beyaz 2 ile dönüp köşede dolgun alan alır; ileride A'da hane imkânı da vardır, siyahın dış gücü kalın değildir."),
'A-1-5-3-1-6': ("Yanlış sıra", 'bad', "Siyah 1 ve 3 yanlış sıradır. Beyaz 4 ile karşı atari akıllıcadır; siyah biraz kayıptadır."),
'A-1-5-3-2-1': ("Siyah bastırır – biraz yavaş", 'bad', "Siyah 1 biraz yavaştır. Beyaz 2 ve 4 ile köşeye girip dönmek sade ve iyidir; pincer taşı kötü yerde kalır. Beyazın ileride A'da yaklaşması iyi bir noktadır, sonra B'de aşağı uzanmayı hedefler."),
'A-1-5-3-2-2': ("Beyaz bağlanır – aşırı", 'bad', "Beyaz 1 fazla serttir. Siyah 2 ile kapatmak güçlüdür, siyah 6 yapışma sıkıdır. Beyaz 7 ve 9 mecburdur; siyah 12 ile pincer yapınca memnundur."),
'A-1-5-3-2-3': ("Beyaz bastırır", 'ok', "Beyaz 1 ile bastırmak da bir yoldur; siyah 2'den sonrası aşağı yukarı böyledir. Siyah 10 güçlüdür, beyaz 11 sağlam açılır; iki taraf da kabul edebilir."),
'A-1-5-3-3-1': ("Bu taraftan bastırmak – kötü", 'bad', "Siyah 1 ile bu taraftan bastırmak kötüdür. Beyaz 2 ve 4 ile yine hane yapıp köşeye girer; siyah A-1-5-3-2-1'deki şekilden de kötü durumdadır."),
'A-1-5-3-3-2': ("Siyah kapatır – şüpheli", 'bad', "Siyah 1 şüphelidir. Beyaz 2 ile sürünüp bağlanınca siyahın şekli kötüdür. Siyah 5 köşeyi tehdit edince beyaz 6 ve 8 ile keskin karşılık verir; değişimde beyaz daha çok kazanır."),
'A-1-5-3-3-3': ("Siyah uzlaşmazsa", 'bad', "Siyah 1 ile uzlaşmak istemezse beyaz 2, 4, 6 iyi sıradır; siyah 7 mecburdur. Beyaz 8 ile başını çıkarınca köşedeki üç siyah taş boşa gider."),
'A-1-5-3-3-4': ("Siyah bağlanır – çok rahatsız", 'bad', "Siyah 1 ile bağlanırsa beyaz 2 ve 4 ile hane yapıp bağlanır. Siyah A'da uzansa da B'de bağlansa da işaretli iki beyaz taş siyahın zayıf noktasındadır; siyah çok rahatsızdır."),
'A-1-5-3-3-5': ("Beyaz hemen 3-3", 'ok', "Beyaz 1 ile hemen köşeye girmek biraz kötüdür. Beyaz 5 kosumi doğru şekildir, siyah 6 ile itmek akıllıcadır; sonuç eşittir."),
'A-1-5-3-3-6': ("Siyah kaplan ağzı – kötü", 'bad', "Siyah 1 kötüdür. Siyah 3 ile yine tamamlamak gerekir; siyahın temposu çok yavaştır."),
'A-1-5-3-3-7': ("Siyah tenuki yaparsa", 'ok', "Siyah tenuki yaparsa beyaz 1 ile hareket etmek serttir. Siyah 2'den sonra en güçlü cevabı verir ama beyaz 9 ve 11 ile güçlü hamleler yapar; savaşta siyah zorlanır."),
'A-1-5-3-3-8': ("Siyah bastırır – plansız", 'bad', "Siyah 1 plansızdır. Beyaz 2 ile hane yapıp rahatça bağlanır; siyahın bütün grubu köksüz kalır."),
'A-1-5-3-4-1': ("Keima ile baskı", 'ok', "Siyah 1 keima ile baskı da olur; beyaz 2 ile köşeye girmek sadedir. Siyah 1 taşı A-1-5-3-1-1'deki A noktasından biraz kötüdür, işaretli beyaz taş daha canlı olur."),
'A-1-5-3-4-2': ("Beyaz yapışıp keser – kötü", 'bad', "Beyaz 1 ve 3 kötüdür. Siyah 4 ve 6 doğru sırayla oynar, sonra siyah 8 ve 10 ile itmek güçlüdür. Beyaz 11 ile sakince geri dönmek zorundadır; siyah belirgin şekilde iyidir."),
'A-1-5-3-4-3': ("İki taşı sarmak – eski yol", 'bad', "Eskiden beyaz 1 ve 3 ile iki taşı sararak yakalamak oynanırdı. Ama siyah 12 ile köşeyi alınca beyazın iki taraftaki şekli de kötüdür; savaş çok zordur."),
'A-1-5-3-4-4': ("Siyah bu taraftan iter – şüpheli", 'bad', "Siyah 1 biraz şüphelidir. Beyaz 4 ile kesip atari verir, beyaz 8 hane ise şekil için iyi hamledir; siyah önceki iki şekildeki kadar rahat değildir."),
'A-1-5-3-4-5': ("Yanlış sıra – ko", 'bad', "Siyah 1 ve 3 yanlış sıradır; beyaz 4 ile karşı atari akıllıcadır. Beyaz 10 ile sert uzanır ve ko ile karşılık verir; siyah zorlanır."),
'A-1-5-3-4-6': ("Beyaz keima ile çıkar – plansız", 'bad', "Beyaz 1 plansızdır. Siyah 2 ve 4 ile ayırıp savaşır, sonra siyah 10 ile köşeyi kapatan önemli noktayı alır; beyaz zor bir savaşa girer."),
'A-1-5-3-5-1': ("Kosumi ile vurup yapışmak", 'ok', "Siyah 1 ve 3 ile kosumi vurup yapışmak da bir yoldur; beyaz 4'ten sonra doğal olarak köşeye girer. Siyah 11 kesmesi iyi bir taş fedasıdır; iki taraf da kabul edebilir."),
'A-1-5-3-5-2': ("Merdiven beyazın lehine – büyük savaş", 'situational', "Merdiven beyazın lehineyse beyaz 1 ile 3-3'e zıplamak da olur; iki taraf da geri adım atmaz. Siyah 6 en güçlü cevaptır, beyaz 7 ve 9 iyi sıradır. Siyah 30'a kadar çözümü zor karışık bir savaş olur."),
'A-1-5-3-6-1': ("Siyah büyük keima", 'ok', "Siyah 1 biraz meydan okumadır; beyaz 2 keima ile keserek karşılık verir. Siyah 9 ve 11 güçlü, siyah 13 sakin taş fedasıdır. Siyah dış güç, beyaz alan alır; beyaz biraz daha iyidir."),
'A-1-5-3-6-2': ("Siyah hane – kötü", 'bad', "Siyah 1 kötüdür. Beyaz 2 ve 4 düzgün sırayla oynar, sonra beyaz 8'den itibaren atarilerle siyahı sıkıştırır; siyah belirgin şekilde kötüdür."),
'A-1-5-3-6-3': ("Siyah kosumi – biraz yavaş", 'bad', "Siyah 1 biraz yavaştır. Siyah 3 ve 5 ile kurtulsa da köşeyi tamamen beyaza kaptırır; siyah memnun olamaz."),
'A-1-5-3-6-4': ("Beyaz yapışıp çıkar – tuzağa düşer", 'bad', "Beyaz 1 tuzağa düşer. Siyah 2 ve 4 ile doğal şekilde itip keser. Siyah 10 saldırarak savunur, siyah 22 verimli tamamlamadır; beyaz zor savaşa girer."),
'A-1-5-3-6-5': ("Siyah yapışır – biraz pasif", 'ok', "Siyah 1 biraz pasiftir. Beyaz 2 ve 4 ile rahatça başını çıkarır; sonuç eşittir."),
'A-1-5-3-7-1': ("Siyah fil adımı", 'ok', "Siyah 1 fil adımı ilginçtir. Beyaz 2 ve 4 ile yapışıp kesmek bir yoldur; sonuç eşittir. Sonra beyazın tenuki yapması iyidir; ileride siyah A'da alır, beyaz B'de zıplar."),
'A-1-5-3-7-2': ("Beyaz köşeye girer", 'ok', "Beyaz 1 ile köşeye girmek sadedir. İşaretli siyah taş A-1-5-3-4-1'deki A noktasından biraz daha aktiftir."),
'A-1-5-3-7-3': ("Beyaz 2. sıradan keima", 'ok', "Beyaz 1 ile 2. sıradan keima da olur; siyah 2 ve 4 yapışmalarıyla iyi şekil kurar. Beyaz 9'dan sonra köşede yaşar, siyah 12 ile dışarıda savaşır; iki taraf da oynayabilir."),
'A-1-5-3-7-4': ("Beyaz araya girer – tuzağa düşer", 'bad', "Beyaz 1 fil adımının ortasına girer ve tuzağa düşer; siyah 2 ve 4 ile itip keser. Beyaz 9 yapışma zamanındadır ve beyaz 19 pinceri mümkün olur. İki taraf da yaşar ama siyah daha memnundur."),
'A-1-5-4-1-1': ("Yüksek çift kakari", 'ok', "Beyaz 1 yüksek çift kakari de bir yoldur; siyah 2 ile bu taraftan bastırmak yaygındır. Beyaz 3 ile hemen köşeye girmek iyidir; sonuç eşittir."),
'A-1-5-4-1-2': ("Beyaz hane yaparsa", 'bad', "Beyaz 1 hane yaparsa siyah 2 ile çapraz kesmek iyidir; beyaz 3 ve 5 en güçlü cevaptır. Siyah 8'den sonra sakince taş almak bir yoldur, sonra duruma göre A'da uzanır ya da B'de kosumi yapar. Beyazın dış gücü incedir, siyah memnundur."),
'A-1-5-4-1-3': ("Siyah döner", 'ok', "Siyah 1 ile dönmek de olur. Beyaz 2 ve 6 ile A'daki siyah taşı kesse de siyah 7 ve 9 iki iyi keimadır; savaşta siyah daha rahattır."),
'A-1-5-4-1-4': ("Beyaz aşağı iter", 'bad', "Beyaz 1 ile aşağı iterse siyah 2'den sonra taş feda ederek sade ve avantajlı oynar."),
'A-1-5-4-1-5': ("Beyaz köşede yaşar – olmaz", 'bad', "Beyaz 1'den sonra köşede yaşamak doğru değildir; işaretli beyaz taş ağır hasar görür."),
'A-1-5-4-1-6': ("Siyah uzanır – kötü", 'bad', "Siyah 1 kötüdür. Beyaz 2 ile sürünüp bağlanınca siyahın şekli kötüleşir; işaretli beyaz taş ileride de tehlike olarak kalır."),
'A-1-5-4-1-7': ("Beyaz önce hane – şüpheli", 'bad', "Beyaz 1 ile önce hane biraz şüphelidir. Beyaz 3 uzanma bir yoldur, sonra beyaz 5 ile yapışıp tempo arar. Siyah 6 ve 8 ile doğal olarak karşılık verir; siyah biraz daha rahattır."),
'A-1-5-4-1-8': ("Beyaz yapışırsa", 'bad', "Beyaz 1 ile yapışırsa siyah 2 kesmesi akıllıcadır; değişimde siyah biraz öndedir."),
'A-1-5-4-1-9': ("Siyah da hane yapar – biraz yavaş", 'bad', "Siyah 1 biraz yavaştır. Beyaz 4 yapışma verimli şekilde keseri kapatır, sonra beyaz 8 ve 10 ile itip keserek savaşır. Siyah 13 ve 15 sıkı oynar; beyaz duruma göre A ya da B'den çıkar, iki yol da karışık savaştır."),
'A-1-5-4-1-10': ("Beyaz 3-3 – kötü", 'bad', "Beyaz 1 kötüdür. Beyaz 5 ile tamamlamak zorundadır, yoksa siyahın A'da yapışması serttir."),
'A-1-5-4-1-11': ("Siyah hemen yapışır", 'ok', "Siyah 1 ile hemen yapışmak da olur; beyaz 2 ve 4 ile zorlamamalıdır. Siyah 3 ve 5 ile basitçe cevap verir, beyaz 6 ile bağlanınca siyah 7 ile tamamlar; siyahın temposu rahattır."),
'A-1-5-4-1-12': ("Beyaz dıştan hane – ko", 'situational', "Beyaz 1 dıştan hane yaparsa siyah 2 ile vurup keser ve karışık bir yarış başlar. Beyaz 5 dirençlidir; yarış ko ile biter. Beyazın tenuki yapıp ko tehdidi araması iyidir, durum çok karışıktır."),
'A-1-5-4-1-13': ("Beyaz hemen koyu alır – yanlış", 'bad', "Beyaz 1 ile hemen koyu almak yanlıştır. Siyah 2 ve 4 keskindir, siyah 10 ile geri alınca beyaz zor durumda kalır."),
'A-1-5-4-1-14': ("Siyah kapatır – kötü", 'bad', "Siyah 1 kötüdür. Beyaz 2 ile sürünüp bağlanır ve A-1-5-4-1-6'daki şekle döner."),
'A-1-5-4-2-1': ("Bu taraftan bastırmak", 'ok', "Siyah 1 ile bu taraftan da bastırabilir. Merdiven beyazın lehineyse beyaz 4 ile hemen 3-3'e girmek olur; sonuç eşittir."),
'A-1-5-4-2-2': ("Merdiven beyazın aleyhine", 'situational', "Merdiven beyazın aleyhineyse önce beyaz 1 ile bastırmak gerekir. Beyaz 7 ile sürünüp bağlanınca siyahın hemen tenuki yapması iyidir."),
'A-1-5-4-2-3': ("Beyaz kaplan ağzı", 'bad', "Beyaz 1 ile kaplan ağzı yaparsa siyah 2 ile vurmak doğru şekildir. Beyaz 3 ile köşeye girmek artık yarım adım geç kalır; siyah 4 keima iyidir, beyazın şekli biraz incedir."),
'A-1-5-4-2-4': ("Siyah yapışır – biraz kötü", 'bad', "Siyah 1 biraz kötüdür. Beyaz 2 ile köşeye girmek güçlüdür. Siyah 3 iyi kesmedir ama beyaz 4 ile sakince sürünür, sonra beyaz 6 hane ile rahatlar; beyaz biraz iyidir."),
'A-1-5-4-2-5': ("Beyaz aşağı uzanır", 'ok', "Beyaz 1 ile aşağı uzanırsa siyah 2 ile kapatmak güçlüdür. Beyaz 5 uzanınca siyah 6 hane ile değişim yapar; sonuç eşittir."),
'A-1-5-4-2-6': ("Siyah aşağı kapatır", 'ok', "Siyah 1 ile aşağı kapatmak da bir yoldur. Siyah 3 kaplan ağzı ve beyaz 4 uzanma iki iyi noktadır; iki taraf da kabul edebilir."),
'A-1-5-4-2-7': ("Siyah geri çekilir", 'bad', "Siyah 1 ile geri çekilirse beyaz 2 ile yine köşeye girer; siyah 3 ve 5 en güçlü cevaptır. Beyaz 12 siyahı çok rahatsız eder, beyaz 14 keima iyi noktadır; savaşta beyaz biraz önde."),
'A-1-5-4-2-8': ("Siyah aşağı hane – aşırı", 'bad', "Siyah 1 fazladır. Beyaz 4 kaplan ağzı iyi hamledir. Siyah 9 mecburdur, beyaz 12 ile aktif yapışır; siyah zor savaşır."),
'A-1-5-4-2-9': ("Siyah sıçrar – olmaz", 'bad', "Siyah 1 doğru değildir. Beyaz 2'den sonra tek hamlede taş feda eder; siyah çok kötü durumdadır."),
'A-1-5-4-2-10': ("Beyaz döner – kötü", 'bad', "Beyaz 1 kötüdür. Siyah 2'den sonrası zorunludur, siyah 14 hane ile merkeze rahatça çıkar. İleride beyazın A'da yapışması iyi hamledir; sonuç eşittir."),
'A-1-5-4-2-11': ("Siyah keser – biraz yumuşak", 'bad', "Siyah 1 biraz yumuşaktır. Beyaz 2 ile sürünüp bağlanması yeterlidir."),
'A-1-5-4-2-12': ("Beyaz hane ile keser – aşırı", 'bad', "Beyaz 1 fazladır. Siyah 4 ve 6 hane çok güçlüdür. Beyaz 9 yapışma sıkıdır, siyah 10 ve 12 doğru karşılıktır. Köşedeki yarış siyahın lehinedir; beyaz 23 ile taş feda etmek zorundadır, siyah belirgin iyidir."),
'A-1-5-4-2-13': ("Atari ve kapatma – eksik", 'bad', "Siyah 1 ve 3 iyi değildir. Merdiven beyazın lehineyse beyaz 4 ile dönmek güçlüdür, sonra beyaz 12 ile girmek keskindir; siyah zor bir seçimle karşı karşıyadır."),
'A-1-5-4-2-14': ("Siyah hane", 'ok', "Siyah 1 hane bir yoldur, sonra siyah 5 önemli noktadır. Beyaz 8 hane yapınca siyah 9 pinceri keskindir; savaş dengelidir."),
'A-1-5-4-2-15': ("Siyah sakince köşeyi tamamlar", 'ok', "Siyah 1 ve 3 ile sakince köşeyi tamamlamak da olur; beyaz 4'ten sonra iki taraf da başını çıkarır. İki taraf da savaşabilir."),
'A-1-5-4-2-16': ("Siyah aşağı hane – ko", 'bad', "Siyah 1 fazladır. Beyaz 2 ile girer, siyah 9 atariye kadar ko olur. Beyaz 10 ko tehdidi arar, siyah 11 ile karşılık verir, beyaz 12 sağlamdır. Sonunda uzlaşırlar; savaşta beyaz biraz öndedir."),
'A-1-5-4-2-17': ("Beyaz üstten atari – biraz kötü", 'bad', "Beyaz 1 biraz kötüdür. Siyah 2 ile kesip atari vermek zorunludur; değişimde beyaz önceki şekildeki kadar iyi değildir."),
'A-1-5-4-2-18': ("Merdiven beyazın aleyhine", 'situational', "Merdiven beyazın aleyhineyse siyah 1 ile hane yapabilir; beyaz çöker."),
'A-1-5-4-2-19': ("Merdiven aleyhine – taş feda", 'situational', "Merdiven beyazın aleyhineyse beyaz 1 ile kosumi yapıp taş feda etmek zorundadır; siyah biraz daha iyidir."),
'A-1-5-4-2-20': ("Siyah alan alır – biraz yumuşak", 'ok', "Siyah 1'den sonra alan almak biraz yumuşaktır; sonuç eşittir."),
'A-1-5-5-1-1': ("İki aralık karşı pincer", 'ok', "Beyaz 1 ile iki aralık karşı pincer de oynanır; siyah 2 keima sağlamdır. Beyaz merkeze rahat çıkar, siyah iki tarafı da alır ve memnundur."),
'A-1-5-5-1-2': ("Beyaz köşeye yapışır – biraz kötü", 'bad', "Beyaz 1 biraz kötüdür. Siyah 4 aşağı uzanma iyi hamledir; beyaz 9 ile bir kez daha tamamlamak zorunda kalır, taşların verimi düşüktür."),
'A-1-5-5-2-1': ("Siyah bastırır", 'ok', "Siyah 1 ile bastırmak da bir yoldur. Beyaz 2 ve 4 ile tempoyla çıkar, beyaz 10 ile göz yapmak esnektir; sonuç eşittir."),
'A-1-5-5-2-2': ("Beyaz köşeye yapışır", 'ok', "Beyaz 1 ile köşeye yapışmak da olur; siyah 6 yapışma sıkıdır. Beyaz 7 ve 9 ile siyah 8 ve 10 önemli noktaları paylaşır; iki taraf da savaşabilir."),
'A-1-5-5-2-3': ("Beyaz köşeye girer", 'ok', "Beyaz 1 ile köşeye girmek de bir yoldur; siyah 2 kaplan ağzı yeterlidir. Siyah 4 ve beyaz 5 kendini tamamlar, iki şekil de sağlamdır."),
'A-1-5-5-2-4': ("Beyaz araya girer – pek iyi değil", 'bad', "Merdiven beyazın lehine olsa bile beyaz 1 pek iyi değildir. Siyah 4 ile köşeyi kapatmak güçlüdür; beyaz 5 yapışma ile yararlanmaya çalışır, siyah 6 ile uzanıp savaşır ve biraz öndedir."),
'A-1-5-5-2-5': ("Merdiven beyazın aleyhine", 'situational', "Merdiven beyazın aleyhineyse siyah 1 ile sertçe uzanır; beyaz 2 ile itip taş feda etmek zorunda kalır. Beyaz 10'dan sonra köşeyi alsa da siyah 15 ile rahatça iter; beyaz belirgin kötüdür."),
'A-1-5-5-3-1': ("Siyah zıplar", 'ok', "Siyah 1 ile zıplamak da bir yoldur; sonra siyah 3 ve 5 ile sakince köşeyi korur. Sonuç eşittir."),
'A-1-5-5-4-1': ("Merdiven lehine – siyah keima", 'situational', "Merdiven siyahın lehineyse siyah 1 keima ile çıkabilir. Beyaz 2 yapışınca siyah 3 hane sıkıdır; beyaz 4 ve 6 sade oynar ve A-1-5-4-2-1'e döner."),
'A-1-5-5-4-2': ("Beyaz keser", 'situational', "Beyaz 1 kesmesi için merdivenin beyazın lehine olması gerekir. Siyah 2, 4, 6 ile doğal olarak alan alır, beyaz 7 ile bir taşı merdivenle yakalar; sonuç eşittir."),
'A-1-5-5-4-3': ("Merdiven siyahın aleyhine", 'situational', "Merdiven siyahın aleyhineyse beyaz 1 ile hemen köşeye girmek güçlüdür. Siyah 4 mecburdur; beyazın köşesi dolgundur, siyah memnun değildir."),
'A-1-5-5-4-4': ("Siyah hane – beyaz keser", 'bad', "Siyah 1 hane yaparsa beyaz 2 ile kesmek serttir. Siyah 5 ve 7 mecburdur; beyazın köşedeki alanı çok büyüktür."),
'A-1-5-5-4-5': ("Merdiven siyahın lehine", 'situational', "Merdiven siyahın lehineyse siyah 1 ile hane yapıp bağlanmak işe yarar; beyaz 4 ve 6 mecburdur. Beyazın köşe şekli öncekinden çok farklıdır; siyah belirgin iyidir."),
'A-1-5-5-4-6': ("Merdiven aleyhine – beyaz önce hane", 'situational', "Merdiven beyazın aleyhineyse beyaz 1 ile önce hane yapmak zorundadır, sonra beyaz 5 kesmesi bir fedakârlıktır; siyah biraz daha iyidir."),
'A-1-5-5-5-1': ("Siyah kosumi ile vurur – biraz kötü", 'bad', "Siyah 1 biraz kötüdür. Beyaz 4 ile büyük zıplama çok rahattır. Siyah 5 yapışarak tempo arar; değişimde beyaz biraz öndedir."),
'A-1-5-6-1-1': ("Beyaz tenuki", 'ok', "Beyaz tenuki yaparsa siyah genelde 1 ile kosumi vurur. Beyaz yine tenuki yapabilir; siyah 3 kaplan ağzı büyüktür, ileride beyazın A'da girme ve B'de hane imkânları kalır."),
'A-1-5-6-1-2': ("Beyaz uzanıp savaşır", 'situational', "Sağ alt beyazı destekliyorsa beyaz 1 ile uzanıp savaşabilir."),
'A-1-5-6-1-3': ("Beyaz esnek döner", 'situational', "Sol taraf değerliyse beyaz 1 ve 3 ile esnekçe dönmek de olur."),
'A-1-5-6-2-1': ("Siyah 3-3 kosumi", 'ok', "Siyah 1 ile 3-3'e kosumi serttir; beyaz 2 keima ile çıkar ve Bir Boşluklu Zıplama josekisindeki bir şekle döner."),
'A-1-5-6-3-1': ("Siyah keima", 'ok', "Siyah 1 keima yaparsa Keima josekisindeki bir şekle döner."),
}
