# Hoshi + ōgeima (大飞守角)
T = {
'A-1-10': ("Başlangıç pozisyonu", 'best', "Sol üst destekliyorsa büyük keima ile köşeyi kapatmak hem köşeyi hem kenarı gözetir, sol tarafı geliştirmeye yardım eder. Keimaya göre köşe daha boştur, bu yüzden yapay zekânın ilk tercihi A'da 3-3 işgalidir. Büyük keima bir çizgi daha geniş olduğu için B'de keima ve C'de yapışma pek iyi değildir."),
'A-1-10-1-1-1': ("3-3 işgali", 'best', "Beyaz 1 doğru hamledir; bu yaygın bir şekildir. Tahta boşken siyah şimdilik tenuki yapabilir; ileride beyazın A'da kesmesi çok değerlidir."),
'A-1-10-1-1-2': ("Siyah önce sürünür", 'situational', "Sağ taraf değerliyse siyah 1 ile önce sürünür, sonra siyah 5 karşı pincer ile gelişme yönünü sağa çevirir."),
'A-1-10-1-1-3': ("Siyah bağlanır", 'ok', "Siyah 1 ile bağlanmak da olur, sonra siyah 3 ile kalınca bastırır; siyah 9 keima ile tamamlayınca iyi şekil kurar. İki taraf da kabul edebilir."),
'A-1-10-1-1-4': ("Beyazın sonraki pinceri", 'ok', "İleride beyaz 1 pincer yapınca siyah tenuki yapabilir. Beyaz 3 kesmesi devam hamlesidir; siyah 4 ve 8 ile sakince taş feda eder, sonuç eşittir."),
'A-1-10-1-1-5': ("Beyaz sürünür", 'ok', "Beyaz 1 ile sürünmek de olur; siyah 2 kaplan ağzı iyi şekildir. Beyaz 5 hane siyahı sınar, siyah 8 ile rahatça tamamlar. Beyaz 9 ile pincerden çıkıp alan alır; iki taraf da savaşabilir."),
'A-1-10-1-1-6': ("Siyah vurur – beyaza yarar", 'bad', "Siyah 1 beyazın işine yarayabilir. Beyaz 2 pincer siyahı sınar; siyah 3 büyük zıplama ile tamamlamak iyidir."),
'A-1-10-1-1-7': ("Siyah 1. sırada hane", 'bad', "Siyah 1 ile 1. sırada hane yapıp bağlantıyı keserse beyaz 2 ile zıplamak siyahı rahatsız eder. Siyah 3 yapışma hem başını çıkarır hem keseri korur, beyaz 4 ve 6 geri adım atmaz. Siyah 7 ile iki taşın başına hane, sonra siyah 9 ile kesmek sıkıdır; değişim olur, siyah biraz memnun değildir."),
'A-1-10-1-1-8': ("Beyaz geri çekilir – biraz yumuşak", 'bad', "Beyaz 1 biraz yumuşaktır. Siyah 2 ile geri çekilince şekli tamamlanır; siyah önceki şekilden biraz daha iyidir."),
'A-1-10-1-1-9': ("Beyaz hemen sürünür – kötü", 'bad', "Beyaz 1 kötüdür. Siyah 2 ile köşede hane yapmak önemli noktadır, beyazın köşesi belirgin küçülür. Beyaz 7 ve 9 ile itip keserek savaşmak zorundadır ama siyahın iki grubu da zor değildir; beyaz biraz zorlanır."),
'A-1-10-1-1-10': ("Beyaz tek keima – kötü", 'bad', "Beyaz 1 de kötüdür; siyah 2 ile aşağı uzanmak önemli noktadır. Beyaz 3 ile sürünerek sente alsa da siyah 8 ile girince beyazın köşesi çok daralır. Beyaz 9 mecburdur, siyah 10 ile sente açılır."),
'A-1-10-1-2-1': ("Siyah hane – kötü", 'bad', "Siyah 1 kötüdür. Beyaz 2 ve 4 ile önce hane yapıp bağlanmak doğru sıradır, sonra beyaz 6 ile sente hane yapınca köşede tamamen yaşar. Beyaz 8 pincer sıkıdır; siyahın şekli kötüdür."),
'A-1-10-1-2-2': ("Beyaz önce bu taraftan hane – kötü", 'bad', "Beyaz 1 kötüdür. Siyah 2 ile bağlanmak akıllıcadır; siyahın şekli önceki şekilden çok daha kalındır."),
'A-1-10-2-1-1': ("Beyaz 2. sıradan keima – biraz kayıp", 'bad', "İşaretli siyah taş A'daki keimadan bir çizgi uzakta olduğu için beyaz 1 ile yine 2. sıradan keima yaparsa siyah 2 ile 3-3'e kosumi yapabilir; beyaz biraz kayıptadır."),
'A-1-10-3-1-1': ("Beyaz yapışır – biraz kayıp", 'bad', "Beyaz 1 yapışma da biraz kayıptır. İşaretli siyah taş A'daki keimadan bir çizgi uzakta olduğu için siyah daha memnundur."),
'A-1-10-4-1-1': ("Beyaz tenuki", 'ok', "Beyazın tenuki yapması da bir yoldur. Büyük keima köşesi zayıf olduğu için siyah 1 ile kosumi vurmanın gücü de azalır. Siyah 3 pincer yapınca beyaz 4 keima ile girmek iyi hamledir, sonra beyaz 6 ile doğal olarak uzanıp çıkar; oynanabilir."),
'A-1-10-4-1-2': ("Beyaz iter – fazla sıkı", 'bad', "Beyaz 1 fazla sıkıdır; siyah 2 kaplan ağzı ile güçlü karşılık verir. Beyaz sol tarafta biraz kazansa da bütünü inceldiği için kazandığından çok kaybeder."),
'A-1-10-4-2-1': ("Siyah alçak bir aralık pincer", 'ok', "Siyah 1 ile alçak bir aralık pincer de olur; beyaz 2 ile zıplayıp savaşabilir. Siyah 3 ile beraber zıplarsa beyaz 4 ile köşeye girmek sadedir. Siyah 7 ile sağlamca döner; sonuç eşittir."),
'A-1-10-4-2-2': ("Siyah aşağı hane", 'ok', "Siyah 1 ile aşağı hane de olur; beyaz sente köşeyi alır ve dışarıdaki iki taşın imkânlarını saklar. İki taraf da kabul edebilir."),
'A-1-10-4-2-3': ("Beyaz doğrudan köşeye girer", 'ok', "Beyaz 1 ile doğrudan köşeye girmek de olur; siyah 4 ile sakince döner. Sonuç eşittir."),
'A-1-10-4-2-4': ("Merdiven lehine – siyah keima", 'situational', "Merdiven siyahın lehineyse siyah 1 ile keima yapmak olur. Beyaz 2 yapışma iyi hamledir, sonra beyaz 4 ve 6 ile itip keserek değişim yapar; sonuç eşittir."),
'A-1-10-4-2-5': ("Merdiven siyahın aleyhine", 'situational', "Merdiven siyahın aleyhineyse beyaz 1 ve 3 ile hemen itip kesmesi yeterlidir; siyah çöker."),
'A-1-10-4-2-6': ("Beyaz büyük keima", 'ok', "Beyaz 1 büyük keima ilginç bir hamledir; siyah 2 ve beyaz 3 kendini tamamlar. Siyah 4 ile beyaz 5 değişimi siyaha biraz yarar; iki taraf da savaşabilir."),
}
