# Hoshi + alçak bir aralık pincer (一间低夹) — 1. bölüm
T = {
'A-1-3': ("Başlangıç pozisyonu", 'best', "Siyah 1 ile alçak bir aralık pincer çok sık oynanır. Beyazın seçenekleri: A'da 3-3 işgali, B'de sıçrama, C ve D'de çift kakari, E'de karşı pincer, F'de çapraz keima, G'de yapışma ya da başka yere oynamak."),
'A-1-3-1-1-1': ("3-3 işgali – en yaygın", 'best', "Beyaz 1 en çok oynanan hamledir. Siyah 8 ile sürünmek yapay zekânın önerisidir; eskiden A'da bağlanılırdı. Sağ alt beyazsa sonuç eşittir, siyahsa beyaz biraz kayıptadır."),
'A-1-3-1-1-2': ("Beyazın sonraki iyi noktası", 'ok', "İleride beyaz 1 iyi bir noktadır, siyah 2 ile tamamlamak zorundadır. İki taraf da istediğini alır."),
'A-1-3-1-1-3': ("Siyah tenuki – iyi değil", 'bad', "Siyahın başka yere oynaması genelde iyi değildir. Beyaz 1 ile şeklini tamamlar ve A'daki kesme siyah için tehlike olarak kalır."),
'A-1-3-1-1-4': ("Siyah bağlanır – eski joseki", 'bad', "Siyah 1 eski bir josekidir. Beyaz ileride A'yı sente oynar ve siyahın şekli biraz tekrarlı olur."),
'A-1-3-1-1-5': ("Sürünmenin faydası", 'best', "Siyah A'da süründüğü için beyaz 1'e cevap vermesi gerekmez. Beyaz 3 ile keserse siyah 4 ile sente alır."),
'A-1-3-1-1-6': ("Sağ alt beyazsa beyaz pincer ile çıkar", 'situational', "Sağ alt beyazsa beyaz 1 güçlüdür. Siyah iki hane ile sabırlı oynar; beyaz sente kazanç sağlar."),
'A-1-3-1-1-7': ("Siyah uzanır – aşırı", 'bad', "Siyah 1 aşırıdır. Beyaz savaşarak çıkar ve 2. sırada yaşar; siyahın dışı zayıf kalır."),
'A-1-3-1-1-8': ("Sağ alt siyahsa", 'situational', "Sağ alt siyahsa beyaz önce keser, sonra 5 ile çıkmak zorunda kalır. Beyaz biraz kayıptadır."),
'A-1-3-1-1-9': ("Siyah hane – kötü", 'bad', "Siyah 1 kötüdür. Beyaz 2 ile güçlü çıkar, siyah bağlanmak zorunda kalır; beyaz sente kazanır."),
'A-1-3-1-1-10': ("Beyaz 2. sıradan keima", 'ok', "Beyaz 1 ile 2. sıradan keima da olur. Sonuç eşit diyagrama çok benzer."),
'A-1-3-1-2-1': ("Siyah dışarıdan engeller – iyi değil", 'bad', "Siyah 1 pek iyi değildir. Beyaz sakin oynar, sente şeklini kurar ve ileride A veya B'den birini mutlaka alır."),
'A-1-3-1-2-2': ("Sağ alt siyahsa beyaz sağlam bağlanır", 'situational', "Sağ alt siyahsa beyaz 1 ile sakin oynayabilir ve ileride A ile savaşır. Beyaz biraz daha iyidir."),
'A-1-3-1-2-3': ("Beyaz yapışarak yükselir", 'ok', "Beyaz 1 de iyi bir hamledir. Siyah sente alır ama dışı zayıftır; beyaz daha memnundur."),
'A-1-3-1-2-4': ("Siyah uzanır – aşırı", 'bad', "Siyah 1 aşırıdır. Beyaz 2'den sonra siyah iki tarafta da zayıf kalır."),
'A-1-3-1-2-5': ("Siyah hane – kötü", 'bad', "Siyah 1 kötüdür. Beyaz 2 ile rahatça çıkar, sonra A veya B'yi seçer."),
'A-1-3-1-2-6': ("Siyah dışarıdan keser – kötü", 'bad', "Siyah 1 kötüdür. Beyaz açıkça kazançlı çıkar."),
'A-1-3-1-2-7': ("Beyaz hemen bağlanır – yetersiz", 'bad', "Beyaz 1 yeterince iyi değildir. Siyah 2 ile beyazı kapatır; sonuç eşittir."),
'A-1-3-2': ("Beyaz sıçrar", 'best', "Beyaz 1 ile sıçramak savaşmak demektir. Siyah genellikle A–C ile köşeyi korur. Sağ taraf önemliyse D'de sıçrayabilir."),
'A-1-3-2-1-0': ("Siyah bir boşluk sıçrar", 'best', "Siyah 1 normal bir hamledir, eskiden çok oynanırdı. Beyaz A'da omuz vuruşu, B'de karşı pincer ya da C'de sıkıştırma seçer."),
'A-1-3-2-1-1': ("Beyaz omuz vuruşu", 'situational', "Sağ alt siyahsa ve merdiven beyaz lehineyse beyaz 1 iyidir. Siyah sürünerek güçlü oynar, beyaz 3-3'e girer; zor bir savaş başlar."),
'A-1-3-2-1-2': ("Beyaz uzanır – plansız", 'bad', "Beyaz 1 plansızdır. Siyah ayırır ve sonunda çok alan kazanır."),
'A-1-3-2-1-3': ("Siyah 1 ve 3 – eski joseki", 'bad', "Bu eski bir josekidir. Beyaz 4 ve 6 iyi hamlelerdir; savaşta beyaz biraz avantajlıdır."),
'A-1-3-2-1-4': ("Beyaz engeller – kötü", 'bad', "Beyaz 1 kötüdür. Siyah sente hane yapar ve köşede çok alan kazanır."),
'A-1-3-2-1-5': ("Siyah doğrudan sürünür", 'ok', "Siyah 1 ile sürünüp 7 ile güçlü keser. Beyaz dört taşı yakalar, siyah sente güç alır. Sonuç eşittir."),
'A-1-3-2-1-6': ("Beyaz yukarıdan atari", 'ok', "Beyaz 1 de bir yoldur. Siyah sert karşılık verir; beyaz köşeye girse de siyah A ile yaşayabilir. Sonuç kabul edilebilir."),
'A-1-3-2-1-7': ("Beyaz bağlanırsa", 'bad', "Beyaz 1 ile bağlanırsa siyahın iki atarisi serttir. Beyaz dar yerden çıkmak zorunda kalır; siyah biraz rahattır."),
'A-1-3-2-1-8': ("Siyah sıçrar – sıradan", 'bad', "Siyah 1 çok sıradandır. Beyaz 3-3'e girerek karşılık verir; siyah memnun değildir."),
'A-1-3-2-1-9': ("Siyah doğrudan kazır", 'ok', "Siyah 1 ile doğrudan kazıyıp taş feda ederek güç alabilir. Sonuç eşittir."),
'A-1-3-2-1-10': ("Beyaz yapışıp feda eder", 'ok', "Beyaz 1 ile taş feda etmek de bir yoldur; beyaz 11 iyi bir noktadır. İki taraf için de oynanabilir."),
'A-1-3-2-1-11': ("Siyah itip keser", 'ok', "Siyah 1 ve 3 de bir yoldur. Siyah 7 ile uzanıp taş feda eder; iki taraf için de kabul edilebilir."),
'A-1-3-2-1-12': ("Siyah döner", 'bad', "Siyah 1 ile dönerse beyaz 2 ile sert oynar. Beyaz biraz avantajlı olur."),
'A-1-3-2-1-13': ("Merdiven kötüyse atari çalışmaz", 'bad', "Merdiven siyah aleyhineyse siyah 1 ile keserek atari çalışmaz."),
'A-1-3-2-1-14': ("Siyah merdiven kırıcı arar", 'ok', "Siyah 1 ile merdiven kırıcı oynamak da olur, beyaz 2 ile tamamlamalıdır. Siyah 3 iyi bir hamledir; siyah sente kazanç sağlar."),
'A-1-3-2-1-15': ("Beyaz takip ederse", 'bad', "Beyaz 1 ile takip ederse siyah itip keser. Siyah sonunda sente bir taşı alır ve memnundur."),
'A-1-3-2-1-16': ("Beyaz kaplan ağzı", 'bad', "Beyaz 1'e karşı siyah 2 iyidir. Beyaz dört taşı yer ama siyah sente beyazı kapatır; beyaz kazandığından fazlasını kaybeder."),
'A-1-3-2-1-17': ("Beyaz keser – çok sert", 'bad', "Beyaz 1 çok serttir. Siyah 10'dan sonra beyaz zorlanır; siyah saldırıyı yönetir."),
'A-1-3-2-1-18': ("Beyaz yapışırsa", 'bad', "Beyaz 1'e karşı siyah 2 ve sonrası çok güçlüdür. Beyaz çok zor durumda kalır."),
'A-1-3-2-1-19': ("Sağ alt beyazsa karşı pincer", 'situational', "Sağ alt beyazsa beyaz 1 ile karşı pincer iyidir. Beyaz önce solu çözer; sonuç eşittir."),
'A-1-3-2-1-20': ("Beyaz sıkıştırır", 'ok', "Beyaz 1 ile sıkıştırmak da olur, siyah köşeyi güçlendirir. Zor bir savaş başlar."),
'A-1-3-2-1-21': ("Beyaz omuz vuruşu – biraz zayıf", 'bad', "Beyaz 1 biraz zayıftır. Merdiven ne olursa olsun siyahın sürünerek çıkması iyidir; siyah biraz avantajlıdır."),
'A-1-3-2-1-22': ("Beyaz 3-3 işgali", 'ok', "Beyaz 1 ile 3-3'e girmek de bir karşılıktır. Beyaz 7 ile kalın oynar; siyah yine biraz daha iyidir."),
'A-1-3-2-1-23': ("Siyah doğrudan kazır", 'ok', "Siyah 1 ile kazıyabilir. Beyaz itip keser, siyah sakince taş feda eder; siyah biraz avantajlıdır."),
'A-1-3-2-1-24': ("Beyaz önce atari verirse", 'bad', "Beyaz önce atari verirse siyah sert karşılık verir. Siyah savaşta daha rahattır."),
'A-1-3-2-1-25': ("Sağ alt beyazsa siyah keser", 'situational', "Sağ alt beyazsa siyahın itip kesmesi kazanç getirmez. Sert bir savaş olur ve pozisyon çok karışıktır."),
'A-1-3-2-1-26': ("Beyaz engeller – oynanabilir", 'ok', "Merdiven beyaz aleyhine olsa bile beyaz 1 ile engellemek savaşılabilir. İki taraf için de oynanabilir."),
'A-1-3-2-1-27': ("Siyah çıkar – aşırı", 'bad', "Siyah 1 biraz aşırıdır. Beyaz 8 ile keser ve taş feda edip dışarıda güç alır; siyah memnun değildir."),
'A-1-3-2-1-28': ("Beyaz kaplan ağzı – biraz zayıf", 'bad', "Beyaz 1 biraz zayıftır. Siyah güçlü oynar ve biraz daha iyi olur."),
'A-1-3-2-1-29': ("Beyaz önce keserse", 'bad', "Beyaz 1 ile önce keserse siyah sürünüp güçlü devam eder. Beyazın köşesi tam yaşayamaz; siyah savaşı yönetir."),
'A-1-3-2-1-30': ("Siyah bağlanır – kötü", 'bad', "Siyah 1 kötüdür. Beyaz sıkı oynar; siyah geri adım atmak zorunda kalır."),
'A-1-3-2-1-31': ("Siyah keserek atari – çok sert", 'bad', "Siyah 1 çok serttir. Beyaz dört taşı yakalar ve köşede kolayca yaşar; siyah zorlanır."),
'A-1-3-2-1-32': ("Siyah kosumi-tsuke – eski fikir", 'bad', "Eskiden siyah 1 iyi sayılırdı. Yapay zekâya göre bu değişim siyahın göz alanını azaltır; siyah kayıptadır."),
'A-1-3-2-2-0': ("Siyah iki boşluk sıçrar (AI)", 'best', "Yapay zekâ çoğunlukla siyah 1'i tercih eder. Hızlıdır ama köşe zayıftır. Beyaz A'da omuz vuruşu, B'de karşı pincer, C'de sıkıştırma ya da D'de yapışma seçer."),
'A-1-3-2-2-1': ("Sağ alt siyahsa omuz vuruşu", 'situational', "Sağ alt siyahsa beyaz 1 yine iyidir. Siyah başka yere oynar, beyaz tamamlar."),
'A-1-3-2-2-2': ("Aynı yol burada daha kötü", 'bad', "Siyah aynı şekilde oynarsa × taşı A'dakinden biraz daha kötü yerde kalır."),
'A-1-3-2-2-3': ("Beyaz yukarıdan atari", 'ok', "Beyaz 1 de olur. İki taraf da kendini güçlendirir; sonuç eşittir."),
'A-1-3-2-2-4': ("Beyaz 3-3 işgali", 'ok', "Beyaz 1 ile 3-3'e girmek de bir yoldur. Siyah karşılık verir ve takas iki taraf için de kabul edilebilir."),
'A-1-3-2-2-5': ("Siyah engeller – tuzak", 'bad', "Siyah 1 tuzağa düşer. Beyaz sente kazanç sağlar ve biraz avantajlı olur."),
'A-1-3-2-2-6': ("Siyah itip keser", 'ok', "Siyah 1 ve 3 ile savaşabilir. Merdiven beyaz lehineyse beyaz güçlü karşılık verir. Sonuç eşittir."),
'A-1-3-2-2-7': ("Siyah döner", 'ok', "Siyah 1 ile dönmek de olur. Siyah taş feda edip beyazı kapatır; sonuç kabul edilebilir."),
'A-1-3-2-2-8': ("Siyah önce kosumi-tsuke – şüpheli", 'bad', "Siyah 1 şüphelidir. Beyaz 10 ile köşeye girer ve memnun olur."),
'A-1-3-2-2-9': ("Sağ alt beyazsa karşı pincer", 'situational', "Sağ alt beyazsa beyaz 1 çok oynanır. Siyah başka yere oynayabilir, sonra A–C ile savaşır."),
'A-1-3-2-2-10': ("Beyaz sıkıştırır", 'ok', "Beyaz 1 de iyi bir hamledir, siyah sağlam oynar. İki taraf için de oynanabilir."),
'A-1-3-2-2-11': ("Beyaz omuz vuruşu – kötü", 'bad', "Beyaz 1 iyi değildir. Siyah basit oynar ve biraz avantajlı olur."),
'A-1-3-2-2-12': ("Siyah itip keser – kötü", 'bad', "Siyah 1 ve 3 kötüdür. Beyaz güçlü oynar ve güzel bir şekil kurar."),
'A-1-3-2-2-13': ("Beyazın bu yolu iyi değil", 'bad', "Merdiven iyi olsa bile beyazın bu yolu iyi değildir; siyahın × taşı çok iyi yerdedir."),
'A-1-3-2-2-14': ("Sol üst beyazsa beyaz yapışıp keser", 'situational', "Sol üst beyazsa beyaz yapışıp keserek savaşabilir. Sonunda bir ko çıkar ve pozisyon çok zordur."),
'A-1-3-2-2-15': ("Sol üst siyahsa siyah hane", 'situational', "Sol üst siyahsa siyah 1 güçlüdür. Beyaz direnir ama siyah 17'den sonra beyaz çok zorlanır."),
'A-1-3-2-2-16': ("Sol üst siyahsa beyaz kosumi", 'situational', "Bu yüzden sol üst siyahsa beyaz 1 ile kosumi yapmak zorundadır. Siyah sert saldırır, beyaz yine zorlanır."),
'A-1-3-2-3-1': ("Siyah keima", 'ok', "Siyah 1 ile keima da olur. Merdiven beyaz lehineyse beyaz omuz vuruşu yapar; sağ alt siyahsa siyah başka yere oynar."),
'A-1-3-2-3-2': ("Aynı yol burada daha kötü", 'bad', "Siyah aynı şekilde oynarsa × taşı A'dakinden biraz daha kötü yerde kalır."),
'A-1-3-2-3-3': ("Siyah sıçrar – memnun değil", 'bad', "Siyah 1'den sonra beyaz omuz vuruşu yapar. Siyah bir taşı keser ama A'daki 3-3 zayıflığı kalır."),
'A-1-3-2-3-4': ("Siyah itip keser – aşırı", 'bad', "Siyah 1 ve 3 biraz aşırıdır. Beyaz çok güçlü karşılık verir; siyah zorlanır."),
'A-1-3-2-3-5': ("Siyah kosumi-tsuke – biraz zayıf", 'bad', "Siyah 1 biraz zayıftır. Beyaz 10 ile 3-3'e girip yaşar ve alan kazanır."),
'A-1-3-2-3-6': ("Siyah kazıyıp bağlanır – kötü", 'bad', "Siyah 1 ve 3 de iyi değildir. Beyaz kesmeyi kapatır ve dışarıda rahat gelişir."),
'A-1-3-2-3-7': ("Beyaz omuz vuruşu", 'situational', "Beyaz 1 aktif bir hamledir, siyah 4 ile sağlam oynar. Sağ alt siyahsa sonuç eşittir."),
'A-1-3-2-3-8': ("Sağ alt beyazsa omuz vuruşu", 'situational', "Sağ alt beyazsa beyaz 1 iyi bir hamledir. Siyah taş feda eder; beyaz biraz avantajlıdır."),
'A-1-3-2-3-9': ("Siyah 2. sıradan keima – zayıf", 'bad', "Siyah 1 biraz zayıftır. Beyaz omuz vuruşu yapar ve güzel bir şekil kurar."),
'A-1-3-2-4-1': ("Siyah sıçrar – destek gerekir", 'situational', "Siyah 1 çevrede destek ister; normalde biraz kayıptır. Siyah sonra başka yere oynar; köşe A sayesinde güvendedir."),
'A-1-3-2-4-2': ("Siyah kafa atarsa", 'bad', "Siyah 1'e karşı beyaz 4 ile esnek oynar. Beyaz × iki taşı feda eder ve memnun olur."),
}
