# Hoshi + alçak bir aralık pincer (一间低夹) — 2. bölüm
T = {
'A-1-3-2-4-3': ("Beyaz keser – aşırı", 'bad', "Beyaz 1 aşırıdır. Siyah beyazı kapatır; nefes yarışında beyazın zaafları çoktur."),
'A-1-3-2-4-4': ("Siyah yapışıp geri çekilir", 'bad', "Siyah 1 ve 3 beyazı güçlendirir. Beyaz sonra A ile sıkıştırabilir ya da B ile açılabilir."),
'A-1-3-2-4-5': ("Siyah 'altın kuyu' – karışık", 'bad', "Siyah 1 eski Çin oyunlarında popüler, çok karışık bir hamledir. İki taraf da geri adım atamaz; sonunda siyahın şekli sıkışır ve savaş siyah aleyhinedir."),
'A-1-3-2-4-6': ("Siyah 13 yerine sagari – kötü", 'bad', "Önceki diyagramda siyah 13'ü 1'de oynamak da kötüdür. Beyaz önemli noktaları alır ve büyük alan kazanır."),
'A-1-3-2-4-7': ("Beyaz keima – yeterince sıkı değil", 'bad', "Beyaz 1 yeterince sıkı değildir. Siyah 2 ile keskin oynar; beyaz önceki iki diyagram kadar iyi olmaz."),
'A-1-3-3': ("Beyaz çift kakari", 'best', "Beyaz 1 ile çift kakari de çok oynanır; beyaz oyunu sol tarafa taşımak ister. Siyah genellikle A veya B'de yapışır, C'de 3-3 kosumi ile savaş da açılabilir."),
'A-1-3-3-1-1': ("Siyah bu taraftan yapışır", 'best', "Siyah 1 ile bu taraftan yapışınca beyaz 2 ile doğrudan 3-3'e girer; siyah 3 ile dışarıdan engeller. Siyah 7 aktif bir pincer'dır."),
'A-1-3-3-1-2': ("Beyaz sağlam bağlanır", 'ok', "Beyaz 1 de bir yoldur ve A'ya çıkmayı hedefler. Sonuç eşittir."),
'A-1-3-3-1-3': ("Beyaz kenara açılır – iyi değil", 'bad', "Ko tehditleri çok iyi değilse beyaz 1 kötüdür. Siyah 2 ile içeri girer ve A'da bir ko savaşı başlar."),
'A-1-3-3-1-4': ("Siyah içeriden engeller – şüpheli", 'bad', "Siyah 1 şüphelidir. Beyaz güzel şekil kurar ve ileride A'yı da kullanabilir."),
'A-1-3-3-1-5': ("Beyaz hane ile çıkar", 'ok', "Beyaz 1 siyahı yoklar; siyah 2 ile karşılık vermek zorundadır. Çok karışık bir savaş başlar."),
'A-1-3-3-1-6': ("Siyah keser – kötü", 'bad', "Siyah 1 kötüdür. Beyaz sente olarak bir taşı alır ve çok rahat eder."),
'A-1-3-3-1-7': ("Siyah kaplan ağzı – gevşek", 'bad', "Siyah 1 gevşektir. Beyaz sürünerek bağlanır; siyahın taşları verimsiz kalır."),
'A-1-3-3-1-8': ("Beyaz hane + yapışma – eski joseki", 'bad', "Bu eski bir josekidir. Siyah solda taşı alıp çok kazanır ve altta da savaşı yönetir; beyaz açıkça kötüdür."),
'A-1-3-3-1-9': ("Beyaz dışarıdan atari", 'bad', "Beyaz 1 önceki diyagramdan iyidir ama siyahın köşesi büyüktür; beyaz yine biraz kayıptadır."),
'A-1-3-3-1-10': ("Siyah kaplan ağzı ile atari", 'ok', "Siyah 1 biraz yumuşaktır; sonuç eşittir."),
'A-1-3-3-2-1': ("Siyah güçlü taraftan yapışır", 'best', "Siyah 1 'güçlü taşa yapış' atasözüne uyar. Beyaz 6 ile önce bağlanmalıdır. Siyah beyazı sıkıştırarak merkeze ilerler; savaş dengelidir."),
'A-1-3-3-2-2': ("Siyah engeller", 'ok', "Siyah 1 ile engellemek de olur. Beyaz × taşını iyi kullanır; siyah başka yere oynar. Sonuç eşittir."),
'A-1-3-3-2-3': ("Beyaz hane – dikkatsiz", 'bad', "Beyaz 1 dikkatsizdir. Siyah 2 ile ayırır ve beyazın göz alanı azalır."),
'A-1-3-3-2-4': ("Beyaz sürünerek döner", 'bad', "Beyaz 1 ile dönerse siyah sağlam yakalar. Siyah 4 çok değerlidir; beyaz memnun değildir."),
'A-1-3-3-2-5': ("Merdiven iyiyse siyah bu taraftan engeller", 'situational', "Merdiven siyah lehineyse siyah 1 ve 3 ile iyi oynar. Beyaz alan, siyah dış güç alır; iki taraf için de kabul edilebilir."),
'A-1-3-3-2-6': ("Merdiven kötüyse siyah uzanır", 'situational', "Merdiven siyah aleyhineyse siyah 1 ile uzanmak zorundadır. Siyah açıkça kötü durumdadır."),
'A-1-3-3-2-7': ("Beyaz uzanır", 'bad', "Beyaz 1 az oynanır. Siyah sakin kalır, beyaz taş feda etmek zorunda kalır; siyah daha memnundur."),
'A-1-3-3-2-8': ("Beyaz kosumi ile çıkar – aşırı", 'bad', "Beyaz 1 aşırıdır. Siyah hazırlık yapıp 12 ile kapatır; beyaz gote yaşamak zorunda kalır."),
'A-1-3-3-2-9': ("Beyaz yapışır – genelde kötü", 'bad', "Beyaz 1 genellikle iyi değildir. Siyah sağlam oynar ve köşede büyük alan kazanır."),
'A-1-3-3-2-10': ("Beyaz kosumi – aşırı", 'bad', "Beyaz 1 aşırıdır. Siyah 6 ile keskin keser ve sonunda beyazın dört taşı kıpırdayamaz."),
'A-1-3-3-3-1': ("Siyah 3-3 kosumi – genelde kötü", 'bad', "Çevrede güçlü siyah taş yoksa siyah 1 genellikle iyi değildir. Beyaz 2 ile iyi bir noktayı alır ve memnun olur."),
'A-1-3-3-3-2': ("Siyah önce bu taraftan iter", 'bad', "Siyah 1'den sonra beyaz 4 yine iyi bir hamledir; takasta beyaz açıkça kazançlıdır."),
'A-1-3-4-1-1': ("Beyaz yüksek çift kakari", 'bad', "Beyaz 1 eskiden sık oynanırdı. Siyah 2 ile bu taraftan yapışır; beyazın taşı iyi yerde değildir, siyah biraz daha iyidir."),
'A-1-3-4-1-2': ("Beyaz sade oynar", 'bad', "Beyaz 1 ve 3 sadedir; siyah 4 ile ustaca atari verir. Bu da siyah için biraz daha iyidir."),
'A-1-3-4-1-3': ("Siyah 3. sıradan atari – eski joseki", 'ok', "Siyah 1 eski bir josekidir. Beyaz ileride sente kazanç sağlar; sonuç eşittir."),
'A-1-3-4-2-1': ("Siyah bu taraftan yapışır – biraz zayıf", 'bad', "Siyah 1 biraz zayıftır. Beyaz köşeyi alır; siyahın × taşı fazla yakın kalır."),
'A-1-3-4-2-2': ("Siyah merdivenle yakalar", 'bad', "Merdiven iyi olsa bile siyahın bir taşı yakalaması avantaj getirmez. Beyaz sente köşeyi alır."),
'A-1-3-4-2-3': ("Siyah geri çekilir", 'ok', "Siyah 1 ile geri çekilip sert oynayabilir. Uzun bir zorunlu sıra olur ve bir ko kalır; beyaz biraz daha rahattır."),
'A-1-3-4-2-4': ("Siyah keser", 'bad', "Siyah 1 ile keserse beyaz 6 can alıcı noktadır. Karışık bir savaş başlar; beyaz biraz avantajlıdır."),
'A-1-3-4-2-5': ("Siyah keser – gevşek", 'bad', "Siyah 1 gevşektir. Beyaz sürünerek bağlanır ve memnun olur."),
'A-1-3-5-1-1': ("Beyaz iki aralık karşı pincer", 'ok', "Beyaz 1 siyaha fazla baskı yapmaz, siyah başka yere oynayabilir. Beyaz 3 ile çıkınca siyah köşede yaşar."),
'A-1-3-5-1-2': ("Beyaz 3-3 işgali", 'ok', "Beyaz 1 ile 3-3'e de girebilir. Siyah 6 iki tarafın yaşam alanı için önemlidir; sonuç eşittir."),
'A-1-3-5-2-1': ("Siyah yapışır", 'ok', "Siyah 1 ile yapışabilir. Beyaz 3-3'e girince siyah içeriden engeller ve sert oynar. İki taraf için de kabul edilebilir."),
'A-1-3-5-2-2': ("Siyah bağlanır – kötü şekil", 'bad', "Siyah 1 ile bağlanırsa beyaz iyi hamleler yapar; siyahın şekli bozulur."),
'A-1-3-5-2-3': ("Siyah dışarıdan engeller – biraz zayıf", 'bad', "Siyah 1 biraz zayıftır. Beyaz 6 ile sert çıkar ve savaşta biraz daha rahattır."),
'A-1-3-5-3-1': ("Siyah kosumi", 'ok', "Siyah 1 ile kosumi de olur. Beyaz 3-3'e girince siyah doğru yöne oynar ve 9 ile güzel kapatır."),
'A-1-3-5-4-1': ("Siyah keima", 'ok', "Siyah 1 ile keima yaparsa beyaz sıçrar; A-1-3-2-3-7 ile aynı şekle döner."),
'A-1-3-5-5-1': ("Merdiven iyiyse siyah keima ile çıkar", 'situational', "Merdiven siyah lehineyse siyah 1 ile çıkabilir. İki taraf sade oynar; sonuç kabul edilebilir."),
'A-1-3-5-5-2': ("Siyah kafa atar – sert", 'bad', "Siyah 1 biraz serttir. Beyaz ustaca oynar ve biraz avantajlı olur."),
'A-1-3-5-5-3': ("Merdiven kötüyse beyaz 3-3'e girer", 'situational', "Merdiven siyah aleyhineyse beyaz 1 çok güçlüdür. Beyaz güzel şekil kurar ve biraz daha iyidir."),
'A-1-3-5-5-4': ("Siyah zorla hane – kötü", 'bad', "Siyah 1 kötüdür. Beyaz 2 ile keser; siyah çok alan kaybeder."),
'A-1-3-5-5-5': ("Merdiven iyiyse 2. sıra hane", 'situational', "Merdiven siyah lehineyse siyah 1 iyi bir hamledir. Beyaz taş feda edip kapatır ama dış gücü siyahın alanına yetmez."),
'A-1-3-6-1-1': ("Beyaz çapraz keima – tuzak", 'bad', "Beyaz 1 bir tuzaktır; siyah 2 ile kosumi-tsuke yapıp tuzağı bozar. Siyah sade oynar ve beyaz memnun olmaz."),
'A-1-3-6-1-2': ("Beyaz uzanır – iyi değil", 'bad', "Beyaz 1 de iyi değildir. Siyah köşeyi alır; beyazın taşları verimsiz kalır."),
'A-1-3-6-2-1': ("Siyah keima – biraz zayıf", 'ok', "Siyah 1 biraz zayıftır. Beyaz iyi noktalara oynar ve köşeye girer; siyah taş feda eder. Sonuç eşittir."),
'A-1-3-6-3-1': ("Siyah atlama kesme – tuzağa düşer", 'bad', "Siyah 1 tuzağa düşer. Beyaz sente kazanç sağlar ve ileride A'da ko açabilir."),
'A-1-3-7-1-1': ("Beyaz yapışıp uzanır", 'bad', "Beyaz 1 ve 3 az oynanır. İki taraf şeklini tamamlar; siyah biraz daha iyidir."),
'A-1-3-7-1-2': ("Sağ alt beyazsa beyaz pincer", 'situational', "Sağ alt beyazsa beyaz 1 güçlüdür ama savaşta yine siyah biraz daha rahattır."),
'A-1-3-7-1-3': ("Sağ alt siyahsa beyaz keima", 'situational', "Sağ alt siyahsa beyaz 1 ile çıkabilir; siyah yine biraz daha iyidir."),
'A-1-3-7-2-1': ("Beyaz geri çekilirse", 'bad', "Beyaz 1'e karşı siyah 2 aktiftir. Beyaz yerinde yaşar; siyah başka yere oynar ve temposu hızlıdır."),
'A-1-3-7-2-2': ("Sağ alt destekliyse siyah kaplan ağzı", 'situational', "Sağ alt siyahın lehineyse siyah 1 ile savaşabilir. Siyah taş feda edip güzel bir dış güç kurar."),
'A-1-3-8': ("Beyaz tenuki", 'best', "Siyah pincer yaptıktan sonra beyaz başka yere de oynayabilir. Siyahın seçenekleri: A'da 3-3 kosumi, B'de yapışma, C'de kosumi-tsuke ve D'de keima."),
'A-1-3-8-1-1': ("Siyah 3-3 kosumi (AI)", 'best', "Siyah 1 yapay zekânın yeni fikridir; beyaza yön değiştirme imkânı bırakmaz. Siyah bir taşı keser ve çok alan kazanır. Sonuç eşittir."),
'A-1-3-8-1-2': ("Beyaz keima ile çıkar", 'ok', "Beyaz 1 ile çıkıp 3 ile tamamlar. Beyaz 9 iyi bir noktadır; iki taraf için de oynanabilir."),
'A-1-3-8-1-3': ("Beyaz yapışarak çıkar", 'ok', "Beyaz 1 de bir yoldur. İki taraf sıkı oynar; sonuç eşittir."),
'A-1-3-8-1-4': ("Beyaz yön değiştirir", 'ok', "Beyaz 1 ve 3 ile esnekçe yön değiştirir; iki taraf için de kabul edilebilir."),
'A-1-3-8-2-1': ("Siyah üstten yapışır", 'situational', "Siyah 1 çok kullanılır. Merdiven beyaz lehineyse beyaz hemen kazıyıp bağlanır ve köşede yaşar. Sonuç eşittir."),
'A-1-3-8-2-2': ("Çevre destekliyse beyaz sert keser", 'situational', "Çevrede destek varsa beyaz 1 çok serttir. İki taraf da saldırır; iki taraf için de oynanabilir."),
'A-1-3-8-2-3': ("Siyah çift hane", 'ok', "Siyah 1 güçlüdür, beyaz 4 en iyi cevaptır. Siyah kenara açılır; ileride A–C sente olur."),
'A-1-3-8-2-4': ("Beyaz sıçrar – kötü", 'bad', "Beyaz 1 iyi değildir. Siyah beyazı kapatır ve çok güçlü bir dış güç kurar."),
'A-1-3-8-2-5': ("Beyaz atari – şüpheli", 'bad', "Beyaz 1 şüphelidir. Siyah 4 iyi bir hamledir; siyah sente beyazı kapatıp çok kazanır."),
'A-1-3-8-2-6': ("Beyaz kafa atar", 'ok', "Beyaz 1 de bir yoldur, siyah 2 ile sağlam bağlanır. Karışık bir savaş başlar."),
'A-1-3-8-2-7': ("Siyah uzanır – biraz zayıf", 'bad', "Siyah 1 biraz zayıftır. Beyaz 8 ile çok iyi bir yoklama yapar ve kazanç sağlar."),
'A-1-3-8-2-8': ("Merdiven beyaz aleyhineyse", 'situational', "Merdiven beyaz aleyhineyse siyahın atari verip bağlanmasından sonra beyaz devam edemez."),
'A-1-3-8-2-9': ("Beyaz yine tenuki", 'ok', "Beyaz yine başka yere oynayabilir; siyah 1 ile şeklini tamamlar."),
'A-1-3-8-3-1': ("Siyah kosumi-tsuke", 'ok', "Siyah 1 saldırgan bir hamledir, beyaz esnek oynar. Siyah 3-3'e kosumi yapar ve zor bir savaş başlar."),
'A-1-3-8-3-2': ("Siyah 7 yerine tenuki", 'ok', "Önceki diyagramda siyah 7 yerine başka yere oynayabilir. Beyaz köşeyi alır; iki taraf için de kabul edilebilir."),
'A-1-3-8-3-3': ("Beyaz yapışarak savaşır", 'bad', "Beyaz 1 ile doğrudan savaşırsa siyah güçlü bastırır. Beyaz yaşar ama siyah savaşta daha rahattır."),
'A-1-3-8-3-4': ("Beyaz yine tenuki", 'ok', "Beyaz yine başka yere oynayabilir; siyah 1 ile A-1-3-8-2-9'a döner."),
'A-1-3-8-4-1': ("Siyah keima", 'ok', "Siyah 1 dengeli bir hamledir; A-1-1-7-1-1 ile aynı şekle döner."),
}
