# Hoshi + bir boşluklu zıplama (单关守角) — kod: (başlık, değerlendirme, sade açıklama)
T = {
'A-1-2': ("Başlangıç pozisyonu", 'best', "Siyah 1 ile bir boşluklu zıplama, keimaya göre dışarıdaki güce daha çok önem verir. Beyazın seçenekleri: A'da keima ile dürtme, B'de yapışma, C'de 2. sıradan keima, D'de 3-3 işgali ya da başka yere oynamak (tenuki)."),
'A-1-2-1': ("Beyaz keima ile dürter", 'best', "Beyaz 1 yapay zekânın ilk tercihidir. Eskiden kaba bir hamle sayılırdı ama siyahın taşlarının verimini düşürür. Siyah için A'da bağlanmak sadedir; B ve C sert karşılıklardır; D sağlamdır ama biraz kayıptır."),
'A-1-2-1-1-1': ("Siyah bağlanır – sade", 'best', "Siyah 1 ile bağlanmak sadedir, beyaz 2 ile 2. sıradan kayar. Siyah 3 ile kenara açılmak iyidir. Sonuç eşittir."),
'A-1-2-1-1-2': ("Siyah tenuki – sol üst destekliyse", 'situational', "Sol üstte siyah taş varsa siyah başka yere oynayabilir. Beyaz 1 ile sıkıştırır, siyah 2 ile karşı pincer yapar; zor bir savaş başlar."),
'A-1-2-1-2-1': ("Siyah kosumi-tsuke – merdiven iyiyse", 'situational', "Merdiven siyah lehineyse siyah 1 güçlü bir hamledir. Beyaz 4 ile içeriden keser. Devamı yine merdivene bağlıdır."),
'A-1-2-1-2-2': ("Siyah hane ile çıkar", 'situational', "Merdiven siyah lehineyse siyah 1 güçlüdür. Siyah 3 ile sakince bağlanır ve sente olarak köşeyi alır; siyah memnundur."),
'A-1-2-1-2-3': ("Siyah sürünür – şüpheli", 'bad', "Siyah 1 ile sürünmek şüphelidir. Beyaz taşları takas eder; siyah önceki diyagram kadar iyi değildir."),
'A-1-2-1-2-4': ("Merdiven kötüyse beyaz keser", 'situational', "Merdiven siyah aleyhineyse beyaz 1 ile keser ve köşede yaşar. Siyah atari ile sıkıştırır ama 2. sırada sürünmek zorunda kalır. Kim daha iyi, belli değil."),
'A-1-2-1-2-5': ("Siyah kaplan ağzı", 'ok', "Siyah 1 ile kaplan ağzı da olur. Karmaşık bir savaş devam eder; iki taraf için de oynanabilir."),
'A-1-2-1-2-6': ("Beyaz hane – iyi değil", 'bad', "Beyaz 1 ile hane iyi değildir. Siyah 2 iyi bir hamledir ve siyah sakin oynayarak biraz avantajlı olur."),
'A-1-2-1-2-7': ("Siyah hane – biraz zayıf", 'bad', "Siyah 1 biraz zayıftır. Beyaz 4 kaçırılmaması gereken bir noktadır; beyaz kazanç sağlar."),
'A-1-2-1-2-8': ("Siyah keser – dış güç için", 'bad', "Siyah 1 dışarıdaki güce önem verir. Beyaz 6 ile köşeyi alır; bu da beyaz için biraz daha iyidir."),
'A-1-2-1-2-9': ("Siyah çok basit oynar", 'bad', "Siyah 1 ve 3 çok basittir. Beyaz 4 iyi bir hamledir; siyahın alttaki grubu zor yaşar ve çok puan kaybeder."),
'A-1-2-1-2-10': ("Beyaz önce uzanırsa", 'ok', "Beyaz 1 ile önce uzanırsa siyah 2 ile mutlaka bastırmalıdır. Sonra beyaz A veya B'yi seçer; iki taraf için de oynanabilir."),
'A-1-2-1-2-11': ("Siyah sagari – sıkışık", 'bad', "Siyah 1 biraz sıkışık bir hamledir. Beyaz sente olarak rahat oynar ve 6 ile güzel çıkar."),
'A-1-2-1-2-12': ("Beyaz 2. sıradan atari", 'ok', "Beyaz 1 ile 2. sıradan atari de olur, siyah 2 güçlü bir hamledir. Beyaz önemli noktaları alır; karışık bir savaş başlar."),
'A-1-2-1-2-13': ("Siyah köşeyi yer", 'ok', "Siyah 1 ve 3 ile köşeyi almak da bir yoldur. Sonuç eşittir."),
'A-1-2-1-2-14': ("Merdiven iyiyse siyah köşeyi engeller", 'situational', "Merdiven siyah lehineyse siyah 1 ile köşeyi engelleyebilir. Beyaz 8 iyi bir hamledir; iki taraf için de oynanabilir."),
'A-1-2-1-2-15': ("Merdiven kötüyse beyaz dışarıdan keser", 'situational', "Merdiven siyah aleyhineyse beyazın 1 ile dışarıdan kesmesi siyahı zorlar. Beyaz savaşı yönetir."),
'A-1-2-1-2-16': ("Siyah uzanır – çalışmaz", 'bad', "Siyah 1 çalışmaz. Beyaz 2 çok iyi bir hamledir ve siyah büyük kayıp verir."),
'A-1-2-1-2-17': ("Siyah yapışır – aşırı", 'bad', "Siyah 1 aşırıdır. Beyaz 4 ile güçlü çıkar; siyahın savaşı çok zordur."),
'A-1-2-1-2-18': ("Siyah atari – kötü", 'bad', "Siyah 1 ile atari kötüdür. Beyaz 2 ile karşı atari verir ve köşede çok alan kazanır."),
'A-1-2-1-2-19': ("Merdiven iyiyse siyah bağlanır", 'situational', "Merdiven siyah lehineyse siyah 1 ile bağlanıp 3 ile çıkabilir. Savaş beyaz için biraz zordur."),
'A-1-2-1-2-20': ("Beyaz uzanır – yumuşak", 'bad', "Beyaz 1 biraz yumuşaktır. Siyah 2 ile güzel bir şekil kurar; beyaz biraz kayıptadır."),
'A-1-2-1-3-1': ("Siyah yapışarak yükselir – şüpheli", 'bad', "Siyah 1 biraz şüphelidir. Beyaz 2 ile köşeye girer ve iki taraf da geri adım atamaz. Savaşta beyaz biraz daha rahattır."),
'A-1-2-1-3-2': ("Siyah iki aralık açılır – yumuşak", 'bad', "Siyah 1 biraz yumuşaktır. Beyaz 2 ile güzel bir şekil kurar."),
'A-1-2-1-3-3': ("Siyah keser – aşırı", 'bad', "Siyah 1 aşırıdır, siyah 3 ile geri dönmek zorunda kalır. Beyaz sakince tamamlar; siyah kayıptadır."),
'A-1-2-1-3-4': ("Siyah kosumi – ısrar kötü", 'bad', "Siyah 1'de ısrar etmek kötüdür. Beyaz 4 güçlüdür ve sonunda siyahın beş taşı sıkışır."),
'A-1-2-1-3-5': ("Siyah yanlış sırayla girer", 'bad', "Siyah 1 yanlış sıradır. Beyaz köşede yaşayıp çok puan alır ve açıkça avantajlı olur."),
'A-1-2-1-3-6': ("Siyah köşeye hane", 'bad', "Siyah 1 ile köşeye hane yaparsa beyaz iyi sırayla oynar ve kenara açılarak memnun olur."),
'A-1-2-1-3-7': ("Beyaz bağlanır – şüpheli", 'bad', "Beyaz 1 şüphelidir. Siyah 2 ile güçlü karşılık verir ve önceki diyagramdan çok daha iyi olur."),
'A-1-2-1-3-8': ("Beyaz uzanır – biraz yumuşak", 'ok', "Beyaz 1 biraz yumuşaktır, siyah 2 ile basitçe bağlanır. İki taraf da güçlenir; sonuç eşittir."),
'A-1-2-1-3-9': ("Siyah kosumi-tsuke", 'bad', "Siyah 1'den sonra beyaz itip keser. Sol üst beyazsa beyaz rahat savaşır ve biraz avantajlı olur."),
'A-1-2-1-3-10': ("Sol üst siyahsa beyaz sürünür", 'situational', "Sol üst siyahsa beyaz 1 ile sürünmek iyidir. Siyah köşeyi korumak zorunda kalır; beyaz biraz daha iyidir."),
'A-1-2-1-3-11': ("Siyah iki kez bastırır", 'bad', "Siyah 1 ve 3 ile bastırırsa beyaz 4 ile sakince açılır. Bu diyagram beyaz lehinedir."),
'A-1-2-1-3-12': ("Siyah keser – kötü", 'bad', "Siyah 1 kötüdür. Beyaz sente olarak yaşar, siyah kendi grubunu korumak zorunda kalır."),
'A-1-2-1-3-13': ("Beyaz başa hane – aşırı", 'situational', "Beyaz 1 fazla ileri gider. Siyah keser ve iki taşı sağlamca yakalar. Sonuç eşittir."),
'A-1-2-1-4-1': ("Siyah sağlam bağlantı – yetersiz", 'bad', "Merdiven iyi olsa bile siyah 1 pek iyi değildir. Beyaz 2 ile açılıp memnun olur; siyah ileride A'daki kesmeye dikkat etmelidir."),
'A-1-2-1-4-2': ("Merdiven kötüyse beyaz keser", 'bad', "Merdiven siyah aleyhineyse beyaz 1 ve 3 ile hemen keser. Savaş açıkça beyaz lehinedir."),
'A-1-2-1-4-3': ("Siyah atari – takas", 'ok', "Siyah 1 ile atari verirse taşlar takas edilir; beyaz da memnundur."),
'A-1-2-2-1-1': ("Beyaz yapışıp çift hane – zayıf", 'bad', "Siyahın × taşı yüksekte olduğu için beyazın yapışıp çift hane yapması biraz zayıftır. Siyah 4 ve 10 ile baskı kurar."),
'A-1-2-2-2-1': ("Siyah ters kaplan ağzı", 'best', "Siyah 1 ile ters kaplan ağzı da olur; × taşı yine iyi yerdedir. Beyaz A'ya oynarsa siyah B ile çok güzel bir şekil kurar."),
'A-1-2-2-3-1': ("Siyah atari", 'best', "Siyah 1 ile atari de düşünülebilir; × taşı burada da iyi çalışır."),
'A-1-2-2-4-1': ("Siyah çift hane – biraz zayıf", 'bad', "Siyah 1 biraz zayıftır. Beyaz yön değiştirip güç alır. Siyahın sonra başka yere oynaması iyidir."),
'A-1-2-3-1-1': ("Beyaz 2. sıradan keima – siyah tenuki", 'best', "Keimada olduğu gibi beyaz 1 siyaha pek baskı yapmaz. Siyahın başka yere oynaması iyidir."),
'A-1-2-3-1-2': ("Beyaz sonra sıkıştırır", 'ok', "İleride beyaz 1 ile sıkıştırmak önemli bir noktadır; siyah 2 ile 3-3'e kosumi yapar. Sağ alt beyazsa beyaz 3 iyidir ve zor bir savaş başlar."),
'A-1-2-3-1-3': ("Sol üst beyazsa beyaz keima", 'situational', "Sol üst beyazsa beyaz 1 iyi bir noktadır; savaş dengelidir."),
'A-1-2-3-1-4': ("Neden önce dürtme?", 'bad', "Beyaz 1 ile şimdi dürtmek A-1-2-1-1-2'ye dönmez; siyah 2 ile karşılık verir. Bu yüzden yapay zekâ önce dürtüp sonra kayar."),
'A-1-2-3-2-1': ("Siyah 3-3 kosumi", 'best', "Siyah 1 sente gibidir, beyaz 2 ile iki aralık açılır. Yapay zekâya göre siyahın hemen kenara açılması acil değildir."),
'A-1-2-3-2-2': ("Sağ alt beyazsa beyaz dürter", 'situational', "Sağ alt beyazsa beyaz 1 aktif bir hamledir; iki taraf da hızla gelişir."),
'A-1-2-3-2-3': ("Siyah pincer", 'ok', "Siyah 1 ile pincer yaparsa beyaz 2 ile güzel sıçrar ve 4 ile karşı pincer yapar. İki taraf için de oynanabilir."),
'A-1-2-3-2-4': ("Sol üst siyahsa siyah yapışır", 'situational', "Sol üst siyahsa siyah 1 ile beyazı sarabilir; A-1-2-3-1-4 ile aynı şekle döner."),
'A-1-2-3-2-5': ("Beyaz tenuki yaparsa", 'ok', "Beyaz başka yere oynarsa siyah 1 ile pincer yapıp saldırır. Bir ko çıkar; siyah biraz avantajlıdır ama beyaz da kurtulur."),
'A-1-2-3-2-6': ("Beyaz hemen hane – riskli", 'bad', "Beyaz 1 ile hemen hane yaparsa siyah 8 güçlüdür. Ko'yu kaybederse beyazın tüm grubu ölür."),
'A-1-2-3-2-7': ("Beyaz geri çekilir – zayıf", 'bad', "Beyaz 1 zayıftır. Siyah 2 çok iyi bir noktadır ve beyaz hâlâ yaşamamıştır."),
'A-1-2-3-2-8': ("Beyaz kosumi-tsuke – uygun değil", 'bad', "Beyaz 1 uygun değildir. Siyah bir taşı yakalar ve saldırmaya devam eder."),
'A-1-2-3-3-1': ("Siyah yüksek iki aralık açılır", 'ok', "Siyah 1 ile yüksek açılmak da bir seçenektir; beyaz başka yere oynayabilir."),
'A-1-2-3-4-1': ("Siyah üç aralık açılır", 'ok', "Siyah 1 hemen hemen aynıdır; beyaz yine başka yere oynayabilir. Beyazın A'sı sente olmadığı için siyah da başka yere oynayabilir."),
'A-1-2-3-5-1': ("Sağ alt siyahsa siyah pincer", 'situational', "Sağ alt siyahsa siyah 1 ile pincer yapıp 3 ile yapışır. İki taraf da memnundur; sağ alt beyazsa siyah biraz kayıptadır."),
'A-1-2-3-5-2': ("Beyaz geri çekilir – biraz kayıp", 'bad', "Beyaz 1 biraz kayıptır. Siyahın × taşı çok iyi yerdedir ve ileride B'deki sıçrayış siyaha kazanç sağlar."),
'A-1-2-3-5-3': ("Siyah kosumi-tsuke – kaba", 'bad', "Siyah 1 kaba bir hamledir. Beyaz sente olarak şeklini belirler ve avantajlı olur."),
'A-1-2-3-6-1': ("Siyah yapışır", 'situational', "Siyah 1 sıkı bir hamledir, beyaz 2 ile yukarıdan hane yapar. Devamı çevredeki taşlara bağlıdır. Sağ alt siyahsa sonuç eşittir."),
'A-1-2-3-6-2': ("Sağ alt beyazsa siyah kosumi", 'situational', "Sağ alt beyazsa siyah 1 ile kosumi yeterlidir; beyazın taşları iyi durmaz."),
'A-1-2-3-6-3': ("Beyaz kafa atar – aşırı", 'bad', "Beyaz 1 aşırıdır. Siyah en güçlü şekilde karşılık verir ve sağ alt siyahsa savaşı yönetir."),
'A-1-2-3-6-4': ("Sol üst siyahsa siyah feda eder", 'situational', "Sol üst siyahsa siyah taş feda edip memnun olur. Merdiven beyaz aleyhineyse siyah doğrudan yakalar."),
'A-1-2-3-6-5': ("Sağ alt beyazsa beyaz sagari", 'situational', "Sağ alt beyazsa beyaz 1 olur, siyah 2 ile sakin kalır. Beyaz iyi noktaları alır ve biraz daha rahattır."),
'A-1-2-3-6-6': ("Siyah keser – acele", 'bad', "Siyah 1 acelecidir. Beyaz iki kez bastırır ve can alıcı noktalara oynar; beyaz savaşı yönetir."),
'A-1-2-3-6-7': ("Sağ alt siyahsa siyah hane", 'situational', "Sağ alt siyahsa siyah 1 iyi bir hamledir; siyahın taşları çok iyi durur."),
'A-1-2-3-6-8': ("Beyaz atari ile çıkar – kötü", 'bad', "Beyaz 1 açıkça kötüdür. Siyah dışarıda güçlü olur, beyazın alanı bunu karşılamaz."),
'A-1-2-3-6-9': ("Sağ alt beyazsa beyaz bağlanır", 'situational', "Sağ alt beyazsa beyaz 1 ile bağlanıp 3 ile büyük bastırma yapar. İki taraf için de oynanabilir."),
'A-1-2-3-6-10': ("Sağ alt siyahsa beyaz küçük sıçrar", 'situational', "Sağ alt siyahsa beyaz 1 ile küçük sıçramak iyidir. Taşlar takas edilir; siyah biraz avantajlıdır."),
'A-1-2-3-6-11': ("Beyaz dürter", 'ok', "Beyaz 1 sente olarak şeklini düzeltmek ister, siyah 2 ile sert karşılık verir. Sonuç eşittir."),
'A-1-2-3-6-12': ("Siyah bağlanır – yumuşak", 'bad', "Siyah 1 yumuşaktır. Beyaz rahatça aşağı uzanır; siyah memnun değildir."),
'A-1-2-3-6-13': ("Beyaz aşağı hane – sıkışık", 'bad', "Beyaz 1 biraz sıkışıktır. Siyah 2 ile basitçe uzanır ve sente güç alır."),
'A-1-2-3-6-14': ("Siyah keser", 'situational', "Siyah 1 de iyi bir hamledir. Merdiven beyaz lehine olsa bile takasta siyah daha çok kazanır."),
'A-1-2-3-6-15': ("Merdiven kötüyse beyaz taşı alır", 'situational', "Merdiven beyaz aleyhineyse beyaz bir taşı almak zorundadır; siyah sente kazanç sağlamıştır."),
'A-1-2-3-6-16': ("Siyah çift hane – uygun değil", 'bad', "Siyah 1 uygun değildir. Beyaz sente olarak bir taşı alır; sonuç eşittir."),
'A-1-2-3-7-1': ("Siyah omuz vuruşu – genelde kötü", 'bad', "Siyah 1 genellikle iyi değildir. Beyaz dürtüp sıkıştırır; siyah A ve B'nin ikisine birden yetişemez."),
'A-1-2-3-7-2': ("Beyaz sürünür – pasif", 'bad', "Beyaz 1 yeterince aktif değildir. Siyah başka yere oynar, sonra A–C arasından seçer."),
'A-1-2-3-7-3': ("Beyaz yapışır – iyi değil", 'bad', "Beyaz 1 de iyi değildir. Siyah sıkı oynar ve memnun olur."),
'A-1-2-4-1-1': ("Beyaz 3-3 işgali", 'situational', "Siyahın × civarında taşı varsa beyaz 1 ile 3-3'e girebilir; normalde beyaz biraz kayıptadır. Siyah sakin oynayıp memnun olur."),
'A-1-2-4-1-2': ("Siyah yapışır – aşırı", 'bad', "Siyah 1 aşırıdır. Beyaz itip keser ve siyah A ile B'yi aynı anda koruyamaz."),
'A-1-2-4-1-3': ("Siyah pincer ile tamamlar", 'ok', "Siyah 1 de bir yoldur. Beyaz sente değişimden sonra başka yere oynar; sonuç eşittir."),
'A-1-2-4-1-4': ("Beyaz keima – biraz kayıp", 'bad', "Beyaz 1 biraz kayıptır. Siyah 2 ile kalın bir şekil kurar."),
'A-1-2-4-1-5': ("Beyaz uzanır – ağır", 'bad', "Beyaz 1 taşlarını ağırlaştırır ve 7 ile güçlenmek zorunda kalır. Siyah rahatça sıçrar."),
'A-1-2-4-1-6': ("Beyaz acele keser", 'bad', "Beyaz 1 ve 3 acelecidir. Beyaz köşesini korumak zorunda kaldığı için savaş beyaza zor gelir."),
'A-1-2-4-1-7': ("Siyah bağlanır – biraz zayıf", 'bad', "Siyah 1 biraz zayıftır. Beyaz 6 ile siyahı zorlar ve hem köşede hem kenarda kazanır."),
'A-1-2-4-1-8': ("Siyah hane ile baskı", 'ok', "Siyah 1 beyaza baskı yapar ama beyazın köşesi artık yaşar. Beyaz başka yere oynayabilir."),
'A-1-2-4-1-9': ("Beyaz kenara açılırsa", 'ok', "Beyaz 1 ile açılırsa siyah 2 ile sağlam bağlanır. Siyah köşeyi öldürmeye çalışsa da beyaz 7 ile kurtulur."),
'A-1-2-4-1-10': ("Beyaz itip keser", 'ok', "Beyaz siyahın nefes zaafını kullanır ve 7 ile yaşar. İki taraf için de oynanabilir."),
'A-1-2-4-1-11': ("Beyaz kaplan ağzı – eski yol", 'bad', "Eskiden oynanan beyaz 1, A'daki pincer imkânını kaybettirir. Beyaz kazandığından fazlasını kaybeder."),
'A-1-2-4-2-1': ("Siyah döner – sade", 'best', "Siyah 1 ile dönmek sade bir çözümdür; çoğu durumda kayıp vermez."),
'A-1-2-5-1-1': ("Beyaz tenuki – siyah kosumi-tsuke", 'ok', "Beyaz başka yere de oynayabilir. Siyah genellikle 1 ile kosumi-tsuke yapar. Beyaz yine başka yere oynayabilir."),
'A-1-2-5-1-2': ("Beyaz keima ile dürter", 'ok', "Beyaz 1 ile dürtebilir, siyah 2 ile karşılık verir. İki taraf için de kabul edilebilir."),
'A-1-2-5-1-3': ("Beyaz uzanır – ağır", 'bad', "Siyah bir boşluklu zıpladıysa beyaz 1 ağır kalır. Siyah 2 ile pincer yapar ve beyaz zorlanır."),
'A-1-2-5-2-1': ("Siyah iki aralık pincer", 'best', "Siyah 1 ile iki aralık pincer yapabilir. Beyaz 6'da başka yere oynar; bu esnek bir düşüncedir. Sonuç eşittir."),
'A-1-2-5-2-2': ("Siyah iter – tuzağa düşer", 'bad', "Siyah 1 tuzağa düşer. Beyaz taşları takas eder; siyah biraz kötü durumdadır."),
'A-1-2-5-2-3': ("Beyaz keima ile dürter", 'ok', "Beyaz 1 ile dürtebilir, siyah 2 ile doğru şekli kurar. İki taraf için de oynanabilir."),
'A-1-2-5-2-4': ("Beyaz 3-3 işgali – biraz zayıf", 'bad', "Beyaz 1 biraz zayıftır. Siyah doğal şekilde oynar ve biraz avantajlı olur."),
'A-1-2-5-2-5': ("Beyaz ōgeima ile köşeyi kapatır", 'ok', "Beyaz 1 ile büyük keima ile köşeyi kapatmak da iyidir. İki taraf için de oynanabilir."),
'A-1-2-5-2-6': ("Siyah kosumi-tsuke – biraz kötü", 'bad', "Siyah 1'den sonra beyaz 2 ile doğru zamanda yoklar ve 4 ile 3-3'e girer. Takasta beyaz biraz avantajlıdır."),
'A-1-2-5-2-7': ("Siyah acele ayırır", 'bad', "Siyah 1 ve 3 acelecidir. Beyaz 10 ve 16 ile iyi oynar; savaşta beyaz biraz daha rahattır."),
}
