# Hoshi + keima kakari → siyah tenuki (A-1-17, 脱先)
T = {
'A-1-17': ("Başlangıç pozisyonu", 'best', "Keima kakariye cevap vermeyip tenuki yapmak da yaygın bir seçimdir. Beyazın genelde üç devamı vardır: A ya da B'den çift kakari veya C'de 3-3 işgali."),
'A-1-17-1': ("Alçak çift kakari", 'ok', "Eskiden beyaz 1 çift kakari çok sert sayılırdı, yapay zekâ öyle düşünmüyor. Köşe siyahın elinde ve iki taraftan da destek alabildiği için siyahın seçeneği çoktur. En doğal cevap A'da yapışmaktır; B–E ve tenuki duruma göre oynanır."),
'A-1-17-1-1-1': ("Yapışıp bastırma", 'best', "Yapay zekânın ilk tercihi siyah 1 ile yapışıp bastırmaktır; en sık cevap beyaz 4 ile alttan yapışmaktır. Siyah 7 bağlanıp köşe tabanını korur, beyaz 8 kosumi ile baskıyı sürdürür. Siyah artık tenuki yapabilir ya da şekli hemen tamamlayabilir."),
'A-1-17-1-1-2': ("Siyah zıplar", 'ok', "Siyah 1 zıplaması sağlamdır, beyaz 2 büyük keima ile solda yerleşir. Siyah 3 pincer iyi noktadır; beyaz 4 ile yapışıp çıkmak bir yoldur. İki taraf da savaşabilir."),
'A-1-17-1-1-3': ("Beyaz araya girer", 'ok', "Beyaz 1 ile araya da girebilir; siyah 4 ile önce işgal etmek iyi sıradır. Sonuç bir önceki diyagramla aşağı yukarı eşittir."),
'A-1-17-1-1-4': ("Beyaz yandan dayanır", 'ok', "Beyaz 1 ile yandan dayanmak da oynanır; beyaz 3 ve 5 sakin hamlelerdir. İki taraf da savaşabilir."),
'A-1-17-1-1-5': ("Beyaz dayanır – kötü", 'bad', "Beyaz 1 ile dayanmak iyi değildir, siyahı güçlendirir."),
'A-1-17-1-1-6': ("Siyah aşağı iner – fazla", 'bad', "Siyah 1 ile aşağı inmek biraz fazladır; beyaz 2 ve 4 ile çıkınca rahatça savaşır."),
'A-1-17-1-1-7': ("Beyaz kaplan ağzı", 'situational', "Sol üst beyazsa beyaz 1 kaplan ağzı ile alt tarafı güçlendirebilir. Siyah 2 karşı pincer doğaldır, beyaz 3 yapışıp çıkar; iki taraf da merkeze çıkmak için mücadele eder, savaş çok karışıktır."),
'A-1-17-1-1-8': ("Siyah hemen karşı pincer", 'ok', "Siyah 1 ile hemen karşı pincer de çok etkindir; beyaz 2'den siyah 5'e kadar iki taraf da çıkar. Beyaz 6 şekil kurar, siyah 7'yi zorlayıp beyaz 10 zıplama noktasını alır. Savaş dengelidir."),
'A-1-17-1-1-9': ("Beyaz zıplayıp çıkar", 'ok', "Beyaz 1 ile zıplayıp çıkmak da olur; siyah 2 ve 4 akıcı oynar. Beyaz 5 omuz vuruşu iyi noktadır, iki taraf da savaşabilir."),
'A-1-17-1-1-10': ("Siyah omuz vuruşu", 'situational', "Sol üst beyazken siyah 1 omuz vuruşu güçlüdür. Beyaz 2 büyük keima sağlamdır; siyah 3 ve 5 sıkı oynar, değiş tokuş iki taraf için de kabul edilebilir."),
'A-1-17-1-1-11': ("Sol üst siyahken", 'situational', "Sol üst siyahsa önceki diyagramda beyaz 4 yerine 1'de içeriden hane güçlüdür. Siyah 6 ile savaş başlatır ama biraz geride kalır."),
'A-1-17-1-1-12': ("Beyaz sürünür", 'ok', "Beyaz 1 ile sürünürse siyah 2 ve 4 güçlü hamlelerdir, kimse geri adım atmaz. Beyaz 15 bağlanmadan önce kazanç arar; siyah 16 iki boşluklu açılışla verimli oynar, beyaz 17 kesince karışık bir savaş çıkar."),
'A-1-17-1-1-13': ("Beyaz itip keser", 'situational', "Beyaz 1 ve 3 ile itip kesmek serttir; siyah 4 kesmesi keskindir ve devamı çok karışıktır. Beyaz 19 ikinci sıradaki güzel hamledir. Sonuç çevredeki taşlara çok bağlıdır."),
'A-1-17-1-1-14': ("Siyah ağ kurar", 'bad', "Önceki diyagramda siyah 10 yerine 1'de ağ kurmak da olur; beyaz 2 ile sabreder, sonra 8 ve 10 ile sert şekilde iter ve keser. Siyah taş feda etmelidir. Beyazın 18, 24 ve 28 hamleleri rahat kazançlardır, beyaz biraz önde."),
'A-1-17-1-1-15': ("Hemen karşı pincer", 'situational', "Sağ alt destekliyse siyah 1 ile hemen karşı pincer yapabilir. Beyaz 2 yapışıp karşılık verir; iki taraf da güçlenir, sonuç kabul edilebilir."),
'A-1-17-1-1-16': ("Sağ alt beyazken", 'situational', "Sağ alt beyazsa beyaz 1 uzaması güçlüdür. Siyah 4 şeklin kilit noktasıdır; beyaz 5 ve 7 ile sabreder, sonra 9 ile iyi çıkış noktasını alır. Siyah iki tarafta da ince kalır."),
'A-1-17-1-1-17': ("Siyah yapışır", 'situational', "Siyah 1 ile yapışmak etkindir, beyaz 2 sakince uzar. Beyaz 4'ten sonra alt tarafta çok kazanır, siyah 9 ile sert saldırır. Sonuç çevreye bağlıdır."),
'A-1-17-1-1-18': ("Beyaz tek boşluklu açılır", 'ok', "Beyaz 1 ile tek boşluklu açılmak sağlamdır; siyah 2 ve 4 tempolu oynar. Beyaz 5 yapışması ile siyah 6 zıplaması şeklin gereğidir. Beyaz 7 iki tarafın tabanı için önemlidir, savaş zordur."),
'A-1-17-1-1-19': ("Beyaz bağlanır – fazla uysal", 'bad', "Beyaz 1 ile bağlanmak fazla uysaldır. Siyah 2 ile şeklini tamamlar ve A ya da B'deki iyi noktalardan birini mutlaka alır; beyaz açıkça geride."),
'A-1-17-1-1-20': ("Beyaz iki boşluklu açılır", 'ok', "Beyaz 1 ile iki boşluklu açılmak hafif ve hızlıdır; siyah 2 yine karşı pincer yapar. Siyah 4 kesme noktasını verimli kapatır, beyaz 5 karşılık verir, siyah 6 geri adım atmaz. Değiş tokuş dengelidir."),
'A-1-17-1-1-21': ("Sert itip kesme", 'ok', "Beyaz 1 ve 3 ile sert şekilde iter ve keser, siyah 4 zıplaması şekildir. Beyaz 5 güçlüdür, siyah 6 ile yarışa girer. Beyaz 11 nefes azaltır, siyah 12 ile taş feda eder. Siyah sente ile merkez, beyaz geniş alan alır; sonuç eşittir."),
'A-1-17-1-1-22': ("Siyah bağlanır – fazla", 'bad', "Önceki diyagramda siyah 12 yerine 1'de bağlanmak fazladır. Beyaz 2 ve 4 çok serttir, siyah 23'e kadar siyah için ağır bir ko çıkar. Beyaz A'dan çıkıp ko'yu bıraksa bile rahatça öndedir."),
'A-1-17-1-1-23': ("Beyaz engeller – yumuşak", 'bad', "Beyaz 1 ile engellemek biraz yumuşaktır; beyaz 7 siyahı sıkıca bağlar. Siyah 10 kilit noktadır, siyah biraz daha rahat."),
'A-1-17-1-1-24': ("Siyah yapışır", 'best', "Siyah 1 ile yapışmak da çok yaygındır; beyaz 2 önce iterek doğru sırayla oynar, siyah 3 bağlanmak zorundadır. Beyaz 8 bağlantısı çok değerlidir, siyah 9 ile kenara açılmayı unutmamalıdır. İki taraf da kabul edebilir."),
'A-1-17-1-1-25': ("Siyah kaplan ağzı – şüpheli", 'bad', "Siyah 1 kaplan ağzı şüphelidir; beyaz 2 ve 4 iyi hamlelerdir, siyahın taşları ağırlaşır."),
'A-1-17-1-1-26': ("Beyaz hemen hane – zayıf", 'bad', "Beyaz 1 ile hemen hane biraz zayıftır; siyah 2 ve 4 ile yerinde yerleşip memnun kalır."),
'A-1-17-1-1-27': ("Siyah hane ile sente", 'ok', "Siyah 1 hane sente almak içindir; sonuç aşağı yukarı eşittir."),
'A-1-17-1-1-28': ("Beyaz tenuki", 'ok', "Beyaz tenuki de yapabilir; siyah 1 ile hane yeterlidir. Beyaz 2'den sonrası akıcıdır, iki taraf da kabul edebilir."),
'A-1-17-1-1-29': ("Ters kaplan ağzı – eski joseki", 'bad', "Siyah 1 ters kaplan ağzı eski bir josekidir; köşede göz biraz iyileşir ama baş zayıflar. Beyaz 2'den sonra çıkar, siyah 3 ve 5 ile uzayınca beyaz biraz önde."),
'A-1-17-1-1-30': ("Merdiven iyiyken kesme", 'situational', "Merdiven siyahın lehineyse siyah 1 kesmesi merkez için iyi hamledir; ileride köşede A'da kesme ihtimali de kalır. İki taraf da savaşabilir."),
'A-1-17-1-1-31': ("Siyah keserek yoklar", 'best', "Siyah 1 kesmesi mükemmel bir yoklamadır, beyaz 2 ve 4 sağlam cevap verir. Siyahın ileride A'da hane ve B'de omuz vuruşu gibi değerli seçenekleri kalır; siyah memnundur."),
'A-1-17-1-1-32': ("Beyaz karşılık verir", 'situational', "Beyaz 1 ile karşılık vermek karışıktır, beyaz 3 ve 5 ile çıkmak zorunludur. Beyaz 7 aşağı inince siyah 8 ikinci sırada ustaca kosumi oynar; beyaz bir seçim yapmalıdır."),
'A-1-17-1-1-33': ("Beyaz kosumi", 'best', "Beyaz 1 kosumi doğru hamledir. Siyah 2 ve 4 ile taş feda edip solda kazanç sağlar; bundan sonra alt taraftaki beş siyah taşın savaşı oyunun odağı olur."),
'A-1-17-1-1-34': ("Beyaz kosumi – fazla", 'bad', "Beyaz 1 kosumi fazladır; siyah 2, 4 ve 6 ile güçlüce kapatır, beyaz sıkışır."),
'A-1-17-1-1-35': ("Beyaz ikinci sırada kaplan ağzı", 'situational', "Uygun bir merdiven kırıcı varsa beyaz ikinci sırada 1 kaplan ağzı yapabilir; siyah 2 ile karşılık verir. Siyah 4 kesmesi zekicedir, beyaz 5 sakince yakalar; siyah biraz önde."),
'A-1-17-1-1-36': ("Beyaz karşılık verir – kötü", 'bad', "Beyazın karşılık vermesi iyi değildir. Siyah 4 uzadıktan sonra beyaz 5 ile mecburen kapatır; ileride siyah köşede seki kurmayı ya da beyazı nefes azaltarak yakalamaya zorlamayı seçebilir."),
'A-1-17-1-1-37': ("Siyah merdivenle yakalar", 'bad', "Siyah 1 ile merdivenle yakalarsa beyaz 2 çift hane ile merdiven kırıcı oynar. Siyah 3 aşağı inince beyaz 4 atari ile yerinde canlı kalır; siyah biraz geride."),
'A-1-17-1-1-38': ("Beyaz karşılık verirse", 'bad', "Beyaz 1 ile karşılık verirse siyah 2 ters atari zorunludur; beyazın alan kaybı biraz büyüktür, çoğu zaman siyah memnundur."),
'A-1-17-1-1-39': ("Siyah aşağı iner", 'situational', "Merdiven siyahın lehineyse siyah 1 ile aşağı inmek ilginç bir hamledir. Beyaz 2 bağlanması doğrudur, siyah 3 dönünce A-1-17-1-1-1 diyagramına döner."),
'A-1-17-1-1-40': ("Beyaz köşeyi engeller – tuzağa düşer", 'bad', "Beyaz 1 ile köşeyi engellemek tuzağa düşmektir; siyah 2 ve 4 ile bir taşı merdivenle rahatça yakalar. Beyaz 5 ve 7'den sonra siyah biraz önde."),
'A-1-17-1-1-41': ("Beyaz iki taşı alır", 'bad', "Beyaz 1 ve 3 ile iki taşı almak da tatmin etmez. Beyazın alanı A-1-17-1-1-30'dakinden iyidir ama siyah sente aldı ve işaretli iki taşın hâlâ kullanım değeri var; siyah açıkça kazançlı."),
'A-1-17-1-1-42': ("Siyah aşağı iner – açgözlü", 'bad', "Önceki diyagramda siyah 4 yerine 1'de aşağı inmek biraz açgözlüdür; beyaz 2 ve 4 ile karşılık vermek zorundadır. Beyaz 14 ile çıkana kadar siyah önceki iki diyagram kadar iyi değildir."),
'A-1-17-1-1-43': ("Beyaz uzar", 'ok', "Beyaz 1 uzaması da çok yaygındır; siyah 2 genelde engeller, beyaz 3 iki boşluklu açılışla sağlam kalır. İki taraf da yerleşir, sonuç eşittir."),
'A-1-17-1-1-44': ("Beyaz kosumi", 'ok', "Beyaz 1 kosumi de düşünülebilir; beyaz 3 bastırınca siyah 4 ile araya sıkışıp sente alır. İki taraf da kabul edebilir."),
'A-1-17-1-1-45': ("İkinci sırada hane", 'ok', "Eskiden beyaz 1 ile ikinci sırada hane daha çok oynanırdı; siyah 2 sıkışması yine önemlidir. Beyaz 3 kaplan ağzı sadedir, siyah 4 köşeyi engeller, iki taraf da huzurludur."),
'A-1-17-1-1-46': ("Beyaz bağlanır – güçlü", 'situational', "Beyaz 1 bağlanması güçlüdür; siyah pinceri mutlaka kendi güçlü tarafından yapmalıdır. Sol üst siyahken siyah 2 ve 4 serttir. Beyaz 5 ile en iyi şekilde canlı kalır, siyah 8 ile iki taş alır; iki taraf da savaşabilir."),
'A-1-17-1-1-47': ("Sağ alt siyahken", 'situational', "Sağ alt siyahsa siyah 1 ile önce hane yapıp 3 ile sert pincer oynar, beyaz 4 ikinci sırada sakin keimadır. İleride siyah A'da kosumi yaparsa beyaz B'de sürünüp işaretli taşı feda eder."),
'A-1-17-1-1-48': ("Siyah engeller", 'bad', "Siyah 1 ile engellerse beyaz 2 pinceri zekicedir. Siyah 5 ile pincer yapmak yarım adım geç kalır; siyah 7 ve 11 ile sakince köşeyi alır, bu diyagram öncekinden biraz kötüdür."),
'A-1-17-1-1-49': ("Siyah hane – tuzak", 'bad', "Siyah 1 ile hane yaparsa beyaz üç taşı feda eder; siyahın şekli çok ağırlaşır. Klasik bir tuzak varyasyonudur."),
'A-1-17-1-1-50': ("İkinci sırada keima", 'ok', "Siyah 1 ikinci sırada keima da yapay zekânın kabul ettiği bir hamledir; beyaz 2 bastırınca siyah 3 ve 5 ile akışında çıkar."),
'A-1-17-1-1-51': ("Beyaz yapışıp kalkar", 'situational', "Sol üst beyazsa beyaz 1 ile yapışıp kalkmayı düşünebilir. Siyah 2 pinceri etkindir, beyaz 3 kosumi ile savaşa çıkar. Siyah 4 ve 6 önünü kesince beyaz 7 ve 9 ile sakince tabanını kurar, sonra 11 pinceri işler. Sonuç eşittir."),
'A-1-17-1-1-52': ("Sol üst siyahken", 'bad', "Sol üst siyahsa beyaz ancak 1 ve 3 ile çıkabilir; beyaz biraz sıkışır."),
'A-1-17-1-1-53': ("Siyah başa hane", 'ok', "Siyah 1 ile başa hane de bir yoldur; iki taraf da güçlenir, sonuç kabul edilebilir."),
'A-1-17-1-1-54': ("İkinci sırada kosumi – tuzak", 'ok', "Beyaz 1 ikinci sırada kosumi bir tuzaktır, siyah dikkatli olmalı; siyah 2 karşı pincer olur. Beyaz 3 bastırınca siyah 4 çift bağlantı ile kesme noktasını kapatır. Siyah 6 saldırının kilit noktasıdır; beyaz 7 ve 9 ile çıkar, siyah biraz önde."),
'A-1-17-1-1-55': ("Soldan karşı pincer", 'ok', "Siyah 1 ile soldan karşı pincer de iyidir; beyazı alçakta tutar, siyah memnundur."),
'A-1-17-1-1-56': ("Siyah bastırır – tuzağa düşer", 'bad', "Siyah 1 ile bastırmak tuzağa düşmektir; beyaz 2 ile araya girince siyahın bütün şekli bozulur, beyaz iki tarafta da iyi şekil kurar."),
'A-1-17-1-1-57': ("Beyaz kosumi", 'ok', "Beyaz 1 kosumi de bir yoldur; siyah 2 ile 3-3 noktasına kosumi kilit noktadır, sonra 4 ve 6 ile yavaş saldırmak iyidir. İki taraf da savaşabilir."),
'A-1-17-1-1-58': ("Beyaz bastırır", 'ok', "Beyaz 1 ile doğrudan bastırmak da savaşılabilir. Siyah 2 kaplan ağzı şeklin kilit noktasıdır, beyaz 3 ters kaplan ağzı esnektir; beyaz 7 ve siyah 8 iyi noktaları paylaşır."),
'A-1-17-1-1-59': ("Beyaz çift hane", 'ok', "Beyaz 1 çift hane taş feda edip sente almak içindir; siyah 2 ve 4 doğaldır, beyaz 5 başa hane güçlüdür. Siyah tenuki yapabilir ya da A'da kesip savaşabilir."),
'A-1-17-1-1-60': ("Beyaz bağlanır – ağır", 'bad', "Beyaz 1 bağlanması biraz ağırdır; beyaz 3 ile köşeyi işgal edince siyah 4 ve 6 ile mutlaka ayırmalıdır, sonra siyah 8 pinceri çok güçlüdür. Siyah 10 yapışması tempo kazandırır, savaşta siyah önde."),
'A-1-17-1-1-61': ("3-3 işgali – yumuşak", 'bad', "Beyaz 1 ile 3-3 işgali biraz yumuşaktır; siyah 2 ve 4 ile kalın bir şekil kurar."),
'A-1-17-1-1-62': ("Beyaz inatla bağlanır", 'bad', "Beyaz 1 bağlanması inatçıdır ama siyah 6 ile ayırdıktan sonra 8 ve 10 ile yapışıp çift hane yapar; savaşta siyah daha etkindir."),
'A-1-17-1-2-1': ("Siyah keima ile kapatır", 'situational', "Siyah 1 ile keima şeklinde bastırmak da olur. Sağ tarafın değeri azsa beyaz 2 ile 3-3 işgali daha iyidir; A-1-6-3-3-1 diyagramına benzer ama beyaz yöne memnundur."),
'A-1-17-1-2-2': ("Beyaz iki boşluklu açılır", 'ok', "Sağ taraf değerliyse beyaz 1 iki boşluklu açılışla sakin kalır. Siyah tenuki yapabilir ya da 2 ile pincer yapar. Beyaz 3 yapışıp çıkar, siyah 8'den sonra değiş tokuş olur; beyaz biraz önde."),
'A-1-17-1-2-3': ("Beyaz kosumi – ağır", 'bad', "Beyaz 1 kosumi biraz ağırdır; siyah 2'den itibaren önce köşeyi sağlama alır, sonra 14 ile uzar; dışarıda zor bir savaş başlar."),
'A-1-17-1-3-1': ("Siyah kosumi ile çıkar – yavaş", 'bad', "Siyah 1 kosumi biraz yavaştır; beyaz 2 ile 3-3 işgali tek hamledir. Siyah 5 ile merkez kurar ama merkezi hâlâ incedir, siyah memnun olamaz."),
'A-1-17-1-3-2': ("Diğer taraftan bastırma", 'bad', "Siyah 1 ile öbür taraftan keima ile bastırmak da iyi değildir; beyaz 2 güzel hamledir, işaretli beyaz taşı almak da almamak da siyahı rahatsız eder."),
'A-1-17-1-3-3': ("Siyah hızlı açılır", 'bad', "Siyah 1 ve 3 ile hızla açılmak da bir yoldur ama siyah yine biraz kayıptadır."),
'A-1-17-1-4-1': ("İkinci sırada keima", 'bad', "Siyah 1 ikinci sırada keima ile yerinde yerleşmeye çalışır, çoğu durumda biraz kayıptır. Beyaz 2 iki boşluklu açılışla sağlam kalır, siyah 3 yine ikinci sırada keima ile köşeyi korur."),
'A-1-17-1-4-2': ("Beyaz köşeye keima", 'ok', "Beyaz 1 ile köşeye keima da bir yoldur; siyah 2 kosumi şekildir. Beyaz 3 iki boşluklu açılır, siyah 4 bastırarak rahat oynar."),
'A-1-17-1-4-3': ("Beyaz keima ile kapatır", 'situational', "Merdiven beyazın lehineyse beyaz 1 keima ile kapatmak güçlüdür; siyah 2 ve 4 aşağı yukarı böyledir, beyaz memnundur."),
'A-1-17-1-4-4': ("Merdiven beyaza kötüyse", 'ok', "Merdiven beyazın aleyhineyse siyah 1 ile yapışıp çıkmak güçlüdür; sonra siyah 7 ile iterek taş feda edip merkez kurar. Sonuç eşittir."),
'A-1-17-1-4-5': ("Beyaz merdivenle yakalar", 'situational', "Merdiven beyazın lehineyse beyaz 1 ile merdiven kurabilir; siyah 2 ve 4 mecburdur. Beyaz 7 kesmesi keskindir, siyah yerel olarak cevap bulamaz ve tenuki yapmak zorunda kalır; alan kaybı büyüktür."),
'A-1-17-1-5-1': ("3-3'e kosumi – kötü", 'bad', "Siyah 1 ile 3-3 noktasına kosumi iyi değildir; beyaz 2 keima ile kapatma iyi noktadır. Siyah sente alsa da beyazın sonraki sıkıştırması çok serttir, siyah memnun değil."),
'A-1-17-1-5-2': ("İki keima", 'bad', "Beyaz 1 ve 3 ile iki keima rahat hamlelerdir; siyah ancak iki gözle zorla yaşar."),
'A-1-17-1-6-1': ("Siyah tenukiye devam eder", 'bad', "Siyahın yine tenuki yapması genelde iyi değildir; beyaz 1 keima ile kapatma çok büyüktür. Siyah 2 ve 4 yaşamak için iyi hamlelerdir, beyazı güçlendirmekten kaçınır."),
'A-1-17-1-6-2': ("Kosumi ile dayanma", 'bad', "Siyah 1 ile dayanmak beyazı güçlendirir, siyaha kazanç sağlamaz."),
'A-1-17-1-6-3': ("Siyah yine tenuki", 'situational', "Siyah bir kez daha tenuki de yapabilir; beyaz 1 keima çok değerlidir. İleride siyahın A'da yapışma imkânı kalır."),
'A-1-17-2': ("Yüksek çift kakari", 'ok', "Beyaz 1 yüksek çift kakari görece nadirdir; yapay zekâ alçak çift kakariden biraz zayıf görür. Siyah genelde A'da yapışıp çıkar; B–E biraz zayıftır."),
'A-1-17-2-1-1': ("Siyah üstten yapışır", 'best', "Siyah 1 ile üstten yapışmak doğru hamledir; beyaz 2 ile hemen 3-3 işgali bir yoldur. Siyah 7 hane yapınca beyaz 8 ile baş kaldırmak iyidir, siyah 9 kaplan ağzı ile iyi şekil kurar; siyah biraz önde."),
'A-1-17-2-1-2': ("Siyah baş kaldırır", 'ok', "Siyah 1 ile baş kaldırmak taş feda edip merkez kurmak içindir; siyah 3 hanenin sırası ustacadır, siyah yine iyidir."),
'A-1-17-2-1-3': ("Hane sonra 3-3", 'situational', "Beyaz 1 ve 3 ile hane yapıp sonra 3-3'e girmek de bir yoldur; siyah 8 ve 10 ile ısrarla ko yapar. Merdiven beyazın lehineyse beyaz 17 ile sakince geri çekilip memnun kalır."),
'A-1-17-2-1-4': ("Merdiven beyaza kötüyse", 'ok', "Merdiven beyazın aleyhineyse beyaz 1 ile bastırmaya devam etmek daha iyidir, siyah 2 ile ko'yu kapatır. Beyaz 5 ile hızla açılır, siyah 6 kaplan ağzı ile kalınlaşır; iki taraf da savaşabilir."),
'A-1-17-2-1-5': ("Siyah keser", 'situational', "Merdiven siyahın lehineyse ve sol taraf destekliyse siyah 1 ile kesip merkez kurmak olur; sonuç eşittir."),
'A-1-17-2-1-6': ("Beyaz bağlanır – şüpheli", 'bad', "Beyaz 1 bağlanması şüphelidir; siyah 2 yapışması şekildir. Beyaz 3 ile köşeyi işgal edince siyah 4 mutlaka engeller. Siyah 10 iyi noktadır, beyazın alt taraftaki verimi düşer."),
'A-1-17-2-1-7': ("Beyaz bastırırsa", 'bad', "Beyaz 1 ile bastırırsa siyah 2 yine yapışır, beyaz 3 uzar. Beyaz iki tarafa da ulaşır ama iki taraf da incedir; siyah memnundur."),
'A-1-17-2-1-8': ("Beyaz 3-3 işgali", 'bad', "Beyaz 1 ile 3-3 işgali başka bir seçimdir; siyah 2 kesmesi beyazı sınar. Beyaz 3 aşağı inerse siyah 4 engelleme sente olur; siyahın köşesi doludur, beyaz memnun değil."),
'A-1-17-2-1-9': ("Beyaz dayanırsa", 'bad', "Beyaz 1 ile dayanırsa siyah 2 ile itip güçlü bir değiş tokuş yapar; siyahın alanı çok büyür."),
'A-1-17-2-1-10': ("Siyah geri çekilir", 'ok', "Siyah 1 ile geri de çekilebilir; beyaz 2 yine 3-3'e girer, siyah 3 kesmesi daha iyidir. Beyaz 4 aşağı inince beyaz 10 kosumi güzel hamlesi doğar. İki taraf birer yer alır, sonuç kabul edilebilir."),
'A-1-17-2-1-11': ("Siyah engeller – fazla", 'bad', "Siyah 1 ile engellemek fazladır, sonrası zorunludur. Siyah 11 ikinci sırada dönmek zorunda kalır, beyaz 12 ile iki taşı alıp çok kalın olur."),
'A-1-17-2-1-12': ("Siyah zıplarsa", 'bad', "Siyah 1 ile zıplarsa beyaz 2'den 12'ye kadar birbirine bağlı hamlelerle saldırır, siyah dayanamaz."),
'A-1-17-2-1-13': ("Beyaz hane yapıp keser", 'situational', "Merdiven beyazın lehineyse beyaz 1 ile hane yapıp kesmek de olur. Siyah 4 ve 6 en güçlüsüdür, beyaz 7 inatla döner. Beyaz 15 pinceri bir seçimdir, siyah 16 ile hane yapıp değiş tokuş eder; beyaz biraz geride."),
'A-1-17-2-1-14': ("Beyaz köşeyi işgal ederse", 'bad', "Beyaz 1 ile köşeyi işgal ederse siyah 2 hane ile keskin karşılık verir; sonrasında taş feda edip merkez kurması çok güzeldir."),
'A-1-17-2-1-15': ("Siyah alanı bırakmazsa", 'bad', "Siyah 1 ve 3 ile alanı bırakmak istemezse beyaz 8 ile saldırının iyi noktasını alır; siyah A-1-17-2-1-13 diyagramı kadar etkin değildir."),
'A-1-17-2-1-16': ("Merdiven beyaza kötüyse", 'situational', "Merdiven beyazın aleyhineyse siyah 1 ile güçlüce hane yapabilir; beyaz iki siyah taşı merdivenle alamaz ve şekli dağılır."),
'A-1-17-2-2-1': ("Bu taraftan yapışma – kötü", 'bad', "Siyah 1 ile bu taraftan yapışmak iyi değildir; beyaz 2 ve 4 ile hane yapıp uzar. Beyaz 6 alan ve iki tarafın tabanı için önemlidir, siyah 7 ile kapatmak zorundadır; ileride beyazın A'da zıplaması iyi noktadır."),
'A-1-17-2-2-2': ("Beyaz alttan yapışır", 'bad', "Beyaz 1 ile alttan da yapışabilir, sonra beyaz 5 kaplan ağzı iyi şekildir. Siyah 6 yine ikinci sırada keima ile kapatmalıdır; beyaz biraz iyidir."),
'A-1-17-2-3-1': ("Siyah kosumi ile çıkar – zor", 'bad', "Siyah 1 kosumi acı bir hamledir; beyaz 2 ile 3-3 işgali siyahın zayıf noktasına vurur, siyahın bütün grubu sıkışır."),
'A-1-17-2-3-2': ("Bu taraftan engelleme – kötü", 'bad', "Siyah 1 ile bu taraftan engellemek de iyi değildir; beyaz 6 ve 8 sıkı oynar, siyahın grubu hâlâ yerleşmemiştir."),
'A-1-17-2-4-1': ("Alttan yapışıp geri çekilme", 'bad', "Siyah 1 ve 3 ile alttan yapışıp geri çekilmek yerinde yerleşmeyi sağlar ama tempo biraz yavaştır."),
'A-1-17-2-4-2': ("Beyaz kosumi ile kapatır", 'bad', "İleride beyaz 1 kosumi güzel bir kapatma hamlesidir; beyazın merkezi tamamen bütün olur."),
'A-1-17-2-5-1': ("İkinci sırada zıplama", 'bad', "Siyah 1 ile ikinci sırada zıplamak da benzerdir; beyaz 2 zıplayıp rahatça kapatır."),
'A-1-17-2-5-2': ("İkinci sırada keima ile taban alma", 'bad', "Beyaz 1 ile ikinci sırada keima tabanı almak için de keskindir. Siyah 2 ile yapışıp çıkarsa beyaz 5 rahat sente kazancıdır, sonra beyaz 7 ile kovalar; siyahın verimi düşüktür."),
'A-1-17-2-5-3': ("Siyah tenuki – kötü", 'bad', "Siyahın tenuki yapması da iyi değildir; beyaz 1 zıplayıp tam kapatır, siyah 2 ile yapışıp zorla yaşamak zorunda kalır."),
'A-1-17-3': ("Doğrudan 3-3 işgali", 'ok', "Beyaz 1 ile doğrudan 3-3 işgali çok kârlı bir hamledir. Siyahın A ya da B'den engellemek gibi iki cevabı vardır, ikisi de aşağı yukarı eşittir."),
'A-1-17-3-1-1': ("Bu taraftan engelleme", 'best', "Siyah 1 genelde bu taraftan engeller; beyaz 4 ve 6 ile hane yapıp bağlanınca siyah tekrar tenuki düşünebilir. İleride beyazın A'da zıplaması ve B'de kesmesi çok büyüktür."),
'A-1-17-3-1-2': ("Siyah sürünür", 'ok', "Siyah 1 ile sürünmek de olur; beyaz 2 önce uzamalıdır, yoksa siyah tek hamlede hane ile kalkar. Siyah 3 pinceri etkindir, beyaz 4 zıplayıp sadece çıkar. İki beyaz taş ileride hâlâ canlıdır, sonuç eşittir."),
'A-1-17-3-1-3': ("Beyaz sert döner", 'ok', "Beyaz 1 ile dönmek serttir, siyah 4 keima saldırısı ile karşılık verir. Beyaz 5 yapışması bir seçimdir, siyah 6 ile sağlam kapatır; ileride beyazın A'da yaklaşma imkânı vardır."),
'A-1-17-3-1-4': ("Siyah da hane yapar", 'ok', "Siyah 1 ile hane yapmak da olur; beyaz 2'den sonra hemen hareket etmelidir, siyah 5 hanesi sıkıdır. Siyah 15 ile araya girmesi ustacadır: A'da engellemeyi sente yapar ve B'deki kesme noktasını da korur."),
'A-1-17-3-1-5': ("Beyaz yaklaşır", 'ok', "Beyaz 1 ile doğrudan yaklaşmak da iyi hamledir, siyah 2 sakince yan yana oynar; beyaz buradaki imkânları saklayıp tenuki yapmalıdır."),
'A-1-17-3-1-6': ("Beyazın sonraki hamleleri", 'bad', "Beyaz 1, 3 ve 5 bu şeklin devam hamleleridir ama beyazın hâlâ bir kesme noktası olduğu için hemen değiş tokuş etmek kazançlı değildir."),
'A-1-17-3-1-7': ("Beyaz yapışıp çıkar – fazla", 'bad', "Beyaz 1 ile doğrudan yapışıp çıkmak fazladır; siyah 2 ve 4 ile sertçe kapatır. Beyaz kaçmaya çalışır, siyah 12 ve 14 ile ustaca taş feda edip dev bir merkez kurar; beyaz siyahı almak için bir hamle daha harcar ve açıkça geride kalır."),
'A-1-17-3-1-8': ("Siyah bağlanır – ağır", 'bad', "Siyah 1 bağlanması ağırlaşır; beyaz 4 zıplaması saldırının kilit noktasıdır, siyahın şekli sıkışır."),
'A-1-17-3-1-9': ("Siyah hane", 'ok', "Siyah 1 hane de bir yoldur; beyaz 2 kesmesi en güçlüsüdür. Siyah 3 ve 5 ile hane yapıp bağlanmak iki tarafın tabanı için önemlidir, siyah 9 atari sıkıdır, beyaz 10 sakince çıkar. İleride beyazın A'da kalkması iyi noktadır; beyaz iki tarafa da ulaşır ve memnundur."),
'A-1-17-3-1-10': ("Beyaz kaçar – fazla", 'ok', "Beyaz 1 ile kaçmak biraz fazladır, beyaz 3'ten sonra bastırarak devam etmek daha iyidir. Siyah 10 ile köşeyi alır, beyaz taş feda edip merkez kurar; sonuç eşittir."),
'A-1-17-3-1-11': ("Beyaz döner – gevşek", 'bad', "Beyaz 1 ile dönmek yeterince sıkı değildir; siyah 4 ve 6 ile esnekçe yön değiştirir, köşede ileride ko imkânı da kalır; siyah önde."),
'A-1-17-3-1-12': ("Beyaz sade hane", 'ok', "Beyaz 1 hanesi sadedir, siyah 2 kaplan ağzı ile etkin şekilde kapatır. Beyaz 3 ile geri uzamak bir yoldur, siyah 4 pinceri yerel olarak ustacadır; sonuç eşittir."),
'A-1-17-3-1-13': ("Beyaz sol tarafa önem verir", 'ok', "Beyaz 1 hanesi sol tarafa önem verir; siyah 2 ve 6 iyi sıradır, iki taraf da kabul edebilir."),
'A-1-17-3-2-1': ("Diğer taraftan engelleme", 'ok', "Siyah 1 ile bu taraftan engellerse A-2-3-3 diyagramına benzer bir şekil oluşur."),
}
