# 3-3 noktası (C-1): omuz vuruşu ve dört kakari
T = {
'C-1': ("Başlangıç pozisyonu", 'ok', "Siyah 1 ile köşeyi 3-3 noktasından alır. Alan sağlamdır ama merkeze gelişimi zayıftır; denge olarak hoshi ve komokudan biraz geridedir. Beyazın beş cevabı vardır: A'da omuz vuruşu, B–E'de kakari."),
'C-1-1-1-1-1': ("Omuz vuruşu", 'best', "Beyaz 1 omuz vuruşu 3-3'ün alçak olmasını hedef alır. Siyah 2 ile sürünmek doğaldır, beyaz 3 hafifçe zıplar; beyaz 7 keima güzel bir şekildir. İki taraf da kabul edebilir."),
'C-1-1-1-1-2': ("Siyah pincer yapar", 'ok', "İleride siyah 1 pinceri yerel olarak iyi hamledir; beyaz 2 ve 4 ile sakince cevap verir. Zamanı gelince beyaz A'da engelleyebilir."),
'C-1-1-1-2-1': ("Siyah bu taraftan pincer", 'ok', "Siyah 1 ile bu taraftan da pincer yapabilir; beyaz tenuki yapsa iyi olur. Sade ve eşit."),
'C-1-1-2-1-1': ("Beyaz uzar – biraz ağır", 'ok', "Beyaz 1 ile uzamak biraz ağırdır. Sol üst siyahsa siyah 2 ile sürünmeye devam eder. Beyaz 3 verimli zıplar, siyah 8 beyazı sınar, beyaz 9 ile bağlamak sadedir. Eşit."),
'C-1-1-2-1-2': ("Beyaz engeller – karışık savaş", 'situational', "Önceki diyagramda beyaz 9 yerine 1'de engelleyebilir; siyah 2 ile kesince karışık bir savaş çıkar, durum çok zordur."),
'C-1-1-2-1-3': ("Beyaz yine uzar – yavaş", 'bad', "Beyaz 1 ile yine uzamak yavaştır; siyah 4 ile karşı pincer yapıp memnun kalır. Ama sol üst beyazsa beyaz savaşabilir."),
'C-1-1-2-2-1': ("Siyah başını çevirir", 'ok', "Sol üst beyazsa siyah 1 ile dönmek daha iyidir. Beyaz 2 hafifçe zıplar; siyah 3 ile çıkınca beyaz tenuki yapar, A'daki kaplan ağzı acil değildir."),
'C-1-1-2-2-2': ("Siyah uzar – yavaş", 'bad', "Siyah 1 ile uzamak biraz yavaştır; beyaz A, B ya da C'den biriyle şeklini tamamlar ve memnun kalır."),
'C-1-1-2-2-3': ("Beyaz tenuki yapar", 'ok', "Beyaz tenuki de yapabilir. Siyah 1 ile itmeye devam ederse beyaz 2 keima ile işaretli iki taşı hafifçe bırakır; siyahın taşları verimsiz kalır."),
'C-1-1-2-2-4': ("Beyaz hane – fazla sıkı", 'bad', "Beyaz 1 hanesi fazla sıkıdır; sonrası B-5-1-1-1-3 diyagramına döner, beyaz biraz ağır kalır."),
'C-1-1-2-2-5': ("Siyah sürünür – zayıf", 'bad', "Siyah 1 ile sürünmek biraz zayıftır; sonrası B-2-1-2-4-1 diyagramına döner."),
'C-1-1-2-2-6': ("Siyah keser – kötü", 'bad', "Merdiven lehine olsa bile siyah 1 kesmesi iyi değildir; beyaz 2 ile uzayınca B-1-3-2-2-1 diyagramına döner."),
'C-1-1-2-2-7': ("Siyah pincer – fazla", 'bad', "Siyah 1 pinceri fazladır; B-1-3-2-2-2 diyagramına döner ve siyah zor durumda kalır."),
'C-1-1-2-3-1': ("Siyah keima ile çıkar – zayıf", 'bad', "Siyah 1 ile hemen keima ile çıkmak biraz zayıftır. Beyaz 2 ile güçlüce döner, siyah 3 keima zorunludur; beyaz 4 ile sade şekilde açılıp memnun kalır."),
'C-1-1-2-3-2': ("Beyaz iki sıra zıplar – eski", 'bad', "Beyaz 1 ile zıplamak eski bir josekidir; siyah 2 keima çok büyüktür, beyaz biraz kayıptadır. Sonra beyaz tenuki yapmalıdır; A'da büyük zıplama fazla yavaştır."),
'C-1-2-1-1-1': ("İki boşluklu alçak kakari", 'best', "Beyaz 1 iki boşluklu alçak kakari de iyi hamledir. Siyah 2 keima normaldir, beyaz 3 ile iki boşluklu açılış sağlamdır. İki taraf da oynayabilir."),
'C-1-2-1-2-1': ("Beyaz sıkıştırır, siyah karşı pincer", 'ok', "Beyaz 1 ile sıkıştırmak aktiftir. Sol üst destekliyse siyah 2 karşı pinceri serttir, siyah 6 ile zıplayıp kovalar. Beyaz 7 ve 11 ile yerinde yaşar, siyah 12 ve 14 ile sol üstü güçlendirir. Eşit."),
'C-1-2-1-2-2': ("Siyah pincer yapar", 'ok', "Sağ alt destekliyse siyah 1 pinceri aktiftir. Beyaz 2 ile dürüstçe zıplar, siyah 3 ile yapışıp bastırarak çıkar. İki taraf da savaşabilir."),
'C-1-2-2-1-1': ("Siyah iki boşluklu açılır", 'ok', "Siyah 1 ile iki boşluklu açılmak da olur; beyaz 2 büyük keima ile sade şekilde oynar."),
'C-1-2-2-2-1': ("Beyaz fil adımı", 'ok', "Beyaz 1 fil adımı aktiftir; siyah 2 ile aradan çıkıp karşı saldırır. Beyaz 3'ten sonra iki taraf kendi yoluna gider; değiş tokuş eşittir."),
'C-1-2-2-2-2': ("Siyah aşağı uzar", 'ok', "Siyah 1 ile aşağı uzamak alanı önemser. Beyaz 2 ve 4 art arda hane ile sıkı oynar, sonra beyaz 8 büyük keimayı alır. İki taraf da savaşabilir."),
'C-1-2-2-2-3': ("Beyaz iter – tuzak", 'bad', "Beyaz 1 ile itmek tuzağa düşmek gibidir; siyah 2 ile aşağı itmek güçlüdür. Siyah 6 kaplan ağzı yapınca beyaz 7 ile dönüp taş feda eder. Siyah biraz iyidir."),
'C-1-2-2-2-4': ("Beyaz köşeyi alır – kötü", 'bad', "Beyaz 1 ile hemen köşeyi almak iyi değildir; siyah 2 kosumisi keskindir. Beyazın büyük grubu hâlâ yaşamaz ve ağır kalır."),
'C-1-2-2-2-5': ("Siyah köşeyi alır", 'situational', "Merdiven lehine olsa bile siyah 1 ile köşeyi almak pek kazandırmaz. Beyaz 4 kaplan ağzı ile çıkıp savaşır, siyah 5 zıplar; savaş çok çetindir."),
'C-1-2-2-2-6': ("Siyah yapışır – zayıf", 'bad', "Siyah 1 yapışması biraz zayıftır; beyaz 2 ile sente yapışıp kazanır."),
'C-1-2-2-2-7': ("Siyah engeller – yumuşak", 'bad', "Siyah 1 ile engellemek yumuşaktır; beyaz 2 ve 4 ile sente kalınlaşır. Siyah önceki diyagramdan açıkça kötüdür."),
'C-1-2-2-3-1': ("Beyaz tenuki, siyah pincer", 'ok', "Beyaz tenuki yapabilir. Siyah 1 ile pincer yapınca beyaz 2 fil adımı yine iyidir; siyah 3 aradan çıkar, beyaz 4 ile yapışıp çıkar. İki taraf da savaşabilir."),
'C-1-2-3-1-1': ("Siyah büyük keima", 'ok', "Siyah 1 büyük keima da olur; beyaz 2 ile iki boşluklu ya da A'da çok büyük keima ile açılabilir. Eşit."),
'C-1-2-4-1-1': ("Siyah pincer yapar", 'ok', "Sağ alt destekliyse siyah 1 pinceri olur; beyaz 2 omuz vuruşu ile rahatça çıkar. Sonrası B-3-3-1-1-1 diyagramına döner."),
'C-1-2-4-2-1': ("Beyaz fil adımı – iyi değil", 'bad', "Merdiven lehine olsa bile beyaz 1 fil adımı pek iyi değildir. Siyah 2 ile aradan keskince çıkar; iki taraf birer taş keser, siyah biraz kazançlıdır."),
'C-1-2-4-2-2': ("Merdiven beyazın aleyhine", 'bad', "Merdiven beyazın aleyhineyse siyah 1 ile köşeyi alabilir; beyaz daha da kötüdür."),
'C-1-3-1-1-1': ("Büyük keima kakari", 'best', "Beyaz 1 büyük keima kakari de bir yoldur. Siyah 2 büyük keima doğru şekildir, beyaz 3 ile geri açılıp sade oynar."),
'C-1-3-1-2-1': ("Beyaz sıkıştırır", 'ok', "Beyaz 1 ile sıkıştırırsa ve sol üst siyahsa siyah 2 karşı pinceri iyidir. Beyaz 5'ten sonra değiş tokuş olur; iki taraf da kabul edebilir."),
'C-1-3-1-2-2': ("Siyah pincer yapar", 'ok', "Sağ alt siyahsa siyah 1 pinceri güçlüdür. Beyaz 2 ve 4 sağlamdır; eşit."),
'C-1-3-2-1-1': ("Siyah iki boşluklu açılır", 'ok', "Siyah 1 ile iki boşluklu açılmak beyaza az baskı yapar; beyaz tenuki yapabilir."),
'C-1-3-2-1-2': ("Siyah sonra pincer yapar", 'ok', "İleride siyah 1 ile pincer yaparsa beyaz 2 ve 4 ile iyi bir şekil kurar."),
'C-1-3-3-1-1': ("Siyah keima – zayıf", 'bad', "Siyah 1 keimasi biraz zayıftır. Beyaz 2 yapışması keskindir, siyah 3 ile mecburen geri çekilir; siyahın şekli üst üste biner."),
'C-1-3-3-1-2': ("Siyah ikinci sırada hane – kötü", 'bad', "Siyah 1 ile ikinci sırada hane iyi değildir. Beyaz 2 karşı hanesi ustacadır, beyaz 6 ile dönünce şekli kalınlaşır; siyah 7 ile yine tamamlamak zorundadır. Beyaz memnundur."),
'C-1-3-4-1-1': ("Siyah karşı pincer – fazla sıkı", 'bad', "Siyah 1 karşı pinceri fazla sıkıdır. Beyaz 2 omuz vuruşu aktiftir, beyaz 6 iyi şekildir. Siyah 1 beyazın merkezine çok yakın kalır; siyah memnun değildir."),
'C-1-4-1-1-1': ("Bir boşluklu alçak kakari", 'best', "Beyaz 1 ile alçak kakari de yapabilir. Siyah 2 keima iyidir; ileride siyah A'da zıplayarak alanı büyütür. Eşit."),
'C-1-4-2-1-1': ("Siyah bir boşluklu açılır", 'ok', "Siyah 1 ile bir boşluklu açılmak çok sağlamdır; beyaz 2 ve 4 ile şekli sadece bitirir. İki taraf da kabul edebilir."),
'C-1-4-3-1-1': ("Siyah büyük keima", 'ok', "Siyah 1 büyük keima da olur; beyaz 2 ile iki boşluklu açılıp sade oynar."),
'C-1-5-1-1-1': ("Keima kakari – fazla sıkı", 'bad', "Beyaz 1 keima kakari fazla sıkıdır; siyah 2 keima açık bir iyi noktadır. Beyaz 3 ile yapışınca siyah 4 ve 6 sağlamdır, siyah 8 ile dönmek güçlüdür. Beyaz biraz sıkışır."),
'C-1-5-2-1-1': ("Siyah iki boşluklu açılır – gevşek", 'bad', "Siyah 1 ile iki boşluklu açılmak yeterince sıkı değildir; beyaz 2 ile geri açılıp memnun kalır."),
}
